### ISSUE TITLE
value of system.host.any_slave.alive is missing sometimes

### ISSUE THREAD

**Issue by rg-engineering** [ioBroker/ioBroker.js-controller#1000]
Sometimes one of my slaves crashes on linux side and so the iobroker instance on that host (slave) is not alive anymore.
Instead of showing alive = false I get an empty value:

![grafik](https://user-images.githubusercontent.com/8238668/90339623-33a8c680-dff2-11ea-9a6e-0a966b7c7227.png)

Up to now I run a script checking alive!=true to inform me when that slave crashed. But with an empty value is this check useless...

**Comment by Apollon77** [comment]
This is as designed. The state value expires after done time. So you need to also check if the state object gets null

**Comment by Apollon77** [comment]
A state object null in your case has the same meaning then state.val === false
