### ISSUE TITLE
Make Multihost Discovery only temporary if enabled via CLI by default

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#1002]
Currently the Multuhost Discovery Service is started and then online and enablement is also persisted in iobroker.json - and it is always running. Is this really needed?

Idea would be to make the "enable" command via CLI only temporary (10-15mins). An additional parameter could allow to make it persistent as before

**Comment by foxriver76** [comment]
Currently, the logic requires a restart of the controller. The CLI changes the config, and the config is then checked at the controller start and the server is activated by the controller.
