### ISSUE TITLE
mercedesme.0	2020-08-25 08:38:48.075	info	(6835) starting. Version 0.0.21 in /opt/iobroker/node_modules/iobroker.mercedesme, node: v10.22.0, js-controller: 3.1.6

### ISSUE THREAD

**Issue by hpiecuch** [ioBroker/ioBroker.js-controller#1010]
Is there someone who can help regarding that json issue - 

mercedesme.0 | 2020-08-25 08:38:48.075 | info | (6835) starting. Version 0.0.21 in /opt/iobroker/node_modules/iobroker.mercedesme, node: v10.22.0, js-controller: 3.1.6
-- | -- | -- | --

**Comment by hpiecuch** [comment]
mercedesme.0 | 2020-08-25 11:49:11.363 | error | (14142) Error getting Vehicles
-- | -- | -- | --
mercedesme.0 | 2020-08-25 11:49:11.361 | warn | (14142) Vehicles not found please start the mercedes me app: SyntaxError: Unexpected token u in JSON at position 0

**Comment by thost96** [comment]
Please open an issue on https://github.com/TA2k/ioBroker.mercedesme as this is adapter related. Thanks!
