### ISSUE TITLE
Multihostsystem update with one command

### ISSUE THREAD

**Issue by Jey-Cee** [ioBroker/ioBroker.js-controller#1014]
As there is no documentation for updating a multihost system and the fact that the slave has to be updated first, it would be nice to have a single command for updating the whole multihostsystem.

**Comment by Apollon77** [comment]
Updating what? Adapters? Controller?

**Comment by Jey-Cee** [comment]
Controller

**Comment by Apollon77** [comment]
makes that really sense? Currently controller needs to be stopped in order to update it ... doing that remote is veeery risky ...

**Comment by Apollon77** [comment]
I think this is way too risky
