### ISSUE TITLE
"upgrade all" command should respect dependencies between adapters to determine upgrade order instead of sorting by name

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.js-controller#1015]
example:

- iot and web both need upgrades.
- iot requires a higher version of web than is currently installed --> Adapter is updated but with an error in the log (Invalid version of web)
- web is updated later.

**Comment by AlCalzone** [comment]
I've already solved the algorithmic side of this:
https://github.com/AlCalzone/node-zwave-js/blob/aeb08ea448d24430c7a5cdbaa6116522f9331138/packages/zwave-js/src/lib/node/Node.ts#L1198-L1203
Build a dependency graph (which adapter requires which one) and sort it topologically (no dependencies first, then the ones that depend on the others)

**Comment by Apollon77** [comment]
So iot was not updated in fact and you wed to update afterwards again?

Because then the easy solution would be to detect such a case and add the updates again „to the end of the queue“

**Comment by AlCalzone** [comment]
No, iot was updated, but the error message in the log might confuse users.
