### ISSUE TITLE
do not scale value if target and alias have a unit != %

### ISSUE THREAD

**Issue by Garfonso** [ioBroker/ioBroker.js-controller#1021]
Current situation:
values are scaled by the alias functionality depending on min/max values of the alias object and the target object. This makes a lot of sense for "level" states. But it is kind of awkward for states with a "real" unit (i.e. not % but °C or KWh or something).

Concrete issue:
I have a set_temperature datapoint which has a default min = -273 and max = 670670 (its KNX, KNX can only detect that it is temperature not what it is for, so the range is set pretty vast). Unit is °C. If I set the same min/max in the alias object I get the whole range to chose from in visualisations, which is nonsense and makes hitting the required temperature range of 18-26 (which is what the device supports, but KNX does not know that) very hard. So I set min/max to more appropriate values for the datapoint, but now the temperature is scaled -> 20 °C becomes something near 5°C (reading) and I was not brave enough to set something, yet... ;-)

So I thought a bit about this problem.. 
Option 1 would be to add some configuration variable to alias that prevents scaling (issue: must be done manually, what happens with values out of range, especially when writing?)
Option 2 would be to not scale values if the datapoints have a real life unit (only convert one unit to the other, if necessary, i.e. Wh to KWh). Because, if you have a real life unit like °C you probably do not want that to be scaled to something else, because 20°C is 20°C no matter in what range you put it. Does that make sense? ;-)

So my proposal would be to not scale values if unit is set (to something else than %?).

**Comment by foxriver76** [comment]
Makes sense

**Comment by foxriver76** [comment]
I am now not sure anymore if it really makes sense, because there are some edge cases where this could also screw up. A configuration variable to net scale aliases is existing. As soon as you define a read/write function. E. g. 
```javascript
        alias: {
            id: 'state.id.of.target',
            read: 'val'
        }
```
will simply disable auto-scaling.

**Comment by Garfonso** [comment]
> But if you have no min max explicitly set on the alias it should not scale anything. So the Error only occurs if you set different min max values for source and target, am I right @Garfonso?

Sorry, must have overlooked that. That is probably true. As said, the knx adapter sets min = -273 and max = 670670 for all temperature values, which is not very smart... ;-)

> I am now not sure anymore if it really makes sense, because there are some edge cases where this could also screw up. A configuration variable to net scale aliases is existing. As soon as you define a read/write function. E. g.
> 
> ```js
>         alias: {
>             id: 'state.id.of.target',
>             read: 'val'
>         }
> ```
> 
> will simply disable auto-scaling.

I would be interested of such edge cases, because the unit should indicate that the value is a measurement in that unit? 
But for me this solution is ok. My case is kind of an edge case (source object not very well defined), too.

**Comment by foxriver76** [comment]
One case we discussed is, having a valve which has `unit: '%'` but can only be opened up to `75 %`, if the user then defines a '%' on the alias with `max: 100`, it will again mess up the value. Perhaps this is only one of many edge cases. However, until now, no user reported such cases, so it may be, that my PR will improve the logic in some cases. We will also discuss this internally before we merge it.

**Comment by Garfonso** [comment]
I would allow unit = % be scaled (I even added unit != % to the issue headline 😄 ). Because % is obviously a value on some relative scale. For other units (like °C, Wh/KWh, ...) this is different, if the unit is set correctly, then only a unit conversion (i.e. Wh -> KWh) should take place and no scaling. But for unit = % I would apply the scaling.
