### ISSUE TITLE
4.0 release --> update type declarations

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.js-controller#1024]
Which methods and properties are new in 3.2 and need to be added to @types/iobroker?

- [x] adapter.setTimeout / adapter.clearTimeout
- [x] adapter.setInterval / adapter.clearInterval
- [x] adapter.getChannelsAsync
- [x] `delay`
- [ ] All the methods that now return a Promise when no callback is given

what else?

**Comment by foxriver76** [comment]
https://github.com/ioBroker/ioBroker.js-controller/blob/0b409412a152314c932c4d92828bfa2184c0d8ce/lib/adapter.js#L20

**Comment by Apollon77** [comment]
Also:
* registerNotification

**Comment by Apollon77** [comment]
* getUserId

**Comment by Apollon77** [comment]
preserve option for extendObject:
use like https://github.com/ioBroker/ioBroker.js-controller/blob/master/lib/adapter.js#L1354-L1360

**Comment by foxriver76** [comment]
Can it be closed?

**Comment by AlCalzone** [comment]
The new things Ingo posted are not done I think.

**Comment by Apollon77** [comment]
Also the get/set(Foreign)BinaryState topics!

**Comment by foxriver76** [comment]
and `delay`

**Comment by AlCalzone** [comment]
> Also the get/set(Foreign)BinaryState topics!

What changed here in terms of signature?
