### ISSUE TITLE
extendForeignObject reset state value to default

### ISSUE THREAD

**Issue by DutchmanNL** [ioBroker/ioBroker.js-controller#1025]
Controller : 3.1.6

https://github.com/iobroker-community-adapters/ioBroker.sourceanalytix/blob/master/main.js#L808

Issue ; When executing await this.extendForeignObject, the value is updated with it's default value.
If the object does not contain a "def" value, all ist fine

Expected behavior : Only attributes defined in the obj for extendForeignObject are set and the value stays as is.

**Comment by foxriver76** [comment]
Can you give a concrete example, how the curren state looked and how the def value looked.

Normally the logic is, only set default object if object did not exist or state did not exist. But codewise, there may be a lack if the current value is 0 or false

**Comment by AlCalzone** [comment]
https://github.com/ioBroker/ioBroker.js-controller/blob/0b31c14049536d5823369bb5183085424160b26c/lib/adapter.js#L2266-L2280
If `getState` returns something falsy, the default state is used to set the state. So this should only happen if the state did not exist.

**Comment by AlCalzone** [comment]
Btw line 2271 is unnecessary :)

**Comment by foxriver76** [comment]
> Btw line 2271 is unnecessary :)

Thats what I meant with `But codewise, there may be a lack if the current value is 0 or false`

**Comment by foxriver76** [comment]
> https://github.com/ioBroker/ioBroker.js-controller/blob/0b31c14049536d5823369bb5183085424160b26c/lib/adapter.js#L2266-L2280
> 
> If `getState` returns something falsy, the default state is used to set the state. So this should only happen if the state did not exist.


Thats what I meant with `But codewise, there may be a lack if the current value is 0 or false`

**Comment by AlCalzone** [comment]
Maybe Dutch is running into the error branch, so currentState is not defined although the state exists? I'm not sure what could cause that.

**Comment by DutchmanNL** [comment]
Praxis example : 

- state created manually within userdata, def = set to ""
- SA code line executes extendObject to write content in custom object
- Value of object is reset to default value

So the state did exist and was filled (javascript is just counting it up), I am using extendForeign to add custom values to the object.

Before executing extendForgeinObject:
<img width="211" alt="Schermafbeelding 2020-09-09 om 09 31 38" src="https://user-images.githubusercontent.com/7318445/92568310-458f2980-f27f-11ea-937c-0ecfdc911a7e.png">

After executing extendForgeinObject:
<img width="159" alt="Schermafbeelding 2020-09-09 om 09 32 03" src="https://user-images.githubusercontent.com/7318445/92568350-53dd4580-f27f-11ea-9aa8-b0b1fcb8de98.png">

rawData of object where this happens (def = "" but could also be 0 or whatever and that value is used)

```
{
  "from": "system.adapter.sourceanalytix.0",
  "user": "system.user.admin",
  "ts": 1599636780006,
  "common": {
    "name": "SA_kWhTest",
    "role": "",
    "type": "number",
    "desc": "Manually created",
    "unit": "kWh",
    "def": "",
    "read": true,
    "write": true
  },
  "native": {},
  "acl": {
    "object": 1638,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1638
  },
  "_id": "0_userdata.0.SA_kWhTest",
  "type": "state"
}
```

As seen in the screenshot other 2 value are fine, RawObject of them as example (No Def defined)

```
{
  "from": "system.adapter.sourceanalytix.0",
  "user": "system.user.admin",
  "ts": 1599636900060,
  "common": {
    "name": "typeTest",
    "role": "",
    "type": "number",
    "desc": "Manually created",
    "read": true,
    "write": true
  },
  "native": {},
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1636
  },
  "_id": "0_userdata.0.typeTest",
  "type": "state"
}
```

**Comment by AlCalzone** [comment]
This must go into 3.2 IMO

**Comment by DutchmanNL** [comment]
thanks guys, this was a quick one !
