### ISSUE TITLE
"Funktionen" werden nicht korrekt gesichert

### ISSUE THREAD

**Issue by JBSullivan** [ioBroker/ioBroker.js-controller#1028]
Musste heute nach langer Zeit mal wieder ein Restore mit BackItUp fahren - dabei ist mir aufgefallen, das von den "Aufzählungen" die Funktionen nicht gesichert waren. Die Räume ja, die Funktionen nicht.

Lt. Auskunft vom Entwickler des BackItUp Adapter, ist das offensichtlich ein Problem, welches durch den js-controller verursacht wird.

------------------------------------- o-Ton simatek -------------------------------------
@JB_Sullivan
Da Backitup die iobroker Backup Funktion aus dem js-controller nutzt, wäre das ein Issue für den js-controller

-------------------------------------------------------------------------------------------------

**Comment by Apollon77** [comment]
Hm ... Gibt es mehr Details? ich kann gerade mit dem Inhalt hier ehrlich nchts anfangen, nichts nachvollziehen und so auch nichts tun

**Comment by AlCalzone** [comment]
Ich denke er meint die enum.functions.

**Comment by JBSullivan** [comment]
genau die meine ich ;)

**Comment by foxriver76** [comment]
Zeig mal die `backup.json` des backups, bei mir wird `enum.functions` problemlos mitgesichert. Sicher, dass es nicht nur die fehlende Anzeige im Admin war?

**Comment by Apollon77** [comment]
@JBSullivan ??
