### ISSUE TITLE
Let's Encrypt renew/new error

### ISSUE THREAD

**Issue by peterbaumert** [ioBroker/ioBroker.js-controller#1029]
error: admin.0 (20637) Cannot get certificates: TypeError: invalid options argument

https://forum.iobroker.net/topic/33170/problem-mit-letsencrypt

I don't know if this is the right spot, if not i appologize and please tell me the right one :)

**Comment by Apollon77** [comment]
duplicate https://github.com/ioBroker/ioBroker.js-controller/issues/439
