### ISSUE TITLE
setState: interpretation of second param incorrect

### ISSUE THREAD

**Issue by Zefau** [ioBroker/ioBroker.js-controller#1037]
According to the function description, second parameter can be passed as object with all attributes (line 5675):

![image](https://user-images.githubusercontent.com/14368811/93126479-aded6900-f6cc-11ea-8a02-b15fffaae64d.png)

But `ack` will be set undefined in case an object is passed:
https://github.com/ioBroker/ioBroker.js-controller/blob/0b31c14049536d5823369bb5183085424160b26c/lib/adapter.js#L5700

**Comment by AlCalzone** [comment]
Yes, but `state.ack` will only be overwritten if `ack !== undefined`.
https://github.com/ioBroker/ioBroker.js-controller/blob/0b31c14049536d5823369bb5183085424160b26c/lib/adapter.js#L5744-L5746

Or is it not working and you wanted to report a bug?

**Comment by Zefau** [comment]
This is a bug report.

If the second argument `state` is an object including `ack`, then it will be ignored by the following code. Specifically, it will be set `undefined` in line 5700.

**Comment by AlCalzone** [comment]
I can't follow your logic. If the 2nd argument is an object and the third argument is not a boolean, then the ack parameter will be set to undefined, because that is the overload of the method without `ack`, specifically this one:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/4e302d63e9bcb3f041cc05c8f228a66731dc2d0e/types/iobroker/index.d.ts#L979-L983
In that case, the used value for `ack` should already be present on the state object.

---

If you still think this is not working as intended, please provide an example of some code that does not work like it should. And please show the result of the setState (e.g. screenshot from admin).

**Comment by Zefau** [comment]
From my understanding of the "documentation" `setState` can be used as
```js
setState('some.state.to.set', { 'val': 'myValue', 'ack': false, 'ts': Date.now()-36000 })
```

At least this is what https://github.com/ioBroker/ioBroker.js-controller/blob/0b31c14049536d5823369bb5183085424160b26c/lib/adapter.js#L5673-L5686 proposes.

In that case, `ack` will end up being set to `undefined`. The third argument is not used, since the object provided in the second argument provides the `ack`.

**Comment by foxriver76** [comment]
Yes the variable ack will be undefined but not state.ack which is what is set to the database as described by @AlCalzone. As already stated, please provide a non-working example. The above example worked as described.

**Comment by Apollon77** [comment]
Unread the code the same as @AlCalzone and @foxriver76

**Comment by Apollon77** [comment]
@Zefau still an issue?

**Comment by Zefau** [comment]
Reading the code again I understand your perspective. In fact, the above mentioned code is a non-working example for me.

Specifically, I was using
```js
.setStateAsync(state, { val: value, ts: Date.now(), ack: true });
```

which I was rewriting to 
```js
.setStateAsync(state, value, options.ack !== undefined ? options.ack : true, { ts: Date.now() }); // id, state, ack, options, callback
```
which is working now.

If this is not a bug in your perspective, feel free to close the issue. Rewriting my code solved it for me now.

**Comment by AlCalzone** [comment]
The first line should work and I currently don't see how it does not. Can you please show the result of that call?

**Comment by Apollon77** [comment]
@Zefau Is the issue solved for you? Can you please give us more details if it is an issue or now. We are very interested in good quality for the controller, so if you still have an issue we should continue discussing until we found the "core"
