### ISSUE TITLE
iobroker upload will not delete old files

### ISSUE THREAD

**Issue by Zefau** [ioBroker/ioBroker.js-controller#1041]
Using `iobroker upload <adapterName>` will only add new and update old files, but will not delete any files which are not existing anymore.

Especially challenging with React "compiled" / minified (builds) adapters, e.g. iot:

![image](https://user-images.githubusercontent.com/14368811/93870855-18eeff00-fcce-11ea-9a42-45b2d8f290ba.png)
![image](https://user-images.githubusercontent.com/14368811/93870882-2310fd80-fcce-11ea-8c1b-78bb460c7465.png)

**Comment by Apollon77** [comment]
Puuh, maybe we need to delete the www/admin first before uploading new stuff? (or check afterwards)

**Comment by foxriver76** [comment]
Hm.. so it is as designed. There is a flag that can be set in io-package called `eraseOnUpload`, if this is set to `true`, the files will be deleted. The flag is also listed here: https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/objectsschema.md#adapter

**Comment by Zefau** [comment]
Thank you very much for this!

**Comment by Zefau** [comment]
@foxriver76 @Apollon77 Do you guys have a rough indication when this will be released?

**Comment by Apollon77** [comment]
With ja-Controller 3.2. GitHub test hopefully end November. Stable approx 4 weeks later?! Roughly

**Comment by foxriver76** [comment]
imo, `eraseOnUpload` flag should also do the trick with stable controller.

**Comment by Apollon77** [comment]
really?Did we added that earlier?

**Comment by Zefau** [comment]
Yeah, looks like. Ok sorry! Thanks again.
