### ISSUE TITLE
Proper handling of regular expressions for states

### ISSUE THREAD

**Issue by UncleSamSwiss** [ioBroker/ioBroker.js-controller#1066]
The current implementation of pattern replacement doesn't work:
```js
pattern = pattern
    .replace(/\?/g, '\\?')
    .replace(/\./g, '\\.')
    .replace(/\(/g, '\\(')
    .replace(/\)/g, '\\)')
    .replace(/\[/g, '\\[')
    .replace(/]/g, '\\]')
    .replace(/\*/g, '.*');
```

Please replace it with one that also supports `+`, doesn't handle excluded characters (see below) and is faster:
```js
pattern = pattern
    .replace(/[-\/^$+.()|{}]/g, '\\$&')
    .replace(/\*/g, '.*');
```

Excluded characters are according to the code:
```js
FORBIDDEN_CHARS   = /[\][*,;'"`<>\\?]/g;
```

**Suggestion:** we could also support `?` as a single character "wildcard" similar to Windows:
```js
pattern = pattern
    .replace(/[-\/^$+.()|{}]/g, '\\$&')
    .replace(/\*/g, '.*')
    .replace(/\?/g, '.');
```

**Comment by AlCalzone** [comment]
I would suggest that we use this pattern replacer which also takes the location of wildcards in a string into account:
https://github.com/ioBroker/ioBroker.javascript/blob/master/lib/sandbox.js#L161-L176
If needed we can modify it to treat `?` as a 1-char-wildcard like @UncleSamSwiss proposed.

**Comment by foxriver76** [comment]
The `?` as single char wildcard is a good idea, as this is also used by redis. Thus we shouldn't get any unwanted interchanges.
