### ISSUE TITLE
Neustart js-controller über Weboberfläche ohne Funktion

### ISSUE THREAD

**Issue by ruhr70** [ioBroker/ioBroker.js-controller#108]
Schon seit einigen Versionen beobachtet:

Nach Update des js-controllers, muss der Rechner mit ioBroker neu gestartet werden. Die Funktion Neustart in der Weboberfläche hat keine Auswirkung.

Das Fenster geht  zwar mit folgender Meldung auf:

```$ ./iobroker _restart
Starting node restart.js
process exited with code 0
```

Die Version bleibt allerdings alt, z.B.: 0.7.10(Running: 0.7.7)

**Comment by GermanBluefox** [comment]
Mit 0.7.14 muss gehen.
