### ISSUE TITLE
Unnötiges Schreiben verhindern

### ISSUE THREAD

**Issue by peterfido** [ioBroker/ioBroker.js-controller#1080]
Beim schreiben eines Objekts zu schauen was vorher drin stand und nur wenn gleich eine Änderung zu vermerken ist, wirklich schreiben.

**Comment by foxriver76** [comment]
https://github.com/ioBroker/db/issues/10

**Comment by Apollon77** [comment]
duplicate https://github.com/ioBroker/db/issues/21
