### ISSUE TITLE
getAdapterObjects does not include folders

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.js-controller#1085]
https://github.com/ioBroker/ioBroker.js-controller/blob/d5c4806fe0218af0732e35c21419d8e0eb9cfcc7/lib/adapter.js#L1870

From what I understand, the object type `folder` should be used if the classical structure `device.channel.state` is not a good match for an adapter or deeper nested structures are needed.
However, there's no way to enumerate all objects of an adapter when using `folder` objects.

**Comment by Apollon77** [comment]
Hehe. Yes See should also return folders
