### ISSUE TITLE
ioBroker start fails when log path is invalid

### ISSUE THREAD

**Issue by JojoS62** [ioBroker/ioBroker.js-controller#1101]
After switching from a windows to a linux installation by using the backup file, the logfile path was invalid for the linux system. This happened because the default logging dir on the windows installation was changed.
Starting the js-controller did not create a log and stopped silently, the exception was only shown by manual starting:

```
jojo@iobroker-prod:/opt/iobroker$ node node_modules/iobroker.js-controller/controller.js
internal/fs/utils.js:269
    throw err;
    ^

Error: EACCES: permission denied, mkdir '/IoBrokerLogs/'
    at Object.mkdirSync (fs.js:921:3)
    at /opt/iobroker/node_modules/file-stream-rotator/FileStreamRotator.js:654:20
    at Array.reduce (<anonymous>)
    at mkDirForFile (/opt/iobroker/node_modules/file-stream-rotator/FileStreamRotator.js:642:27)
    at Object.FileStreamRotator.getStream (/opt/iobroker/node_modules/file-stream-rotator/FileStreamRotator.js:519:5)
    at new DailyRotateFile (/opt/iobroker/node_modules/winston-daily-rotate-file/daily-rotate-file.js:80:57)
    at /opt/iobroker/node_modules/iobroker.js-controller/lib/logger.js:165:34
    at Array.forEach (<anonymous>)
    at logger (/opt/iobroker/node_modules/iobroker.js-controller/lib/logger.js:114:48)
    at Object.init (/opt/iobroker/node_modules/iobroker.js-controller/main.js:4161:40) {
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path: '/IoBrokerLogs/'
}
```

This error could be caught and the default logging directory should be tried.

**Comment by Apollon77** [comment]
Hm ... In my yes an invalid configuration should always be very visible and yes then that error can be thrown and iobroker should not start - yes it could be catched and logged "nicer", but thats all.

I'm against silently ignoring invalid configuration. So in your case I think iobroker-data/iobroker.json should be changed accordingly.

**Comment by JojoS62** [comment]
> I'm against silently ignoring invalid configuration.
yes, me too. Its only about getting some information about the error. With 'iobroker start' the crash message is not shown in the console. 

> So in your case I think iobroker-data/iobroker.json should be changed accordingly.
yes, that is how I fixed the problem.

Maybe it is better to check some settings in ioBroker.json before restoring?
