### ISSUE TITLE
Prevent adapter error restart loops

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#1128]
The js-controller should basically already prevent adapter start loops when the adapter never reports an alive after the start. In such cases the adapter is stopped after 3 tries.

But when the adapter basically starts but then crash some seconds later because of a connection issue or such then the adapter runs into an crash-restart-loop.

We should add a detection for this for deamon type adapters if they run "only too short" and crash then (so not a normal end). Time could be 30-60s (??)

What do you think?

**Comment by AlCalzone** [comment]
Can we not check the exit code instead of having a heuristic for the time?
Node.js crashes normally have exit code 1.

**Comment by Apollon77** [comment]
yes but is it that problematic if the adapter crashes once a day and gets restarted?

**Comment by Apollon77** [comment]
We have many adapters where error handling is far from being ideal ;-) ... so a nightly reconnect of internet could cause such a restart ... which is completely ok.

It is only bad (and we had such a case these days on hm-rpc or I on alexa2 where because of reasons 2 users generated >1k sentry messages ;-)

**Comment by AlCalzone** [comment]
I guess we should reset the counter after a certain time. So if an adapter crashes twice, but then runs over (lets say) 10 minutes, it is not in a restart loop.
