### ISSUE TITLE
Move Tests for States/Objects into db repo

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#1139]

**Comment by Apollon77** [comment]
Basics are done, thanks to @AlCalzone 

Rest:
* check which tests should be moved to db repo itself in general (all that are not run via "adapter")
* decide if we still need Redis checks in js.controlelr or only in db repo

**Comment by foxriver76** [comment]
Do we still want to do this? Currently all tests are executed by both repositories and basically I think this isn't bad. Especially, having the adapter tests etc also running if underlying DB changes, because this can affect those functionalities too.

**Comment by foxriver76** [comment]
We plan to move everything in a monorepo so would no longer see this as an open issue

**Comment by Apollon77** [comment]
right
