### ISSUE TITLE
Adjust Object ID Regex to respect "adapter naming check"

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#1152]
In the DB CLient we have defined this regex for an object ID: https://github.com/ioBroker/db/blob/master/packages/db-objects-redis/lib/objects/objectsInRedisClient.js#L73 This kind of defined the first character of an adaptername limitation.

The Regex for FORBIDDEN_IDs do not refect this definition for the first charactr. SHould we sync that?

**Comment by foxriver76** [comment]
I don't see a first character limitation there, could you explain what you mean?

**Comment by Apollon77** [comment]
The linked regect define this regex for the "first letter of any object"

[_A-Za-z0-9]+

in fact the first part of objects is the adaptername :-)

**Comment by foxriver76** [comment]
I think we should pretty much keep it in sync with https://github.com/ioBroker/ioBroker.js-controller/blob/2b7284bdcb7100c11469e7dc1f3d24b34f69fa57/lib/tools.js#L38 as a single point of truth, like adjusting ioRegExp to just checking that we have the correct iob objects namespace and then checking for `!FORBBIDEN_CHARS.test(channel)'`, else we have multiple files we have to maintain when changing the regexp.

**Comment by Apollon77** [comment]
Yes we can sync them ... just the obe in DB adds stuff at the beginning ...
