### ISSUE TITLE
CLI debug always starts adapter instance zero

### ISSUE THREAD

**Issue by raintonr** [ioBroker/ioBroker.js-controller#1154]
Trying to debug instance one of web adapter in my system I do this:

```
DEBUG=* node /opt/iobroker/node_modules/iobroker.js-controller/iobroker.js debug web.1
```

However, notice that this actually fires up instance zero. In fact, notice that the instance number given is completely ignored (ie. can be omitted completely or put any random number in there - makes no difference).

To debug instance number > 0 is useful if one wants to debug a specific instance configuration, check side effects of running multiple adapters, etc.

**Comment by Apollon77** [comment]
yes just "iobroker debug name instancenumber" ( so separate by space and not "point"

**Comment by Apollon77** [comment]
But yes we could also parse the name and split the instance name out there

**Comment by raintonr** [comment]
> yes just "iobroker debug name instancenumber" ( so separate by space and not "point"

I this documented anywhere?

**Comment by Apollon77** [comment]
ok, I check it ... it is not in yet and so a feature request
