### ISSUE TITLE
'Cannot find search "folder" in "system"' bei JS-Controller 3.2.[1-2] 

### ISSUE THREAD

**Issue by SBorg2014** [ioBroker/ioBroker.js-controller#1165]
Nach Update auf 3.2.[1-2] von etlichen Adaptern, besonders beim Shelly im 5 Sekunden-Rhythmus

unter Linux und File-DB.
ioB stoppen und ein nochmaliges "iobroker setup first" brachte keinen Erfolg.

**Comment by Apollon77** [comment]
fixed in 3.2.3
