### ISSUE TITLE
[feature request] Bei [y]es / [n]o - Abfrage noch [a]ll hinzufügen

### ISSUE THREAD

**Issue by SBorg2014** [ioBroker/ioBroker.js-controller#1178]
Ich kann ja zB. mittels iob upgrade --y einen unattended Upgrade ausführen. Es wäre schön wenn dies auch noch nachträglich bei ohne "--y" möglich wäre. Könnte man zur [y]es / [n]o Abfrage noch ein [a]ll hinzufügen?

**Comment by Apollon77** [comment]
@foxriver76 @AlCalzone @GermanBluefox What do you think?

**Comment by foxriver76** [comment]
Finde ich ziemlich unkonventionell, man kann doch an jeder Stelle abbrechen und dann mit der Flag neu durchlaufen lassen wenn man merkt dass man sie vergessen hat.

**Comment by SBorg2014** [comment]
Ich hatte aber auch schon den Fall mal ein Update explizit auslassen zu wollen, bei einem ganzen Haufen an Updates. Unattended kann ich es so dann nicht laufen lassen, wenn ich aber dann das "unerwünschte" erreicht und ausgelassen habe, kann ich so trotz allem jetzt automatisch beenden.

**Comment by AlCalzone** [comment]
Nitpick: optionen sind üblicherweise entweder lang `--yes` oder kurz `-y` :)

**Comment by foxriver76** [comment]
> Nitpick: optionen sind üblicherweise entweder lang `--yes` oder kurz `-y` :)

Soweit ich das sehe parsed `yargs` sowohl `-- ` als auch `-` nach argv und lässt sich somit erst mal nicht unterscheiden, ohne jetzt nachzusehen ob man das parsing verhalten verändern kann. Somit lässt der check auf params.y beispielsweise `-y` als auch `--y` zu.

**Comment by AlCalzone** [comment]
Möglich ist es, es ist aber konvention, die langversion einer option mit zwei dashes zu versehen und die Abkürzung mit einem.
Siehe u.a. Man pages vieler Linux tools

**Comment by foxriver76** [comment]
Ja ich weiß, dass das Verhalten u.a. bei `apt` selbiges ist, was jedoch nichts an dem yargs Verhalten ändert.

**Comment by AlCalzone** [comment]
Ich glaube wir nutzen nicht die [yargs.options()](https://yargs.js.org/docs/#api-reference-optionskey-opt) methode oder?

**Comment by foxriver76** [comment]
Ne nutzen wir nicht, kommt allerdings für den Fall auf das gleiche heraus.

```javascript
        case 'upgrade': {
            yargs
                .command(
                    'upgrade',
                    'Upgrade adapter/s',
                    (yargs) => {
                        return yargs.option('a', {
                            alias: 'all',
                            describe: 'Upgrades all adapters'
                        });
                    },
                    function (argv) {
                        console.log(argv.all)
                    }
                )
                .argv;

            console.log(yargs.argv);
```

```
iob upgrade -a
```
ergibt
```
true
{
  _: [ 'upgrade' ],
  a: true,
  all: true,
  '$0': '/opt/iobroker/node_modules/iobroker.js-controller/iobroker.js'
}
```
Es wird zwar das `a` nun automatisch auch zu all geparsed, `--a` allerdings auch weiterhin.

``` 
iob upgrade --a
```

```
true
{
  _: [ 'upgrade' ],
  a: true,
  all: true,
  '$0': '/opt/iobroker/node_modules/iobroker.js-controller/iobroker.js'
}
```

Also wäre etwas schicker als die aktuelle Mechanik, allerdings noch nicht das was wir wollen.

**Comment by AlCalzone** [comment]
Hm mir gehts auch eher drum die Option in der Doku (Befehlsauflistung) entsprechend der Konvention anzugeben. Wenn neben `--yes`, `-y` auch noch `--y` funktioniert (undokumentiert), soll mir das recht sein ;).
