### ISSUE TITLE
Preserve name field on instance object creation/update 

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#1183]
When we update instance objects (or objects configured in io-package.json) we should preserve the common.name field ... maybe add that as a general option to extendObject and use extendObject for object updates/creations.

needed for clean solution for https://github.com/Apollon77/ioBroker.daikin/issues/54

**Comment by foxriver76** [comment]
`extendObject` could respect `options.preserve` which defines which elements should not be overwritten if they already exist. The object creation at instance creation should be okay https://github.com/ioBroker/ioBroker.js-controller/blob/11a08366cbde71f23597256576a92fc488ba50ad/lib/setup/setupInstall.js#L1017 and on adapter level, we could then use `adapter.extendForeignObject` with the new option.
https://github.com/ioBroker/ioBroker.js-controller/blob/11a08366cbde71f23597256576a92fc488ba50ad/lib/adapter.js#L1313

**Comment by Apollon77** [comment]
Like that idea!!

**Comment by Apollon77** [comment]
Want to add for 3.2? :-)

**Comment by foxriver76** [comment]
maybe ;-)

**Comment by foxriver76** [comment]
okay seems like

**Comment by Apollon77** [comment]
Thank you very much!!
