### ISSUE TITLE
Adjust Typings after adjusting Promise rejects in PR #1185

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#1187]
List:

- [x] setObject
- [x] getAdapterObjects
- [x] extendObject
- [x] setForeignObject
- [x] extendForeignObject
- [x] getObject
- [x] getObjectView
- [x] getObjectList
- [x] getEnum
- [x] getEnums
- [x] getForeignObjects
- [x] findForeignObject
- [x] getForeignObject
- [x] delObject
- [x] delForeignObject
- [x] subscribeObjects
- [x] unsubscribeObjects
- [x] subscribeForeignObjects
- [x] unsubscribeForeignObjects
- [x] setObjectNotExists
- [x] setForeignObjectNotExists
- [x] createDevice
- [x] createChannel
- [x] createState
- [x] deleteDevice
- [x] addChannelToEnum
- [x] deleteChannelFromEnum
- [x] deleteChannel
- [x] deleteState
- [x] getDevices
- [x] getChannelsOf
- [x] getChannels
- [x] getStatesOf
- [x] addStateToEnum
- [x] deleteStateFromEnum
- [x] chmodFile
- [x] readDir
- [x] unlink
- [x] rename
- [x] mkdir
- [x] readFile
- [x] writeFile
- [x] fileExists - **MISSING**
- [x] sendTo
- [x] sendToHost
- [ ] registerNotification - **MISSING**
- [x] setState
- [x] setStateChanged
- [x] setForeignState
- [x] setForeignStateChanged
- [x] getState
- [x] getForeignState
- [ ] ?? getHistory
- [x] delState
- [x] delForeignState
- [x] getStates
- [x] getForeignStates
- [x] subscribeForeignStates
- [x] unsubscribeForeignStates
- [x] subscribeStates
- [x] unsubscribeStates
- [ ] getSession - **MISSING**
- [ ] setSession - **MISSING**
- [ ] destroySession - **MISSING**
- [x] setBinaryState
- [x] getBinaryState
- [x] delBinaryState - **MISSING**
- [ ] pushFifo - **MISSING**
- [ ] trimFifo - **MISSING**
- [ ] getFifoRange - **MISSING**
- [ ] getFifo - **MISSING**
- [ ] lenFifo - **MISSING**
- [ ] subscribeFifo - **MISSING**

**Comment by AlCalzone** [comment]
I've identified a few missing methods from the type definitions. Back when I wrote them I didn't understand the session and FIFO stuff - and I still don't.
These are new to me:
* registerNotification
* fileExists
* getHistory (I didn't think this has a Async version)

**Comment by Apollon77** [comment]
fifo = deprecated ... so gone (was just there for completeness)

**Comment by Apollon77** [comment]
The first of the three named ones are new, correct

**Comment by Apollon77** [comment]
@AlCalzone we do not do it right?!

**Comment by AlCalzone** [comment]
correct - I only added the new ones (except registerNotification, which I haven't gotten to so far)
