### ISSUE TITLE
Feature idea: Detect difference between system timezone and configuration in ioBroker

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.js-controller#1198]
and notify the user (since we now have that shiny notification system).

**Comment by trollvottel** [comment]
Where can this even be configered in ioBroker?!

**Comment by AlCalzone** [comment]
not directly, but if you have a location configured one could calculate which timezone you should be in.

**Comment by foxriver76** [comment]
@Apollon77 mainly an Admin enhancement, does admin needs anything from controller for this, like system time?

**Comment by Apollon77** [comment]
Yes we would maybe need to include the "local system time" into a host data response to compare
