### ISSUE TITLE
Adapter restart loop

### ISSUE THREAD

**Issue by algar42** [ioBroker/ioBroker.js-controller#1217]
It is really good feature to detect adapter restart loops and stop restarting after 3 crashes. But can we also implement maybe some additional delay after which js-controller will make yet another try to start adapter? 
E.g. my system uses mobile internet and it sometimes happens that internet is down for 15-30 minutes. During this time some adapters (like Telegram) crashes while attempting to connect to the server and js-controller stops them.. 
Really it is not what I'm expecting from home control system. e.g. Telegram stopped by system makes me think that everything is Ok as I'm not receiving any messages from IoBroker.. 
I understand that adapters should be updated to try-catch such crashes, but do you think it is really possible for all the adapters to be updated to catch all the possible crashes that may happen?

**Comment by Apollon77** [comment]
In fact yes the adapter would need to take care here ... can you please open another issue (or update existing) on relevant adapters so that we can try to fix there
