### ISSUE TITLE
Wrong logger date pattern

### ISSUE THREAD

**Issue by UncleSamSwiss** [ioBroker/ioBroker.js-controller#1225]
The following logger date pattern causes issues on Windows:
https://github.com/ioBroker/ioBroker.js-controller/blob/da83438c399bfed708b03e4f3ddfe7c5ace4b3e1/lib/logger.js#L321

The resulting path ends in something like `\\log\\iobroker..2021-02-Th.2/4\\`. This directory name can't be created under Windows (mkdir: ENOENT)

My guess is, it actually interprets `dd` as short day of week and also the string `log` gets interpreted as shortcut instead of a literal. Also, this is the directory name, so I think there is no need for a file extension.

I know, this line of code shouldn't be reached under normal circumstances, but still, it should be corrected or removed.

**Comment by UncleSamSwiss** [comment]
The issue stems from the way the logger is configured when no config file is found:

https://github.com/ioBroker/ioBroker.js-controller/blob/da83438c399bfed708b03e4f3ddfe7c5ace4b3e1/main.js#L119-L124

**Comment by foxriver76** [comment]
It looks like the date pattern and filename are a little bit mistaken here.
