### ISSUE TITLE
Rethink auto encryption via encryptedNative

### ISSUE THREAD

**Issue by foxriver76** [ioBroker/ioBroker.js-controller#1227]
Currently, we need to maintain admin as well as js-controller for autoEncryption feature and they are a little bit out of sync. Also whenever we change the encryption mechanism, we have to update both. Why we don't just do encryption as well as decryption (already done) in js-controller. 

So on `adapter.setForeignObject` (+ maybe extend for all cases via CLI) which is called by admin to save the settings https://github.com/ioBroker/ioBroker.admin/blob/e15daa15a882b79fe5bd53fb64627d72619ad33e/src/js/adapter-settings.js#L283 we would simply check if it's a `system.adapter.name.instance` object, if yes, then check for the presence of `encryptedNative` if it's matching then encrypt all matching native attributes. Finally, set it to the DB.

Another big advantage that initially led me to this idea is, that then attributes will also be encrypted if someone configures an instance completely via CLI instead of admin. This currently would lead to malfunctions in some adapters, because they will try to decrypt a value that has never been encrypted.

Thoughts on this?

**Comment by Apollon77** [comment]
I think the main reason to do it in admin is that you else would need to transfer the plan text data via HTTP to the server side ...

**Comment by foxriver76** [comment]
Then we should detect if already encrypted, else do it so cli config would be possible and over https Admin could maybe also send plain so we then have the state of the art encryption in all cases except for http admin.

**Comment by foxriver76** [comment]
Okay, due to the fact, that objects set/extend is using the objects db directly I would just implement it in those cli commands
