### ISSUE TITLE
Caught by controller[0]: FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by RESDE** [ioBroker/ioBroker.js-controller#1231]
Hallo,

seit einem der letzten Updates strauchelt der JS controller:
er wird vom PI Host gestoppt aufgrund der Fehlermeldung "Caught by controller[0]: FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory)
JS Adapter wird genau 3x neu gestartet und verabschiedet sich dann auf Pause modus quasi unendlich pausierend.

IObroker läuft seit 1 Jahr stabil auf einem PI4B mit 8GB Ram.  Parallel zu JS Adapter laufen KNX, SQL Adapter, WEB, Simple API, Hue-extended, modbus... aber die Belasten den IOBroker host ressourcentechnisch nicht.

Folgendes habe ich schon versucht:
-alle anderen Adapter pausieren obwohl die RAM Ressource noch zwischen 70-80% verfügbar ist.
- Downgrade von aktueller Version auf jetzt 4.10.11, leider keine Besserung.

JS Controller ist Version 3.12.14
Node Version: 10.23.2
Könnte mir bitte jemand helfen, dass ich den JS Adapter wieder stabil ans Laufen bekomme, da ich dringend einige Blockly Script wieder anwerfen muss bei dieser Kälte sind damit kritische Bereiche getThemen in unserem Zuhause.
Benutze einige Blockly Scripts, die immer alle brav Ihren Dienst gemacht hatten.
Danke.

**Comment by Apollon77** [comment]
Bitte auf 3.2.16 updaten.Dann weg?

**Comment by Apollon77** [comment]
PS: ggf syslog aktiv?
