### ISSUE TITLE
Check object write flag on setState and similar

### ISSUE THREAD

**Issue by Garfonso** [ioBroker/ioBroker.js-controller#1234]
Like the checks proposed in #698 it would be a good idea to start checking the write-flag on setState and emit a warning (and later an error?) if write is false. Currently I don't see much effect of write: false. Only admin honors it, it seems.

**Comment by foxriver76** [comment]
So who is allowed to write to a read-only state? Only own instance? E.g. hm-rega updates states for hm-rpc this could be a problem.

**Comment by Apollon77** [comment]
noooo ... I would see it like "if read only then only setState with ack=true are allowed" -.. no forbid ack=false

**Comment by foxriver76** [comment]
Not sure if this is what was intended by @Garfonso and maybe would lead to other confusions?

**Comment by Apollon77** [comment]
@Garfonso ?
But in the end this is the only interpretation that makes sense in my opinion. Someone needs to be allowed to write to a "read only state" and becasue of the nature all "commands" (ack=false) are impossible by definition, so only final values are allowed on that.
Now the question is if the owninstance is the only one which will be problematic for userdata_0 states btw ... thats why I would propose to only check "ack" flag on that

**Comment by Garfonso** [comment]
ack = true makes sense. That's how I interpret the write = false flag, too, for sensor readings or things like that, that the user can not change. 
I did not think about other adapters, tbh. Maybe checking ack flag makes most sense and avoids problems in such cases.
