### ISSUE TITLE
Feature idea: execute TypeScript adapters directly with ts-node

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.js-controller#1236]
The basic idea is that we can invoke TypeScript adapters with https://github.com/TypeStrong/ts-node, a TypeScript wrapper around node. We could detect if the `main` file has a `.ts` extension and invoke it the following way instead:

```
node -r ts-node/register/transpile-only main.ts ...arguments...
```

Questions left to be solved (would be best if these are not necessary):
- [ ] Does the adapter need to include `tsconfig.json`?
- [ ] Does the adapter need to include `@types` packages as `devDependencies`?

**Comment by AlCalzone** [comment]
There is a new kid on the block: [esbuild](https://github.com/evanw/esbuild) with a [runner](https://www.npmjs.com/package/esbuild-runner) similar to ts-node.
Might want to use that instead, it is much much faster.

**Comment by Apollon77** [comment]
Still uncertain for compact mode!!

**Comment by Apollon77** [comment]
@AlCalzone Whats still open?? Only documentation and getting infos?

**Comment by foxriver76** [comment]
Something left to do?

**Comment by AlCalzone** [comment]
Documentation and verifying that everything works in compact mode.

**Comment by foxriver76** [comment]
I will try it in compact mode

**Comment by foxriver76** [comment]
Comapct mode works, also `iob debug` works with ts-node adapters
