### ISSUE TITLE
Command "plugin disable sentry" doesn't work immediately after installation

### ISSUE THREAD

**Issue by UncleSamSwiss** [ioBroker/ioBroker.js-controller#1240]
When installing ioBroker without starting it, I get the following error when calling:

```bash
user@my-host-name:/opt/iobroker$ iob plugin disable sentry
The host "my-host-name" does not exist!
```

Even if I do a `iob host this` before the above command, I still get the same error.

**Comment by foxriver76** [comment]
why dont we just create raw host object at `iob setup` @Apollon77 ?

**Comment by Apollon77** [comment]
Till now on install and first start there could be different hostnames. If we create a host and then the name has changed on first start there could be weird cases where system thinks it is multihost. If we do we need to make sure this can not happen.

**Comment by Apollon77** [comment]
Is the hostname pinned in iobroker.json?? Then we could think about it for this case.

**Comment by foxriver76** [comment]
in both my installations `system.hostname` is just an empty string in iobroker.json

**Comment by foxriver76** [comment]
But the same issues would happen if someone renames host later, or not? maybe you can give some details regarding the mentioned case..

**Comment by foxriver76** [comment]
it seems that iobroker.json `system.hostname` is only set when `iob host` is used

**Comment by Apollon77** [comment]
When system.hostname is empty then the real hostname is requested and used. When yu set syste.hostname (and yes this is done when using ´iob host` you overwrite the hostname to define that the configured one is used over the "real" one.

**Comment by UncleSamSwiss** [comment]
The problem about the changing hostname is exactly as @foxriver76 said: in the Docker image we actually have to change the hostname at first start-up: 
It is set during the build process of the temporary build container [here](https://github.com/buanet/ioBroker.docker/blob/a919ca07380a9dac31393ca0aae49e4ddfa0feef/aarch64/Dockerfile#L70) and then fixed to the hostname of the running container [here](https://github.com/buanet/ioBroker.docker/blob/a919ca07380a9dac31393ca0aae49e4ddfa0feef/aarch64/scripts/iobroker_startup.sh#L188).

In my case, the hostname is defined in the config file, so this would would also be enough.

Now, this issue is no longer pressing for me as @Apollon77 pointed out that setting diag to "none" also disables Sentry.

**Comment by foxriver76** [comment]
> Till now on install and first start there could be different hostnames. If we create a host and then the name has changed on first start there could be weird cases where system thinks it is multihost. If we do we need to make sure this can not happen.

With the name could be changed between `setup` and first start you mean via `iob host` command or do you mean something else? Because `iob host` will rename the old objects and so there shouldn't be two host objects. Let me know if there are any concerns, else we could create the raw host object already in setup first, will then be extended on controller start.
