### ISSUE TITLE
js-controller wird nach einem Stromausfall nicht mehr gestartet 

### ISSUE THREAD

**Issue by motugozu** [ioBroker/ioBroker.js-controller#1241]
Hallo  

ich habe die Version 3-2-16  installiert  mir ist gestern der Stromausgefallen und seit dem startet mein Iobroker nicht mehr bzw der JS controller  startet nicht  bei früheren versionen hatte ich nie Probleme mit  dieser art

**Comment by Apollon77** [comment]
naja was sagt denn das System? Was sagen die Logs? Bei Stromausfall gibt es eine große Wahrscheinlichkeit das das Filesystem defekt ist. In meinen Augen wird das zu 100% nichts mit ioBroker an sich zu tun haben
