### ISSUE TITLE
ESPHome Adapter not starting

### ISSUE THREAD

**Issue by FredF63** [ioBroker/ioBroker.js-controller#1251]
@Apollon77 as requestet via [forum](https://forum.iobroker.net/topic/42741/esphome-beta-release/38?_=1614580980660)
[ESPHomeFehler.txt](https://github.com/ioBroker/ioBroker.js-controller/files/6060006/ESPHomeFehler.txt)

**Comment by Apollon77** [comment]
Sorry, Not you misunderstood it. I asked for an issue with the "iobroker url "...": was not working because master was not found
