### ISSUE TITLE
Blockly "Schreibe Objekt ID" übernimmt keine Werte aus Variablen

### ISSUE THREAD

**Issue by ITCrowdIOB** [ioBroker/ioBroker.js-controller#1262]
![grafik](https://user-images.githubusercontent.com/64137907/111633036-5fdd2d80-87f5-11eb-8ab0-df5bf9f01c56.png)
 
Seit Version 5.x übernimmt das Blockly "Schreibe Objekt ID" keine Werte die über Variable programmiert worden sind. Direkte Werteeingaben werden korrekt verarbeitet.

**Comment by Apollon77** [comment]
Bitte issue im Javascript adaptert anlegen und auch den generierten Javascript code zeigen
