### ISSUE TITLE
Backup Validation false positives on invalid json files

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#1268]
When we validate the backup we do a JSON file content validation if the Filename ends with ".json". We do this to make sure that a broken FS or such did not compromised the backup.

This is basically good, BUT if the user or an adapter managed to create an invalid file with .json in storage the backup will always fail because of the validation fails ...

We should find a way to handle these false positives better. Ideas could be to just verify the "important big json" with all objects/states. or if we find an error we also compare the original file an donly fail if this one is a valid json or such?! Other ideas welcome

**Comment by foxriver76** [comment]
is this a problem which actually came up or just of theoretical nature?

**Comment by Apollon77** [comment]
We saw that 2-3 times in Forum and also BF had a "manuel support case" where minuvis manages to create an empty file called ".json" and backup was no longer working because validation errored on it ...

I just decided now to create an issue for it

**Comment by foxriver76** [comment]
What are the important backup files besides backup.json? 

We currently have to methods, one to check the backup after creation, I would adapt this one to only abort the process if backup.json is corrupted, else only log warnings/errors which files are corrupted.

**Comment by Apollon77** [comment]
As I know we pack all data in backup.json so this needs to be correct... all rest should be copied and so I would not care
