### ISSUE TITLE
letsencrypt cert renewal tries although it is disabled

### ISSUE THREAD

**Issue by Diginix** [ioBroker/ioBroker.js-controller#1284]
js-controller 3.2.16
web 3.3.0
nodejs 12.21.0

web adapter instance tries to renewal my LE cert after 1 month, although this feature is disabled in the settings. 
Port 80 is only open for iobroker every 3 months when I manually renewal the LE cert. Otherwise this port is used for other device. So, it is senseless to try it multiple times per day and this already after first month of creation.

web.0 2021-04-04 09:47:01.846 error (2308) [LE] {"code":"E_FAIL_DRY_CHALLENGE","context":"cert_renewal","subject":"mydomain.tld","altnames":["mydomain.tld"]}

**Comment by foxriver76** [comment]
We need to set `renew: false` in such a case at

https://github.com/ioBroker/ioBroker.js-controller/blob/8b7f8e01aabfd58dd6ee7fa778645b777e5362b5/lib/letsencrypt.js#L58

if not it will try to check every ~90 min 

https://github.com/coolaj86/greenlock/blob/006e15ac5358551c90ef59357174ae19f2929115/greenlock.js#L102

probably it's already in `leSettings.renew` in letsencrypt.js if it's passed from https://github.com/ioBroker/ioBroker.web/blob/451b8ea93186a57f6b35aeaae1a3e90ac80d33d7/main.js#L795

@Diginix can you show me an example `system.certificates` object when using LE, just remove the certs itself

**Comment by Diginix** [comment]
@foxdriver76

> {
>   "_id": "system.certificates",
>   "type": "config",
>   "common": {
>     "name": "System certificates"
>   },
>   "native": {
>     "certificates": {
>       "defaultPrivate": "-----BEGIN RSA PRIVATE KEY-----\r\n...\r\n-----END RSA PRIVATE KEY-----\r\n",
>       "defaultPublic": "-----BEGIN CERTIFICATE-----\r\n...\r\n-----END CERTIFICATE-----\r\n"
>     },
>     "letsEncrypt": {
>       "path": "letsencrypt",
>       "email": "myemail@mail.tld",
>       "domains": "domain.com"
>     }
>   },
>   "acl": {
>     "owner": "system.user.admin",
>     "ownerGroup": "system.group.administrator",
>     "object": 1536
>   },
>   "from": "system.host.iobroker.cli",
>   "ts": 1518630934064,
>   "user": "system.user.admin"
> }

**Comment by foxriver76** [comment]
If you have a test instance or if you are confident with your installation, you could manually modify this line of the file as shown here: https://github.com/ioBroker/ioBroker.js-controller/pull/1285/files#diff-97fdb895e7e586349a03b223246d95bfb49cc982bf0904da45c1c987247a19b0R64

I would assume that it fixes the problem. However, I have no LE running and can't test easily

**Comment by Diginix** [comment]
@foxriver76 
No problem so far, but there is another difference on my letsencrypt.js compared to you version on git in line 22 that is now shown in the git commit diff:
original line from js-controller 3.2.16:
`    if (typeof leSettings.domains === 'string') {`
your git commit:
`    if (leSettings && typeof leSettings.domains === 'string') {`

**Comment by foxriver76** [comment]
These two lines are the only two changes since January.

You can use the version from my `le-update` branch, you can find the file here https://raw.githubusercontent.com/foxriver76/ioBroker.js-controller/le-update/lib/letsencrypt.js

**Comment by Diginix** [comment]
Ok, you have done the patch not on the 3.2 branch. I have updated the file now and restarted the host.
Let's see what happens in around 90 min.

btw: it is not possible to restart the js-controller here:
![image](https://user-images.githubusercontent.com/39678667/113923873-59851480-97e9-11eb-9166-e2b5def57019.png)

**Comment by foxriver76** [comment]
> ![image](https://user-images.githubusercontent.com/39678667/113924765-7b32cb80-97ea-11eb-9be7-0e060f75ffc9.png)

Yes, this is the flag which should be represented by `settings.leUpdate`

**Comment by Diginix** [comment]
2 minutes after iobroker restart yesterday there was one fail try with the patched file. But only once and since then I haven't seen any other tries/error log entries with the patched file until now.
Seems to work.
In the past I have renewal the LE cert by hand in CLI.
If I open port 80 and enable the auto renewal in web.0 instance, will it trigger the renewal immediately or should I continue to do it manually?

**Comment by foxriver76** [comment]
> If I open port 80 and enable the auto renewal in web.0 instance, will it trigger the renewal immediately or should I continue to do it manually?

I am not deep into this LE/greenlock management, if you say you still had one renewal try after the new code runs, I could imagine that it still tries it once at the start. In greenlock code, if `get` is called it seems like it tries to renew not respecting the set options https://github.com/coolaj86/greenlock/blob/006e15ac5358551c90ef59357174ae19f2929115/greenlock.js#L212

maybe this is called once at the beginning, in this case, just changing the option in the web adapter instance would lead to a renewal at instance startage.
