### ISSUE TITLE
Flag for delete custom settings 

### ISSUE THREAD

**Issue by Jey-Cee** [ioBroker/ioBroker.js-controller#1292]
Actual custom settings for objects are not deleted when adapter will be uninstalled.

Idea is to ask the user if he wants to delete these settings when uninstall the adapter.

**Comment by foxriver76** [comment]
So option in controller needed, but popup and co on admin side to use this option if user says yes

**Comment by Apollon77** [comment]
I would see a cli param and the logic here on delete instance logic. AFterthat it will be in "next" controller and then it can be added to admin
