### ISSUE TITLE
After Upgrading to 3.3.1 - Warnings "wrong type "string" but has to be "number""

### ISSUE THREAD

**Issue by ajeder** [ioBroker/ioBroker.js-controller#1299]
Good Morning,

I've  never posted an issue here, so I hope I am doing it the right way.
After Upgrading to Version 3.3.1 the LOG includes many warnings concerning not only one specific adapter, but nearly all adapters.

Here's the message for example with the "tuya-adapter":

tuya.0 | 2021-04-30 06:33:15.040 | warn | (27978) State value to set for "tuya.0.77165603bcddc28afb2a.2" has wrong type "string" but has to be "number"

The same message is spread over the variety of installed adapters.
It is always the same Warning:  ..."has wrong type "string" but has to be "number"

Thx for your great work on this project.

Greetings,

Axel

**Comment by vaaarg** [comment]
omg log is flooded with warnings as mentioned above

**Comment by TheBrain26** [comment]
same Problem since upgrade js-controller

**Comment by HGlab01** [comment]
I understand the data quality check in the controller.
I think the log-message is missleading, e.g.
`.serialNo" has wrong type "string" but has to be "number"`
This state is currently defined as number, so the message should be
`has wrong type "number" but has to be "string"`
isn't it?

**Comment by itProfi** [comment]
same problem
![Uploading Скриншот 30-04-2021 085557.jpg…]()

**Comment by KayThe95** [comment]
same problem!

**Comment by Apollon77** [comment]
Please create issues for each adspter where you experience this!!The adapters need to adjust that!

**Comment by HGlab01** [comment]
Hi @Apollon77!
Please have a look at this:

I think the log-message is missleading, e.g.
`.serialNo" has wrong type "string" but has to be "number"`
This state is currently defined as number, so the message should be
`has wrong type "number" but has to be "string"`
isn't it?
