### ISSUE TITLE
3.3.1 Backup error after host update

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.js-controller#1300]
Just updated my host to 3.3.1 and I see this in my log file:

host.iobroker-Server | 2021-04-30 07:59:06.161 | error | Cannot backup file /opt/iobroker/iobroker-data/states.json.bak: ENOENT:  no such file or directory, rename  '/opt/iobroker/iobroker-data/states.json' ->  '/opt/iobroker/iobroker-data/states.json.bak'
-- | -- | -- | --
host.iobroker-Server | 2021-04-30 07:58:41.584 | error | Cannot backup file /opt/iobroker/iobroker-data/states.json.bak: ENOENT:  no such file or directory, stat  '/opt/iobroker/iobroker-data/states.json'
host.iobroker-Server | 2021-04-30 07:56:53.174 | error | Cannot move /opt/iobroker/iobroker-data/states.json.new to  /opt/iobroker/iobroker-data/states.json: ENOENT: no such file or  directory, stat '/opt/iobroker/iobroker-data/states.json.new'. Try  direct w
host.iobroker-Server | 2021-04-30 07:56:32.021 | error | Cannot backup file /opt/iobroker/iobroker-data/states.json.bak: ENOENT:  no such file or directory, stat  '/opt/iobroker/iobroker-data/states.json'
host.iobroker-Server | 2021-04-30 07:55:56.422 | error | Cannot move /opt/iobroker/iobroker-data/states.json.new to  /opt/iobroker/iobroker-data/states.json: ENOENT: no such file or  directory, stat '/opt/iobroker/iobroker-data/states.json.new'. Try  direct w
host.iobroker-Server | 2021-04-30 07:55:43.938 | error | Cannot backup file /opt/iobroker/iobroker-data/states.json.bak: ENOENT:  no such file or directory, rename  '/opt/iobroker/iobroker-data/states.json' ->  '/opt/iobroker/iobroker-data/states.json.bak'

**Comment by daniel-lo** [comment]
3.3.2


ng to rebuild it... 1 attempt
--
info.0 | 2021-04-30 17:22:58.751 | warn | (3684) State value to set for "info.0.sysinfo.cpu.temperature.cores" has wrong type "object" but has to be "string"
info.0 | 2021-04-30 17:22:58.371 | warn | (3684) State value to set for "info.0.sysinfo.cpu.currentspeed.coresSpeed" has wrong type "object" but has to be "string"
info.0 | 2021-04-30 17:22:55.780 | warn | (3684) State value to set for "info.0.sysinfo.cpu.temperature.cores" has wrong type "object" but has to be "string"
info.0 | 2021-04-30 17:22:55.367 | warn | (3684) State value to set for "info.0.sysinfo.cpu.currentspeed.coresSpeed" has wrong type "object" but has to be "string"
info.0 | 2021-04-30 17:22:52.763 | warn | (3684) State value to set for "info.0.sysinfo.cpu.temperature.cores" has wrong type "object" but has to be "string"
info.0 | 2021-04-30 17:22:52.367 | warn | (3684) State value to set for "info.0.sysinfo.cpu.currentspeed.coresSpeed" has wrong type "object" but has to be "string"
info.0 | 2021-04-30 17:22:49.746 | warn | (3684) State value to set for "info.0.sysinfo.cpu.temperature.cores" has wrong type "object" but has to be "string"
info.0 | 2021-04-30 17:22:49.366 | warn | (3684) State value to set for "info.0.sysinfo.cpu.currentspeed.coresSpeed" has wrong type "object" but has to be "string"
info.0 | 2021-04-30 17:22:46.756 | warn | (3684) State value to set for "info.0.sysinfo.cpu.temperature.cores" has wrong type "object" but has to be "string"
info.0 | 2021-04-30 17:22:46.418 | warn | (3684) State value to set for "info.0.sysinfo.cpu.currentspeed.coresSpeed" has wrong type "object" but has to be "string"
telegram.0 | 2021-04-30 17:22:44.359 | warn | (5208) State value to set for "telegram.0.communicate.botSendChatId" has wrong type "number" but has to be "string"
telegram.0 | 2021-04-30 17:22:44.359 | warn | (5208) Read-only state "telegram.0.communicate.botSendChatId" has been written without ack-flag with value "644134529"
telegram.0 | 2021-04-30 17:22:44.357 | warn | (5208) State value to set for "telegram.0.communicate.botSendMessageId" has wrong type "number" but has to be "string"
telegram.0 | 2021-04-30 17:22:44.357 | warn | (5208) Read-only state "telegram.0.communicate.botSendMessageId" has been written without ack-flag with value "5836"
info.0 | 2021-04-30 17:22:43.749 | warn | (3684) State value to set for "info.0.sysinfo.cpu.temperature.cores" has wrong type "object" but has to be "string"
info.0 | 2021-04-30 17:22:43.366 | warn | (3684) State value to set for "info.0.sysinfo.cpu.currentspeed.coresSpeed" has wrong type "object" but has to be "string"
info.0 | 2021-04-30 17:22:40.765 | warn | (3684) State value to set for "info.0.sysinfo.cpu.temperature.cores" has wrong type "object" but has to be "string"
info.0 | 2021-04-30 17:22:40.363 | warn | (3684) State value to set for "info.0.sysinfo.cpu.currentspeed.coresSpeed" has wrong type "object" but has to be "string"
info.0 | 2021-04-30 17:22:37.743 | warn | (3684) State value to set for "info.0.sysinfo.cpu.temperature.cores" has wrong type "object" but has to be "string"
info.0 | 2021-04-30 17:22:37.366 | warn | (3684) State value to set for "info.0.sysinfo.cpu.currentspeed.coresSpeed" has wrong type "object" but has to be "string"
info.0 | 2021-04-30 17:22:34.850 | warn | (3684) State value to set for "info.0.sysinfo.cpu.temperature.cores" has wrong type "object" but has to be "string"
info.0 | 2021-04-30 17:22:34.363 | warn | (3684) State value to set for "info.0.sysinfo.cpu.currentspeed.coresSpeed" has wrong type "object" but has to be "string"
info.0 | 2021-04-30 17:22:31.754 | warn | (3684) State value to set for "info.0.sysinfo.cpu.temperature.cores" has wrong type "object" but has to be "string"
info.0 | 2021-04-30 17:22:31.365 | warn | (3684) State value to set for "info.0.sysinfo.cpu.currentspeed.coresSpeed" has wrong type "object" but has to be "string"
info.0 | 2021-04-30 17:22:28.815 | warn | (3684) State value to set for "info.0.sysinfo.cpu.temperature.cores" has wrong type "object" but has to be "string"
info.0 | 2021-04-30 17:22:28.360 | warn | (3684) State value to set for "info.0.sysinfo.cpu.currentspeed.coresSpeed" has wrong type "object" but has to be "string"
info.0 | 2021-04-30 17:22:25.744 | warn | (3684) State value to set for "info.0.sysinfo.cpu.temperature.cores" has wrong type "object" but has to be "string"
info.0 | 2021-04-30 17:22:25.359 | warn | (3684) State value to set for "info.0.sysinfo.cpu.currentspeed.coresSpeed" has wrong type "object" but has to be "string"
info.0 | 2021-04-30 17:22:22.748 | warn | (3684) State value to set for "info.0.sysinfo.cpu.temperature.cores" has wrong type "object" but has to be "string"
info.0 | 2021-04-30 17:22:22.362 | warn | (3684) State value to set for "info.0.sysinfo.cpu.currentspeed.coresSpeed" has wrong type "object" but has to be "string"
info.0 | 2021-04-30 17:22:19.773 | warn | (3684) State value to set for "info.0.sysinfo.cpu.temperature.cores" has wrong type "object" but has to be "string"
info.0 | 2021-04-30 17:22:19.360 | warn | (3684) State value to set for "info.0.sysinfo.cpu.currentspeed.coresSpeed" has wrong type "object" but has to be "string"
info.0 | 2021-04-30 17:22:16.823 | warn | (3684) State value to set for "info.0.sysinfo.cpu.temperature.cores" has wrong type "object" but has to be "string"
info.0 | 2021-04-30 17:22:16.360 | warn | (3684) State value to set for "info.0.sysinfo.cpu.currentspeed.coresSpeed" has wrong type "object" but has to be "string"
info.0 | 2021-04-30 17:22:13.743 | warn | (3684) State value to set for "info.0.sysinfo.cpu.temperature.cores" has wrong type "object" but has to be "string"
info.0 | 2021-04-30 17:22:13.399 | warn | (3684) State value to set for "info.0.sysinfo.cpu.currentspeed.coresSpeed" has wrong type "object" but has to be "string"
node-red.0 | 2021-04-30 17:22:11.985 | warn | (4283) 30 Apr 17:22:11 - [warn] Projekte deaktiviert: editorTheme.projects.enabled=false
info.0 | 2021-04-30 17:22:10.835 | warn | (3684) State value to set for "info.0.sysinfo.cpu.temperature.cores" has wrong type "object" but has to be "string"
info.0 | 2021-04-30 17:22:10.393 | warn | (3684) State value to set for "info.0.sysinfo.cpu.currentspeed.coresSpeed" has wrong type "object" but has to be "string"

**Comment by daniel-lo** [comment]
3.3.2 also seem to break zigbee adapter

**Comment by Apollon77** [comment]
Das Log im zweiten Post bitte bei den relevanten Adaptern Posten!

**Comment by daniel-lo** [comment]
Leider war die ganze Instanz grad zerschossen .. stelle grad das Image von gestern wieder her .. aber mach ich .. danke

**Comment by Apollon77** [comment]
Die Meldung im ersten Post: Kam die nur einmalig beim start? Lief es danach oder tat nichts? Scheinbar war die states.json nicht vorhanden was von einenm vorherigen unsanften Shutdown o.ä. gekommen sein kann. Bitte states.json aus einem Backup wiederherstellen. tut dann alles?

**Comment by daniel-lo** [comment]
Schaue ich mir an wenn mein Backup eingespielt ist

**Comment by daniel-lo** [comment]
was mir schonmal auffällt ist, dass "iobroker stop" nicht mehr wirklich funktioniert .. es sagt mir immer einige Prozesse laufen noch .. please stop them first and try again. Muss dann rebooten.

**Comment by daniel-lo** [comment]
Schaut grad ok aus .. bis auf die Objekt-Typen beim info-adapter. Firefox scheint mit der aktuellen Konfiguration ein wenig Probleme zu haben .. Chrome lädt die Seiten ordentlich.

**Comment by WolfgangGr** [comment]
Nach Update auf js-controller 3.3.2 bekomme ich gleiche Warnungen wie "daniel-lo" von diversen Adaptern Warnungen:

alexa2.0 | 2021-04-30 20:19:03.013 | warn | (1874) State value to set for "alexa2.0.Echo-Devices.ca197750cc594ea4990658b37453af98.Player.mediaLength" has wrong type "string" but has to be "number"

sonoff.1 | 2021-04-30 20:13:43.971 | warn | (3101) State value to set for "sonoff.1.S20_5.Wifi_Downtime" has wrong type "string" but has to be "number"

nuki-extended.0 | 2021-04-30 20:09:54.554 | warn | (3126) State value to set for "nuki-extended.0.bridges.nukibridge.scanResults.0.rssi" has wrong type "number" but has to be "string"

trashschedule.0 | 2021-04-30 20:00:51.845 | warn | (2627) State value to set for "trashschedule.0.nextAfter.weekday" has wrong type "number" but has to be "string"

info.0 | 2021-04-30 20:00:48.229 | warn | (2144) State value to set for "info.0.sysinfo.cpu.temperature.cores" has wrong type "object" but has to be "string"

Wie bekomme ich das System wieder ans Laufen?

Vielen Dank, Wolfgang

**Comment by WolfgangGr** [comment]
Habe auf js-controller 3.2.16 zurückgerüstet ---> läuft wieder

**Comment by Apollon77** [comment]
@daniel-lo  Der Fehler/Effekt mit iobroker stoppen wird mit der kommenden 3.3.4 gefixt sein

@WolfgangGr Bitte beiden betroffenen Adapters Issues anlegen. Die Adapter müssen updaten sind aber nur logmeldungen. es tut alles wie es soll

**Comment by daniel-lo** [comment]
Host 3.3.5 hat mein Zigbee-Adapter abgeschossen und der Updateversuch aus dem Git dann die ganze VM. Hatte ich gestern auch schonmal .. irgendwas hakt da.

**Comment by Apollon77** [comment]
der Controller kann keinen Adapter abschiessen so wirklich. Das oben sah irgendwie aus das npm Dinge zuerschossen hat. Die ganze VM kann iobroker auch nicht abschliessen.

Am besten bitte Logs die zeigen was du meinst

**Comment by daniel-lo** [comment]
Ich komme dann einfach nicht mehr drauf .. weder per GUI noch per Terminal .. Instanz ist dann nicht erreichbar. Hab das Backup zurückgespielt .. versuche vielleicht nachher nochmal.

**Comment by Apollon77** [comment]
naja dann ist die Farge was in der VM passiert ... /var/log/syslog?

**Comment by daniel-lo** [comment]
diesmal hab ich das host update so gemacht dass ich statt

iobroker fix
iobroker start

das image nach "upgrade self" neu gestartet habe.

Diesmal hat der zigbee adapter überlebt aber der ble adapter bleibt rot.

Refresh des Fensters (will schauen ob ble dann vielleicht grün ist) und ich bekomme die Lade-Animation oben angezeigt aber der gesamte Content fehlt .. sowohl in der Menüleiste .. als auch im Arbeitsbereich.
Dauert ewig .. dann kommt die Menüleiste aber "info", "Adapter", "Instanzen" .. leerer Arbeitsbereich .. "Objekte" sind da. Log ist leider auch leer (File tab_m_html not found).

Wechsel von FF zu Chrome:

Ladeanimation .. hört gar nicht auf .. warte schon 3 Minuten.

Terminal:

stoppe iobroker .. und führe fix aus .. und starte iobroker

iobroker funktioniert wieder.

bei den Logs tauchen im Filter host.iobroker und host.iobroker-server auf. Beim "..server" gibt es keine Logeinträge. Die gibts nur bei host.iobroker .. hier die errors:

host.iobroker	2021-05-02 19:33:10.992	error	instance system.adapter.amazon-dash.0 terminated with code 7 (ADAPTER_ALREADY_RUNNING)
host.iobroker	2021-05-02 19:33:02.873	error	instance system.adapter.mqtt.0 terminated with code 7 (ADAPTER_ALREADY_RUNNING)
host.iobroker	2021-05-02 19:32:59.392	error	instance system.adapter.whatsapp-cmb.0 terminated with code 7 (ADAPTER_ALREADY_RUNNING)
host.iobroker	2021-05-02 19:32:55.211	error	instance system.adapter.text2command.0 terminated with code 7 (ADAPTER_ALREADY_RUNNING)
host.iobroker	2021-05-02 19:32:50.933	error	instance system.adapter.fritzdect.0 terminated with code 7 (ADAPTER_ALREADY_RUNNING)
host.iobroker	2021-05-02 19:32:40.091	error	instance system.adapter.lgtv.0 terminated with code 7 (ADAPTER_ALREADY_RUNNING)
host.iobroker	2021-05-02 19:32:36.004	error	instance system.adapter.linkeddevices.0 terminated with code 7 (ADAPTER_ALREADY_RUNNING)
host.iobroker	2021-05-02 19:32:27.363	error	instance system.adapter.tr-064.0 terminated with code 7 (ADAPTER_ALREADY_RUNNING)
host.iobroker	2021-05-02 19:32:23.258	error	instance system.adapter.web.0 terminated with code 7 (ADAPTER_ALREADY_RUNNING)
host.iobroker	2021-05-02 19:32:16.016	error	instance system.adapter.telegram.0 terminated with code 7 (ADAPTER_ALREADY_RUNNING)
host.iobroker	2021-05-02 19:32:10.971	error	instance system.adapter.sonos.0 terminated with code 7 (ADAPTER_ALREADY_RUNNING)
host.iobroker	2021-05-02 19:32:07.190	error	instance system.adapter.sonoff.0 terminated with code 7 (ADAPTER_ALREADY_RUNNING)
host.iobroker	2021-05-02 19:32:03.085	error	instance system.adapter.simple-api.0 terminated with code 7 (ADAPTER_ALREADY_RUNNING)
host.iobroker	2021-05-02 19:31:59.728	error	instance system.adapter.shelly.0 terminated with code 7 (ADAPTER_ALREADY_RUNNING)
host.iobroker	2021-05-02 19:31:54.959	error	instance system.adapter.scenes.0 terminated with code 7 (ADAPTER_ALREADY_RUNNING)
host.iobroker	2021-05-02 19:31:50.876	error	instance system.adapter.sayit.0 terminated with code 7 (ADAPTER_ALREADY_RUNNING)
host.iobroker	2021-05-02 19:31:46.978	error	instance system.adapter.pushover.0 terminated with code 7 (ADAPTER_ALREADY_RUNNING)
host.iobroker	2021-05-02 19:31:43.271	error	instance system.adapter.nut.0 terminated with code 7 (ADAPTER_ALREADY_RUNNING)


Alle Adapter wieder grün.

**Comment by Apollon77** [comment]
Upgrade gemacht von welchem controller auf welchen?

**Comment by daniel-lo** [comment]
332 auf 335

**Comment by Apollon77** [comment]
Hast DU das log mal vollständiger? ... Aber naja egal: Bitte schau was beim update auf 3.3.5 auf 3.3.6 passiert. Falls es die "restart probleme beim upgrade" von 3.3.2 waren wäre das jetzt weg, SOnst bitte vollständiges iobroker log um den ugrade zeitpunkt

**Comment by daniel-lo** [comment]
du meinst bestimmt das log aus dem verzeichnis und nicht von der gui .. mach ich

**Comment by daniel-lo** [comment]
335->337

host.iobroker	2021-05-03 07:34:31.657	error	instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.iobroker	2021-05-03 07:33:57.674	error	instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.iobroker	2021-05-03 07:33:18.722	warn	adapter "ble" seems to be installed for a different version of Node.js. Trying to rebuild it... 2 attempt
host.iobroker	2021-05-03 07:33:13.751	warn	adapter "ble" seems to be installed for a different version of Node.js. Trying to rebuild it... 1 attempt


zigbee.0	2021-05-03 07:34:31.479	error	(5226) Cannot read property 'mapped' of undefined
zigbee.0	2021-05-03 07:34:31.479	error	at processImmediate (internal/timers.js:434:9)
zigbee.0	2021-05-03 07:34:31.479	error	at runNextTicks (internal/process/task_queues.js:66:3)
zigbee.0	2021-05-03 07:34:31.479	error	at processTicksAndRejections (internal/process/task_queues.js:97:5)
zigbee.0	2021-05-03 07:34:31.479	error	at runMicrotasks (<anonymous>)
zigbee.0	2021-05-03 07:34:31.479	error	at Zigbee.publishFromState (/opt/iobroker/node_modules/iobroker.zigbee/main.js:449:36)
zigbee.0	2021-05-03 07:34:31.479	error	(5226) TypeError: Cannot read property 'mapped' of undefined
zigbee.0	2021-05-03 07:34:31.479	error	(5226) unhandled promise rejection: Cannot read property 'mapped' of undefined
zigbee.0	2021-05-03 07:34:31.478	error	(5226) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
zigbee.0	2021-05-03 07:34:31.477	error	(5226) Cannot read property 'mapped' of undefined
zigbee.0	2021-05-03 07:34:31.477	error	at processImmediate (internal/timers.js:434:9)
zigbee.0	2021-05-03 07:34:31.477	error	at runNextTicks (internal/process/task_queues.js:66:3)
zigbee.0	2021-05-03 07:34:31.477	error	at processTicksAndRejections (internal/process/task_queues.js:97:5)
zigbee.0	2021-05-03 07:34:31.477	error	at runMicrotasks (<anonymous>)
zigbee.0	2021-05-03 07:34:31.477	error	at Zigbee.publishFromState (/opt/iobroker/node_modules/iobroker.zigbee/main.js:449:36)
zigbee.0	2021-05-03 07:34:31.477	error	(5226) TypeError: Cannot read property 'mapped' of undefined
zigbee.0	2021-05-03 07:34:31.477	error	(5226) unhandled promise rejection: Cannot read property 'mapped' of undefined
zigbee.0	2021-05-03 07:34:31.476	error	(5226) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

**Comment by daniel-lo** [comment]
[iobroker.2021-05-03.zip](https://github.com/ioBroker/ioBroker.js-controller/files/6412993/iobroker.2021-05-03.zip)

**Comment by daniel-lo** [comment]
Alles geht .. bis auf Zigbee

**Comment by Apollon77** [comment]
Ok, dann aber zigbee bitte dort issue öffenen
