### ISSUE TITLE
Hundrets of warnings about wrong type

### ISSUE THREAD

**Issue by sbormann** [ioBroker/ioBroker.js-controller#1306]
Since last update to 3.3.2 i get hundrets of warnings in the log (from several adapters):
![image](https://user-images.githubusercontent.com/49171332/116760206-a4730000-aa14-11eb-8ecf-eb99301db652.png)

node 12.22.1
npm 6.14.12

Do you need any further informations?

**Comment by Apollon77** [comment]
Please Create issues on all the adapters that are producing them :-) Thank you. Tha adapters needs to adjust that

**Comment by sbormann** [comment]
Sorry, but the log is FULL of these. Hundrets per minute! 
I understand that the fault is on the adapters side - but i dont think all adapters can and will be fixed soon. And for now the log is unusable, because of all these hundrets, no thousands of entries.

**Comment by Apollon77** [comment]
I know and understand that this is annoying and honestly noone expected that "shitload of warnings". We shoukd use the chance now to collect the affected adapters and create issues and we will discuss before a stable release how we proceed here. ALternative for now is to set loglevel to error foe the affected adapters

**Comment by Apollon77** [comment]
>  Please make this log message optional!

Then noone will check and fix it (sorry,but reality)

**Comment by Apollon77** [comment]
@sbormann whcih adapters filled the most for you?

**Comment by sbormann** [comment]
- [ ] coronavirus-statistik
- [ ] nut
- [ ] rpi2
- [ ] wolf
- [ ] synology
