### ISSUE TITLE
State Value on 3.3.4

### ISSUE THREAD

**Issue by Matt77CHE** [ioBroker/ioBroker.js-controller#1316]
Seit dem vorletzten und letzten Update des js-controllers (3.3.4) habe ich etliche warn Logeinträge bezüglich state values:

![Unbenannt](https://user-images.githubusercontent.com/73795309/116775542-c5af0d00-aa63-11eb-81bf-d49686b45091.JPG)

vorher war alles ok.

**Comment by anwa** [comment]
Hallo, kann ich leider bestätigen.
Habe gerade von 3.2.16 auf 3.3.4 upgedated. Danach war das log voll.
node v14.16.1/npm v6.14.12

**Comment by itProfi** [comment]
same problem 3.3.6
![Uploading Скриншот 01-05-2021 103119.jpg…]()

**Comment by anwa** [comment]
Na toll, jetzt hats mir den ioBroker scheinbar zerschossen:
File admin/index.html not found: {}

**Comment by Matt77CHE** [comment]
nö, iobroker mit Port (8081) laden...

**Comment by amg666** [comment]
> 
> 
> Seit dem vorletzten und letzten Update des js-controllers (3.3.4) habe ich etliche warn Logeinträge bezüglich state values:
> 
> ![Unbenannt](https://user-images.githubusercontent.com/73795309/116775542-c5af0d00-aa63-11eb-81bf-d49686b45091.JPG)
> 
> vorher war alles ok.

Bei mir leider auch der Fall, ich hab allerdings node.js v14.16.1. Mit dem js-controller 3.2.15 lief es gut, nach update auf 3.3.4 kommen die Fehlermeldungen mit falschen Typen

**Comment by anwa** [comment]
This is because of #1301
No easy solution here. I checked the sonoff and unifi adapter.
In the sonoff adapter, i could add some datapoints to make it better, but finally the conzept of the adapter is not ready for this, because of non unique datapoint names in tasmota.
The unifi adapter makes everything korrekt, but unifi lib sends some of the json numbers in " so it gets a string. Not shure if this could be fixed so easy...

**Comment by Apollon77** [comment]
Please create issues with the respective adapters. They need to adjust their logic in order to set correct values. Yes it is annoying right now, but please support in collecting the cases as issues with the adapters

**Comment by foxriver76** [comment]
> but finally the concept of the adapter is not ready for this

Keep in mind that you also can use `common.type = 'mixed'` for such cases.

**Comment by Matt77CHE** [comment]
After the Updates today, it has changed from warn to info - but still exists.

**Comment by Apollon77** [comment]
Yes because the adapter developers still need to fix these things... so please open issues at the adapters. Thank you
