### ISSUE TITLE
... has to be type "number" but received type "string"

### ISSUE THREAD

**Issue by schmupu** [ioBroker/ioBroker.js-controller#1324]
Seit js-controller 3.3.5 stehen Unmengen an Meldungen `has to be type "number" but received type "string"` (Type Info) im Log für die Adapter Unifi, Proxmox, MQTT, Sonoff.  Keine Ahnung, ob das gewollt ist oder ob es sich hierbei ume einen Fehler im js-controller handelt.
Workaround: Instanzen  auf Warn zu stellen.

**Comment by Apollon77** [comment]
Ja ist gewollt weil da alles Entwickler nicht sauber gearbeitet haben :-( Muss alles gefixt werden, daher bitte Issues melden.
