### ISSUE TITLE
Update lässt Zigbee Geräte verschwinden

### ISSUE THREAD

**Issue by Frank1604** [ioBroker/ioBroker.js-controller#1329]
Ich habe keine Ahnung wie das zusammen hängt, aber es ist (leider) reproduzierbar bei  mir so, dass alle angelernten Zigbee Geräte verschwunden sind, wenn ich diesen Controller aktualisiere.

Ich habe innerhalb einer Woche 3mal alle Geräte neu anlernen müssen, das ist bei 62 Geräten die teilweise in Unterputzdosen und hinter Schaltern in der Wand stecken kein Spaß.

Das erste mal aufgetreten ist das als ich auf Version 3.3.1 altualisiert habe. Die Updates auf 3.3.4 und 3.3.5 haben das Gleiche ausgelöst. Sobald ich den Host-controller update und ioBroker starte meldet mir der ZigBee Stick das zur Zeit keine Geräte angemeldet sind. Restore bringt auch nichts, die Geräte sind weg. Ich sehe die Objekte im ioBroker, aber der Stick hat sie nicht mehr.

Alle anderen Updates sind kein Problem, auch Update des Zigbee Adapters macht keine Probleme. Neustart des Systems auch nicht.

**Comment by Apollon77** [comment]
Bitte Issue bei zigbee adapter öffnen. Der 3.3er controller hat wenig Änderungen und keine die sich auf Geräte einzelner Adapter auswirken sollten. Da müsen die Adapter devs rausfinden was sache ist. sorry
Bitte mit mentionen wenn nötig
