### ISSUE TITLE
Object common read / write Parameter (write=false) führt kein Beschreiben des Wertes aus.

### ISSUE THREAD

**Issue by SurfGargano** [ioBroker/ioBroker.js-controller#1333]
Mit der neuen Version 3.3.7 habe ich ein anderes Verhalten als mit der 3.2
Wenn ich im Object unter common write = false setze , lässt sich nicht immer der Wert setzen den der Adapter setzen will. Seltsamerweise sind dies Werte die der Adapter auf 0 setzen will.
Wenn also vorher 30 drin stand und der Adapter (mit setstate (...,ack)) den Wert auf 0 setzen will , bleiben die 30 stehen und auch die Update Time ist dann die vom Wert 30.
(common / min ist 0 und common / max ist 100)

{
  "from": "system.adapter.resol.0",
  "user": "system.user.admin",
  "ts": 1620048450021,
  "common": {
    "name": "Drehzahl Relais",
    "type": "number",
    "unit": "%",
    "role": "level.volume",
    "min": 0,
    "max": 100,
    "read": true,
    "write": false   <-- dies führt zum nicht Setzen des Wertes ;  "write": true funktioniert
  },
  "native": {},
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1636
  },
  "_id": "resol.0.0011210010.4385.000010112110010001210",
  "type": "state"
}

Ist der common / write parameter nicht so gedacht, daß zwar das System (Adapter) reinschreiben darf, aber der Anwender nicht ?

**Comment by foxriver76** [comment]
Sollte absolut keinen Unterschied machen. Der write Parameter wird vom Controller nicht berücksichtigt. Das einzige was passiert ist, dass wenn `write: false` und mit `ack: false` geschrieben wird, eine Warnung im Log generiert wird.

Die Frage hier ist, wie validierst du das der State nicht geschrieben wird? Bräuchte da schon ein minimal breaking example. Falls mit Admin validiert wird, bitte besser auf den `stateChange` per Adapter triggern.

**Comment by SurfGargano** [comment]
Aufgefallen ist es mir weil die Drehzahl-Anzeige in der VIS auf 30% stand, obwohl die Pumpe schon aus war. Im Admin stand unter den Objekten auch 30 %
Hier der Log :

Der Log sagt um 19:43, daß er die Drehzahl mit 0 reingeschrieben hat.

2021-05-03 19:43:30.006 | debug | (26559) Writing Object {"name":"Drehzahl Relais","type":"number","unit":"%","read":true,"write":false,"min":0,"max":100,"role":"level.volume"} : 0

In Ereignisse ist dies er letzte Eintrag (mit dem Wert 30): Danach ist keiner mehr.

resol.0.0011210010.4385.000010112110010001210	30	true	resol.0	2021-05-03 19:20:30.173	2021-05-03 19:14:00.297

Also müßte doch spätestens um 19:43 noch ein Eintrag mit Wert = 0 vorhanden sein, da ist aber keiner mehr.  Seltsamerweise passiert dies nur , wenn der Wert = 0 ist. Ich habe mal den Wert =1 geschrieben, das geht wieder.

**Comment by foxriver76** [comment]
Verlinke mal bitte den Code Part, welcher das `setState` ausführt. Rein aus den Ausschnitten hier werde ich nicht wirklich schlau.

**Comment by SurfGargano** [comment]
Jetzt hast Du mich doch auf die richtige Stelle geführt, das war mein (Code) Fehler.
Danke für die Hilfe.

**Comment by foxriver76** [comment]
Gerne, schön dass es doch kein größerer Fehler war. :-)
