### ISSUE TITLE
Keep /doc in Repository up to date

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.js-controller#1334]
Or is this still in use anywhere? Last change 13 months ago.

https://github.com/ioBroker/ioBroker.js-controller/tree/master/doc

**Comment by Apollon77** [comment]
Good question ... I think when this would be the api doc ... needs to be updated, generated and then included into the webpage :-)

**Comment by foxriver76** [comment]
Belongs to the docs repo imho, however we should ensure that the information is incorporated in https://github.com/ioBroker/ioBroker.docs before we drop anything.

**Comment by Apollon77** [comment]
maybe theway to go would be to start auto genration of API docs out of adapter.js and such  and provide here ... and then the docs process can get that content regulary like with the other docs dirs ...

So Step 1:
* generate API docs here automatically (GitHub actions? or such)
* discuss with @GermanBluefox how to get it into webpage

**Comment by foxriver76** [comment]
I've already built docs automatically via Sphinx from Python code, there is most likely something similar to generate docs from Code and JSDOC

**Comment by foxriver76** [comment]
Auto generated Markdown docs could look like https://github.com/foxriver76/ioBroker.js-controller/blob/doc/docs/adapter.md#Adapter

Of course, if we want this we need to fix some typings and mark methods as private which should be private ;-)

**Comment by foxriver76** [comment]
Updated plans: adapter.js will be adapter.ts soon and we will use https://github.com/TypeStrong/typedoc

**Comment by foxriver76** [comment]
Part of https://github.com/ioBroker/ioBroker.js-controller/pull/1917
