### ISSUE TITLE
Provide Functions (sendTo?) to start / stop instances from scripts

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.js-controller#1338]
I've received an issue, that stopping and starting an instance leads to loss of configuration data.

https://github.com/klein0r/ioBroker.octoprint/issues/45

Example code:

```javascript
var obj = getObject("system.adapter.octoprint.0");
obj.common.enabled = false;
setObject("system.adapter.octoprint.0", obj);
```

The ioBroker CLI performs the start / stop of an instance exactly this way:

https://github.com/ioBroker/ioBroker.js-controller/blob/5884e470359a08df6c4f5fba8b7bc93457434baf/lib/cli/cliProcess.js#L316

The 'problem' is, that one of the options is protected by `protectedNative`. So `getObject` is not able to return the complete configuration to the javascript adapter. That is the intended behaviour.

## Issue

There is no way to start / stop an instance from a script without loosing protected data (or to set them again before restart).

What is the correct way to start / stop an instance from another adapter (e.g. JavaScript adapter).

*The admin adapter hasn't an issue, since this adapter is an exception and is allowed to receive protected data*

**Comment by Apollon77** [comment]
The easiestway is to simply write on the system.adapter.adaptername.alive state ... with ack=false you can controll it and controller does the rest :-)

But yes you are right that this is an interesting thing.

Alternatively an "extendObject" could also work by just manipulating the enabled flag

**Comment by klein0r** [comment]
Thanks a lot 😄 Too easy... I thought that is just an indicator of the current state
