### ISSUE TITLE
js-controller 3.3.8 warning and info some drivers

### ISSUE THREAD

**Issue by itProfi** [ioBroker/ioBroker.js-controller#1340]
After update js-controller with version 3.3.8 - always recieve:
```
telegram.0 | 2021-05-05 12:36:36.216 | warn | Read-only state "telegram.0.communicate.botSendMessageId" has been written without ack-flag with value "264710"
```

Also:
```
telegram.0 | 2021-05-05 12:36:36.217 | info | State value to set for "telegram.0.communicate.botSendMessageId" has to be type "string" but received type "number"
```

**Comment by itProfi** [comment]
```

**Comment by thost96** [comment]
Hi @itProfi, these messages are from the iobroker.telegram adapter, so please open the issue again there as this needs to be fixed on the adapter itself. Please see https://github.com/iobroker-community-adapters/ioBroker.telegram/issues/227
