### ISSUE TITLE
Missing licenses in io-package.json schema

### ISSUE THREAD

**Issue by crycode-de** [ioBroker/ioBroker.js-controller#1341]
In the json schema for `io-package.json` some licenses from the [SPDX License List](https://spdx.org/licenses/) are missing.
E.g. the _NC_ and _ND_ ones of Creative Commons like `CC-BY-NC-SA-4.0`.

Or is this intended and these licenses shouldn't be used in ioBroker?
The adapter checker doesn't complain about it.

**Comment by foxriver76** [comment]
We could use https://github.com/shinnn/get-spdx-license-ids for enum  creation
