### ISSUE TITLE
js-controller Update 3.3.8

### ISSUE THREAD

**Issue by Kufstein** [ioBroker/ioBroker.js-controller#1342]
Hi,

I have Errors in the hp-ilo Adapter since I update the js-controller to version 3.3.8:

hp-ilo.0 2021-05-05 17:18:57.673 error (62741) The id "temperatures.33-PCI_3_Zone." is invalid. Ids are not allowed to end in "." hp-ilo.0 2021-05-05 17:18:57.673 error (62741) Error: The id "temperatures.33-PCI_3_Zone." is invalid. Ids are not allowed to end in "." at validateId (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:532:23) at Ada hp-ilo.0 2021-05-05 17:18:57.672 error (62741) unhandled promise rejection: The id "temperatures.33-PCI_3_Zone." is invalid. Ids are not allowed to end in "." hp-ilo.0 2021-05-05 17:18:57.672 error (62741) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). hp-ilo.0 2021-05-05 17:18:57.671 error (62741) The id "temperatures.32-PCI_2_Zone." is invalid. Ids are not allowed to end in "." hp-ilo.0 2021-05-05 17:18:57.671 error (62741) Error: The id "temperatures.32-PCI_2_Zone." is invalid. Ids are not allowed to end in "." at validateId (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:532:23) at Ada hp-ilo.0 2021-05-05 17:18:57.670 error (62741) unhandled promise rejection: The id "temperatures.32-PCI_2_Zone." is invalid. Ids are not allowed to end in "." hp-ilo.0 2021-05-05 17:18:57.670 error (62741) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). hp-ilo.0 2021-05-05 17:18:57.669 error (62741) The id "temperatures.31-PCI_1_Zone." is invalid. Ids are not allowed to end in "." hp-ilo.0 2021-05-05 17:18:57.669 error (62741) Error: The id "temperatures.31-PCI_1_Zone." is invalid. Ids are not allowed to end in "." at validateId (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:532:23) at Ada hp-ilo.0 2021-05-05 17:18:57.668 error (62741) unhandled promise rejection: The id "temperatures.31-PCI_1_Zone." is invalid. Ids are not allowed to end in "." hp-ilo.0 2021-05-05 17:18:57.668 error (62741) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). hp-ilo.0 2021-05-05 17:18:57.636 error (62741) The id "temperatures.33-PCI_3_Zone." is invalid. Ids are not allowed to end in "." hp-ilo.0 2021-05-05 17:18:57.636 error (62741) Error: The id "temperatures.33-PCI_3_Zone." is invalid. Ids are not allowed to end in "." at validateId (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:532:23) at Ada hp-ilo.0 2021-05-05 17:18:57.635 error (62741) unhandled promise rejection: The id "temperatures.33-PCI_3_Zone." is invalid. Ids are not allowed to end in "." hp-ilo.0 2021-05-05 17:18:57.634 error (62741) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). hp-ilo.0 2021-05-05 17:18:57.634 error (62741) The id "temperatures.32-PCI_2_Zone." is invalid. Ids are not allowed to end in "." hp-ilo.0 2021-05-05 17:18:57.633 error (62741) Error: The id "temperatures.32-PCI_2_Zone." is invalid. Ids are not allowed to end in "." at validateId (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:532:23) at Ada hp-ilo.0 2021-05-05 17:18:57.633 error (62741) unhandled promise rejection: The id "temperatures.32-PCI_2_Zone." is invalid. Ids are not allowed to end in "." hp-ilo.0 2021-05-05 17:18:57.632 error (62741) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). hp-ilo.0 2021-05-05 17:18:57.630 error (62741) The id "temperatures.31-PCI_1_Zone." is invalid. Ids are not allowed to end in "." hp-ilo.0 2021-05-05 17:18:57.630 error (62741) Error: The id "temperatures.31-PCI_1_Zone." is invalid. Ids are not allowed to end in "." at validateId (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:532:23) at Ada hp-ilo.0 2021-05-05 17:18:57.627 error (62741) unhandled promise rejection: The id "temperatures.31-PCI_1_Zone." is invalid. Ids are not allowed to end in "." hp-ilo.0 2021-05-05 17:18:57.626 error (62741) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

I have try to uninstall and reinstall the ilo-adapter, but no luck.

**Comment by Apollon77** [comment]
Please create this issue in the adapter repository!

**Comment by Kufstein** [comment]
In the adapter repository they wrote that i should create a issue in the js-controller repository.
https://github.com/SebastianSchultz/ioBroker.hp-ilo/issues/24
