### ISSUE TITLE
v3.3.8: State value to set for [state] has to be stringified but received type "object" when setting a date

### ISSUE THREAD

**Issue by HGlab01** [ioBroker/ioBroker.js-controller#1343]
js-controller v3.3.8

Updating a state with
```
await this.setStateAsync(`teststate`, {
            val: new Date(),
            ack: true,
            expire: 0
        });
```
results in
`State value to set for "test_jsonexplorer.0.teststate" has to be stringified but received type "object"`

The state is defined with the type 'object':
```
{
  "from": "system.adapter.test_jsonexplorer.0",
  "user": "system.user.admin",
  "ts": 1620291646926,
  "common": {
    "name": "teststate",
    "type": "object",
    "role": "value.time",
    "read": true
  },
  "native": {},
  "acl": {
    "object": 1632,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1632
  },
  "_id": "test_jsonexplorer.0.teststate",
  "type": "state"
}
```

Is this an js-controller issue or what is wrong?

**Comment by foxriver76** [comment]
`role` needs to be `date.<type>` and `common.type` should be number. Also see discussion here https://github.com/klein0r/ioBroker.trashschedule/issues/38

**Comment by HGlab01** [comment]
> `role` needs to be `date.<type>` and `common.type` should be `number`. Also see discussion here [klein0r/ioBroker.trashschedule#38](https://github.com/klein0r/ioBroker.trashschedule/issues/38)

But then the following messages occurs:
`State value to set for "test_jsonexplorer.0.teststate" has to be type "number" but received type "object"`

State definition
```
{
  "from": "system.adapter.test_jsonexplorer.0",
  "user": "system.user.admin",
  "ts": 1620291646926,
  "common": {
    "name": "teststate",
    "type": "number",
    "role": "date",
    "read": true
  },
  "native": {},
  "acl": {
    "object": 1632,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1632
  },
  "_id": "test_jsonexplorer.0.teststate",
  "type": "state"
}
```

**Comment by foxriver76** [comment]
As stated in the issue, ioBroker wants to receive a number and not a Date object, you can simply convert it. Admin will automatically display it as a timestamp.

**Comment by HGlab01** [comment]
> As stated in the issue, ioBroker wants to receive a number and not a Date object, you can simply convert it. Admin will automatically display it as a timestamp.

so there is no support for native date objects in iobroker? Really?

**Comment by Apollon77** [comment]
In fact there was "Never" support for that - it was just "not verified" in the past. Also in fact with Redis as DB it was already broken because on saving the object gets stringified ... means it becomes a string and on reading you just get the string back and no object anymore! Soin fact it was never supported and gave indifferent results already in the past. SO we now just make sure it is clear what is supported and how. See it that way

**Comment by HGlab01** [comment]
Understood, thanks for explanation.
