### ISSUE TITLE
Check if host exists if add instance to specific host.

### ISSUE THREAD

**Issue by GermanBluefox** [ioBroker/ioBroker.js-controller#1356]
The command 
`ioBroker a socketio --host myOtherHost`
Does not check if the host myOtherHost exists. But should do.

**Comment by Apollon77** [comment]
How should we determine what to check? If parameter in "host"?
How to check it? Formally you at least also need to assume that there is a "port"§ parameter and then open a telnet or such. Or do we need to detect of it is a "non IP hostname" and try to do a DNS lookup?

What exactly is required here?

**Comment by Apollon77** [comment]
aahhh now I got it ... we need to verify the host  from multihost
