### ISSUE TITLE
Remove _design/custom from controller with 4.0

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#1359]
And before that update all relevant adapters to use sytem/custom

**Comment by foxriver76** [comment]
Is there an overview of relevant adapters? And with system custom they will need controller 3.3 as dep

**Comment by Apollon77** [comment]
The following adapter cvurrently define the "old" _design/custom:
* ioBroker.fullcalendar/io-package.json:            "_id": "_design/custom",
* ioBroker.history/io-package.json:            "_id": "_design/custom",
* ioBroker.influxdb/io-package.json:            "_id": "_design/custom",
* ioBroker.lovelace/io-package.json:            "_id": "_design/custom",
* ioBroker.mqtt-client/io-package.json:            "_id": "_design/custom",
* ioBroker.powermonitor/io-package.json:            "_id": "_design/custom",
* ioBroker.sourceanalytix/io-package.json:            "_id": "_design/custom",
* ioBroker.sql/io-package.json:            "_id": "_design/custom",
* ioBroker.statistics/io-package.json:            "_id": "_design/custom",
* ioBroker.telegram/io-package.json:            "_id": "_design/custom",

Additionally the following are using a custom objectView
* ioBroker.upnp/main.js
* ioBroker.valuetrackerovertime/main.js
* pot. ioBroker.zigbee

**Comment by foxriver76** [comment]
as i see the ones who are defining the design object view themself are not critical, so only upnp, valuetrackerovertime and zigbee needs update with system custom and controller 3.3. as dep

**Comment by foxriver76** [comment]
upnp fixed
https://github.com/iobroker-community-adapters/ioBroker.upnp/commit/0cafffa64ab2206b0412e70574330fd83c7e27b9

**Comment by Apollon77** [comment]
In fact all should remove the "self defined" view and migrate to the new system/custom one AND increase their js.controller dep

**Comment by foxriver76** [comment]
Yes but as long as they are bringing the object themselves they will work like before. But yes we can create issues or prs too if necessary

**Comment by foxriver76** [comment]
I've created issues for all adapter except ioBroker.powermonitor, which is not in Repo and I also cannot find it on GH

**Comment by Apollon77** [comment]
Ja das war glaube der frügere name von sourceanalytix :-)) muss ich lokal mal löschen

**Comment by Apollon77** [comment]
PRs:
* https://github.com/ioBroker/ioBroker.fullcalendar/issues/22
* https://github.com/ioBroker/ioBroker.history/issues/141
* https://github.com/ioBroker/ioBroker.influxdb/issues/192
* https://github.com/Pmant/ioBroker.mqtt-client/issues/85
* https://github.com/ioBroker/ioBroker.lovelace/issues/288
* https://github.com/ioBroker/ioBroker.sql/issues/210
* https://github.com/iobroker-community-adapters/ioBroker.telegram/issues/283
