### ISSUE TITLE
v3.3.11: certain dates are shown as invalide 

### ISSUE THREAD

**Issue by HGlab01** [ioBroker/ioBroker.js-controller#1366]
Certain dates, eg. 'Fri May 28 2021 04:23:41 GMT+0200' delivers in v3.3.11 'Invalide date' if using the role 'value.time' or 'date'. If using value some decimales are shown. In all cases 'number' was used as type.

Repo:
```
let readDate = new Date ('Fri May 28 2021 04:23:41 GMT+0200');
this.log.info('readDate.getTime() ' + readDate.getTime());
await this.setStateAsync('aaa.test', readDate.getTime());
let getDate = await this.getStateAsync('aaa.test');
this.log.info('ReadState ' + getDate.val);
```

Log:
```
2021-05-28 12:45:08.510 | info | ReadState 1622168621000
2021-05-28 12:45:08.495 | info | readDate.getTime() 1622168621000
```

State with role value.time:
![image](https://user-images.githubusercontent.com/54232526/119972657-c11e3b80-bfb2-11eb-9fa3-59ad600c7bf2.png)

State with role value:
![image](https://user-images.githubusercontent.com/54232526/119972772-e6ab4500-bfb2-11eb-8bd0-40a5eb9ded62.png)

What's wrong? ;-)

**Comment by foxriver76** [comment]
This validation is all on Admin site.

However, to get a valid UNIX timestamp, as expected by Admin and many vis Widgets you need to perform `Math.round(readDate.getTime() / 1000)`

**Comment by HGlab01** [comment]
This did not help or did you mean Math.round(readDate.getTime()/1000)*1000?

```
let readDate = new Date ('Fri May 28 2021 04:23:41 GMT+0200');
this.log.info('Math.round(readDate.getTime()/1000) ' + Math.round(readDate.getTime()/1000));
await this.setStateAsync('aaa.test', Math.round(readDate.getTime()/1000));
let getDate= await this.getStateAsync('aaa.test');
this.log.info('ReadState ' + getDate.val);
```

```
2021-05-31 19:53:22.354 | info | ReadState 1622168621
2021-05-31 19:53:22.329 | info | Math.round(readDate.getTime()/1000) 1622168621
```
![image](https://user-images.githubusercontent.com/54232526/120227914-6141c200-c24a-11eb-9ef2-253d0b761a95.png)

**Comment by foxriver76** [comment]
Tried it from the JS adapter and works fine, admin 5 can display it:

```
await createStateAsync('javascript.0.testTime', {
        type: 'number',
        role: 'date'
})

let readDate = new Date ('Fri May 28 2021 04:23:41 GMT+0200');
await setStateAsync('javascript.0.testTime', Math.round(readDate.getTime()));
```
![Bildschirmfoto von 2021-05-31 20-17-11](https://user-images.githubusercontent.com/25484431/120229439-70763f00-c24d-11eb-968a-c36177487820.png)


The `/ 1000` of course does not work, thought it worked at some point in the past.

**Comment by HGlab01** [comment]
Then, I guess, it is an open admin adapter issue and you are using a different admin adapter version.

As
```
let readDate = new Date ('Fri May 28 2021 04:23:41 GMT+0200');
this.log.info('readDate.getTime() ' + readDate.getTime());
```
does not show any decimals (1622168621000) the `Math.round()` does not change something. Behavior is still the same.
I am using the latest admin adapter version v5.1.5
With admin adapter v4.2.1 it looks fine. I will create an adapter ticket.

**Comment by foxriver76** [comment]
Math round was just an relict in this example. If the problem still occurs with latest admin then open up an issue there please.
