### ISSUE TITLE
v3.3.11: falscher Objekt-Zustand nach Browser-Refresh

### ISSUE THREAD

**Issue by fu-zhou** [ioBroker/ioBroker.js-controller#1367]
Folgendes Verhalten ist nach einigen Tests aufgefallen: Bei Konfiguration eines Alias mit getrenntem Kommando / Status wird der korrekte Zustand "ein" des Alias im Admin / Vis nur bis zu einem Browser-Refresh angezeigt.
Nach einem Browser-Refresh nimmt der Alias den Zustand des Kommando-Datenpunktes an, was falsch ist.
![image](https://user-images.githubusercontent.com/11984960/120106401-14cc8880-c15d-11eb-9aaf-ba9bccb8efa7.png)
Es werden auch die Zeitstempel im Admin nicht aktualisiert. Nach einem Browser-Refresh hat der Alias die letzte Änderung vom Zeitpunkt des "write"-Datenpunktes (Taster).
Der Alias hat nicht tatsächlich einen falschen Zustand, denn getState(id) liefert den richtigen, sondern es wird ein falscher Zustand angezeigt (Vis und Admin/ Objekt-Baum).

Das Thema diskutieren wir auch im Forum: https://forum.iobroker.net/post/636058

Was kann ich tun, um bei der Behebung des Problems zu unterstützen? Tests kann ich gerne übernehmen.

**Comment by Apollon77** [comment]
Das klingt dann aber eher nach einem Admin5 issue oder ?! @GermanBluefox ?

**Comment by Apollon77** [comment]
@foxriver76 identified an issue in controller that was caused by getStates ... maybe a js-controller issue since the beginning ;-)

**Comment by fu-zhou** [comment]
Awesome news! Thanks for all your efforts and support!

**Comment by Apollon77** [comment]
@fu-zhou will come in js-controller 3.3.12 soon

**Comment by fu-zhou** [comment]
Looking forward to it!
