### ISSUE TITLE
Cleanup invalid user group assignments in setup first

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#1375]
We seem that have some rara cases where users are assigned as group members that no longer exist.
This then sometimes triggers the error from https://github.com/ioBroker/db/blob/d937b3d6ffc6385ccb0e6436cf9f0432fccf08bf/packages/db-objects-redis/lib/objects/objectsUtils.js#L384

We should add a task for "setup first" to check the user groups and fix such invalid assignments and log a line for such a corrected case

**Comment by foxriver76** [comment]
So user does no longer exist? So iterate through all groups and then check each user and check if for each user an object exists, else remove from group?

**Comment by Apollon77** [comment]
Yes

**Comment by Apollon77** [comment]
Normally Users are also removed from groups when deleted ... so no idea where it came from. maybe we had a buch earlier somewhen :-)
