### ISSUE TITLE
Monorepo: Split up the remaining controller in multiple npm packages

### ISSUE THREAD

**Issue by foxriver76** [ioBroker/ioBroker.js-controller#1378]
To modularity but maintain them alle here. And dB should then also be a part of the monorepo. With db we have already tested that this works out well.

**Comment by foxriver76** [comment]
MAybe first step would be to convert this repo into a monorepo having packages

- controller
- one package for each db (as currently in the db monorepo)

then go on and split controller up e. g. cli into a single package

**Comment by Apollon77** [comment]
I would directly split into

* common (all these lib things for now)
* core (main.js and the "compat layer") for the externally used files like lib/tools or letsencrypt
* adapter (mainly adapter.js)
* cli
* db's

This stuff should be relatively good encapsulated already and you mainly need to switch the "requires"

**Comment by foxriver76** [comment]
done ;-)
