### ISSUE TITLE
adapter invalid version - crash iobroker update

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.js-controller#1392]
![grafik](https://user-images.githubusercontent.com/6681528/123937005-05c43a80-d996-11eb-98c9-22ab0af89067.png)

![grafik](https://user-images.githubusercontent.com/6681528/123937153-2b514400-d996-11eb-87d9-3f32a0d2dbea.png)

**Comment by Apollon77** [comment]
Even if "Unpublished "is not an allowed version number we should prevent the crash

**Comment by foxriver76** [comment]
With what strategy, if invalid version list it as non updateable?

**Comment by Apollon77** [comment]
yes ... a try catch , log error, ignore entry as "not upgradable"
