### ISSUE TITLE
make deleteDevice work with full id (and for devices not in instance root?)

### ISSUE THREAD

**Issue by Garfonso** [ioBroker/ioBroker.js-controller#1401]
Yesterday I recognized that deleteDevice was not working for me. I did call it with the full id of a device ( i.e. `adapter.x.deviceName` ). 

The documentation speaks of "deviceName" which lead me in a wrong direction (I though of common.name and by coincidence my first test with that worked) but the description is right, supplying the last part of the id works (if the device is a direct child of the instance object).

Today I did a bit more digging. This line breaks the object id if you supply the full id:
https://github.com/ioBroker/ioBroker.js-controller/blob/master/lib/adapter.js#L3767

After that `adapter.x.deviceName` becomes `adapter_x_deviceName` which obviously does not contain the namespace, so afterwards it will get `adapter.x.adapter_x_deviceName` which obviously won't work. 

Currently it will work if you just supply `deviceName` but it can not work if the device is not a direct child of `adapter.x`. (Maybe that is intended? But I do not really see a reason for that).

My suggestion would be to alter the code and allow a full id. I'm not sure why there are so strict checks in a delete-call. Probably that is a copy & paste error? Also I'd suggest changing the

**Comment by Apollon77** [comment]
Sorry but then it ids more a documentation issue.

deleteDevcie is the counterpart for createDevice and both rely on the hard structure "adaptername.instance.device.[channel.]state" ... nothing more, nothing less.

And hey always work "locally" in the adapter.

If you also check createChannel and delete Channel you will find two parameters - one for "deviceName" and second is "channelName"

We can not break the functionality, but I personally consider this as a morelegacy case becaue emost adapters do not have that hard structure

**Comment by Garfonso** [comment]
ok
