### ISSUE TITLE
JS-Adapter startet nach Node update 12.22.4 nicht mehr

### ISSUE THREAD

**Issue by Audianer** [ioBroker/ioBroker.js-controller#1424]
Hi Zusammen, 

ich hoffe ihr könnt mir helfen. Bisher hatte ich über Blockly immer meine Tonnenabholung terminiert und über den whatsapp die nächste Abholung ausgeben lassen. Seit ich node.js auf die aktuelle Version gebracht habe, kam keine Message mehr an. Nach Überprüfung stellte ich fest, dass der JS-Adapter nicht mehr läuft (Log im Anhang).

Systemupdates sind eigentlich alle soweit durch und ich hab den Adapter auch schon deinstalliert und neu installiert. 

Kann mir hier wer helfen?

Danke und viele Grüße :)

[iobroker log.txt](https://github.com/ioBroker/ioBroker.js-controller/files/6915191/iobroker.log.txt)

**Comment by Apollon77** [comment]
Also für den "Javascript" adapter ist das hier das falsche Repo aber bei Dir sieht es aus dwie ein defektes File ...

> 2021-08-02 00:00:15.021  - [31merror[39m: host.raspberrypi Caught by controller[0]: �       functioj getNodeToInsertPzopertyAfter(#ls) {


Deine Zeile hat am beginnein defektes zeichen und das "j" am Ende von "function" ist auch defekt. Sieht für mich eher nach Filesystem aus.

Daher: SD Karte (nehme ich mal an das das ein sd karten system ist) überprüfen, ggf backup und neue karte nutzen.
