### ISSUE TITLE
function deleteChannel does not delete objects

### ISSUE THREAD

**Issue by DutchmanNL** [ioBroker/ioBroker.js-controller#1429]
js-controller 3.3.14

Current behavior

function deleteChannel will delete all underlying states but not the channel itself or nested structures.

Expected behavior
deleteChannel should word recursively, equal to delObjectAsync(state, {recursive:true}); and ensure all underlying objects/states are removed

**Comment by AlCalzone** [comment]
> or nested structures.

AFAIK a channel is not allowed to have underlying structures other than states.

But honestly I think we should remove that special behavior for those "strict" structures. If you ask me, `deleteChannel` should be equivalent to this:
```
if current object is a channel:
  delObjectAsync("id", {recursive:true});
```

Likewise for `deleteDevice`.

**Comment by DutchmanNL** [comment]
> > or nested structures.
> 
> AFAIK a channel is not allowed to have underlying structures other than states.
> 
> But honestly I think we should remove that special behavior for those "strict" structures. If you ask me, `deleteChannel` should be equivalent to this:
> 
> ```
> if current object is a channel:
>   delObjectAsync("id", {recursive:true});
> ```
> 
> Likewise for `deleteDevice`.

I ageren hat we should release that structure and allow channel.channel or channel.folder as the device.channel structure is only valid for Homematic several other adapters need more nesting.

That will mean more impact as the createChannel currently requires a device, I assume something to handle in another feature request ?
