### ISSUE TITLE
State value to set for "..." has to be type "string" but received type "boolean"

### ISSUE THREAD

**Issue by Dirk-Peter-md** [ioBroker/ioBroker.js-controller#1430]
js-controller 3.3.15
Hallo,
ich erhalte die Meldung im log 'State value to set for "sprinklecontrol.0.sprinkle.Auffahrt.triggerPoint" has to be type "string" but received type "boolean"'. 
Das State wird aber so gesetzt:  
`adapter.setState(objPfad + '.triggerPoint', {
                            val: '-',
                            ack: true
                        });`
bzw. so: 
`adapter.setState(objPfad + '.triggerPoint', {
                            val: (myConfig.config[j].soilMoisture.pctTriggerIrrigation).toString(),
                            ack: true
                        });`
Er kann also nicht vom Type 'boolean' sein!

**Comment by Apollon77** [comment]
Wenn der Check es sagt ist es ein Boolean :-)

see https://github.com/Dirk-Peter-md/ioBroker.sprinklecontrol/blob/master/main.js#L1002

**Comment by AlCalzone** [comment]
Betrifft übrigens auch alle weiteren default-Werte, z.B.
https://github.com/Dirk-Peter-md/ioBroker.sprinklecontrol/blob/e15c2ddda4cf810bf73beff69599d364ed74c716/main.js#L1020
https://github.com/Dirk-Peter-md/ioBroker.sprinklecontrol/blob/e15c2ddda4cf810bf73beff69599d364ed74c716/main.js#L1033
etc...

**Comment by sv-fepa** [comment]
Hallo,

vielleicht hilft dir der Hinweis nachzuschauen, woher der neue Wert kommt. 
Es kann sein, dass in der Visualisierung oder in der ObjektOberfläche ein anderer Typ gesetzt wird, als du intern in deinem Adapter verarbeitest bzw. kann es sein, dass du aus diesem Quellen verschiedene Typen bekommst, also immer den, der in dieser Oberfläche hinterlegt ist.

**Comment by Apollon77** [comment]
Das steht in der Logzeile ganz am Anfang beim verursachenden Adapter! Das ist schon da

**Comment by Dirk-Peter-md** [comment]
Hallo,
der Fehler liegt bei mir, und zwar in dem Befehl „setObjectNotExists“. Hier konnte ich mit „‘def‘: false“ nichts anfangen und habe es dann aus anderen Adaptern so übernommen. Da ich nirgends eine vernünftige Doku gefunden hatte und ich vor einem Jahr noch keine Fehlermeldung bekam, sah ich es auch nie als Fehler an. Jetzt nach einer intensiven Suche mit Google , ist mir der Fehler klar und er wird mit dem nächsten update der Vergangenheit angehören. Ich hoffe es zumindest.
Eine Frage habe ich aber trotzdem:
"common": {
    "role": "indicator",
    "name": "Arbeitszimmer / Gästezimmer",
    "type": "number",
    "unit": "%",
    "read": true,
    "write": false,
    "def": ""
  } 
Wenn der "type": "number" ist, warum steht dann in vielen Adaptern "def": ""? ““ ist doch ein leerer String und ist nicht vom type "number", oder ist das eine Ausnahme wenn das Feld für das State leer bleiben soll, wenn kein Wert beim schreiben ankommt.

Entschuldige wenn ich mich nicht Fachmännisch ausdrücke, aber ich komme nicht aus der Informatik-Branche und bin erst seit einem Jahr bei JS .-)

MfG Dirk Peter

**Comment by Apollon77** [comment]
def istder "default" value der beim Anlegen des Objekts gesetzt wird wenn er angegeben wird :-)

**Comment by Dirk-Peter-md** [comment]
Hallo,
➢ def istder "default" value der beim Anlegen des Objekts gesetzt wird wenn er angegeben wird :-)
das ist mir klar, aber warum steht in einigen Adaptern unter "common": {… bei "type": "number" dann bei "def": "". 
““ ist doch ein leerer String und kein Number, oder ist das so korrekt.

Sorry, für die blöden Fragen, die mir Google nicht beantwortet. 
Dirk Peter

**Comment by Apollon77** [comment]
... weil die im zweifel auch buggy sind und das gleiche Problem haben wie Du jetzt hattest :-)
