### ISSUE TITLE
Warning message for incorrect type of state default is misleading

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.js-controller#1431]
See https://github.com/ioBroker/ioBroker.js-controller/issues/1430
The current message is
> State value to set for "..." has to be type "string" but received type "boolean"

which leads to believe that a `setState` call is incorrect. A better message would be
> The default value for object "..." is of type "boolean" but has to be the defined type "string"

**Comment by Apollon77** [comment]
The error is generic because also setState do not know it it was called from user or from default value of from "wherever" and thats why it is formulated that generic

**Comment by AlCalzone** [comment]
Then we need to add a check before the default is being set.

**Comment by foxriver76** [comment]
Would extend the object check https://github.com/ioBroker/ioBroker.js-controller/blob/287743063dc849bbccbbe557f22e0e7b59445f20/lib/tools.js#L2085
