### ISSUE TITLE
*** is not iterable

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.js-controller#1434]
![grafik](https://user-images.githubusercontent.com/6681528/129957721-392c6a45-38f0-4c59-abb3-4366381eb6f5.png)

**Comment by AlCalzone** [comment]
Any chance you could log before that line what `deps` and `globalDeps` are? I can't think of a single situation where an array is not iterable. If `deps` were not iterable, the error would be `deps is not iterable` instead.

**Comment by foxriver76** [comment]
cannot reproduce this..

**Comment by foxriver76** [comment]
This is really strange and  it only came up once, I would close this until it occurs again. Other opinions? @Apollon77 @AlCalzone
