### ISSUE TITLE
Instances: description is not part of backup / restore

### ISSUE THREAD

**Issue by GitBaer** [ioBroker/ioBroker.js-controller#1448]
If the user changes the default instance descriptions, this is not part of backup / restore ("iobroker backup" / "iobroker restore X"):

![grafik](https://user-images.githubusercontent.com/49997071/131973179-96b10797-5444-4a0b-9bc2-2c940251a652.png)

![grafik](https://user-images.githubusercontent.com/49997071/131973198-999662f4-47bb-4506-a218-1f36008ca66d.png)

The values above are stored in "\iobroker\iobroker-data\objects.json".

I think it should be part of backup / restore process because these descriptions made by the user can be important, especially in large environments.

**Comment by foxriver76** [comment]
Nothing specially to do with a backup, the problem is on an upload, most of the instance attributes expect from native and some special handled things are overwritten and this happens on restore. So in this case we would need to explicitly preserve titleLang
