### ISSUE TITLE
Remove  the testing workaround from *ServerClass when testing is updated in all adapters

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#1457]
see e.g. https://github.com/ioBroker/ioBroker.js-controller/blob/master/packages/db-states-file/lib/states/statesInMemServerClass.js#L25

**Comment by foxriver76** [comment]
is it updated everywhere? ;-)

**Comment by foxriver76** [comment]
AFAIS: We need https://github.com/ioBroker/testing/pull/375/files and then everyone needs to have the new version
