### ISSUE TITLE
[Featurerequest] Filter beim Reiter Ereignisse

### ISSUE THREAD

**Issue by lubeda** [ioBroker/ioBroker.js-controller#146]
Bei der Suche nach Fehler in Skripten ist der Reiter "Ereignisse" sehr hilfreich. Die systemseitigen Events z.B. *.memHeapUsed und *.memRss, etc. stören dabei. 

Ein Schalter um diese Systemevents auzublenden wäre sehr hilfreich.

**Comment by Apollon77** [comment]
Bitte wenn noch relevant in "iobroker.admin" Repo neu eröffen
