### ISSUE TITLE
Optimize Jsonl database implementation

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#1460]
Now with the first experimental Jsonl db we should enhance it in some places:
* allow confguration to come from connection config from iobroker.json (settings object)
* add compressed db backups from time to time (ideally after a compression, based on normal rules like file db - requires "trigger" in compaction)
* how to easirly deliver it to the users? ;-) Maybecreate an "mode none" adapter that only have an inistall trigger and on install finds js-controller dir and installs the packages in dir-context of js-controller :-)
* optimize compactionand else settings

**Comment by Apollon77** [comment]
Additional/Enhanced to above:

0.) Allow confog via settings objects
1.) Automatische Migration - also wenn objects/states.json da ist aber nicht jsonl beim Start dann Daten initialisieren und alte Files löschen
2.) FileDB hat einen backup mechanismus das immer beim speichern nach Zeit X eine .gz Version angelegt wird. Sowas sollten wir auch tun. Könnte man durch ein "compacted" event von jsonl machen ... Frage auch ob jsonl sichern oder oldstyle komplett json. Wenn wir jsonl sichern kann m,an sogar denke einiges wiederverwenden aus InMemFileDB ... nur das triggern des backups fehlt
3.) Kurz über fälle nachdenken wo user aus gewohnheit alte backups zurückkopieren ...
4.) dann file und jsonl pakete "syncen" das sie das gleiche liefern für die user die vorher umgestellt haben (müssen wir dann spöter aufräumen)
5.) Nochmal die performance tests machen ... letzte tests hatten ja 30% weniger durchsatz bei jsonl im Vergleich zu FileDB

**Comment by Apollon77** [comment]
Here are some results of discussion about migration, so here the idea:
* We stay with separate classes for "file" and "jsonl" as now (for compatibility reasons for rollback cases and for the case that we need to react fast if jsonl has issues; file can be removed in 4.x)
* We add a migration logic to the jsonl class that:
    * when no json/json.bak file exists but a json file reads the json file (old style logic incl. fallbacks) and initialize te jsonl with it (https://github.com/AlCalzone/jsonl-db#import--export)
    * if jsonl exists but an existing json/json.bak has newer date also obverwrite jsonl with the json file (?)
    * When this was done the json files should be renamed to e.g. "*.automigrated" or such, also that next starts do not have to check them all the time
    * We need to adjust "backup restore infos" because someone could try to restore a json backup after jsonl was used (and gunzip could restore old filedate?)
* the "setup" logic adjusts the iobroker config file and replace file by json (only exactly this case!!) in db type - we need to check where best to do that ... no idea if other places do this already

Buy doing it that way a rollback to at least controller 3.3 is possible because jsonl was also included there already for all cases. Only controller downgrades <3.3 will make issues/are not possible (without a custom migration to "file" before the downgrade).
And with this is is really clear also in "iobroker status" which DB type is used and file stay with the defined meaning - same for jsonl.

**Comment by AlCalzone** [comment]
> when no json/json.bak file exists but a json file reads the json file (old style logic incl. fallbacks)

You mean when no json**L** file exists, right? There is no jsonl.bak though (no need). Do we look at potential jsonl.gz backups too?

> if jsonl exists but an existing json/json.bak has newer date also obverwrite jsonl with the json file (?)

👍🏻

**Comment by Apollon77** [comment]
Adjusted the sentence ... and no, .gz is ignore as now too

**Comment by AlCalzone** [comment]
First parts are done in https://github.com/ioBroker/ioBroker.js-controller/pull/1639

**Comment by Apollon77** [comment]
Ok, basically only the "adjust db types at the end of "setup" is open

**Comment by Apollon77** [comment]
I close here. Finalizing in #1688
