### ISSUE TITLE
Nach Update JS-Conztroller auf 3.3.16 VIS-Lizenz ungültig

### ISSUE THREAD

**Issue by Harry-58** [ioBroker/ioBroker.js-controller#1464]
Nach Update des JS-Contollers auf die aktuelle Version 3.3.16 meldet VIS, dass keine gültige Lizenz vorhanden ist.

Der Fehler kommt nur bei der Offline-Lizenz. Wenn ich die "normale" Lizenz benutze funktioniert VIS.
Habe vor dem Update die Seriennummer, die in den Einstellungen von  VIS angezeigt wird, gesichert.
Nach dem Update war eine andere Seriennummer eingetragen!

Im Changelog vom JS-Controller steht: (bluefox) Adjust generation of installation UUID
Vermute, es hängt damit zusammen.

siehe auch mein Issue in ioBroker.vis
#https://github.com/ioBroker/ioBroker.vis/issues/400#issue-992070824

**Comment by foxriver76** [comment]
Docker?

**Comment by foxriver76** [comment]
Wie von Ingo erwähnt bitte E-Mail an mailto:info@iobrtoker.net

**Comment by Harry-58** [comment]
raspberry pi 4
Plattform    linux
Betriebssystem    linux
Architektur    arm
CPUs    4
Geschwindigkeit    1500 MHz
Modell    ARMv7 Processor rev 3 (v7l)
RAM    3.75 GB
System-Betriebszeit    02:57:39
Node.js    v14.17.6 
NPM    6.14.15
