### ISSUE TITLE
Redis errors without Redis

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.js-controller#1479]
Hi .. I get errors about the zigbee adapter not being able to write to a Redis DB .. without ever having Redis installed.
I thought it was zigbee's fault .. so I reference to that thread:

https://github.com/ioBroker/ioBroker.zigbee/issues/1210#issuecomment-923304967

**Comment by Apollon77** [comment]
ioBroker uses internally the Redis protocol also to communicate the the own "file DB" .. so this error is normal. I commented in other thread
