### ISSUE TITLE
native part of object is overwritten from io-package.json on every adapter restart

### ISSUE THREAD

**Issue by Garfonso** [ioBroker/ioBroker.js-controller#1481]
lovelace defines an object with native part in io-package.json: [control.alarm](https://github.com/ioBroker/ioBroker.lovelace/blob/master/io-package.json#L503)

On every adapter restart the native part is reset to the value in io-package,json (which makes the proposed use impossible ;-) ). This code is quite old (and from bluefox). Not sure if this ever worked or if this is supposed to work, but for the proposed use it would be nice if the native part was not set on every adapter start but only if the object did not exist.

**Comment by foxriver76** [comment]
Yes, I think we should preserve the native. Native is meant to be adapted at runtime with e.g. parameters of the real devices. I will create an PR later. 

It has most likely worked somewhere in the past but with introducing our extend logic it's behaviour has changed a bit.

**Comment by Garfonso** [comment]
Thanks for fixing. 

Do I understand the labels correctly and it will be fixed in 4.0.x and won't make it into 3.x?

**Comment by Apollon77** [comment]
Correct
