### ISSUE TITLE
Nach Update auf 1.1.1 keine Verbindung der Multihost Slaves zum Master

### ISSUE THREAD

**Issue by buanet** [ioBroker/ioBroker.js-controller#149]
Wie hier berichtet:

http://forum.iobroker.net/viewtopic.php?p=75027

Verbinden sich die Slaves meiner Multihostumgebung nach dem Update auf js-controller 1.1.1 nicht mehr mit dem Master. 

Nach Anpassung der /opt/iobroker/iobroker-data/iobroker.json wie im Changelog erwähnt:

"host": "127.0.0.1",
=>
"host": "0.0.0.0",

startet ioBroker nicht mehr. Nach Änderung zurück auf 127.0.0.1 startet zumindest ioBroker wieder.

MfG,
André

**Comment by GermanBluefox** [comment]
Sollte mit 1.1.2 fixed sein
