### ISSUE TITLE
New installation: Repositories are named default/latest instead of stable/beta

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.js-controller#1495]
I've installed ioBroker by using the installation script:

```
curl -sLf https://iobroker.net/install.sh | bash -
```

After that, both repositories are not named correctly (default / latest):

<img width="2036" alt="Screenshot 2021-10-03 at 15 26 38" src="https://user-images.githubusercontent.com/1959049/135755771-9f4d2e57-51a6-4bc1-a126-5057711f7fab.png">

AFAIK they should be renamed to stable / beta:

https://github.com/ioBroker/ioBroker.js-controller/blob/5034a8a31a26c74d1347c13e9339cd7c883a7d32/packages/controller/lib/setup.js#L542-L543

- js-controller 3.3.18
- admin: 5.1.25

**Comment by foxriver76** [comment]
Thanks for reporting, on fresh installations we missed a spot. Calling `iob setup` will fix it for your installation.
