### ISSUE TITLE
Error: chmod auf Mac (Darwin)

### ISSUE THREAD

**Issue by justr1** [ioBroker/ioBroker.js-controller#150]
Hi Bluefox,
im js-controller kommt mehrfach ein
"chmod 777 -R ..." oder "chmod 777 ... -R"
vor. Ich bekomme unter MacOS (Darwin) dann immer den Fehler
"chmod: -R: No such file or directory"
und ich führe den chmod manuell aus. Unter MacOS muss das "-R" zwingend vor dem Mode "777" stehen. Weiß nicht, wie es unter Linux ist. Habe deshalb von einer direkten Code-Änderung Abstand genommen.  ;-)

**Comment by Locke** [comment]
Hi,

unter Linux (Debian 8.8) gehen beide Varianten.

Beim Ausprobieren habe ich eben festgestellt dass ich für `chmod` das `-R` zwischen den Attributen und dem Ordner verwende, aber für `chown` vor dem Benutzer. Interessanterweise ist das nur eine Gewohnheit und bei beiden Befehlen funktionieren beide Varianten.

**Comment by GermanBluefox** [comment]
Eigentlich es schon geändert.
https://github.com/ioBroker/ioBroker/commit/7c4ac133b473702861db8d31699bab215c328769

Oder gibt es noch irgendwo?

2 Авг 2017 г. 12:35 пользователь "André Wolski" <notifications@github.com>
написал:

**Comment by justr1** [comment]
Mir ist gerade die Aufteilung zwischen den Repositories "ioBroker/ioBroker" sowie "ioBroker/ioBroker.js-controller" nicht klar. Aber im js-controller gibt es mindestens Vorkommen in:
```
reinstall.sh
lib/setup/setupUpgrade.js
lib/objects/objectsInMemServer.js
```
