### ISSUE TITLE
Add common.jsonCustom and common.jsonConfig to io-package.json Schema

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.js-controller#1500]
https://github.com/ioBroker/ioBroker.js-controller/blob/5034a8a31a26c74d1347c13e9339cd7c883a7d32/packages/controller/schemas/io-package.json

**Comment by klein0r** [comment]
What is the correct way to define Admin 5 json config usage?

```
    "adminUI": {
        "config": "json"
    }
```

or

```
    "jsonConfig": true,
```

**Comment by foxriver76** [comment]
AFAIR it was only during development of admin 5, that BF introduced jsonConfig boolean flag etc. and we came to the conclusion, that it will be better structured in an `adminUI` attribute, thus `jsonConfig` and similar are only needed for some admin versions which have never been in stable repo. 

Hence, I would close this one.
