### ISSUE TITLE
Translated instance objects lead to type error

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.js-controller#1521]
> /opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupInstall.js:1005 Object.keys(adapterConf.instanceObjects[i].common.name).forEach(lang => adapterConf.instanceObjects[i].common.name[lang] = adapterConf.instanceObjects[i].common.name.replace('%INSTANCE%', instance)); ^TypeError: adapterConf.instanceObjects[i].common.name.replace is not a function at /opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupInstall.js:1005:211 at Array.forEach () at Immediate. (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupInstall.js:1005:101) at processImmediate (internal/timers.js:463:21)

## See

https://github.com/ioBroker/ioBroker.js-controller/blob/2a45f11e46e3c9c8acd8e401744c0d84a9819310/lib/setup/setupInstall.js#L1005

## Example

```
        {
            "_id": "type.json",
            "type": "state",
            "common": {
                "name": {
                    "en": "Types as JSON",
                    "de": "Typen als JSON",
                    "ru": "Типы как JSON",
                    "pt": "Tipos como JSON",
                    "nl": "Typen als JSON",
                    "fr": "Types en JSON",
                    "it": "Digita come JSON",
                    "es": "Tipos como JSON",
                    "pl": "Typy jako JSON",
                    "zh-cn": "类型为 JSON"
                },
                "type": "string",
                "role": "json",
                "read": true,
                "write": false
            },
            "native": {}
        },
```

## Solution

```javascript
Object.keys(adapterConf.instanceObjects[i].common.name).forEach(
lang => adapterConf.instanceObjects[i].common.name[lang] = 
adapterConf.instanceObjects[i].common.name[lang].replace('%INSTANCE%', instance)
);
```

**Comment by klein0r** [comment]
Found in https://github.com/klein0r/ioBroker.trashschedule/issues/89

**Comment by foxriver76** [comment]
will look at it as soon as monster PR is merged #1520 👍

**Comment by foxriver76** [comment]
we are just missing to access lang attribute at first look I would say.

**Comment by klein0r** [comment]
OMG 😆

**Comment by klein0r** [comment]
> we are just missing to access lang attribute at first look I would say.

Is it not recommended to use translated object names right now? I'm currently updating all my adapters 😨

**Comment by foxriver76** [comment]
It is good style to do it, but seems like no one has done it (at least) for instanceObjects yet. On a quick search I haven't found an object using it yet on my test env, so you are a beta tester dev ;-)
