### ISSUE TITLE
js-controller update  3.3.19 - "TZID without Luxon available is unsupported" 

### ISSUE THREAD

**Issue by realwax** [ioBroker/ioBroker.js-controller#1528]
`
host.iobrokerQNAP | 2021-11-21 09:43:15.309 | error | Caught by controller[8]: Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone
-- | -- | -- | --
host.iobrokerQNAP | 2021-11-21 09:43:15.309 | error | Caught by controller[7]: Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone
host.iobrokerQNAP | 2021-11-21 09:43:15.309 | error | Caught by controller[6]: Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone
host.iobrokerQNAP | 2021-11-21 09:43:15.309 | error | Caught by controller[5]: Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone
host.iobrokerQNAP | 2021-11-21 09:43:15.309 | error | Caught by controller[4]: Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone
host.iobrokerQNAP | 2021-11-21 09:43:15.308 | error | Caught by controller[3]: Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone
host.iobrokerQNAP | 2021-11-21 09:43:15.308 | error | Caught by controller[2]: Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone
host.iobrokerQNAP | 2021-11-21 09:43:15.308 | error | Caught by controller[1]: Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone
host.iobrokerQNAP | 2021-11-21 09:43:15.307 | error | Caught by controller[0]: Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone
`

Logs are getting filled with the above. Seems to be related. 

https://github.com/jakubroztocil/rrule/issues/441

**Comment by foxriver76** [comment]
Can you please show what happens before and after that in the log

**Comment by foxriver76** [comment]
can you please show what happens before and after that in the logs

**Comment by Apollon77** [comment]
Also which adapter generates this log? iCal? Then the issue needs to go there

**Comment by realwax** [comment]
Yes. ical....

2021-11-21 12:01:07.553  - [32minfo[39m: ical.0 (21640) processing URL: xyz
2021-11-21 12:01:08.395  - [32minfo[39m: ical.0 (21640) processing URL: xyz2
2021-11-21 12:01:14.505  - [32minfo[39m: ical.0 (21640) Terminated (NO_ERROR): Without reason
2021-11-21 12:01:15.293  - [31merror[39m: host.iobrokerQNAP Caught by controller[0]: Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone
2021-11-21 12:01:15.293  - [31merror[39m: host.iobrokerQNAP Caught by controller[1]: Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone
2021-11-21 12:01:15.293  - [31merror[39m: host.iobrokerQNAP Caught by controller[2]: Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone
2021-11-21 12:01:15.294  - [31merror[39m: host.iobrokerQNAP Caught by controller[3]: Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone
2021-11-21 12:01:15.294  - [31merror[39m: host.iobrokerQNAP Caught by controller[4]: Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone

**Comment by foxriver76** [comment]
Then it s an ical issue controller just catches

**Comment by realwax** [comment]
Thanks for the quick reply. Created there an issue. Closing this....
Have a nice sunday!

**Comment by wendy2702** [comment]
How to be sure that this is coming from ical?

I'm not able to see that error at iob log but my syslog is full:

`Feb  3 17:34:05 iobroker bash[4117]: Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone
Feb  3 17:34:05 iobroker bash[4117]: Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone
Feb  3 17:34:05 iobroker bash[4117]: Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone
Feb  3 17:34:05 iobroker bash[4117]: Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone
Feb  3 17:34:05 iobroker bash[4117]: Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone
Feb  3 17:34:05 iobroker bash[4117]: Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone
Feb  3 17:34:05 iobroker bash[4117]: Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone
Feb  3 17:34:05 iobroker bash[4117]: Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone
Feb  3 17:34:05 iobroker bash[4117]: Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone
Feb  3 17:34:05 iobroker bash[4117]: Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone
Feb  3 17:34:05 iobroker bash[4117]: Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone
Feb  3 17:34:05 iobroker bash[4117]: Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone
Feb  3 17:34:05 iobroker bash[4117]: Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone
Feb  3 17:34:05 iobroker bash[4117]: Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone
Feb  3 17:34:05 iobroker bash[4117]: Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone
Feb  3 17:34:05 iobroker bash[4117]: Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone
Feb  3 17:34:05 iobroker bash[4117]: Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone
Feb  3 17:34:05 iobroker bash[4117]: Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone
Feb  3 17:34:05 iobroker bash[4117]: Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone
Feb  3 17:34:05 iobroker bash[4117]: Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone
Feb  3 17:34:05 iobroker bash[4117]: Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone
Feb  3 17:34:05 iobroker bash[4117]: Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone
Feb  3 17:34:05 iobroker bash[4117]: Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone
Feb  3 17:34:05 iobroker bash[4117]: Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone
Feb  3 17:34:05 iobroker bash[4117]: Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone
Feb  3 17:34:05 iobroker bash[4117]: Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone
Feb  3 17:34:05 iobroker bash[4117]: Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone
Feb  3 17:34:05 iobroker bash[4117]: Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone
Feb  3 17:34:05 iobroker bash[4117]: Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone
Feb  3 17:34:05 iobroker bash[4117]: Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone
Feb  3 17:34:05 iobroker bash[4117]: Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone
Feb  3 17:34:05 iobroker bash[4117]: Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone
Feb  3 17:34:05 iobroker bash[4117]: Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone
Feb  3 17:34:05 iobroker bash[4117]: Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone
`
