### ISSUE TITLE
3.3.19 multihost not working

### ISSUE THREAD

**Issue by JustMe0815** [ioBroker/ioBroker.js-controller#1535]
tried installing iobroker with latest 3.3.19 and had issues getting multihost working.

see https://forum.iobroker.net/topic/49654/slave-installation-reassign-instance-falsch/32?_=1637749391114

**Comment by Apollon77** [comment]
thank you! We will prepare 3.3.20 soon and also fix it isn 4.0 dev

**Comment by Apollon77** [comment]
@JustMe0815 Can you please try controller 3.3.20 just released to npm? ... hsould be in latest repo soonbut can be installed with "npm i iobroker.js-controller@3.3.20"

**Comment by Ilovegym66** [comment]
Hi ah, yesterday I created a new host in my multihost system, and he don't found the server, I got error message, I upgraded today to 3.3.20, but the same.  Before I do this, I'd set the iobroker with iobroker setup custom to the redis, what I'm use.  In prinzip every thing is working fine, I can control everything, but at the config the multihost connection is not avaivable.. 
here in this case I test it with Node 16 and NPM8, but the same with Node 12 and 14 etc..
`ilovegym@berrymotion:~ $ cd /opt/iobroker
ilovegym@berrymotion:/opt/iobroker $ iobroker update
Used repository: Beta (latest)
hash unchanged, use cached sources
update done
Adapter    "admin"         : 5.1.28   , installed 5.1.28
Controller "js-controller" : 3.3.20   , installed 3.3.19 [Updateable]
ilovegym@berrymotion:/opt/iobroker $ iobroker stop
ilovegym@berrymotion:/opt/iobroker $ iobroker upgrade self
Update js-controller from @3.3.19 to @3.3.20
NPM version: 8.1.0
npm install iobroker.js-controller@3.3.20 --loglevel error --unsafe-perm                                                                                --prefix "/opt/iobroker" (System call)
ilovegym@berrymotion:/opt/iobroker $ iobroker multihost browse
No Multihost server found. Make sure iobroker is running on the host where you enabled multihost discovery (and it is not this host)!
ilovegym@berrymotion:/opt/iobroker $ iobroker multihost connect
No Multihost server found. Make sure iobroker is running on the host where you enabled multihost discovery (and it is not this host)!
ilovegym@berrymotion:/opt/iobroker $ iobroker start
ilovegym@berrymotion:/opt/iobroker $

`

**Comment by JustMe0815** [comment]
@Apollon77 
> @JustMe0815 Can you please try controller 3.3.20 just released to npm? ... hsould be in latest repo soonbut can be installed with "npm i iobroker.js-controller@3.3.20"

Yes, this seems to have solved the issue. salve is connecting to master without issues now. Master admin is starting up and can see slave just fine.

**Comment by Apollon77** [comment]
@Ilovegym66 This isssue is not about mutlihost discovery ... are UDP packages routed between the hosts?

**Comment by Ilovegym66** [comment]
ah sorry, I check this and if I found something, I open another issue. Thanks.
