### ISSUE TITLE
Add info to all log messages, if current adapter was installed over github (instead of npm)

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.js-controller#1540]
Current situation:

Some users install "undefined versions" from GitHub URLs instead of using fixed npm releases / packages. In this situation, it is very hard to support the user, because no one knows

1) that the adapter was installed by using github and
2) which version (commit) has been installed.

@Apollon77 said, that the js-controller saves the installed source in `iopack.common.installedFrom` (which is already used in Admin 5).

After some discussion on Discord, it would be great if we can add the information to every log entry. In that case, every "supporter" recognizes immediately, that the current log file was generated by an "undefined version" from github.

e.g. `[git install] <original log message>` or `<original log message> [dev]`

**Comment by klein0r** [comment]
The Admin 5 info is `<Tooltip title={t('Non-NPM-Version: ') + installedFrom}>`

Maybe we should use that wording in log messages, too

**Comment by foxriver76** [comment]
I would admit to add it to the `starting version xy` logging which happens on `ìnfo` level. But extend every log message.. I am not quite sure yet.

**Comment by AlCalzone** [comment]
> add it to the starting version xy logging which happens on ìnfo level

👍🏻

**Comment by klein0r** [comment]
> But extend every log message.. I am not quite sure yet.

The idea was, that the user cannot avoid to copy / show the "non npm usage".

**Comment by foxriver76** [comment]
I get the idea, but it's really radical to enrich every log message. Of course then you have to ask for logs from adapter start, personally I hadn't many problems with users which are on GH versions. And now in admin 5 we already have some hints + then logging at start.. would be good to see how it goes.

**Comment by Apollon77** [comment]
I see it the same. on every logline it is overkill in my eyes. SHould be enough to log with the start log.

I also think that this "problem" is made bigger then it actually is in reality. But yes as long as Videos and such tell people to install from GitHub it will not get better - and also the logging will not make the issue go away, it "Just" helps the developer when he gets issues ...

**Comment by klein0r** [comment]
> I also think that this "problem" is made bigger then it actually is in reality.

Just search for "Katze" in our forums 😄
A lot of (inexperienced) users give the "hint" to use that feature to solve a problem.

**Comment by Apollon77** [comment]
But then the better solution is to enhance the "awareness" in admin about what someone does.
