### ISSUE TITLE
Add Sentry into CLI executions

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#1576]
Sentry is only used in main.js and not on CLI, so we are blind for error happening there.

We could use the  Sentry Plugin like in main.js - but this needs an initialized DB ...

**Comment by foxriver76** [comment]
for many commands we need dbconnect anyways, so we could try to make an initial db connect load sentry if allowed by current settings and if it's not possible just fail silently. but the active PR of bf is currently blocking work in setup.js

**Comment by Apollon77** [comment]
Will be merged very soon
