### ISSUE TITLE
js-controller state subscription error

### ISSUE THREAD

**Issue by frankjoke** [ioBroker/ioBroker.js-controller#160]
I tried Alexa script and have in-memory states (still could not get redis working again since 2 month).

The scripts works but it uses an sunbscription with an regexp and this generates the following error:
`

iobroker | 2018-01-03 00:59:44.798 | info | _restart
-- | -- | -- | --
TypeError: | 2018-01-03 00:59:44.793 | error | at process._tickCallback (internal/process/next_tick.js:104:9)
TypeError: | 2018-01-03 00:59:44.793 | error | at _combinedTickCallback (internal/process/next_tick.js:73:7)
TypeError: | 2018-01-03 00:59:44.793 | error | at /opt/iobroker/node_modules/socket.io/lib/socket.js:503:12
TypeError: | 2018-01-03 00:59:44.793 | error | at Socket.emit (events.js:191:7)
TypeError: | 2018-01-03 00:59:44.793 | error | at emitTwo (events.js:106:13)
TypeError: | 2018-01-03 00:59:44.793 | error | at Socket. (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInMemServer.js:400:28)
TypeError: | 2018-01-03 00:59:44.793 | error | at Socket.StatesInMemory.subscribe (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInMemServer.js:717:9)
TypeError: | 2018-01-03 00:59:44.793 | error | at subscribe (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInMemServer.js:302:53)
TypeError: | 2018-01-03 00:59:44.793 | error | at pattern2RegEx (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInMemServer.js:286:27)
TypeError: | 2018-01-03 00:59:44.793 | error | pattern.replace is not a function
uncaught | 2018-01-03 00:59:44.778 | error | exception: pattern.replace is not a function
javascript.0 | 2018-01-03 00:59:44.630 | info | script.js.script.Alexa: --- Subscriptions angelegt ---

`
Whole ioBroker restarts afterwards, it happens not when subscription is generated but 3-4 seconds later when maybe first event is checked against it.

**Comment by frankjoke** [comment]
p.s.: Others who have redis semm not to have the problem, and I don't know so far if it is the javascript or js-controller who is the cause.

**Comment by Apollon77** [comment]
which js-controller version?

**Comment by frankjoke** [comment]
Ingo, it's 1.2.3  on my production and test system.

**Comment by GermanBluefox** [comment]
OK. I will check this. 
But another question: Who sends `subscribe(null)` ?

**Comment by frankjoke** [comment]
I could not identify this exacly, only that if I do not executre the on("id":reg ...) below by inserting a return the error does not appear.
`    var reg = new RegExp("^javascript\\."+instance+"\\." + devicePfad.replace(/\./g, '\\\.') + ".+\\.(volume|pause|play|next|forward|rewind|shuffle|tunein|radio|previous|bluetooth)$");
    return;
    on({"id":reg , "change": "any"}, function (obj) {
`
It could be a bug in javascript adapter on() as well, the regexp is working.

**Comment by GermanBluefox** [comment]
Ok. Now I understand. You regexp returns "null". Sometimes.

**Comment by frankjoke** [comment]
Yes, as I mentioned, the regexp works and the script should subscribe to all id's which match the regexp.
I don't know now if javascript on() or the js-controller generates the 'null' sent to the object store.

**Comment by GermanBluefox** [comment]
> I don't know now if javascript on() or the js-controller generates the 'null' sent to the object store.

I know. It is so.
