### ISSUE TITLE
Fehler beim Upgrade auf 3.3.22

### ISSUE THREAD

**Issue by MarkSau** [ioBroker/ioBroker.js-controller#1604]
Hi

Habe diesen Fehler beim Upgrade auf 3.3.22 bekommen:

Update js-controller from @3.3.21 to @3.3.22
NPM version: 6.14.15
npm install iobroker.js-controller@3.3.22 --loglevel error --unsafe-perm --prefix "/opt/iobroker" (System call)
/bin/sh: 1: cmake: not found
make: *** [config_deps.target.mk:13: /opt/iobroker/node_modules/cpu-features/deps/cpu_features/build/Makefile] Error 127
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
gyp ERR! System Linux 5.13.19-2-pve
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/iobroker/node_modules/cpu-features
gyp ERR! node -v v14.18.2
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok

OS: Ubuntu 21.04

**Comment by MarkSau** [comment]
Habe jetzt cmake nachinstalliert und den NPM Befehl nochmal ausgeführt. Ok, soweit...Aber sollte das der js-controller install nicht selbst machen?

**Comment by AlCalzone** [comment]
Nur wenn der Adapter der das benötigt die Abhängigkeit angibt. Was hier wohl nicht der Fall ist.

**Comment by Apollon77** [comment]
Exakt, die dop kommt von irgendeinem anderen npm modul ... @AlCalzone cmake mit beim installer installieren?

**Comment by AlCalzone** [comment]
Keine Ahnung. Spricht was dagegen?

**Comment by Apollon77** [comment]
Nix :-)

**Comment by Apollon77** [comment]
https://github.com/ioBroker/ioBroker/issues/365
