### ISSUE TITLE
Remove "noNamespace" from Adapter constructor type info

### ISSUE THREAD

**Issue by jogibear9988** [ioBroker/ioBroker.js-controller#1616]
Parameter does not exist any more

**Comment by jogibear9988** [comment]
Paremter is removed, needs to fixed here too: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/iobroker/index.d.ts#L305

**Comment by AlCalzone** [comment]
I'll take care of the 2nd part if someone can confirm.

**Comment by foxriver76** [comment]
Only occurrence in controller was a legacy comment which has been removed by @Apollon77 now. So only typings need to be fixed or is it somewhere in docs too?

**Comment by Apollon77** [comment]
I adjusted the one docs-repo place too ... so typings should be only left
