### ISSUE TITLE
Better support for "non-root"-Usage for better security

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#162]
The idea is to have a flag per Adapter if he needs special root rights to be installed or used. Candidates are zwave, all Adapter with Serialport like discovery and such.

Flag in "io-package.json" could be 

```
"requireRoot": true
```

If this flag is set then the adapter will be installed with "sudo" in front on Linux/macOS, and maybe also --unsafe-perm. Additionally when starting the adapterproess the start is also done via "sudo".
When such an Adapter get's installed Admin should show an info message stating that this is a special adapter and such.
If the user can do things (e.g. with the serial ports) to get rid of the root requirement then it should also be possible to start the adapter without sudo from then on. or we need the option on install to show what can be done and allow to install without root (because requirement cleared).

This maybe really would allow to get rid of the "you need root to run iobroker" and/or "chmod 777" :-)

**Comment by AlCalzone** [comment]
IMO we should differentiate between 
* installation requires root
* execution requires root

Tradfri for example only requires root for installation because a package might potentially be compiled, but not for execution.

**Comment by Apollon77** [comment]
Also "compilation" itself do not always require root ... only if library files are installed by the process to system directories (like zwave) ... if it is only nodejs specific comple it may not need root

**Comment by AlCalzone** [comment]
Here's an example where a module installation only seems to work with `sudo` and `--unsafe-perm`:
http://forum.iobroker.net/viewtopic.php?f=30&t=11565&start=20

**Comment by Apollon77** [comment]
@AlCalzone postpone to 2.1+?

**Comment by AlCalzone** [comment]
Fine with me

**Comment by Apollon77** [comment]
Downgrade to backlog because shifted several times now. Put to planned again if someone really plans to work on it please

**Comment by foxriver76** [comment]
This now seems to be a duplicate of #348

**Comment by AlCalzone** [comment]
Seems so
