### ISSUE TITLE
installDir is undefined under Windows

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.js-controller#1632]
Adapter update from GIT is not available
![grafik](https://user-images.githubusercontent.com/6681528/147859401-3b87f618-6857-473e-8269-b446bca7f604.png)

![grafik](https://user-images.githubusercontent.com/6681528/147859405-1c4ed91b-021d-4f59-8779-75927b60f1be.png)

direct Update works
![grafik](https://user-images.githubusercontent.com/6681528/147859415-d5c386a9-1716-408d-ad8c-f8ff135d9174.png)

**Comment by foxriver76** [comment]
Fixed on GH, please try new build tomorrow
