### ISSUE TITLE
`logger` is undefined, but used when loading it fails with a different error than `EACCES_LOG`.

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.js-controller#1638]
See
https://github.com/ioBroker/ioBroker.js-controller/blob/fd9503254056dd5fba57972394c61bdd5d04fddb/main.js#L4554-L4557

and the following lines.

**Comment by Apollon77** [comment]
Should we crash without logger or what we should do in such a case?

**Comment by foxriver76** [comment]
I think we should crash, there’s no reason on a working system that this can happen, so better not start.
