### ISSUE TITLE
Enhance diag Data for db types and compact mode

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#1648]
We should enhance the sent diag data by
* db types to get a statistic of number of stae/object DB combinations as chart
* compactmode controler true/false
* number of compactmode instances (if enabled)
@GermanBluefox what do you think??

**Comment by AlCalzone** [comment]
Size of the DBs? (no. of states and objects could be intersting to know what to optimize for)

**Comment by Apollon77** [comment]
could be harder to get  ebacsue file/jsonl different then redis or such .... so prio b for me personally ... but yes interesting
