### ISSUE TITLE
[Testing] Add tests for promisified functions

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.js-controller#165]
See discussion in #163

**Comment by foxriver76** [comment]
We are more and more changing all methods to promisified versions. Do we really need separate tests?

**Comment by foxriver76** [comment]
I would tend to close this one, as it has no real purpose anymore. We are writing new tests in async/await style and also new methods are implemented without callback style. Also if someone touches old tests they are often rewritten to async/await style
