### ISSUE TITLE
Compact Mode should be supported for npm modules wich have type 'module'

### ISSUE THREAD

**Issue by jogibear9988** [ioBroker/ioBroker.js-controller#1667]
When a NPM Package (a iobroker Adapter) now uses full ES6,
then it could not use the compact mode code :

      if (require.main !== module) {
          // Export the constructor in compact mode
          /**
           * @param {Partial<utils.AdapterOptions>} [options={}]
           */
          module.exports = (options) => new WebUi(options);
      } else {
          // otherwise start the instance directly
          new WebUi();
      }

cause require is not defined.

Maybe a ES6 package should always export it's adapter class, and never instantiate it. And the Controller then imports it and creates the instance (as compact or as extra process)

like this maybe?

      export default WebUi

**Comment by Apollon77** [comment]
We need something backward comatible ... so if then we would need to detect an instance vs "Just the exported class"

**Comment by jogibear9988** [comment]
What needs to be backward compatible? The Adapter or the controller?
The controller could look for the "type" field in the package.json.
And the Adapter could only work with new controllers wich support this.

**Comment by AlCalzone** [comment]
Side note: I don't think "next version" is a good target for this mammoth project 🙈 @Apollon77

**Comment by Apollon77** [comment]
Already removed it :-) I would put the "prepare" ticket into backlog  for more like" plan a road to it ... or not" :-)

**Comment by foxriver76** [comment]
related to #1379

**Comment by AlCalzone** [comment]
> related to #1379 

Indeed ![image](https://user-images.githubusercontent.com/17641229/149142203-88de81ac-f7a4-4b92-865f-19723dd4d39c.jpeg)

🤣

**Comment by foxriver76** [comment]
> > related to #1379
> 
> Indeed ![image](https://user-images.githubusercontent.com/17641229/149142203-88de81ac-f7a4-4b92-865f-19723dd4d39c.jpeg)
> 
> 🤣

Oops ;-)

Doppelt hält besser

**Comment by foxriver76** [comment]
What seems to be very hard on a first glance is the decaching done at https://github.com/ioBroker/ioBroker.js-controller/blob/5c68c593a86f333597a4506cf6e8c9c301a8ebe0/packages/controller/src/main.ts#L4708 it seems like there is no possibility currently to decache an imported ESM module.

**Comment by foxriver76** [comment]
Go to would be to create a dummy adapter with ESM support and then see if it generally starts and then check if we can do something about compact mode.

**Comment by jogibear9988** [comment]
If you need a sample, my adapter here: https://github.com/iobroker-community-adapters/ioBroker.webui/blob/master/dist/backend/main.js is a ESM one

**Comment by foxriver76** [comment]
Thanks. And generally is working correctly with controller just compact mode is not working?

**Comment by mcm1957** [comment]
@jogibear9988 

> If you need a sample, my adapter here: https://github.com/iobroker-community-adapters/ioBroker.webui/blob/master/dist/backend/main.js is a ESM one

If compact does not work please set compact to false at io-package!

**Comment by jogibear9988** [comment]
> Thanks. And generally is working correctly with controller just compact mode is not working?

Think so. But my adapter does not use many features, but I think it's workin.
