### ISSUE TITLE
"iobroker multihost xxx" not working

### ISSUE THREAD

**Issue by eric2905** [ioBroker/ioBroker.js-controller#167]
On master:
"iobroker multihost enable" and set a password

On slave:
"iobroker multihost browse"
Shows list with master

"iobroker multihost connect"
Shows again the master, choose 1 and give the password
Message " Config ok. Please restart ioBroker: "iobroker restart" "

On the master there is only one host ... only the master.

Using the manuell way (iobroker setup custom) everything works fine.

**Comment by GermanBluefox** [comment]
Fixed. Please test with 1.2.6
