### ISSUE TITLE
Add eslint-plugin-jsdoc to improve documentation quality

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.js-controller#1676]
https://github.com/gajus/eslint-plugin-jsdoc

**Comment by Apollon77** [comment]
Ok, just adding the plugin will not change anything :-) So the real question is what the "wanted" settings should be :-)

**Comment by klein0r** [comment]
Of course, this is just a hint to add and configure this feature to avoid incorrect jsdoc.

**Comment by foxriver76** [comment]
We can have a look at it. Not sure if we have a problem here..  Of course this will have no effect for external devs, here the typings should be relevant.
