### ISSUE TITLE
Redis simulator freaking slow on multi/exec

### ISSUE THREAD

**Issue by foxriver76** [ioBroker/ioBroker.js-controller#1678]
No matter if Pipeline or not used.. we haven’t found anything helpful until now. Plan is to rebuild redisHandler in a minimal setup to validate and find out more.

**Comment by foxriver76** [comment]
Branch: https://github.com/ioBroker/ioBroker.js-controller/tree/test-client

**Comment by foxriver76** [comment]
It seems like only linux is affected

**Comment by Apollon77** [comment]
Re-Eval with new build

**Comment by foxriver76** [comment]
Seems like we were able to speed it up again to ~5x the old multi/exec performance by answering with a batch response for the batch multi/exec calls.

**Comment by Apollon77** [comment]
Well done @foxriver76 . Thank you!
