### ISSUE TITLE
EADDRINUSE: address already in use when js-controller in list instances and run(port 9091).

### ISSUE THREAD

**Issue by saykl** [ioBroker/ioBroker.js-controller#1684]
I have js-controller in instances. When i run it: EADDRINUSE: address already in use
Then all adapaters terminate.
Please add to command "iobroker fix" delete js-controller from instances
![intances](https://user-images.githubusercontent.com/30440331/150741967-207ca77d-75e2-4b3c-a442-6869dabb0915.JPG)

![Screenshot 2022-01-24 103108](https://user-images.githubusercontent.com/30440331/150741953-8515b15c-f965-4e2e-ad2e-146930fa3ef6.JPG)

![jscontroller](https://user-images.githubusercontent.com/30440331/150741941-70d48c4f-41ff-42a7-9ff4-af2bed22fcaf.gif)

**Comment by Apollon77** [comment]
Yes, because of a strange bug it was possible that such an entry was created in the instance list. please simply ignore it or delete it ... the js-controller 4.0 which comes soon will fix this issue and also remove the relevant entries

**Comment by Apollon77** [comment]
PS: Normally there should never be such a "js-controller" entry in "Instances"
