### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by dfrozen** [ioBroker/ioBroker.js-controller#172]
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/cross-spawn/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.admin/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.admin/node_modules/engine.io/package.json'
npm ERR! Linux 3.4.113-sun8i
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "iobroker.js-controller"
npm ERR! node v6.13.1
npm ERR! npm  v3.10.10
npm ERR! path /opt/iobroker/node_modules/.staging/ansi-be95de54
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/opt/iobroker/node_modules/.staging/ansi-be95de54' -> '/opt/iobroker/node_modules/npm/node_modules/ansi'
npm ERR! enoent ENOENT: no such file or directory, rename '/opt/iobroker/node_modules/.staging/ansi-be95de54' -> '/opt/iobroker/node_modules/npm/node_modules/ansi'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/iobroker/npm-debug.log
root@orangepiplus:/opt/iobroker# iobroker start
module.js:478
    throw err;
    ^

Error: Cannot find module '/opt/iobroker/node_modules/iobroker.js-controller/iobroker.js'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._load (module.js:424:25)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:387:7)
    at startup (bootstrap_node.js:153:9)
    at bootstrap_node.js:500:3
root@orangepiplus:/opt/iobroker#

**Comment by Apollon77** [comment]
"npm cache clean" mal gemacht?

**Comment by dfrozen** [comment]
I tried, but it does not help. iobroker does not start

**Comment by wendy2702** [comment]
Hi, a lot of users seems to have this problem. It looks that the upgrade mainly failed at "Host" System while it is working fine at "Slaves".

In many cases this can be fixed by

```
cd /opt/iobroker
iobroker stop
npm install iobroker.js-controller --production
iobroker start
```

or 

``npm install iobroker.js-controller``

**Comment by Apollon77** [comment]
Could it be that the installation was done with "sudo" or as root and the update now without?
Did you do a "chmod -R 777 * before t make sure all right are correct? Can you please try this too?

The mysterious thing is that npm seems not to be able to find files he put there by himself ... so it's now application related topic somehow ... We have no idea aboiut the reason

**Comment by dfrozen** [comment]
the result is still unchanged

**Comment by wendy2702** [comment]
Is a discussion ongoing at iobroker forum as well?

**Comment by dfrozen** [comment]
no, i can't registred on forum

**Comment by dfrozen** [comment]
root@orangepiplus:/opt/iobroker# npm cache clean
root@orangepiplus:/opt/iobroker# iobroker upgrade js-controller -self
module.js:478
    throw err;
    ^

Error: Cannot find module '/opt/iobroker/node_modules/iobroker.js-controller/iobroker.js'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._load (module.js:424:25)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:387:7)
    at startup (bootstrap_node.js:153:9)
    at bootstrap_node.js:500:3
root@orangepiplus:/opt/iobroker#

**Comment by Apollon77** [comment]
The question is if nothing from before killed your installation ... because with this error it means that js.controller is no longer on your HDD somehow ...

**Comment by wendy2702** [comment]
did you try with this 

``npm install iobroker.js-controller --production``

as well?

**Comment by dfrozen** [comment]
only root user)) 
chmod -R 777 *
npm cache clean
npm install iobroker.js-controller --production or
iobroker upgrade js-controller -self
and same combinations of command = result only one can't install

**Comment by dfrozen** [comment]
Apollon77 this message type if i am doin first

> npm install iobroker.js-controller --production 

system is down

> npm ERR! enoent ENOENT: no such file or directory, rename '/opt/iobroker/node_modules/.staging/ansi-be95de54' -> '/opt/iobroker/node_modules/npm/node_modules/ansi'
> npm ERR! enoent ENOENT: no such file or directory, rename '/opt/iobroker/node_modules/.staging/ansi-be95de54' -> '/opt/iobroker/node_modules/npm/node_modules/ansi'
> npm ERR! enoent This is most likely not a problem with npm itself
> npm ERR! enoent and is related to npm not being able to find a file.
> npm ERR! enoent
> 
> npm ERR! Please include the following file with any support request:
> npm ERR! /opt/iobroker/npm-debug.log
and then i am doin only 

> npm install iobroker.js-controller@1.2.5
And system is up

**Comment by wendy2702** [comment]
``only root user)) no sudo user in system``

sudo is NOT an user. It's an option to give some rights to an command.

And this 

```
only root user)) no sudo user in system
chmod -R 777 *
npm cache clean
npm install iobroker.js-controller --production or
iobroker upgrade js-controller -self
and same combinations of command = result only one can't install```

at ``/opt/iobroker`` directory ?


And why isn't it possible to register at iobroker forum?

**Comment by dfrozen** [comment]
solved 

>  npm install -g npm@=>5.7.1

**Comment by dfrozen** [comment]
> And why isn't it possible to register at iobroker forum?
there was no confirmation of registration on the e-mail, now I can not register again. I do not want to use other mail for registration
