### ISSUE TITLE
Differences between 1.2.6 and 1.2.7?

### ISSUE THREAD

**Issue by wendy2702** [ioBroker/ioBroker.js-controller#173]
Yesterday i upgrade my systems to 1.2.6 Version. Today i installed iobroker to a new RPI3 and want to update to 1.2.6 as well but now i can see version 1.2.7 only.

Version 1.2.6. is missing at change log doc as well.

This is very confusing!

**Comment by GermanBluefox** [comment]
1.2.6 was invalid. If you really want to know the changes, see git commits

**Comment by wendy2702** [comment]
Invalid...

but now installed at my and many other systems.

I'm not familar with JS and because of this the commits are not helpfull.

**Comment by Apollon77** [comment]
1.2.6 hd the problem that "admin" Adapter was downgraded to stable version on update of js-controller. This was fixed in 1.2.7, so now the admin version is preserved if higher then 2.0.9.
The second fix to prevent a "false positive" logging message
