### ISSUE TITLE
v4.0: what is a valid obj.common.states default value?

### ISSUE THREAD

**Issue by HGlab01** [ioBroker/ioBroker.js-controller#1730]
What is a valide state definition for obj.common.states if no concrete states are defined (so all values are allowed)?
Triggered is this question by issue
https://github.com/DrozmotiX/ioBroker.tado/issues/459

In the past I used state definitions like
```
{
  "type": "state",
  "common": {
    "modify": "",
    "name": "Temperature Fahrenheit",
    "type": "number",
    "role": "value.temperature",
    "read": true,
    "unit": "°F",
    "states": ""
}
```
With JS-Controler v4.0 this results in
`Object xxxx.Rooms.1.nextScheduleChange.setting.temperature.fahrenheit is invalid: obj.common.states has an invalid type! Expected "object", received "string"`

I tried to change to
`"states": null`
which results in
`...is invalid: obj.common.states has an invalid type! Expected "object", received "object"`

To skip the attribute "obj.common.states" if it is empty is in my point of view not a good option, because then all existing states would   keep the wrong definition.

**Comment by foxriver76** [comment]
just remove the states property if you don't use it as in the above definition, else it is like https://github.com/foxriver76/ioBroker.denon/blob/6b9c94cda90771066b0a6975d5323e9a1d98f84e/lib/utils.js#L195-L221.


To remove the property it really depends on the method you use in your adapter, e.g. extendObject should remove it if you pass `states: null`

**Comment by HGlab01** [comment]
I call
await adapter.extendObjectAsync(objName, {
                type: 'state',
                common
            });
where common includes
common.states = null
which results in
{
  "type": "state",
  "common": {
    "modify": "",
    "name": "Temperature Fahrenheit",
    "type": "number",
    "role": "value.temperature",
    "read": true,
    "unit": "°F",
    "states": null
}

**Comment by foxriver76** [comment]
okay, maybe I remember it wrong with the null deletion, tests say something different, gotta check

**Comment by foxriver76** [comment]
However, it is most likely a bug, that he logs a warning on extend with null

**Comment by Apollon77** [comment]
might "Undefined" work?

**Comment by Apollon77** [comment]
Ok, wil lnot work ...

**Comment by foxriver76** [comment]
I just read the question again and if it is about object creation and you don’t want to set the States attribute at all, don’t define it or pass undefined. For deletion you currently need to read write objects separate.

**Comment by HGlab01** [comment]
> I just read the question again and if it is about object creation and you don’t want to set the States attribute at all, don’t define it or pass undefined. For deletion you currently need to read write objects separate.

I agree for new installation it will work if I just pass the property "states".
But how can I manage the 1000+ existing installations where each and every state has a property "states" with value ""?

For a better understanding:
The states are defined like this
https://github.com/DrozmotiX/ioBroker.tado/blob/17e8fde84438b8bd3e268205fb7934a444eb47d7/lib/state_attr.js#L4-L8
and managed here
https://github.com/HGlab01/ioBroker-jsonExplorer/blob/2793e4b661e143c706180f912632140bdbb618f4/jsonExplorer.js#L233-L260

**Comment by Apollon77** [comment]
@HGlab01 Ok we decided to supress the error messge for now when you set "null" for common.states ... but it will not have a real effect for now. In #1735 we will think about the real solution for later

**Comment by HGlab01** [comment]
Thanks for the quick solution!

**Comment by HGlab01** [comment]
HI @Apollon77!
The current solution works for existing states, but for new states I got the following warning:
Using
```
await adapter.extendObjectAsync(objName, {
                type: 'state',
                common
            });
```
with
`common.states = null`
results in
`Object followthesun.0.current.azimuth is invalid: obj.common.states has an invalid type! Expected non-null "object", received "null"`

**Comment by HGlab01** [comment]
extendObjectAsync() is capable to deal with both (existing and new states). How to handle the two scenarios in a generic way if the framework reacts differently?

**Comment by foxriver76** [comment]
Extend should not complain else we missed a case

**Comment by foxriver76** [comment]
https://github.com/ioBroker/ioBroker.js-controller/blob/8ee77b56657440ca4bf8396d1abb8b063a48c802/packages/adapter/src/lib/adapter/adapter.js#L2250
