### ISSUE TITLE
JS 4: nach Update  - Cannot configure secure web server, because no certificates found

### ISSUE THREAD

**Issue by MarkSau** [ioBroker/ioBroker.js-controller#1732]
Hi,

ich hatte eigene Zertifikate hinzugefügt, die nach dem Update nun weg sind
Div. Fehlermeldungen dbzgl. kommen für verschiedene Adapter im Log:

2022-02-02 08:07:37.498  - [31merror[39m: admin.0 (451) Cannot configure secure web server, because no certificates found: Priv_Public, Priv_Private, priv_chained
2022-02-02 08:09:29.678  - [31merror[39m: jarvis.0 (954) Cannot configure secure web server, because no certificates found: Priv_Public, Priv_Private, priv_chained
2022-02-02 08:09:34.067  - [31merror[39m: jarvis.1 (969) Cannot configure secure web server, because no certificates found: Priv_Public, Priv_Private, priv_chained
2022-02-02 08:10:05.335  - [31merror[39m: socketio.0 (1076) Cannot configure secure web server, because no certificates found: Priv_Public, Priv_Private, priv_chained
...

**Comment by Apollon77** [comment]
Ok, Dazu bitte mehr detaikls ... was heisst "Du hattest eigene zertifikate"? Was heisst "sind weg"?

Wurd eirgendein Objekt geändert? SInd die FIles verschwunden? Was genau ist passiert? Wie genau war es aufgesetzt?

**Comment by MarkSau** [comment]
Nach dem Update auf V4 werden die Zertifikate nicht mehr im Admin angezeigt und wohl auch nicht genutzt
![image](https://user-images.githubusercontent.com/22911084/152111245-752f4768-cf1d-42c6-a10b-9e13d7d6c04d.png)

![image](https://user-images.githubusercontent.com/22911084/152111301-dbf5b473-6a52-4891-bda4-c4376d78de69.png)

Die Zertifikate liegen aber noch unter /opt/certs

![image](https://user-images.githubusercontent.com/22911084/152111072-3beb5990-b43f-4f03-8328-69d5cbb329b8.png)

**Comment by Apollon77** [comment]
Kannst du bitte mal alles wieder neu anlegen, dann am besten via Admin das Objekt "system.certificates" (Expertenmodus) sichern und dann "iob setup first" ausführen. Ist es danach wieder weg?

**Comment by MarkSau** [comment]
das Objekt "system.certificates" gibt es nicht

![image](https://user-images.githubusercontent.com/22911084/152112068-1d768b17-05fc-4d40-b206-633ce8566a24.png)

**Comment by Apollon77** [comment]
--> Expertenmodus! und ggf Admin5?

**Comment by Apollon77** [comment]
Most likely issue is https://github.com/ioBroker/ioBroker.js-controller/blob/9279132d9c79cc56d76bfbff05f78ea4b65e4cdc/packages/cli/lib/cli/cliCert.js#L47

**Comment by MarkSau** [comment]
Expertenmodus ist an, habe aber nicht weiter unten geschaut.. und Admin5 bringt Fehler:
![image](https://user-images.githubusercontent.com/22911084/152112818-9ac4ccb0-b959-4d66-9624-468a8b4b9269.png)

PS: Ich habe noch eine zweite Admin Instanz mit dem alten Admin Gui.

**Comment by Apollon77** [comment]
Ok, dann sehe es mit altem admin erstmal wieder auf..w eir denken wir kennen den grund ... Näcjstes update bringt dann fix

**Comment by Apollon77** [comment]
Pleas retry with @next (alpha.70+)
