### ISSUE TITLE
JS4 : iobroker multihost enable Fehler TypeError: dbTools.isLocalObjectsDbServer is not a function

### ISSUE THREAD

**Issue by MarkSau** [ioBroker/ioBroker.js-controller#1742]
sudo iobroker multihost enable
Multihost discovery server activated on this host. If iobroker is currently not running please start befeore trying to discover this host.
Important: Multihost discovery works with UDP packets. Make sure they are routed correctly in your network. If you use Docker you also need to configure this correctly.
Multihost discovery will be automatically deactivated after 15 minutes. If you want to activate it permanently use the --persist flag
Discovery authentication activated.
Enter secret phrase for connection:
Repeat secret phrase for connection:
TypeError: dbTools.isLocalObjectsDbServer is not a function
    at showMHState (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupMultihost.js:80:25)
    at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupMultihost.js:209:33)
    at processImmediate (internal/timers.js:466:21)

Nutze Jsonl
Node.js:v14.19.0
NPM:6.14.16
JS: 4.0.0-alpha.73

**Comment by AlCalzone** [comment]
> sudo iobroker multihost enable

Just to make sure you read it: DO NOT USE `sudo` with iobroker

**Comment by MarkSau** [comment]
Ohne SUDO gehts auch nicht, gleicher Fehler...aber macht es halt einfach zu, ohne nachfragen..ich habe mich eh anders entschieden. Sollen doch andere ohne SUDO ins Problem laufen..

**Comment by AlCalzone** [comment]
Siehe Kommentar im anderen issue. Du hast dir mit sudo die permissions verbogen und musst die erst wieder gerade rücken.
