### ISSUE TITLE
JS4 update auf neu installieren Pi3 bring Fehler

### ISSUE THREAD

**Issue by MarkSau** [ioBroker/ioBroker.js-controller#1743]
`pi@MSRPI-Slave1:~ $ iob stop
pi@MSRPI-Slave1:~ $ cd /opt/iobroker/
pi@MSRPI-Slave1:/opt/iobroker $ sudo npm i iobroker.js-controller@next

> iobroker.js-controller@4.0.0-alpha.74-20220203-a06ae9e1 preinstall /opt/iobroker/node_modules/iobroker.js-controller
> node lib/preinstallCheck.js

NPM version: 6.14.16

> iobroker.js-controller@4.0.0-alpha.74-20220203-a06ae9e1 install /opt/iobroker/node_modules/iobroker.js-controller
> node iobroker.js setup first

Cannot delete file. Not critical: EACCES: permission denied, unlink '/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/../../_service_iobroker.bat'
Cannot delete file. Not critical: EACCES: permission denied, unlink '/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/../../iobroker.bat'
Cannot delete file. Not critical: EACCES: permission denied, unlink '/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/../../iob.bat'
Uncaught Rejection: Error: EACCES: permission denied, mkdir '/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/../../tmp'
    at Object.mkdirSync (fs.js:1013:3)
    at Setup.setup (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupSetup.js:1012:16)
    at processCommand (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup.js:567:23)
    at Object.module.exports.execute (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup.js:3316:5)
    at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/iobroker.js:1:24)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

npm ERR! code ELIFECYCLE
npm ERR! errno 6
npm ERR! iobroker.js-controller@4.0.0-alpha.74-20220203-a06ae9e1 install: `node iobroker.js setup first`
npm ERR! Exit status 6
npm ERR!
npm ERR! Failed at the iobroker.js-controller@4.0.0-alpha.74-20220203-a06ae9e1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-02-04T09_33_51_544Z-debug.log
[2022-02-04T09_33_51_544Z-debug.log](https://github.com/ioBroker/ioBroker.js-controller/files/8001706/2022-02-04T09_33_51_544Z-debug.log)
`

**Comment by MarkSau** [comment]
Zusatz: danach ist die iobroker Installtion kaputt

pi@MSRPI-Slave1:/opt/iobroker $ iob status
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '/opt/iobroker/node_modules/iobroker.js-controller/iobroker.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
pi@MSRPI-Slave1:/opt/iobroker $

**Comment by foxriver76** [comment]
why `sudo`?

**Comment by AlCalzone** [comment]
`sudo` ist böse. Siehe auch https://forum.iobroker.net/topic/17109/wichtige-hinweise-bei-neueren-npm-versionen-und-sudo, Regel Nr. 1

**Comment by MarkSau** [comment]
ohne sudo gleicher fehler, mal abgesehen, das so in der doku steht
https://www.iobroker.net/docu/index-24.htm?page_id=3068&lang=de

**Comment by MarkSau** [comment]
Könnt ihr auch zumachen. ich habe mich anders entschieden. Dann ohne SUDO...
Das Problem wird aber wohl bleiben...Löschen von windows files, die unter linux nicht da sind, geht halt nicht.

**Comment by foxriver76** [comment]
Was hat

```
Uncaught Rejection: Error: EACCES: permission denied, mkdir '/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/../../tmp'
```

mit löschen von Windows files zu tun?

**Comment by AlCalzone** [comment]
Wenn du einmal sudo genutzt hast, sind die permissions der Verzeichnisse hinüber und müssen erst wieder gerade gebogen werden. 
=> `iobroker fix`, wenn das denn noch geht.

Erst dann wird das Update ohne sudo Erfolg haben können.

**Comment by Apollon77** [comment]
@MarkSau wo findet man so nen link?? outdated

**Comment by Apollon77** [comment]
I would say furthwr diskussions in Forum in the 4.0 alpha thread - warum auch immer ein controller 4 nicht so installiert wurde wie es im thread steht :-)
