### ISSUE TITLE
Docker setcap works differently ...

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#1755]

**Comment by AlCalzone** [comment]
How?

**Comment by buanet** [comment]
To be able set `cap_net_admin` in docker you have to set this capability when deploying the docker container. This is not done by default.

So if we are trying to set the capability during the js-controller upgrade it will fail in a docker environment. we have to leave it out like it is done here: 

https://github.com/ioBroker/ioBroker/blob/6bbd41286d01913308db3b5631a248088bb941d0/installer_library.sh#L272

**Comment by buanet** [comment]
Capability NET_ADMIN set for Docker Container:

```
root@iobrokertest:/opt/iobroker# grep ^CapBnd /proc/$$/status
CapBnd: 00000000a80435fb
root@iobrokertest:/opt/iobroker# capsh --decode=00000000a80435fb
0x00000000a80435fb=cap_chown,cap_dac_override,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_net_bind_service,cap_net_admin,cap_net_raw,cap_sys_chroot,cap_mknod,cap_audit_write,cap_setfcap
```

Capability NET_ADMIN **not** set for Docker Container:

```
root@iobrokertest:/opt/iobroker# grep ^CapBnd /proc/$$/status
CapBnd: 00000000a80425fb
root@iobrokertest:/opt/iobroker# capsh --decode=00000000a80425fb
0x00000000a80425fb=cap_chown,cap_dac_override,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_net_bind_service,cap_net_raw,cap_sys_chroot,cap_mknod,cap_audit_write,cap_setfcap
```

**Comment by Apollon77** [comment]
fixed by https://github.com/ioBroker/ioBroker.js-controller/pull/1756
