### ISSUE TITLE
fehler bei update

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.js-controller#1757]
Nur mal so zur Sicherheit .. einige Meldungen beim Update .. alles ok so?

bla@iobroker:~$ iob upgrade self
Update js-controller from @3.3.22 to @4.0.4
NPM version: 6.14.16
npm install iobroker.js-controller@4.0.4 --loglevel error --unsafe-perm --prefix                                                            "/opt/iobroker" (System call)
Server Objects 127.0.0.1:59006 Error from InMemDB: Error: GET-UNSUPPORTED for na                                                           mespace cfg.: Data=["meta.objects.features.useSets"]
Server States 127.0.0.1:38746 Error from InMemDB: Error: GET-UNSUPPORTED for nam                                                           espace meta.: Data=["meta.states.protocolVersion"]
Server Objects 127.0.0.1:59006 Error from InMemDB: Error: GET-UNSUPPORTED for na                                                           mespace cfg.: Data=["meta.objects.protocolVersion"]
Server States 127.0.0.1:38748 Error from InMemDB: Error: PSUBSCRIBE-UNSUPPORTED                                                            for namespace meta.: Data=["meta.*"]
Server Objects 127.0.0.1:59006 Error from InMemDB: Error: Unknown LUA script loa                                                           d
Server Objects 127.0.0.1:59006 Error from InMemDB: Error: Unknown LUA script loa                                                           d
Server Objects 127.0.0.1:59006 Error from InMemDB: Error: Unknown LUA script loa                                                           d
Server Objects 127.0.0.1:59006 Error from InMemDB: Error: SET-UNSUPPORTED for na                                                           mespace cfg.: Data=["meta.objects.features.useSets",{"type":"Buffer","data":[49]                                                           }]
Could not migrate objects to corresponding sets: Error SET-UNSUPPORTED for names                                                           pace cfg.: Data=["meta.objects.features.useSets",{"type":"Buffer","data":[49]}]
Server Objects 127.0.0.1:59006 Error from InMemDB: Error: multi NOT SUPPORTED
Server Objects 127.0.0.1:59006 Error from InMemDB: Error: sadd NOT SUPPORTED
Server Objects 127.0.0.1:59006 Error from InMemDB: Error: exec NOT SUPPORTED

**Comment by Apollon77** [comment]
Ja ok so wie auch im Forum Thread unter https://forum.iobroker.net/topic/52208/js-controller-4-0-jetzt-im-beta-latest beschrieben

**Comment by daniel-lo** [comment]
danke!
