### ISSUE TITLE
Error messages on update (from @3.3.22 to @4.0.4)

### ISSUE THREAD

**Issue by passuff** [ioBroker/ioBroker.js-controller#1758]
` iob upgrade self
Update js-controller from @3.3.22 to @4.0.4
NPM version: 7.5.2
npm install iobroker.js-controller@4.0.4 --loglevel error --unsafe-perm --prefix                                                     "/opt/iobroker" (System call)
Server Objects 127.0.0.1:37942 Error from InMemDB: Error: GET-UNSUPPORTED for na                                                    mespace cfg.: Data=["meta.objects.features.useSets"]
Server Objects 127.0.0.1:37942 Error from InMemDB: Error: GET-UNSUPPORTED for na                                                    mespace cfg.: Data=["meta.objects.protocolVersion"]
Server States 127.0.0.1:60678 Error from InMemDB: Error: GET-UNSUPPORTED for nam                                                    espace meta.: Data=["meta.states.protocolVersion"]
Server States 127.0.0.1:60680 Error from InMemDB: Error: PSUBSCRIBE-UNSUPPORTED                                                     for namespace meta.: Data=["meta.*"]
Server Objects 127.0.0.1:37942 Error from InMemDB: Error: Unknown LUA script loa                                                    d
Server Objects 127.0.0.1:37942 Error from InMemDB: Error: Unknown LUA script loa                                                    d
Server Objects 127.0.0.1:37942 Error from InMemDB: Error: Unknown LUA script loa                                                    d
Server Objects 127.0.0.1:37942 Error from InMemDB: Error: SET-UNSUPPORTED for na                                                    mespace cfg.: Data=["meta.objects.features.useSets",{"type":"Buffer","data":[49]                                                    }]
Server Objects 127.0.0.1:37942 Error from InMemDB: Error: multi NOT SUPPORTED
Server Objects 127.0.0.1:37942 Error from InMemDB: Error: sadd NOT SUPPORTED
Server Objects 127.0.0.1:37942 Error from InMemDB: Error: exec NOT SUPPORTED
Server Objects 127.0.0.1:37942 Error from InMemDB: Error: multi NOT SUPPORTED
Server Objects 127.0.0.1:37942 Error from InMemDB: Error: sadd NOT SUPPORTED
Server Objects 127.0.0.1:37942 Error from InMemDB: Error: exec NOT SUPPORTED
`

**Comment by Apollon77** [comment]
yes ok and normal that way ... see also Forum https://forum.iobroker.net/topic/52208/js-controller-4-0-jetzt-im-beta-latest

**Comment by passuff** [comment]
just a hint. In the forum thread you added a screenshot off the error messages instead of the code, otherwise I would have found it myself with forum search...

**Comment by Apollon77** [comment]
Good idea, will update in forum

**Comment by MrSonei6** [comment]
the option a was not working

 "objects": {
    "type": "jsonl",
    "typeComment": "Possible values: 'file' - [port 9001], redis - [port 6379], couch - [port 5984].",
    "host": "127.0.0.1",
    "port": 9001,
    "user": "",
    "pass": "",
    "noFileCache": false,
    "connectTimeout": 2000,
    "options": {
      "auth_pass": null,
      "retry_max_delay": 5000
    },
    "backup": {
      "disabled": false,
      "files": 24,
      "filesComment": "Minimal number of backup files, after the deletion will be executed according to backupTime settings",
      "hours": 48,
      "hoursComment": "All backups older than 48 hours will be deleted. But only if the number of files is greater than of backupNumber",
      "period": 120,
      "periodComment": "by default backup every 2 hours. Time is in minutes. To disable backup set the value to 0",
      "path": "",
      "pathComment": "Absolute path to backup directory or empty to backup in data directory"
    }
  },
  "states": {
    "type": "jsonl",




-----------------
after start the iobroker the web services are not reachable
