### ISSUE TITLE
js-controller 4.0 cannot get logs

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.js-controller#1759]
![grafik](https://user-images.githubusercontent.com/6681528/152727825-c14a3e56-0562-461c-81c2-417263304a87.png)
![grafik](https://user-images.githubusercontent.com/6681528/152727834-87d89dca-73af-4c92-bfec-878f43b64312.png)
![grafik](https://user-images.githubusercontent.com/6681528/152727846-eea18436-fd19-488d-8f83-7d7b6a43dd28.png)

**Comment by Apollon77** [comment]
I would assume that there is a link without a loglevel  https://github.com/ioBroker/ioBroker.admin/blob/master/src-rx/src/Workers/LogsWorker.js#L209 ... but needs to be verified, so could also be an admin issue
