### ISSUE TITLE
Check backup restore when using force mode

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#1775]
@simatec deliver more infos?

**Comment by simatec** [comment]
Ich schreibe mal in Deutsch, um es verständlicher rüberzubringen.
Beim testen von Backitup Funktionen ist mir beim restore aufgefallen, dass der iobroker nicht mehr startet.
Erst dachte ich, das beim restore etwas schief gegangen ist. Nach ein paar weiteren tests stellte ich aber fest, dass der Admin nicht vorhanden war und es eine ganze Weile benötigt, eh der Admin wieder durchgestartet ist.

ich denke das könnte durchaus einen Aufschrei geben, da der iobroker eine gewisse Zeit nach dem restore nicht mehr erreichbar ist.
Viele User werden hier Probleme melden.

Wie mit @Apollon77 besprochen, wäre hier sicher gut, die Installation vom Admin mit in den eigentlichen restore Prozess zu legen.
Somit würde beim Start von iobroker der Admin bereits vorhanden sein und direkt lauffähig sein.

Da auch Backitup aktuell beim restore gelöscht und neu installiert wird, gehen mir aktuell auch der Start Shell verloren. 
Hier versuche ich das ganze in iobroker-data auszulagern, damit ein automatischer Start nach dem Restore wieder möglich ist

**Comment by foxriver76** [comment]
Reinstallation of admin and backitup is done during restore command up from now.
