### ISSUE TITLE
ERROR: Cannot save backup /opt/iobroker/iobroker-data/backup-objects

### ISSUE THREAD

**Issue by Tombra1889** [ioBroker/ioBroker.js-controller#1779]
Cannot save backup /opt/iobroker/iobroker-data/backup-objects/2022-02-09_14-47_states.jsonl.gz: The "fd" argument must be of type number. Received undefined

<img width="1496" alt="image" src="https://user-images.githubusercontent.com/60692414/153214246-832b721b-0a83-4e6a-9058-75301be184e2.png">

**Comment by AlCalzone** [comment]
Looks like the controller attempts to backup the DB while the DB is closed.

**Comment by Tombra1889** [comment]
same with 4.0.6:


host.raspberrypi | 2022-02-10 08:28:02.682 | error | host.raspberrypi-Server Cannot save backup /opt/iobroker/iobroker-data/backup-objects/2022-02-10_08-28_objects.jsonl.gz: Cannot read property 'destroy' of undefined

host.raspberrypi | 2022-02-10 08:28:02.673 | error | host.raspberrypi-Server Cannot save backup /opt/iobroker/iobroker-data/backup-objects/2022-02-10_08-28_states.jsonl.gz: The "fd" argument must be of type number. Received undefined

host.raspberrypi | 2022-02-10 08:28:02.670 | error | host.raspberrypi-Server Cannot save backup /opt/iobroker/iobroker-data/backup-objects/2022-02-10_08-28_states.jsonl.gz: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined

host.raspberrypi | 2022-02-10 08:28:02.306 | error | host.raspberrypi-Server Cannot save backup /opt/iobroker/iobroker-data/backup-objects/2022-02-10_08-28_objects.jsonl.gz: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined

host.raspberrypi | 2022-02-10 08:28:02.164 | error | host.raspberrypi-Server Cannot save backup /opt/iobroker/iobroker-data/backup-objects/2022-02-10_08-28_objects.jsonl.gz: EBADF: bad file descriptor, write

host.raspberrypi | 2022-02-10 08:28:02.164 | error | host.raspberrypi-Server Cannot save backup /opt/iobroker/iobroker-data/backup-objects/2022-02-10_08-28_states.jsonl.gz: EBADF: bad file descriptor, write

host.raspberrypi | 2022-02-10 08:28:02.163 | error | host.raspberrypi-Server Cannot save backup /opt/iobroker/iobroker-data/backup-objects/2022-02-10_08-28_states.jsonl.gz: Cannot read property 'read' of undefined

host.raspberrypi | 2022-02-10 08:28:01.224 | error | host.raspberrypi-Server Cannot save backup /opt/iobroker/iobroker-data/backup-objects/2022-02-10_08-28_objects.jsonl.gz: Cannot read property 'read' of undefined

host.raspberrypi | 2022-02-10 08:28:01.129 | error | host.raspberrypi-Server Cannot save backup /opt/iobroker/iobroker-data/backup-objects/2022-02-10_08-28_objects.jsonl.gz: Cannot read property 'read' of undefined

**Comment by Tombra1889** [comment]
![image](https://user-images.githubusercontent.com/60692414/153359583-8a637a4b-9a6d-4372-a1f0-27a0ef06889f.png)

**Comment by AlCalzone** [comment]
@Apollon77 @foxriver76 this can only mean that this variable
https://github.com/ioBroker/ioBroker.js-controller/blob/3581cca2a0661a5fc346e5cb99bf664898b3d652/packages/db-objects-jsonl/lib/objects/objectsInMemJsonlDB.js#L187

is undefined. But why?!

**Comment by Tombra1889** [comment]
<img width="1375" alt="image" src="https://user-images.githubusercontent.com/60692414/153369329-2727d69b-6fd9-4f9e-9c0d-72a6f617500b.png">

**Comment by AlCalzone** [comment]
@Tombra1889 can you please open `/opt/iobroker/node_modules/@iobroker/db-objects-jsonl/lib/objects/objectsInMemJsonlDB.js` with a text editor and change the `e.message` in line 210 (give or take) to `e.stack`:
```diff
-             this.log.error(`${this.namespace} Cannot save backup ${backupFileName}: ${e.message}`);
+             this.log.error(`${this.namespace} Cannot save backup ${backupFileName}: ${e.stack}`);
```

Then save, and restart iobroker.

**Comment by Tombra1889** [comment]
<img width="1480" alt="image" src="https://user-images.githubusercontent.com/60692414/153380365-d091eec6-838c-4867-b022-c49431dbc4b0.png">

**Comment by AlCalzone** [comment]
@Tombra1889 kannst du die genannte Datei mal komplett ersetzen durch die in folgendem Zip-Archiv:

[objectsInMemJsonlDB.zip](https://github.com/ioBroker/ioBroker.js-controller/files/8039935/objectsInMemJsonlDB.zip)

Dann wieder iobroker neu starten.

**Comment by Tombra1889** [comment]
ja, ein echt komisches Verhalten. Hab die Datei angepasst. Der PI ist dadurch auch unter Volllast, ein stop / restart dauert immer ziemlich lange.

<img width="1479" alt="image" src="https://user-images.githubusercontent.com/60692414/153384572-ebb4876a-e1c5-4aa0-a949-c2be5d75a375.png">

**Comment by AlCalzone** [comment]
Ok das sieht jetzt aus als werden die backups überhaupt nicht raus geschrieben vorm Komprimieren 🤔

Kannst du nochmal den Inhalt von dem backup Verzeichnis zeigen?

**Comment by Tombra1889** [comment]
<img width="624" alt="image" src="https://user-images.githubusercontent.com/60692414/153391057-89f1f3f7-c13f-4ea4-ad24-bc457b72a138.png">

**Comment by AlCalzone** [comment]
Was hast du denn in /opt/iobroker/iobroker-data/iobroker.json für ein Backup intervall konfiguriert?

**Comment by Tombra1889** [comment]
<img width="1011" alt="image" src="https://user-images.githubusercontent.com/60692414/153393540-c34308ab-1bcf-44f1-8eb2-2d806bafef8b.png">
<img width="1043" alt="image" src="https://user-images.githubusercontent.com/60692414/153393608-9888db23-5e42-45e7-b6a6-1640fa47bf41.png">

**Comment by Tombra1889** [comment]
puhh, vielen Dank!! Das war die Ursache, kann mich nicht entsinnen dort mal etwas eingestellt zu haben.
