### ISSUE TITLE
Potential problem with github urls and NPM5

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.js-controller#180]
When installing adapters from a github url, especially from a branch tarball, e.g. `https://github.com/owner/repo/tarball/branch`, this can lead to problems down the line when using NPM 5. 
If the branch is removed in the meantime, no other packets can be installed or uninstalled, because NPM for some reason tries to re-check the no-longer existing github url and errors out with a 404.
One has to manually remove the entry from package.json and retry, but this can lead to the no longer referenced packet being uninstalled aswell.

Potential solutions off the top of my head:
* After an installation from a custom url, edit the package.json entry from `https://github...` to `"*"`
* Change installation process from a custom url:
  * download the referenced packet/tarball and store it somewhere safe, e.g. `/opt/iobroker/downloads`
  * install using the local file system reference
  * only delete the download when the packet is uninstalled

**Comment by Apollon77** [comment]
Can this be closed in the meantime?

**Comment by AlCalzone** [comment]
Why would you close it? It's something we should take a look at before npm5 becomes the standard as might affect a lot of installs from github.

**Comment by Apollon77** [comment]
Aaahhh so it is not the issue fixed in 5.7.1 ... then ;-)

**Comment by Apollon77** [comment]
@AlCalzone is it fixed in npm 6?

**Comment by AlCalzone** [comment]
I don't think this is going to be fixed. We should explore one of the solutions I provided.

**Comment by Apollon77** [comment]
Js-Controller 2.0 now tries to look up the commit id (but only for Master branch) and use this to request it. We also could do this for branches (only need to add detection logic). Would the commit be still there also when branch gets deleted?

**Comment by AlCalzone** [comment]
> Would the commit be still there also when branch gets deleted?

Not necessarily. If the branch got squash-merged and then deleted, its gone. 
The problem is that `npm` seems to check this when installing other adapters, so even a handling in JS-Controller won't help.

The only solution where I'm sure that it will continue to work is my 2nd bullet point in the OP.

**Comment by Apollon77** [comment]
since controller 2.2 we try to catch the commit when master and from current knowledge it works ... but I also never tested such special cases. For branches alays the "latest"" is used. SO I would close here and we wait if we get problems again. Please reopen if you see it different

**Comment by AlCalzone** [comment]
> For branches alays the "latest"" is used.

Does this mean the commit is also stored in this case? Should be fine, unless the branch and/or commit is deleted from Github. Then we're back to square 1

**Comment by AlCalzone** [comment]
Probably easier to write in the documentation how to fix this instead of adding complicated logic.

**Comment by Apollon77** [comment]
Check the "installFrom" property in the system.adapter.name.instance objects on your installation. It is "npm-package@version" for npm installs, OR the exact last commit when from master (and commit was possible to get fetched) or the used "install location"

**Comment by AlCalzone** [comment]
The problem is that this also affects other installations. So for example:
1. Adapter A was installed from a branch
2. The branch is deleted 
3. Adapter B cannot be installed because the package.json is referencing the missing branch for A.

**Comment by AlCalzone** [comment]
So, we had our first case of this (although the user broke it himself):
https://forum.iobroker.net/topic/36272/npm-uninstall-err-code-404-get-fehler-falsche-github-url
