### ISSUE TITLE
Adapter Installation vis.icontwo Fehler Code 25

### ISSUE THREAD

**Issue by sigi2345** [ioBroker/ioBroker.js-controller#1808]
Hallo, bekomme beim installieren vom Adapter folgende Fehler:

`$ iobroker add vis-icontwo auto --host Medion(Home)

NPM version: 6.14.16Installing iobroker.vis-icontwo@0.86.0... (System call)

host.Medion(Home) Cannot install iobroker.vis-icontwo@0.86.0: 4294963248

host.Medion(Home) install adapter vis-icontwo

adapter "vis-icontwo" cannot be installed: Cannot destructure property 'stoppedList' of '(intermediate value)' as it is undefined.

ERROR: Process exited with code 25`

Plattform: Windows
RAM: 16 GB 
NODE.JS: V14.19.0
NPM: 6.14.16
JS Controller: 4.0.10
Admin: 5.3.0

CMD LOG:

`**********************************************************
***               Welcome to ioBroker.                 ***
***                                                    ***
***   Type 'iobroker help' for list of instructions.   ***
***                For more help see                   ***
***     https://github.com/ioBroker/ioBroker.docs      ***
**********************************************************

Your environment has been set up for using Node.js 14.19.0 (x64) and npm.

C:\Program Files\iobroker\Home>iobroker add vis-icontwo  --debug
NPM version: 6.14.16
Installing iobroker.vis-icontwo@0.86.0... (System call)
npm WARN @material-ui/pickers@3.3.10 requires a peer of @material-ui/core@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @material-ui/pickers@3.3.10 requires a peer of react@^16.8.0 || ^17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @material-ui/pickers@3.3.10 requires a peer of react-dom@^16.8.0 || ^17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN http-cookie-agent@1.0.4 requires a peer of tough-cookie@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-transition-group@4.4.2 requires a peer of react@>=16.6.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-transition-group@4.4.2 requires a peer of react-dom@>=16.6.0 but none is installed. You must install peer dependencies yourself.
npm WARN rifm@0.7.0 requires a peer of react@>=16.8 but none is installed. You must install peer dependencies yourself.

npm ERR! code EPERM
npm ERR! syscall rename
npm ERR! path C:\Program Files\iobroker\Home\node_modules\npm\node_modules\.node-gyp.DELETE\node_modules\@tootallnate
npm ERR! dest C:\Program Files\iobroker\Home\node_modules\npm\node_modules\node-gyp\node_modules\@tootallnate
npm ERR! errno -4048
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Program Files\iobroker\Home\node_modules\npm\node_modules\.node-gyp.DELETE\node_modules\@tootallnate' -> 'C:\Program Files\iobroker\Home\node_modules\npm\node_modules\node-gyp\node_modules\@tootallnate'
npm ERR!  [OperationalError: EPERM: operation not permitted, rename 'C:\Program Files\iobroker\Home\node_modules\npm\node_modules\.node-gyp.DELETE\node_modules\@tootallnate' -> 'C:\Program Files\iobroker\Home\node_modules\npm\node_modules\node-gyp\node_modules\@tootallnate'] {
npm ERR!   cause: [Error: EPERM: operation not permitted, rename 'C:\Program Files\iobroker\Home\node_modules\npm\node_modules\.node-gyp.DELETE\node_modules\@tootallnate' -> 'C:\Program Files\iobroker\Home\node_modules\npm\node_modules\node-gyp\node_modules\@tootallnate'] {
npm ERR!     errno: -4048,
npm ERR!     code: 'EPERM',
npm ERR!     syscall: 'rename',
npm ERR!     path: 'C:\\Program Files\\iobroker\\Home\\node_modules\\npm\\node_modules\\.node-gyp.DELETE\\node_modules\\@tootallnate',
npm ERR!     dest: 'C:\\Program Files\\iobroker\\Home\\node_modules\\npm\\node_modules\\node-gyp\\node_modules\\@tootallnate'
npm ERR!   },
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'rename',
npm ERR!   path: 'C:\\Program Files\\iobroker\\Home\\node_modules\\npm\\node_modules\\.node-gyp.DELETE\\node_modules\\@tootallnate',
npm ERR!   dest: 'C:\\Program Files\\iobroker\\Home\\node_modules\\npm\\node_modules\\node-gyp\\node_modules\\@tootallnate',
npm ERR!   parent: 'npm'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Program Files\iobroker\Home\env\npm-cache\_logs\2022-02-16T18_26_29_960Z-debug.log
host.Medion(Home) Cannot install iobroker.vis-icontwo@0.86.0: 4294963248
host.Medion(Home) install adapter vis-icontwo
adapter "vis-icontwo" cannot be installed: Cannot destructure property 'stoppedList' of '(intermediate value)' as it is undefined.

C:\Program Files\iobroker\Home>`

**Comment by sigi2345** [comment]
Mit diesem Befehl funktioniert die Installation in der CMD

iobroker add vis-icontwo@0.68.0

**Comment by Apollon77** [comment]
ok, aber 68 ist ne alte Version ... ?! dann wäre die Frage bei welche Version die Probleme angefangen haben?

**Comment by Apollon77** [comment]
According to @sigi2345 issues start with 0.82 ... here the "Incliuded npm" was updated to 8.0.0 ... BUT WHY THERE IS AN NPM INSIDE??????

**Comment by Apollon77** [comment]
The sroppedList issue will be fixed in js-controller 4.0.11

**Comment by Apollon77** [comment]
I also close here, seems that after removing npm from adapter deps it works
