### ISSUE TITLE
missing data of saving system-files in system.host

### ISSUE THREAD

**Issue by mguenther1** [ioBroker/ioBroker.js-controller#1810]
hi, I would like to use the data-set from the info systembox of the info-adapter (included multihost-information). I wrote to the developer (ldittmar) of the info-adapter and he asked me to open this issue here, cause he got all the information from the controller.
So, would be nice if all system data will be saved in files and folder in and below system.host (included multihost-systems) in future.

**Comment by Apollon77** [comment]
What exactly is your usecase? These are more or less static data and some of them are already available in system-host.xy.* states. The data are available right now by sending amessage to the host

**Comment by mguenther1** [comment]
usecase - I would like to put some information data in my vis. eg NPM version or nodejs version of my multihost-slave. I can find only the information about my master multihost. You can see all the data in the info adapter but you cannot find it in the objects.
So, would be nice, if there will be more information in files and folders in system.host

**Comment by foxriver76** [comment]
Data is accessible via messages, thus I don’t see anything which needs to be done here.

**Comment by Apollon77** [comment]
I basically agree here ...
