### ISSUE TITLE
SEQ event logging incorrect adapter source

### ISSUE THREAD

**Issue by DutchmanNL** [ioBroker/ioBroker.js-controller#1813]
I have seen a situation where the logging is provide as source JS-Controller routed to SEQ but in regular ioBroker logfile it is correctly logged on the adapter.

Correct view in ioBroker log : 
<img width="1566" alt="Schermafbeelding 2022-02-18 om 10 51 21" src="https://user-images.githubusercontent.com/7318445/154659140-1d33bc30-db28-4137-a20e-94ff388b8362.png">

Incorrect source property in SEQ : 
<img width="1232" alt="Schermafbeelding 2022-02-18 om 10 51 47" src="https://user-images.githubusercontent.com/7318445/154659225-5ac9b939-b3c9-4841-ad70-fb0215db31a9.png">

Message received in SEQ : ""@mt": "esphome.0 (4091) [ESPHome - Console] \u001B[32mINFO Starting dashboard web server on port 6052 and configuration dir /opt/iobroker/iobroker-data/esphome.0...\u001B[0m\n","

Message shown in file log : 
<img width="1610" alt="Schermafbeelding 2022-02-18 om 10 54 32" src="https://user-images.githubusercontent.com/7318445/154659698-b9383de6-915c-4f81-9063-942df82c8047.png">

2022-02-18 10:23:08.779 - info: esphome.0 (4091) [ESPHome - Console] INFO Starting dashboard web server on port 6052 and configuration dir /opt/iobroker/iobroker-data/esphome.0...[0m

**Comment by Apollon77** [comment]
Seems that our regex in https://github.com/ioBroker/ioBroker.js-controller/blob/master/packages/common/lib/common/logger.js#L86

is not capable parsing 

```
esphome.0 (4091) [ESPHome - Console] \u001B[32mINFO Starting dashboard web server on port 6052 and configuration dir /opt/iobroker/iobroker-data/esphome.0...\u001B[0m
```

But I do not see why ... maybe becaus eof the unicode character in it?
