### ISSUE TITLE
Static folders for some adapter is not cleared from old js, css, etc on adapter update - hundreds of Megabytes of crap

### ISSUE THREAD

**Issue by PeterVoronov** [ioBroker/ioBroker.js-controller#1822]
**Describe the bug**  
On example of [ioBroker.javascript](https://github.com/ioBroker/ioBroker.javascript)
Folder `iobroker-data/files/javascript.admin/static` is not cleared from old static files, after installing new version of adapter.

**To Reproduce**  
Install adapter and made several upgrades of version

**Expected behavior**  
Only actual static files have to be in 

**Screenshots & Logfiles**  
![javascript admin](https://user-images.githubusercontent.com/66964358/155282503-4ae883cd-dbee-402f-8da4-a04f5ab95824.png)
![javascript admin css](https://user-images.githubusercontent.com/66964358/155283408-f9881814-90a7-4e14-aec1-ac9ccdd5e7de.png)

**Versions:**  
 - Adapter version: 5.2.11
 - JS-Controller version: 4.0.9
 - Node version: 14.18.2
 - Operating system: Debian 11
 
 Other affected adapters: [ioBroker.web](https://github.com/ioBroker/ioBroker.web), [ioBroker.iot](https://github.com/ioBroker/ioBroker.iot) ...
 
Opened to replace https://github.com/ioBroker/ioBroker.javascript/issues/962

**Comment by itProfi** [comment]
Same problem
![Скриншот 22-02-2022 191813](https://user-images.githubusercontent.com/6728198/155325449-64d7779b-a419-43c6-9a34-caa9a3a88d5c.jpg)

**Comment by foxriver76** [comment]
`earseOnUpload` flag needs to be set in javascript

**Comment by itProfi** [comment]
> `earseOnUpload` flag needs to be set in javascript

Where is it?

**Comment by foxriver76** [comment]
Information for us internally, @Apollon77 will fix it for JavaScript

**Comment by Apollon77** [comment]
Current approach would be:
* Set the flag manually in adapters that have generated UIs for admin/web
* Discuss here if it is maybe better to change te default to "if not disabled then always erase" for .admin and/or .www with controller 4.1

**Comment by Apollon77** [comment]
Decision is to always delete by default, so we ajust is to "do not delete if set to false"

Affected to add the flag for now:

* admin
* iot - hat das flag schon
* s7
* text2command
* cameras
* devices
* web
* eventlist
* javascript - mache ich
* scenes
* modbus
* homekit-controller
* echarts
* material - hat Flag schon

und zwave2. (?)
