### ISSUE TITLE
Error on iobroker after update node.js

### ISSUE THREAD

**Issue by guthubps1304** [ioBroker/ioBroker.js-controller#1824]
after updating to js.controller 4.x I do see multiple errors.
I am running iobroker on a Pi4 with Ubuntu server 20.04.4; node.js 4.18.0 nom 8.1.4

1. when going to the hosts tab - configure - logs:

> TypeError: n.transport[t].maxSize.includes is not a function
    at BaseSettingsLog.js:77:65
    at Array.forEach (<anonymous>)
    at new s (BaseSettingsLog.js:75:41)
    at zc (react-dom.production.min.js:135:172)
    at Uo (react-dom.production.min.js:181:146)
    at Zi (react-dom.production.min.js:269:427)
    at jl (react-dom.production.min.js:250:347)
    at Sl (react-dom.production.min.js:250:278)
    at Cl (react-dom.production.min.js:250:138)
    at zl (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Ga (react-dom.production.min.js:122:325)
    at Ka (react-dom.production.min.js:123:61)
    at Za (react-dom.production.min.js:122:428)
    at ke (react-dom.production.min.js:292:101)
    at Yt (react-dom.production.min.js:73:352)
    at HTMLBodyElement.a (helpers.ts:98:17)

all other settings like multi-host are working.

2. time not displaying in readable format on the info tab
time: 1645865427665
timeOffset: -60

3. system.info adapter terminating permanently after restart.

> 2022-02-26 09:57:56.493 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | --
systeminfo.0 | 2022-02-26 09:57:56.491 | info | terminating
systeminfo.0 | 2022-02-26 09:57:56.464 | error | Cannot read property 'getObjectList' of undefined
systeminfo.0 | 2022-02-26 09:57:56.462 | error | TypeError: Cannot read property 'getObjectList' of undefined at Function.initAdapter (/opt/iobroker/node_modules/iobroker.systeminfo/myAdapter.js:44:55) at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.systeminfo/myAdapter.js:118:37) at Adapter.emit (events.js:400:28) at /opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:8223:26
systeminfo.0 | 2022-02-26 09:57:56.458 | error | unhandled promise rejection: Cannot read property 'getObjectList' of undefined
systeminfo.0 | 2022-02-26 09:57:56.457 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
systeminfo.0 | 2022-02-26 09:57:56.417 | info | starting. Version 0.3.1 in /opt/iobroker/node_modules/iobroker.systeminfo, node: v14.18.0, js-controller: 4.0.15

**Comment by foxriver76** [comment]
1. Please ensure you admin adapter is up to date, if so please open up an issue at admin adapter
2. If you mean in Overview Tab, same as 1 if you mean tab of info adapter please open issue there
3. is because of https://github.com/frankjoke/ioBroker.systeminfo/issues/35, we can try if we can do something here

**Comment by guthubps1304** [comment]
Tx for the response - will follow your suggestions.
