### ISSUE TITLE
missing explanation for "EDIT" function at HOSTS Tab

### ISSUE THREAD

**Issue by wendy2702** [ioBroker/ioBroker.js-controller#183]
Can somebody please add a explanation what can be edited here:

![host_edit](https://user-images.githubusercontent.com/33424168/38030134-115cee62-3298-11e8-8d01-5b1487aed02a.jpg)

![host edit_1](https://user-images.githubusercontent.com/33424168/38030139-15383212-3298-11e8-9aa3-66db824fd4f0.jpg)

**Comment by Apollon77** [comment]
Can you please reopen that if needed on Admin Repo?

Ou can change the details that are shown in Admin and the color of the Bar for the host in Admin

**Comment by wendy2702** [comment]
Still not clear to me.

Will reopen at Admin repo
