### ISSUE TITLE
Fatal error Check failed: !backing_store->is_wasm_memory()

### ISSUE THREAD

**Issue by blackeagle998** [ioBroker/ioBroker.js-controller#1841]
Hallo,
ich bekomme im LOG folgende Meldungen:
`host.raspi-master | 2022-03-03 16:42:30.353 | error | Caught by controller[0]: #FailureMessage Object: 0xffe5fb08
-- | -- | -- | --
host.raspi-master | 2022-03-03 16:42:30.353 | error | Caught by controller[0]: #
host.raspi-master | 2022-03-03 16:42:30.352 | error | Caught by controller[0]: #
host.raspi-master | 2022-03-03 16:42:30.352 | error | Caught by controller[0]: #
host.raspi-master | 2022-03-03 16:42:30.351 | error | Caught by controller[0]: # Check failed: !backing_store->is_wasm_memory().
host.raspi-master | 2022-03-03 16:42:30.351 | error | Caught by controller[0]: # Fatal error in , line 0
host.raspi-master | 2022-03-03 16:42:30.350 | error | Caught by controller[0]: #
`

Den Auslöser kann ich nicht ausfindig machen.
Kann ich irgendwas tun um noch mehr Informationen zu liefern und die Quelle ausfindig zu machen?

js-controller: 4.0.15
Admin: 5.3.1
node: 14.18.2
nodejs: 14.18.2
npm: 6.14.11

**Comment by Apollon77** [comment]
Bitte im Log vorher bzw nachher schauen. "Caught by controller" ist von einem Adapetr oder einem Compact-Mode Prozess ... Das heisst das muss vorher nachher sein was genau sich da beendet hat mit welchem Fehelr!

Der Fehler an sich ist ein "out of memory" Fall

**Comment by Apollon77** [comment]
Ich mache hier zu weil kein Controlelr ISsue - gern mehr Log posten
