### ISSUE TITLE
"iob url <js-controller url>" will create an js-controller adapter object

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#1845]
> iob url https://github.com/ioBroker/ioBroker.js-controller
install ioBroker/ioBroker.js-controller#205fbd9067643fb999e779aa49ce8b4d08bd5e24
NPM version: 6.14.16
Installing ioBroker/ioBroker.js-controller#205fbd9067643fb999e779aa49ce8b4d08bd5e24... (System call)
INFO: Directory "/opt/iobroker/node_modules/iobroker.js-controller/admin" was not found! Nothing was uploaded or deleted.

**Comment by foxriver76** [comment]
detect it and say cannot install controller from url -> exit

**Comment by AlCalzone** [comment]
(unless the url matches `iobroker.js-controller@<npm-version>`)

**Comment by Apollon77** [comment]
But still check in "UploadAdapter" for io-package-common-controller and prevent any upload/object creation and such

**Comment by Apollon77** [comment]
> (unless the url matches iobroker.js-controller@<npm-version>)

Ni please not ... controller upgrade works differently then adapter updates
