### ISSUE TITLE
VIS Adapter startet nicht mehr neu bei Installation Widget Adapter

### ISSUE THREAD

**Issue by gerbuchner** [ioBroker/ioBroker.js-controller#1849]
Hallo,

bisher wurde, wenn ich mein Widget (https://github.com/gerbuchner/ioBroker.vis-owl) per Katze von Github installiert habe auch der VIS Adapter neu gestartet. Somit war dann auch das Widget selbst sofort im Editor sichtbar. Jetzt habe ich ein Update gemacht auf die aktuellen Versionen und nun wird die VIS nicht mehr neu gestartet, weshalb das Widget nun auch nicht im Editor auftaucht, bis man den VIS Adapter händisch neu startet.

Aktuelle Versionen sind:
NPM - 6.14.16 (vorher 6.14.15)
Node.js - v14.19.0 (vorher 14.18.x)
js-controller - 4.0.18 (vorher 3.3.x)

Vor dem Update:
![image](https://user-images.githubusercontent.com/36327853/156898013-d56b97ac-f5b1-4d48-ae11-96342b0457cb.png)

Nach dem Update:
![image](https://user-images.githubusercontent.com/36327853/156898029-9a967e3f-e243-40b1-8112-19944a756dec.png)

**Comment by Apollon77** [comment]
4.0.12 fixes this
