### ISSUE TITLE
Bug in getForeignObjects on GitHub version adapter.js

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#185]
I had strange problems while experimenting with "limited user rights" testcases in simple-api.

I tracked it down to https://github.com/ioBroker/ioBroker.js-controller/blob/master/lib/adapter.js#L1553 and currently added this "Failsafe" with debug logging (so no final solution!!) befause before it was trying to do "split()" on the object. So question is why an object with localization is returned there (only when using limited user!!)

See simple-api test results:
- Limited User: logging is there  multiple times
https://travis-ci.org/ioBroker/ioBroker.simple-api/jobs/363132708#L496

- no limited user: logging not there
https://travis-ci.org/ioBroker/ioBroker.simple-api/jobs/363132708#L340

Anything to do with Objects-Refactoring??

**Comment by Apollon77** [comment]
Relates to https://github.com/ioBroker/ioBroker.admin/issues/247 ?! Seems to be same "topic"

**Comment by GermanBluefox** [comment]
Should be fixed in 1.5.0

**Comment by Apollon77** [comment]
verified
