### ISSUE TITLE
setObjectNotExists sometimes do not return id

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#1852]
https://github.com/ioBroker/ioBroker.js-controller/blob/ef364284a964d6854558dc6ce16647f2993ed126/packages/adapter/src/lib/adapter/adapter.js#L3605 (after "null" should be a {id: '...'} :-(

**Comment by AlCalzone** [comment]
> the "null" should be a {id: '...'} :-(

`null, {id: "..."}`, right?

**Comment by Apollon77** [comment]
yes
