### ISSUE TITLE
Enhance logging on npm errors

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#1857]
With js-
controller 4 and the usage of pak most likely all npm messages (also error ones) are hidden and when npm fails only an error code is stated.

If we do not find a way to output the error messages at least in case of an error (maybe get the logs and only log if error?) we should at least inform the user to execute the command with "--debug" in order to get details for the error reason ...

**Comment by AlCalzone** [comment]
We could extend the options for pak to return the stderr when installing fails. I kinda like that the usual npm native package "error"s don't show up in the admin.

**Comment by Apollon77** [comment]
> I kinda like that the usual npm native package "error"s don't show up in the admin.

me too thats why the idea to just show that when an error actually occured :-)
