### ISSUE TITLE
current js version harms iobroker

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.js-controller#1858]
Hi .. haven't got details to report atm .. but after updating just the new js controller I can hardly reach my iobroker. Hosts timout .. compact mode timout .. etc.  Don't know how to help myself .. I will probably return to a backup.
Two days ago I updated all adapters that were due .. incl. js .. and the same thing happened .. this time I only updated js.

**Comment by daniel-lo** [comment]
"Uncaught (in promise) timeout"

**Comment by daniel-lo** [comment]
5.3.3 ->5.4.1

**Comment by foxriver76** [comment]
Are we talking about js-controller or javascript adapter?

**Comment by daniel-lo** [comment]
No I mean the adapter. I just installed the controller (host) and as I am used to it hangs at first but a restart helps. This was not the case with the adapter .. so I rather leave that one alone for now.

**Comment by Apollon77** [comment]
Sorry without logs we can not do anything. js.controller and also js adapter are widely installed in these versions and no issues are known

**Comment by daniel-lo** [comment]
will provide .. probably tomorrow .. after tonights backup ran through

**Comment by daniel-lo** [comment]
5:25 installation start

Div. Cannot Get Hosts Timout beim Aufrufen

5:30 iob restart

Prompt ca bei 5:32

hängt hängt hängt

[iobroker.2022-03-17.zip](https://github.com/ioBroker/ioBroker.js-controller/files/8281447/iobroker.2022-03-17.zip)

**Comment by Apollon77** [comment]
Also im Log sehe ich folgendes
* 5:25 update javascript Adapter
* 5:26 fertig damit und er startet wieder
* 5:30 alles stoppt (wohl wegen dem restart)

Ich sehe hier keinerlei "cannot get host" fehler im Log? Wo kamen die her? Was genau meinst du? stehen die in deinem browser? Ist dein Netzwerk stabil? Auf ioBroker seite sehe ich KEINERLEI Fehler, ausser das scheinbar einige Adapter sich beim stop nicht sauber beendet haben ... daher kommen die DB Closed im Log. Scheinbar wurde der js-cntroller mitten im stoppen hart gekillt. Steht 5:30 irgendwas in /var/log/syslog ??

**Comment by Apollon77** [comment]
Und PS: nutze am besten ertsmal "iob stop" ... erst wenn danach alle prozesse weg sind und log nix neues reinkommt machste ein "iob start" irgendwas ist bei dir komisch ... Aber s said: Das ist im Forum an sich einfacher zu besprechen als im GitHub!

**Comment by daniel-lo** [comment]
ja .. Meldungen werden im Browser eingeblendet .. unten in einem bunten Kaschterl.

**Comment by Apollon77** [comment]
Ok, wenn du forum nicht magst "chatten" wir halt hier und Limitieren uns auf meine persönliche Klugheit sowas zu lösen

* Ausgabe von `free -m` ?
* Irgendwelche Einträge in /var/log/syslog von heute?
* Screenshot von "top" bitte

**Comment by daniel-lo** [comment]
OK .. dann muss ich den Adapter wieder installieren .. dauert ein klein Wenig

**Comment by Apollon77** [comment]
Wo bitte in den letzten Fragen steht irgendwas von Adapter installieren??????

**Comment by daniel-lo** [comment]
Na ich  hatte doch ein Backup zurückgespielt damit ich meinen Iobroker wieder benutzen kann. 
Also hab ich auch keinen passenden Syslog zum Iobroker log von vorhin.

**Comment by Apollon77** [comment]
>  Die komplette VM zu recovern ist für mich am einfachsten.

naja damit verlierst Du alle infos und helfen wird für mich am schwersten :-(

**Comment by daniel-lo** [comment]
Kapiere ich .. aber ich bin handlungsunfähig wenn das (siehe oben) passiert. Weiß keinen besseren Weg :-(

**Comment by daniel-lo** [comment]
script engine 5.3.3 -> 5.4.3
05:16:15
[iobroker.zip](https://github.com/ioBroker/ioBroker.js-controller/files/8301563/iobroker.zip)

**Comment by Apollon77** [comment]
Naja ich bin ehrloich ... fang mal an in deinem Javasript und deaktiviere alle skripte und starte eins nach dem anderen ...ich habe das Gefühl das eher da was im argen liegt. Und damit ist hier auf GitHub schluss. GitHub ist kein Support-System. Bitte im Forum Thread machen mit allen Details wie oben angehängt.

Dein "top" sagt das zigbee (!!) >70% CPU braucht UND javascript >35% ... der Controller wird denke ich der effekt sein wel die beiden Adapter komische Dinge tun. ... Also entweder dein zigebee hat ne macke weg oder Skripte verursachen sowas.

**Comment by daniel-lo** [comment]
Das mit der Auslastung hatten wir alles schonmal bei anderen Tickets durch .. ist bei schon lange so. Böses Skript kann natürlich sein .. aber eigentlich unerklärlich warum der Iobroker dann vor dem Update funktioniert und nach dem Update nicht mehr. VG

**Comment by Apollon77** [comment]
Nutzt du "rules" skripte? Die wurden vorher beim javascript start nie automatisch gestartet - bug - das ist jetzt gefixt... ansonsten ggf genauer reinschauen. Auch werden Schedules jetzt etwas paralleler gestartet und nicht mehr nacheinander ... also alles das wären ggf Themen die bei "Komischen skripten" effekte auslösen können. EIn Bug kann nicht ausgeschlossen werden, aber wäre wenn eher im JavaScript Adapter ... aber am Ende wurde nicht soo viel geändert.

Also ich empfehle weiterhin: Alle skripte stoppen, dann javascript adapter restarten ... dann schauen ob alles ok ist und dann ein skript nach dem anderen starten und das system beobachten was passiert ... du kannst auch unter Admin - Instanzen mit aktiviertem Exertenmodus die eingehenden/ausgehenden state changes sehe .. dort vor allem auf javascript und zigbee schauen ... wenn das hoch geht nachdem ein skript gestartet wurde  dann dort genau hinschauen was es tut.

Solche Effekte waren bisher an sich immer Skriptfehler

**Comment by daniel-lo** [comment]
Puh .. danke Dir .. aber echt ätzend .. muss ich mir mal Luft für schaffen. Hätte soo gerne mal Ruhe im Karton.

**Comment by daniel-lo** [comment]
Skript ist gefunden .. naja .. es ist eher eine Blockly-Seite und kein JS die böse ist. Keine Ahnung was da haken könnte aber sobald ich dieses Skript mit dem neuen JS-Adapter aktiviere ist Schluss. Danke!!!

**Comment by Apollon77** [comment]
na dann am besten mal das skript zeigen (aber nbitte Wiiiiiiiiiiiiirklich im Forum!!)

**Comment by daniel-lo** [comment]
Moin .. bitte hasse mich nicht .. ich fürchte hier sollte ein Fehler abgefangen werden .. natürlich weiß ich darüber nichts ... 
Böses Skript:

![grafik](https://user-images.githubusercontent.com/4311558/159150638-5d5c6a62-11c8-4dd0-a742-1d0c2d7769fe.png)

Wenn ich den JS-Adapter mit aktivierten skript stoppe kommt dies:

![grafik](https://user-images.githubusercontent.com/4311558/159150611-60e781a6-6c33-4e6c-bd0b-f1030e7dc4f8.png)

Vermutlich ein User-Fehler .. z.B. könnte ich mir vorstellen, dass ich statt "steuere" mal "aktualisiere" probieren könnte. Aber den IOB unbrauchbar zu machen .. sollte nicht passieren.

**Comment by Apollon77** [comment]
Verstehst du was dein Skript tut? Du steuerst einen Wert. Wenn der Wert dann geändert wird (was ja durch dein steuern passiert) steuerst du wieder … damit gilt der letzte Satz erneut. 

Und das ganze bei zwei States. 

Schöne endlos Schleife die du gebaut hast. Und ja das zieht dann controller, JavaScript und zigbee Adapter in Mitleidenschaft.

**Comment by daniel-lo** [comment]
Wo ich doch der beste Programmierer der Welt bin :-)

Hatte das aus einem Youtube .. initial den Wert auf 5 Sekunden setzen und dann immer wenn er aktualisiert wird sicherstellen, dass er auf 5 Sekunden bleibt.

So war es zumindest gedacht.

**Comment by Apollon77** [comment]
Aber jetzt wirklivch: Skripting support === FORUM!

**Comment by daniel-lo** [comment]
Wenn es hier nichts abzufangen gibt .. sehe ich das natürlich ein :-)

**Comment by Apollon77** [comment]
Dasin so einem Fall abzufangen ist nahezu unmöglich

**Comment by daniel-lo** [comment]
Inzwischen hat es Klick gemacht .. dumm .. ich hab bestimmt ein Jahr darunter gelitten. Im Forum wurde dankenswerter Weise mitgedacht .. aber der Groschen ist erst bei der dritte BBQ-Pizza-Scheibe gefallen. Meine Frau hat sich gefragt warum ich mir in Stellung Facepalm gehe ;-)
