### ISSUE TITLE
Function deleteDevice ignore states in first instance

### ISSUE THREAD

**Issue by Jey-Cee** [ioBroker/ioBroker.js-controller#186]
The function deleteDevice ignore this structure:
`adapter.instance.device.state`
So all states are there after delete the device.
This structure is working:
`adapter.instance.device.channel.state`

Discussion on forum: https://forum.iobroker.net/viewtopic.php?f=24&t=12856&p=141995#p141995

**Comment by Jey-Cee** [comment]
I've tested it. Seems not to Work, now the function does nothing.

Can anyone verify this?

**Comment by Jey-Cee** [comment]
@GermanBluefox tested again with new Adapter only for Testing. Now it works. 

Notice: It respects only first level Channel and States. That means if there is an sub channel they and there states wan't be deleted.

**Comment by GermanBluefox** [comment]
Try to avoid subchannels.
All visualisations will not support such a complex trees

ср, 13 июн. 2018 г., 8:55 Jey-Cee <notifications@github.com>:
