### ISSUE TITLE
Add subscription regex try/catch

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#1868]
to prevent: https://forum.iobroker.net/post/782769

(or already on subscribe try to "use" the regex for a dumma string just to validate it??)

In fact we would need to "validate a Redis pattern" in general but should also verify that in our sim server

**Comment by AlCalzone** [comment]
Stupid/pragmatic approach: Forbid using IDs with a length of >1000 in `subscribe` methods and similar ones.
I don't think anyone realistically uses IDs longer than 100 or maybe 200, so 1000 should be a safe bet.

**Comment by Apollon77** [comment]
In my eyes yes this is one topic but s we saw in last log also an regex could got invalid ... so I would not just check length :-) But yes length check would be "easy"

**Comment by AlCalzone** [comment]
Maybe make sure that the string is a valid ID before converting to regex first? It's pretty easy to block the regex executor in Node.js:
```
> str = "b" + "a".repeat(150) + "cbab"
'baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaacbab'
> reg = new RegExp("b" + "(a|a)*?".repeat(5) + "b")
/b(a|a)*?(a|a)*?(a|a)*?(a|a)*?(a|a)*?b/
> reg.test(str)
... takes forever
```

**Comment by Apollon77** [comment]
"valid ID with allowed wildcards" ... yes :-)
