### ISSUE TITLE
Feature: notification if file was written

### ISSUE THREAD

**Issue by GermanBluefox** [ioBroker/ioBroker.js-controller#1878]
I as developer and as javascript user want to be informed if some file was written in order to implement different file handlers for cameras, and other usecases.

**Comment by Apollon77** [comment]
Do you mean kind of an "onFileAction" handler? where you get the info on an successfull change with "action" and "location" or what? And this for what? own namespace? all user.meta namespaces?

In fact we also could add an "onBinaryStateChange" handler which only transprts the change binarystate id and not the value ...

**Comment by GermanBluefox** [comment]
Yes. I would like **onBinaryStateChange** too.
But originally I meant "fileChange(adapter, filename, stat)"  from Objects DB. Like "objectChange" and "stateChnage" events.

**Comment by Apollon77** [comment]
All changes or also with "subscriber patterns"?

And "fileChange(adapter, filename, stat)" ... 0_userdata.0 would then als be an adapter? ;-)

**Comment by Apollon77** [comment]
WIUll be available in js-controller 4.1
