### ISSUE TITLE
Remove (or update) hints to install npm in version 4

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.js-controller#1895]
I've seen a screenshot on Facebook, which contained a hint to install npm in version 4. And I found it in the current version:

https://github.com/ioBroker/ioBroker.js-controller/blob/86e3a2e82e535713b07691b7cf4cd22f8119bcf1/packages/controller/lib/setup/setupInstall.js#L254-L256

https://github.com/ioBroker/ioBroker.js-controller/blob/86e3a2e82e535713b07691b7cf4cd22f8119bcf1/packages/controller/lib/setup/setupInstall.js#L265

These hints should be updated

**Comment by klein0r** [comment]
https://github.com/ioBroker/ioBroker.js-controller/blob/86e3a2e82e535713b07691b7cf4cd22f8119bcf1/packages/controller/lib/preinstallCheck.js#L40-L53

**Comment by klein0r** [comment]
@foxriver76 Update to npm 8 for js-controller 4.1?

**Comment by foxriver76** [comment]
Now with the slow npm 6 GitHub installations it may be desirable. Are there currently concerns with npm 8 + iob @Apollon77?

**Comment by Apollon77** [comment]
Npm 8 is ok and we also have recommended nodejs Version on v16 that also brings npm8

**Comment by klein0r** [comment]
@foxriver76 There are more files with npm versions

https://github.com/ioBroker/ioBroker.js-controller/blob/8ff04f7986dcd3bf438fa57d42c0376167b7c580/packages/controller/lib/setup/setupInstall.js#L254-L256

https://github.com/ioBroker/ioBroker.js-controller/blob/8ff04f7986dcd3bf438fa57d42c0376167b7c580/packages/controller/lib/setup/setupInstall.js#L265
