### ISSUE TITLE
Check if changes in `os.networkInterfaces()` in node 18 affect us

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.js-controller#1898]
```
<       family: 'IPv4',
---
>       family: 4,
14c14
<       family: 'IPv6',
---
>       family: 6,
```

**Comment by AlCalzone** [comment]
The numbers are node.js 18, the strings are 16:
https://github.com/nodejs/node/pull/41431#pullrequestreview-929717323

**Comment by Apollon77** [comment]
Hm ... veeery super that someone noted it but then accepted it as if he would be the only one potentially affected :-(

**Comment by Apollon77** [comment]
A code check at least show that we do not use ".family" and also "IPv" as string is only used in a setting

**Comment by AlCalzone** [comment]
We might need to update some deps though, basically everything that  does mDNS

**Comment by AlCalzone** [comment]
I think this can be closed now, right?

**Comment by Apollon77** [comment]
in which version the revert was now in finally?

**Comment by AlCalzone** [comment]
https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V18.md#2022-06-16-version-1840-current-danielleadams
18.4.0
