### ISSUE TITLE
io-package schema - supportCustoms deprecated?

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.js-controller#1900]
``materialize`` and ``materializeTab`` have hints that those features are deprecated.

https://github.com/ioBroker/ioBroker.js-controller/blob/7a305a4511d6ee67c4691312cf8be648792b82a2/schemas/io-package.json#L905-L912

Isn't ``supportCustoms`` also deprecated? I thought ``adminUi. custom`` should be used instead:

https://github.com/ioBroker/ioBroker.js-controller/blob/7a305a4511d6ee67c4691312cf8be648792b82a2/schemas/io-package.json#L116-L120

Please add a hint in schema

**Comment by klein0r** [comment]
Confused. ``noConfig`` is deprecated, because ``adminUI.config = "none"`` should be used. That's good 👍 

https://github.com/ioBroker/ioBroker.js-controller/blob/7a305a4511d6ee67c4691312cf8be648792b82a2/schemas/io-package.json#L925-L928

So I thought ``supportCustoms: false`` (which is the default) should be equal to ``adminUi.custom = "none"`` (makes no sense to define that)

In my opinion it would be consequent if all admin options are moved to the ``adminUI`` object (long term). Like ``supportCustoms: true`` equals to ``adminUi.custom = "json"`` or ``adminUi.custom = "html"`` (doesn't exist)

*(just to share my opinion)*

**Comment by AlCalzone** [comment]
> Confused

That's `io-package.json` options in a nutshell :D

**Comment by klein0r** [comment]
Thanks for the explanation - my fault. I thought those custom options are just an admin feature, but the js-controller is also involved.
