### ISSUE TITLE
Update nodejs dependency to >=14.0.0 [js-controller 4.1.x]

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.js-controller#1910]
Since nodejs 12.x is EOL since April '22, the js-controller should drop the support for that version.

https://github.com/ioBroker/ioBroker.js-controller/blob/1350bfedc4e2c5972d27821f5ee4f4772762c8aa/packages/adapter/package.json#L4-L6

https://github.com/ioBroker/ioBroker.js-controller/blob/1350bfedc4e2c5972d27821f5ee4f4772762c8aa/packages/cli/package.json#L4-L6

...

https://github.com/ioBroker/ioBroker.js-controller/blob/1350bfedc4e2c5972d27821f5ee4f4772762c8aa/.github/workflows/ci-tests.yml#L41

**Comment by Apollon77** [comment]
I'm against dropping a nodejs version support wiothout any need (and I personally hate that very much on other libraries). We will drop the support if needed because one of our other dependendcies require us to do that ...

**Comment by klein0r** [comment]
Yes, you're right. Raising the required nodejs version in a minor release would also break semver. Sorry - bad idea

**Comment by foxriver76** [comment]
You can of course require Node 14 in your adapters, if you need to or want to use the introduced features.
For Controller we currently see no requirement and until a new official release of controller it will have no impact anyways.
