### ISSUE TITLE
Remove cp from build process

### ISSUE THREAD

**Issue by GermanBluefox** [ioBroker/ioBroker.js-controller#1912]
and replace it with e.g. cpx module or gulp

**Comment by GermanBluefox** [comment]
there are still some "cp"s in the build:
![image](https://user-images.githubusercontent.com/4582016/168605040-778de5ab-58b1-4772-9d71-534b211f907a.png)

**Comment by foxriver76** [comment]
where?

**Comment by foxriver76** [comment]
it should be fixed now @GermanBluefox
