### ISSUE TITLE
createState has issues when used on Binary States

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#1918]
When createState (because the convenient create Stucture should be used) is used on a binaryState then the adapter.js logic tries to do getState (to see if there is a value) and set null if not after object creation.

This leads to a "getState" on a binaryState which leads to an error because content is no JSON.

We should make createSTate BinaryState compatible or add a createrBinaryState

**Comment by Apollon77** [comment]
Workaround is to use setObjectNotExists instead of createState for BinnaryStates

**Comment by foxriver76** [comment]
Would be fixed by porting binary states to a unique namespace as currently planned. Then a getState would not return a binary state and thus all fine (assumption without looking into code).

**Comment by foxriver76** [comment]
https://github.com/ioBroker/ioBroker.js-controller/issues/2048
