### ISSUE TITLE
Binary States broken after js-controller Restart when usign File/JSONL-DB

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#1926]
There seems to be an issue that (since ages) destroy binary state content when the js-controller gets restarted. This means that during runtime there is no issue because the content is served from RAM and all great there.

The issue relies in the serialization of Buffer objects. They are serialized into an object form from their "toJSON" method but there is no special "deserialize" handling implemented when the database is read on start. This then renders the binary state content to be still in Object form rather then becoming a valid Buffer again.

Example:
* I write two BinaryStates ... once with a real binary Buffer (hex '010203040506070809') and one with a string "Huhu"

When reading these using GetBinaryState the results are:

* During runtime where value was set too:
>Bin-stringify: {"type":"Buffer","data":[1,2,3,4,5,6,7,8,9]}
Bin-toString: 
Bin-isBuffer: true

>StringBin-stringify: {"type":"Buffer","data":[72,117,104,117]}
StringBin-toString: Huhu
StringBin-isBuffer: true

* After a restart without re-setting the value:
> Bin-stringify: {"type":"Buffer","data":[123,34,116,121,112,101,34,58,34,66,117,102,102,101,114,34,44,34,100,97,116,97,34,58,91,49,44,50,44,51,44,52,44,53,44,54,44,55,44,56,44,57,93,125]}
Bin-toString: {"type":"Buffer","data":[1,2,3,4,5,6,7,8,9]}
Bin-isBuffer: true

> StringBin-stringify: {"type":"Buffer","data":[123,34,116,121,112,101,34,58,34,66,117,102,102,101,114,34,44,34,100,97,116,97,34,58,91,55,50,44,49,49,55,44,49,48,52,44,49,49,55,93,125]}
StringBin-toString: {"type":"Buffer","data":[72,117,104,117]}
StringBin-isBuffer: true

**Comment by Apollon77** [comment]
Additionally to this while looking into the whole logic we experienced that the "is Binary" Detection is also not exact because several places try to "JSON-parse" the State content when when it is parsable (e.g. also '{"huhu":true}' too) is considered a normal state rather than a binary state which is also very strange and not accurate

**Comment by Apollon77** [comment]
One idea to solve this would be to give binary states their own namespace in the DB, but this requirs some migration - and also Fallbacks and will be an issue again in Multihost environments.

One basic idea could be:
* File/JSONL DBs try to detect such broken Buffers or "non state objects" on "setup first" and move the data over to the other place. The Redis-Sim-Server can still have the "old "logic as fallback and so offer backward compatibility for old and new hosts
* For Redis-DBs this is a bit more tricky ... here one idea would be to have the stateClient write twice - old location and new location as long as not all hosts are on the newest version - and we clean that up later in 4.2 or such
* For JSONL/File we could also think about not storing buffers but storing the content as files in filesystem and just save a refernce to the file in it. For this also Backup would need to be adjusted

**Comment by AlCalzone** [comment]
> not storing buffers but storing the content as files in filesystem and just save a refernce to the file in it.

Since the default json representations of buffers is really really really space inefficient, this sounds like a good idea.
Worst case each byte in the buffer gets transformed to 4 characters `255,` plus the fixed boilerplate around the data.

**Comment by foxriver76** [comment]
https://github.com/ioBroker/ioBroker.js-controller/issues/2048
