### ISSUE TITLE
Question: Why saves iob backup ID values contents double in "value" and "doc"?

### ISSUE THREAD

**Issue by mcuiobroker** [ioBroker/ioBroker.js-controller#1928]
In the backup.json there is for each ID the object "value" and object "doc" with the same Content?
Is it possible to save storage space? 
Or is there an special reason for that saving?
https://forum.iobroker.net/topic/27267/test-adapter-iobroker-backitup-v2-4-x/1956

**Comment by Apollon77** [comment]
The content is not alwys the same ... but in fact I would say "this is historic" ... exact reasons would need to be deeply checked ... yes could save some megabytes :-)

**Comment by foxriver76** [comment]
It is the result from a `getObjectList` call and yes it should be 100 % identical https://github.com/ioBroker/ioBroker.js-controller/blob/128e8b10f7b78bc7142a708d467270b661cdf15a/packages/db-objects-redis/src/lib/objects/objectsInRedisClient.ts#L4434 probably only there for backward compatibility.

**Comment by foxriver76** [comment]
On a first look restore only uses `doc`, thus we could get rid of saving `value` without breaking backward compatibility.

**Comment by Apollon77** [comment]
But maybe rewritable to use doc too?
