### ISSUE TITLE
[Feature request] Add a way to change the loglevel of adapter without restarting them

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.js-controller#193]
Currently, changing the loglevel of an adapter instance results in an immediate restart of that instance. It would be nice if there was a way to change the loglevel on-the-fly without restarting the adapter. 

This could be helpful to debug when the adapter is in a weird state that only happens after it has been running for a while.

**Comment by Apollon77** [comment]
One idea could be add messagebox to all adapters and support a message. Other (and maybe better) idea is to have a "system.adapter.name.X.logLevel" state which is set to the value which is defined in instance object on start. Adapter subscribes to this sate and on change it re-initialize the logger object.

makes this sense?

**Comment by Apollon77** [comment]
should be relatively easy to implement the proposed way
