### ISSUE TITLE
Deleting artnetDMX not working

### ISSUE THREAD

**Issue by Fibbefobbe** [ioBroker/ioBroker.js-controller#1934]
it's not possible, to delete art netDMX. I get the following note:

Error deleting adapter artnet from disk: Cannot find module 'iobroker.artnet/io-package.json'Require stack:- /opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupInstall.js- /opt/iobroker/node_modules/iobroker.js-controller/lib/setup.js- /opt/iobroker/node_modules/iobroker.js-controller/iobroker.js
You might have to delete it yourself!

How can I do this?

**Comment by Apollon77** [comment]
Please show the full commandline you used and the full stack trae/error

But in fact you need to remove execute "rm -rf /opt/iobroker/node_modules/iobroker.artnet"

**Comment by Fibbefobbe** [comment]
Thanx,

I just turned on the expert modus and deleted again. than I installed an older version, and deleted ist again. 
After that I restartet iobroker an installed the last version of artnetDMX

Now it's woking.
