### ISSUE TITLE
NewBie Problem

### ISSUE THREAD

**Issue by theo-69** [ioBroker/ioBroker.js-controller#195]
Getting this PopUp

> ioBroker unterstützt die LTS Versionen 4, 6 und 8 von node.js. Bitte aktualisieren Sie die verwendete node.js Version ("v10.0.0") auf dem Rechner "***-Mac-mini.local" auf eine unterstützte Version. Wir empfehlen die Verwendung von node.js 6.

>

**Comment by Apollon77** [comment]
Which admin version?
