### ISSUE TITLE
cli upgrades fail / only work with manually switching user

### ISSUE THREAD

**Issue by Garfonso** [ioBroker/ioBroker.js-controller#1952]
Today I tried to upgrade some adapters using cli ( `iobroker upgrade all`). They failed:

```
Would you like to upgrade yamaha from @0.5.2 to @0.5.3 now? [(y)es, (n)o]: y
Update yamaha from @0.5.2 to @0.5.3
NPM version: 8.11.0
Installing iobroker.yamaha@0.5.3... (System call)
host.Server Cannot install iobroker.yamaha@0.5.3: 243
```

I tried some other adapters, all the same error and googled -> 243 means access error.

I recognized that in the past (tm) every iobroker cli command would ask me for my root password, but that stopped since a few versions (or so?). Usually the command (like start / stop of adapters) seem to work. But installation fails. I need to manually switch to iobroker user to get it working again (i.e. `sudo -u iobroker iobroker upgrade all` works).

Was there some change in iobroker to avoid the user change? Or is there something wrong with my system? Not sure where to look. 

This is on Ubuntu 22.04
node v16.15.1
npm 8.11.0

**Comment by foxriver76** [comment]
Every command should be executed as user `ìobroker` automatically. It seems like your installation is a bit older and no fixer ran in between? Try `iob fix` and then check if the commands work.

**Comment by Apollon77** [comment]
Please run the command with --debug to see the real npm errors ...

**Comment by Garfonso** [comment]
Ok. Sorry for the confusion then. Something in the system seems to be broken... This seems to also affect the fix command:
```
achim@Server:/opt/iobroker$ iob fix
iobroker fix

Execute the installation fixer script, this updates your ioBroker installation

Options:
--help  Show help  [boolean]
```

Will search how to manually run fixer.

**Comment by foxriver76** [comment]
Ah okay.. it is that old that the fixer script is not there yet *gg* 

`curl -sL https://iobroker.net/fix.sh | bash -`

after that you can use the short command in the future.

**Comment by Garfonso** [comment]
Yes, it is quite old. The fixer was run before, though... somewhere in 2020, IIRC. But that's quite some time ago, too. ;-)

Fixer did run, but I'm still not asked for passwords... 

I did some more digging. There is a file /etc/sudoers.d/ which configures a lot of ioBroker commands to be used without password. This seems to be created by the [installer](https://github.com/ioBroker/ioBroker/blob/master/installer_library.sh#L663). So at least I know understand why I don't have to enter a password anymore since some time. (funny thing, just running `iobroker` will still ask for a password, but add any command and none is needed ;-) )

But fixer must have repaired something, now upgrades / installs are again possible from cli. Thanks. :-)
