### ISSUE TITLE
Fehler im Bereich Skripte - Syntax highlightning

### ISSUE THREAD

**Issue by SteveWi-291** [ioBroker/ioBroker.js-controller#1957]
Ich bekomme neuerdings Fehler im Skript - Teil, wie im Bild angezeigt. Dieser Fehler trat erst auf, als ich auf Admin 6.1.11 bzw die letzten Updates von iosocket etc. installiert habe...

System: 
Node.js v16.15.1
NPM 8.11.0

![image](https://user-images.githubusercontent.com/71070045/178146202-bfc6cfdf-548a-410c-8313-cb1c98ba0e09.png)
![image](https://user-images.githubusercontent.com/71070045/178146244-1012e9d2-17af-484a-9a66-574a29c259b8.png)

**Comment by Apollon77** [comment]
Wo kommt diese ANzeige?Im Javascript-Adapter? Dann bitte issue dort eröffnen
