### ISSUE TITLE
can't update any adapter 

### ISSUE THREAD

**Issue by igitlin** [ioBroker/ioBroker.js-controller#1974]
try to update admin
Dependencies
js-controller (>=3.3.22): 4.0.23
node (>=12.0.0): 18.5.0
changes
6.2.13
___________________________
discovery
Dependencies
js-controller (>=2.0.0): 4.0.23
node (>=12.17.0 <13.0 || >=14.0.0): 18.5.0

**Comment by Apollon77** [comment]
Hi @igitlin,

please read the posted infos and tell me what you would do with this when you read it and want to help ...

Please provide more information ... Where you have issues upgrading? Screenshots? Error logs? What did you try ? Results?
Current version of relevant adapters (e.g. Admin)....

**Comment by igitlin** [comment]
I haven’t looked into iob for a long time - since everything worked fine, I went in, suggested updating iob. I have updated to the latest version.
![image](https://user-images.githubusercontent.com/30923527/183216026-931a2d61-213d-4b1c-b6f2-50fa8f8821a1.png)
Then there were updates for adapters
![image](https://user-images.githubusercontent.com/30923527/183216332-96536065-2f69-439d-81dc-77b539bed3ca.png)
i try to update any of them and i can't because i get an error
![image](https://user-images.githubusercontent.com/30923527/183216468-e91cd020-ce17-4e2f-b045-4026550f4c27.png)
![image](https://user-images.githubusercontent.com/30923527/183217447-ccc93e53-d263-447c-8aa1-5e77f7121467.png)
![image](https://user-images.githubusercontent.com/30923527/183217462-9f015ea0-6c5b-4d68-9bb0-9eb008c232a4.png)
immediately after the error appeared, I tried to reinstall iobroker
reinstall node, upgrade and downgrade node
nothing has changed, there is nothing in the logs

**Comment by foxriver76** [comment]
`iob upgrade Admin` on the command line then please see if it works. This is then executed by controller. I remember an admin beta had a bug.

**Comment by igitlin** [comment]
> `iob upgrade Admin` on the command line then please see if it works. This is then executed by controller. I remember an admin beta had a bug.

yes it work, after update admin all other updated from web

**Comment by Apollon77** [comment]
Info: The reason was an issue in Admin 6.0.0 that prevented all updates ... only commandline was solution to fix that

**Comment by jhg28** [comment]
Tried also to update the admin on my slave:
Node.js v16.16.0
NPM 8.11.0

pi@iobroker-s:/opt/iobroker $ iobroker stop
pi@iobroker-s:/opt/iobroker $ iob upgrade admin

This upgrade of "admin" will introduce the following changes:
==========================================================================
-> 6.2.14:
Fix for OAuth2 authentication response success page

-> 6.2.13:
Corrected JSON config

-> 6.2.12:
Corrected the Text input field in JSON configuration

-> 6.2.6:
Implemented Oauth2 workflow for adapters
Corrected encrypt/decrypt functions
==========================================================================

Would you like to upgrade admin from @6.2.4 to @6.2.14 now? [(y)es, (n)o]: y
Update admin from @6.2.4 to @6.2.14
host.iobroker-s Adapter "system.adapter.admin.1" is stopped.
NPM version: 8.11.0
Installing iobroker.admin@6.2.14... (System call)
host.iobroker-s Cannot install iobroker.admin@6.2.14: 217

Can the issue the same as described here?

**Comment by foxriver76** [comment]
No, it is something else. Please use `iob upgrade admin --debug` for more information on the error.

**Comment by jhg28** [comment]
Here the error message:

Installing iobroker.admin@6.2.14... (System call)
npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /opt/iobroker/node_modules/abbrev
npm ERR! dest /opt/iobroker/node_modules/.abbrev-5eNud0FY
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename '/opt/iobroker/node_modules/abbrev' -> '/opt/iobroker/node_modules/.abbrev-5eNud0FY'

Renamed the folder and tried it once more. A new error message came up.

Update admin from @6.2.4 to @6.2.14
NPM version: 8.11.0
Installing iobroker.admin@6.2.14... (System call)
npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /opt/iobroker/node_modules/abab
npm ERR! dest /opt/iobroker/node_modules/.abab-bvmibCm3
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename '/opt/iobroker/node_modules/abab' -> '/opt/iobroker/node_modules/.abab-bvmibCm3'

**Comment by Apollon77** [comment]
Yes and this will rpeat untill all of these dirs are fixed :-(( In the ioBroker Fporum there is a command to remove them all ins one, but I do not have the link right now ... but search should help there

**Comment by jhg28** [comment]
Sounds like, all of the directories which creates an error, can be deleted.
Is this correct?
Will try to find the link, otherwise I will remove them manually.

**Comment by Apollon77** [comment]
Yes, it seems liek npm cretes theese dirs with a point at the beginning as temporary stuff when doing package installs/updates to be able to rollback ... question is why he do not clean them up properly in all cases and in which cases they stay

**Comment by jhg28** [comment]
Renamed now the files which are shown in the error messages.

And now I receive the following error message:

Installation broken or unknown objects type: jsonl configured.

**Comment by Apollon77** [comment]
I get s more and more a "support "topic ... please open a thread in our Forum and lets adress it there please
