### ISSUE TITLE
Add object type "chart"

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#1984]
for e-charts adapter

```
{common: {name: 'A', expert: true}, native:{data: {...LARGE OBJECT}, type: 'chart'}
```

@GermanBluefox please add object

**Comment by foxriver76** [comment]
So just a simple Object like Meta? What was the reason to add this new Object types again, instradare of using existing ones, they seem very Special?

Same for #1983

**Comment by Apollon77** [comment]
Ithink they are already there snce longer ... we just not saw them

**Comment by foxriver76** [comment]
Okay then it would be good to have some description + example for docs and schema @GermanBluefox

**Comment by GermanBluefox** [comment]
Example: 
```
{
  "common": {
    "name": "preset_1"
  },
  "native": {
    "url": "",
    "data": {
        CUSTOM_DATA: null
    }
  },
  "type": "chart",
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1669931266565,
  "_id": "echarts.0.MyFlde.preset_1",
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}
```
It can have all normal common attributes: color, name, enabled, ...
