### ISSUE TITLE
[1.5] Error: Cannot find module 'le-acme-core'

### ISSUE THREAD

**Issue by 61stephan** [ioBroker/ioBroker.js-controller#199]
beim start von socket.io mit ssl kommt 
Error: Cannot find module 'le-acme-core'
siehe https://forum.iobroker.net/viewtopic.php?f=22&t=14322

**Comment by Apollon77** [comment]
seems to be fixed in 1.5 already, Verification needed

**Comment by Apollon77** [comment]
1.5.7 is released, so I close here
