### ISSUE TITLE
Cannot read /proc/meminfo: TypeError: text.match is not a function

### ISSUE THREAD

**Issue by tiedev** [ioBroker/ioBroker.js-controller#200]
After a complete crash of my iobroker system. I installed js-controller version 1.5.0 by mistake.
Every 150ms there was an entry:

`host.cubietruck   error   Cannot read /proc/meminfo: TypeError: text.match is not a function`

created in my log and sometimes even wrong:

`Cannot   error   read /proc/meminfo: TypeError: text.match is not a function`

I checked that iobroker user has access to meminfo.

And discussed this issue in a german [thread](https://forum.iobroker.net/viewtopic.php?f=17&t=14349#p151121). Maybe it helps.

**Comment by Apollon77** [comment]
Fixed by #201
