### ISSUE TITLE
formatDate and formatValue - format is optional

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.js-controller#2001]
https://github.com/ioBroker/ioBroker.js-controller/blob/db6b87d93d388b330eed47dda5f27ae7f1f4fc70/packages/adapter/src/lib/adapter/adapter.ts#L6707-L6709

Format should be optional

-----

https://github.com/ioBroker/ioBroker.js-controller/blob/db6b87d93d388b330eed47dda5f27ae7f1f4fc70/packages/adapter/src/lib/adapter/adapter.ts#L6673-L6674

Format should be optional

See also: https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/60355

**Comment by foxriver76** [comment]
If you find more of these, let me know, there a probably a bunch of imperfect types in the repo and knowledge is currently spread a bit until we manage https://github.com/ioBroker/ioBroker.js-controller/issues/1962
