### ISSUE TITLE
Save tier level settings

### ISSUE THREAD

**Issue by pafade89** [ioBroker/ioBroker.js-controller#2002]
Hello everyone,

since the ioBroker controller update 3.3.19 it is possible to start adapters according to three different tiers. I've been waiting for this function for a long time. The tier level can be set for every adapter individually. Unfortunately this setting resets after an adapter upgrade.

So is it possible to save these tier level settings?

**Comment by Apollon77** [comment]
Oh ... yes makes sense to preserve the value
