### ISSUE TITLE
getStatesOf() parentChannel is not optional anymore.

### ISSUE THREAD

**Issue by holomekc** [ioBroker/ioBroker.js-controller#2014]
Hi,

the api says that getStatesOfAsync() can be called without parentChannel. In fact it even says it can be called without any parameters at all.

Due to #1917 assertString() calls were added for parentDevice and parentChannel, which do not consider this. 

I am not sure what the truth is now. Without this possibility, it seems like it is impossible to get states of a one level folders with states. 

Can you please check this.

**Comment by foxriver76** [comment]
If it was optional before then we will check if it should be optional again, the validation is mainly done on existing types and these are not 100 % valid especially for methods which are not frequently used

**Comment by holomekc** [comment]
I could work around by setting it to an empty string. At least this is what I could see was done with other methods.

**Comment by foxriver76** [comment]
Fixed with https://github.com/ioBroker/ioBroker.js-controller/commit/c4a73b713d74f23dde8bc992db85776fe9b8c8a2
