### ISSUE TITLE
Add check for setimeout/Interval on adapter for too high numbers

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#2046]
> When delay is larger than 2147483647 or less than 1, the delay will be set to 1. Non-integer delays are truncated to an integer.

This is suprising and not well known ... maybe we can protect opur developers from it :-)

**Comment by foxriver76** [comment]
duplicate of #1994

**Comment by Apollon77** [comment]
oohh was I that good already ? ;-))
