### ISSUE TITLE
Default DNS lookup fallback to ipv4first

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#2053]
In Node.js 17 the default for DNS lookup was changed from ipv4first to "verbatim". We hard fix this in js-controller 4.0.24 as seen in https://github.com/ioBroker/ioBroker.js-controller/pull/2052

For js-controller 4.1/5 we should do the same but configurable in iobroker.json "system" section. Default should stay for us "ipv4first" but users can change it to "verbatim". The relevant method exists since v16.4.0, v14.18.0.

**Comment by foxriver76** [comment]
Check if there is more to do except from providing the ipv6 option: https://github.com/ioBroker/ioBroker/issues/413
