### ISSUE TITLE
[2.0.0] Rebuid reinstall.sh in JavaScript

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#206]
to have it available for all OS

Can use tooling from https://github.com/ioBroker/ioBroker.js-controller/issues/202 :-)

**Comment by Apollon77** [comment]
Also simpify:

cd /opt/iobroker

npm rebuild -f

**Comment by GermanBluefox** [comment]
There is a reinstall.js file . Till yesterday

вт, 12 июн. 2018 г., 9:38 Ingo Fischer <notifications@github.com>:

**Comment by Apollon77** [comment]
Should the new reinstall.js then not use nom rebuild -f instead of working different?

On the other hand it would be a clean way to get started (again)

**Comment by GermanBluefox** [comment]
Reinstall.js is a hard way to rebuild. After the npm rebuild failed.

and rebuild.sh should be deleted or call rebuild.js

ср, 13 июн. 2018 г., 8:39 Ingo Fischer <notifications@github.com>:

**Comment by Apollon77** [comment]
> Reinstall.js is a hard way to rebuild. After the npm rebuild failed.
Then maybe add a question to rebuild.js if the other command was tried first and only afetr "yes" doing it? Because people do not read docs and see a rebuild.js file and execute it :-)

> and rebuild.sh should be deleted or call rebuild.js

let's call the js file  - mainly to make sure updates of js.controller really overwrite the .sh file

**Comment by GermanBluefox** [comment]
Done? The rebuild.sh should be extended with cli requests like:
> Do you want to delete node_modules? [Y/n]:
> Do you want to start "npm install" [Y/n]:

**Comment by GermanBluefox** [comment]
Done?

**Comment by Apollon77** [comment]
What about your last comment from june? if this is done/unneeded then I think yes :-) If not then no
