### ISSUE TITLE
Types on v5 release

### ISSUE THREAD

**Issue by foxriver76** [ioBroker/ioBroker.js-controller#2063]
- We need to communicate this, that adapters then need @iobroker/types instead of @types/iobroker
- We should deprecate @types/iobroker
- Probably adapter-core needs adaption to new package too

**Comment by Apollon77** [comment]
Can we not create a @types/iobroker that for now 1:1 exports @iobroker/types?

**Comment by AlCalzone** [comment]
Not sure if that works, need to check. We can deprecate the package though and reference our package.

**Comment by AlCalzone** [comment]
We should probably...
- do [this](https://github.com/DefinitelyTyped/DefinitelyTyped/#removing-a-package)
- update adapter-core to reference the new package
- and let the devs know who might be using the type definitions directly.

**Comment by foxriver76** [comment]
> We should probably...
> 
>     * do [this](https://github.com/DefinitelyTyped/DefinitelyTyped/#removing-a-package)
> 
>     * update adapter-core to reference the new package
> 
>     * and let the devs know who might be using the type definitions directly.

Should be done after my vacation.

**Comment by foxriver76** [comment]
This is done
