### ISSUE TITLE
Bug: The `id` variable is used before its declaration

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.js-controller#207]
https://github.com/ioBroker/ioBroker.js-controller/blob/2a32f4028a6ae49f4096886ffa1a33c17c16477c/lib/adapter.js#L1590

Relevant lines of code:
```js
if (!res.rows[i].value) {
    that.log.debug('Invalid id returned from getEnums: ' + JSON.stringify(id));
    continue;
}
const id = res.rows[i].value._id;
```

I'm not sure how to fix this. If `res.rows[i].value` does not exist, we cannot read the id from it.

**Comment by Apollon77** [comment]
ALso the error message is wrong at all because the "res" comes from a "getObjectView" call and not from enums.
So errormessage wpould be more

'Invalid result at Index i returned from getObjectsView'
