### ISSUE TITLE
Let's Encrypt certificates do not work for multiple adapters/hostnames/addresses

### ISSUE THREAD

**Issue by raintonr** [ioBroker/ioBroker.js-controller#2078]
Originally titled: Let's Encrypt settings need bind address to accompany 'Port to check the domain'

Necessary in the scenario where one wants to create a HTTPS server on a private LAN interface but needs to accept Lets Encrypt challenges on a second public LAN interface.

Currently the challenge server starts on the same interface as the main server which will not work in the case above.

A new `settings.leBind` is required?

It *could* be up to the caller to actually set this, but maybe that would be an error? After all, every Let's Encrypt challenge *has* to come via port 80 on a public facing interface. Maybe it should be a system-wide setting (configured in the "Let's Encrypt SSL" tab)? In fact, maybe the `settings.lePort` that is currently set on a per-adapter basis should also be on that page?

**Update:** In fact, after spending a lot of time looking at this I don't see how it is currently possible to have more than one HTTPS instance using LE certificates per IoB host (or at least per public IP address available to said host). 

1. It is possible to uncheck _'Use this instance for automatic certificate update'_ option for an adapter. One would assume that if there is a public facing adapter performing LE certificate issue then they can run a second adapter on a different port, uncheck this option and LE certificate will still be used. This is not the case. If one does not check this box then any HTTPS request to the configured host/port fails with TLS handshake failure.
Ie. _'Use this instance for automatic certificate update'_ option **seems broken** and should never be unchecked anyway.
2. Current Let's Encrypt certificate issue process only seems if work if both the caller (eg. IoB web instance) and server (the Let's Encrypt issuing server) can both access the Challenge Server on port 80 of every domain listed (including subject and altnames).
3. As the Challenge Server *has* to start on port 80 that means only one Challenge Server can run per interface. At least per public interface at that (see point 2.).

When IoB was updated to use Greenlock V4 that was done in a rather quick and dirty way using greenlock-express. I'm beginning to form the opinion that using greenlock-express is not the correct solution for ioBroker as it is a system which may require multiple servers to run possibly using multiple certificates with different hostnames. TBH, I think the whole certificate process probably needs re-working again. Doh!

**Comment by Apollon77** [comment]
yes, in fact we also need an issue for web and all relevant adapters to provide the setting.

**Comment by raintonr** [comment]
I'm not sure about that. I think you miss my point that for (most users there will be...) a single host with a single public facing port that will be mapped to port 80 of their public IP address, so in that case why have a setting in every adapter when a single, global setting will do?

**Comment by raintonr** [comment]
This will be fixed with #2099

**Comment by Apollon77** [comment]
Then we leave open till merged and really done :-)
