### ISSUE TITLE
Let's Encrypt Challenge server should only listen during certificate issue

### ISSUE THREAD

**Issue by raintonr** [ioBroker/ioBroker.js-controller#2079]
As part of the Let's Encrypt certificate issue process a Challenge Server is required. This challenge server must listen on port 80 of a public facing interface.

The current implementation (using [greenlock-express](https://www.npmjs.com/package/greenlock-express)) creates (or tries to create) this Challenge Server on startup of any adapter requiring Let's Encrypt certificates.

This is problematic if one wants to have multiple HTTPS servers, who should all generate their own Let's Encrypt on the same host. This is a valid scenario for me as I have a HTTPS web instance running the Google Fulfilment server on the host's public facing interface, but I would also like to use a Let's Encrypt certificate for a HTTPS server running on a private LAN interface of this host (getting the second private server to start it's Challenge Server on the public interface is a separate issue, see #2078).

If the Challenge Server can be made to listen only when certificate issue is in progress this problem could be overcome.

That aside, it probably isn't great security practice to leave a server listening on port 80 of a public facing interface for longer than necessary anyway.

**Comment by Apollon77** [comment]
Are you really sure? When I remember it is exactly only listening when certificate exchange is in progress ...

**Comment by raintonr** [comment]
Afraid so...

![image](https://user-images.githubusercontent.com/3794098/210106548-80adf7a0-7f30-46d2-9f1d-1e6bd9ea8289.png)

![image](https://user-images.githubusercontent.com/3794098/210106556-2a263485-9a39-4e6a-b5c7-cba66459df12.png)

```
# netstat -anp | grep io.web.1 | grep LISTEN
tcp        0      0 192.168.1.30:8080       0.0.0.0:*               LISTEN      1977/io.web.1       
tcp        0      0 192.168.1.30:8443       0.0.0.0:*               LISTEN      1977/io.web.1
```

Obviously I have port 80 from the public IP address forwarded to 192.168.1.30:8080.

**Comment by Apollon77** [comment]
is it then a topic on our side or with greenlock?

**Comment by raintonr** [comment]
Well, it is code within our `letsencrypt.js` that initiates listen of the Challenge Server soooooo...

Seeing as I wrote that (ahem :wink:) I will look at how to make it only listen during the certificate issue process.

**Comment by raintonr** [comment]
Hmmmmm... this doesn't seem to be supported by greenlock-express v4. I can find reference to handlers in older versions but that seems to have been removed :disappointed:

**Comment by raintonr** [comment]
In fact, I'm going to close this issue. It seems to me like the whole certificate thing needs re-working as mentioned in #2078 so can be tracked there.
