### ISSUE TITLE
leSettings.domains should all be added to Greenlock as altnames?

### ISSUE THREAD

**Issue by raintonr** [ioBroker/ioBroker.js-controller#2080]
Kindof related to #2078 & #2079.

For the scenario I discuss in #2079 of having both public Internet and private LAN facing HTTPS servers with different names... I believe this could be solved if the public facing server always obtained a certificate, that the server name of the private HTTPS server was listed in `altnames` on that certificate and that the private server then used the same certificate.

As this isn't the case right now, seems like an _'Add all domains to a single certificate as altnames'_ option would be necessary on the System Settings -> Let's Encrypt SSL page.

**Comment by raintonr** [comment]
In fact, I notice that this is already possible if one manually edits the settings and creates an array of arrays for `letsEncrypt.domains`. So what is really needed is a change to the admin. Issue opened: https://github.com/ioBroker/ioBroker.admin/issues/1859

**Comment by raintonr** [comment]
Not necessary with https://github.com/iobroker-community-adapters/ioBroker.acme

**Comment by foxriver76** [comment]
Also if I am not using this, I like that it gets some maintainable structure now due to your efforts. Thanks @raintonr
