### ISSUE TITLE
Augment 'Cannot configure secure web server, because no certificates found' message

### ISSUE THREAD

**Issue by raintonr** [ioBroker/ioBroker.js-controller#2081]
For dummies like me who delete their default certs and don't know how to re-create :clown_face: 

Can we please add to the _'Cannot configure secure web server, because no certificates found'_ message:

_'Run 'iobroker cert create' to create default certificates'_

**Comment by foxriver76** [comment]
closed in https://github.com/ioBroker/ioBroker.js-controller/commit/2ac60643e10f3bc17bb5feefa0cb44642c4ecd8d
