### ISSUE TITLE
`config.system` is not always defined

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.js-controller#209]
This leads to an error `TypeError: Cannot read property 'statisticsInterval' of undefined` in
https://github.com/ioBroker/ioBroker.js-controller/blob/2a32f4028a6ae49f4096886ffa1a33c17c16477c/lib/adapter.js#L5196

See failing tests, e.g.
https://ci.appveyor.com/project/Apollon77/iobroker-js-controller/build/test-422/job/n30wd7ovxixgv4qy

**Comment by Apollon77** [comment]
Still open?
