### ISSUE TITLE
jsonwebtoken has insecure input validation in jwt.verify function

### ISSUE THREAD

**Issue by Grothesk242** [ioBroker/ioBroker.js-controller#2095]
Seems to me as if js-controller is affected: 

https://github.com/advisories/GHSA-27h2-hvpr-p74q

Please check and update deps.

**Comment by Apollon77** [comment]
The GitHub version (aka js-controller 5.0) already is updated to 9.0.0. The js.controller 4.0.24 and smaller has vulnerable versions used, BUT the way its is used can not trigger the issue (unless you have already access to the comouter and then it is not longer a topic). Thank you for bringing this up
