### ISSUE TITLE
Please provide more information in system notifications

### ISSUE THREAD

**Issue by Standarduser** [ioBroker/ioBroker.js-controller#2097]
Today I got a restart loop notification in `system.host.srv-iobroker1.notifications.system`-state with this content:
`{"restartLoop":{"count":1}}`
This loop came from the unifi-adapter having problems with a hanging restart of my unifi console.

I would appreciate if there was more information in this notification, e.g. the name of the adapter, to make my telegram notification more useful.

And I wonder why `count` is just `1`. What does this mean? Is `count` the number of restarts (makes no sense) or the number of adapters with restart loop?

**Comment by foxriver76** [comment]
You should get a valid message from the admin adapter with more details. The state is not really meant to be used by users directly. All information are stored on the file system in your data dir should be a `notifications.json`, which you can read if you are interested in doing it right now. Just never modify this file yourself. 

A notification adapter is planned, which handles these notifications and forwards it to message adapters. Probably I am going to implemented it somewhere in the summer if no one is faster.

**Comment by Apollon77** [comment]
>  All information are stored on the file system in your data dir should be a notifications.json, which you can read if you are interested in doing it right now. Just never modify this file yourself.


Better is to send a message to the host controller like admin does ... much better then reading the file :-)

**Comment by foxriver76** [comment]
Yes `getNotifications` message

**Comment by foxriver76** [comment]
Sometimes I forget my own docs https://github.com/ioBroker/ioBroker.js-controller#how-to-read-notifications
