### ISSUE TITLE
Depricate letsencrypt.js in favour of new mechanism that uses collections

### ISSUE THREAD

**Issue by raintonr** [ioBroker/ioBroker.js-controller#2099]
Dependant on #2098.

**Comment by foxriver76** [comment]
We will need some logging in the methods https://github.com/ioBroker/ioBroker.js-controller/blob/master/packages/controller/src/lib/letsencrypt.js and of course publish https://github.com/ioBroker/webserver

**Comment by raintonr** [comment]
Done with https://github.com/ioBroker/webserver certificate manager.
