### ISSUE TITLE
[1.5] Backup/Restore adapter files

### ISSUE THREAD

**Issue by kirovilya** [ioBroker/ioBroker.js-controller#216]
In adapter (ioBroker.zigbee) I need persistent-store file for work.
I put this file in adapters-data directory:
```
var dbDir = utils.controllerDir + '/' + adapter.systemConfig.dataDir + adapter.namespace.replace('.', '_');
```
And it need to be backup/restore with other ioBroker files.

**Comment by Apollon77** [comment]
I just wonder: Is this really the correct place?
Other adapters that needed tomatier files do this in iobroker-data directory. 
Or where this path is located at the end?

**Comment by kirovilya** [comment]
May be I am choose wrong place ...
adapter.systemConfig.dataDir - is iobroker-data directory. then added directory with instance name and there put files.
https://github.com/ioBroker/ioBroker.zigbee/blob/master/main.js#L642

**Comment by Apollon77** [comment]
Hehe I use the same I think, only a different function to get it :-)
But yes, Backup would be great

**Comment by GermanBluefox** [comment]
https://github.com/ioBroker/ioBroker.js-controller/commit/345efc1e4ee65dff5d0680ce927609db17b8325a

**Comment by GermanBluefox** [comment]
let parts = tools.getConfigFileName().split('/');
parts.pop();
let configPath = parts.join('/');

**Comment by Apollon77** [comment]
When I understand correctly then this is already in 1.5.
Adapter need to provide common.dataFolder and then this folder is included in the backup.
Need to verify

**Comment by kirovilya** [comment]
I checked it last year :) with js-controller 1.5
https://github.com/ioBroker/ioBroker.zigbee/blob/master/io-package.json#L105
it is working

**Comment by Apollon77** [comment]
cool thank you, then we only need to check if we need to add it to some docs or if this was also done :-)

--> https://github.com/ioBroker/ioBroker/wiki/Adapter-Development-Documentation#structure-of-io-packagejson

**Comment by GermanBluefox** [comment]
The description is here: https://github.com/ioBroker/ioBroker/blob/master/doc/SCHEMA.md#adapter

**Comment by AlCalzone** [comment]
> 
> 
> let parts = tools.getConfigFileName().split('/');
> parts.pop();
> let configPath = parts.join('/');

```js
const path = require("path");
const configPath = path.basename(tools.getConfigFileName());
```
