### ISSUE TITLE
[2.0.0] Letsencrypt via CLI, Show & update

### ISSUE THREAD

**Issue by GermanBluefox** [ioBroker/ioBroker.js-controller#222]
Make it possible directly from iob cli to show the information about letsencrypt and to update the certificates.

iobroker le    - iobroker letsencrypt
iobroker le update

**Comment by Apollon77** [comment]
Do we need to do this for 2.0.0 or will we postpone to 2.1? @GermanBluefox

**Comment by AlCalzone** [comment]
When we do, we should probably include it in the `cert` command @Stabilostick  added a while ago

**Comment by Apollon77** [comment]
I postpone it now

**Comment by Apollon77** [comment]
@GermanBluefox What do we do here? Update Lets encrypt or kill it?

**Comment by GermanBluefox** [comment]
We must try. If too complex, then kill.

**Comment by foxriver76** [comment]
we now have `cert view` which shows the cert so we would only need to add an update command, now where it is working again

**Comment by Apollon77** [comment]
But honestly I'm nore sure that LE really updtes the certs object or if that uses it's own storage ... so maybe more

**Comment by foxriver76** [comment]
As acme adapter now does this stuff we likely don't need it in controller anymore or?
