### ISSUE TITLE
Windows: A call of ioBroker.js with parameters start, stop and restart does not work properly

### ISSUE THREAD

**Issue by Gaspode69** [ioBroker/ioBroker.js-controller#2221]
If ioBroker is started under Windows as a service (which is the dfault installation), ioBroker.js does not work as I would expect.

`node node_modules/iobroker.js-controller/iobroker.js stop`
seems to have no effect at all and displays ...
"iobroker controller daemon is not running"
If ioBroker was not started as a service, ioBroker is stopped properly.

`node node_modules/iobroker.js-controller/iobroker.js stop`
displays ...
"Starting iobroker controller daemon..."
... even if ioBroker is already running as a service. In some cases the service is stopped after a few seconds because of a port conflict.
If the according Windows service is not running, ioBroker is started, but NOT the according Windows Service.

Restart behaves like a combination of stop and start including the same problems if ioBroker is already running as a windows service.

With PR https://github.com/ioBroker/ioBroker/pull/441 this should be no real problem, because under Windows consequently calls of start stop and restart are forwarded to the windows service. and ioBroker.js start/stop/restart is not used anyway.

**Comment by foxriver76** [comment]
On a first glance, yes it would be best, if the bat file can handle it like it is done for Linux https://github.com/ioBroker/ioBroker/blob/d00a5641516995aa912ab73e428454a389b3ea44/installer.sh#L182. For Linux the command is not forwarded to iobroker.js for a while now, we should decide if we can remove the whole handling for both oses from the js code after the PR is merged and widely used.

**Comment by Apollon77** [comment]
SOrry, can't remember ... whats status here @Gaspode69 ?

**Comment by Gaspode69** [comment]
As far as I remember @foxriver76 implemented the changes as described here (https://github.com/ioBroker/ioBroker/blob/d00a5641516995aa912ab73e428454a389b3ea44/installer.sh#L182):

For systems with js-controller 5:
    controller will not add any bat files anymore - only installer package does
    controller assumes iob.bat to be there and use this on restarts
    Means: With the release of conteoller 5 to stable to can also remove iobroker.bat from installer

So from my point of view, this issue can be closed as soon as Controller 5 ist released and iobroker.bat is removed from https://github.com/ioBroker/ioBroker/blob/master/lib-npx/installSetup.js
