### ISSUE TITLE
Missing line break hides feature CONTROLLER_MULTI_REPO

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.js-controller#2229]
https://github.com/ioBroker/ioBroker.js-controller/blob/06227a927134448afdbb30908b1df8cae3017b76/packages/adapter/src/lib/adapter/constants.ts#L28

Should be

```
'CONTROLLER_LICENSE_MANAGER', // Controller can read licenses from iobroker.net. Since js-controller 4.0    
'CONTROLLER_MULTI_REPO', // Controller supports multiple repositories
```

EDIT: `CONTROLLER_MULTI_REPO` is already in the line above `CONTROLLER_LICENSE_MANAGER`. Not an issue. Just remove the comment

**Comment by Apollon77** [comment]
uuups, thank you!
