### ISSUE TITLE
[2.0.0] fix "npm audit" problems and outdated dependecies (if possible)

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#223]
npm audit reports:

found 33 vulnerabilities (25 low, 8 high)
  run `npm audit fix` to fix them, or `npm audit` for details

We should analyze and fix them

**Comment by Apollon77** [comment]
First status: see already done testwise in https://github.com/Apollon77/ioBroker.js-controller/tree/update-deps

To clarify is how we proceed with the jscs based grunt stuff because jscs got discontinued in favor of eslint

**Comment by Apollon77** [comment]
Ref: #243

**Comment by Apollon77** [comment]
Closing this because done in the referenced subtasks for details

**Comment by GermanBluefox** [comment]
https://github.com/ioBroker/ioBroker.js-controller/commit/7951af55d0dba04ee951f7868428b33796ee3073
