### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by tipp88** [ioBroker/ioBroker.js-controller#2253]
Not 100% sure if it fits to js-controller but I have random crashes which I can't explain and not able to figure out the root cause. It happens fairly every 24h at least once. There is no special activity and the time varies through the day. 
![image](https://github.com/ioBroker/ioBroker.js-controller/assets/68737433/de3cded0-296e-46c1-9d79-46e067a0e2a6)

13:31 the system stops reacting after starting js-controller again. No access to Iobroker anymore, no SSH possible. Nothing 
Not sure why the system here seems to "start" even if was running. 
13:52 I unplugged the raspberry from electricity and plugged it again to restart and get back to work. 

Somebody have any ideas?

also attaching here the full log because the timing in this log is quite strange and time series does not match....
![image](https://github.com/ioBroker/ioBroker.js-controller/assets/68737433/75babfa3-1bdd-4ea2-aad3-c4b7d8a1ecac)

**Comment by Apollon77** [comment]
No this error looks clear like a crash and reboot of the whole host ... why ... because of the time jumps back in the logs.

So please check /var/log/syslog in these timepoints and timeframes. But in general -> Forum topic!
