### ISSUE TITLE
[2.0.0] setObject/setObjectNotExists do not set default value of state

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#228]
While developing the alexa2 adapter I saw a unexpected behaviour: Also when setting a default value for an object on creation this value was mostly not set/shown in Admin (also not after reload).

Reason: The whole handling for default value in only in "createState" method. setObject and extendObject (which is used more often by adapters!) do not have this logic at all.

1.) https://github.com/ioBroker/ioBroker.js-controller/blob/master/lib/adapter.js#L2236

Should we change this?

**Comment by GermanBluefox** [comment]
Yes. It sounds reasonable

пт, 20 июл. 2018 г., 13:37 Ingo Fischer <notifications@github.com>:

**Comment by Apollon77** [comment]
I will try to prepare a PR to check it.

**Comment by Apollon77** [comment]
fixed by https://github.com/ioBroker/ioBroker.js-controller/commit/d348b9d02ebc05e7c917da3e78f81fae6f504cdf
