### ISSUE TITLE
[1.5? Fixed?] Always check/recreate objects for all system.adapter.X objects/states

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#229]
sometimes these objects are missing. Need to fix the the same way as we didi with instanceObjects

**Comment by stabilostick** [comment]
I second this.

**Comment by Apollon77** [comment]
I think this is already taken care in 1.5 ... need to verify

**Comment by GermanBluefox** [comment]
These objects will be created by upload and not by every start. 
I think this is not required to be called by EVERY start if the user see the problem he can just call upload from CLI or from admin.
This is not normal and happens very seldom (e.g. I have never see that)

**Comment by Apollon77** [comment]
1.5.7 is released, so I close here
