### ISSUE TITLE
Decline setState when object is not existing

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#230]
we should prevent a state from being set in state db when object is not existing.

**Comment by Apollon77** [comment]
But we need to think about it because we have many "bad" adapters where setObject and setState are called parallel without caring about asynchronity and they allwould break partially ... So maybe add warnings first so that adapter developers can fix it?

**Comment by Apollon77** [comment]
Then the main question is where do we get the info about the object from?
Do the State-DB classes (Mem+Redis) need to have an info on existing objects? I think Mem can have already, but Redis has not really, or?

**Comment by stabilostick** [comment]
Use objects.pushAll to provide in-memory filter list in the redis/in-memory client. Therefore subscribe states-client to objects-db. Possibility to check every get/set state event on object key existance. Possibility to delete states automatically when state-keys not in filter list. Possibility to generate automatically states for objects with default values.

**Comment by Apollon77** [comment]
see also #268/#203

**Comment by Apollon77** [comment]
I would only implement that in adapter.js, there we have states and objects available. This means the only decision left is a performance decision - do we really want to read the object any time before setting a state? Or we need to cache all objects ... also not nice.

So depending on these pitfalls ... what do we want ;-)

**Comment by foxriver76** [comment]
For redis `exists` would be a more performant option compared to reading the JSON

**Comment by foxriver76** [comment]
Basically we have a warning from now on if Adapter is not explicitly started with `strictObjectChecks: false`, we could decline later but let’s first try with a warning. I would close this issue for now.

**Comment by Apollon77** [comment]
agreed
