### ISSUE TITLE
[TOOLING] Enable production release with active branch protection policy

### ISSUE THREAD

**Issue by foxriver76** [ioBroker/ioBroker.js-controller#2300]
My latest thoughts go into a direction like: 

1. Implement a GH action with workflow dispatch (one for `patch`, `minor` and `major`)
2. In the action: Execute release script, without pushing anything, version bump according to the triggered dispatch
3. We need to add our custom io-pack translation with `see CHANGELOG.md` in all languages, because release script would try to translate the whole CHANGELOG. Maybe we can also add a option to release script to use a passed parameter to translate.
4. Go on just like our current actions workflow -> add label for auto merging
5. After tests are passed on the PR, `publish`, `GH release` + `merge`

Thoughts on this @AlCalzone @Apollon77

**Comment by Apollon77** [comment]
make sense ... and needs to work main and also version branches
