### ISSUE TITLE
Bcontrol showing error after installing host controller 5.0.5

### ISSUE THREAD

**Issue by looxer01** [ioBroker/ioBroker.js-controller#2307]
Hi,
I have received the below error log for B-Control after installing controller version 5.0.5. 
I have tried iobroker fix and a B-Control Rebuild but the issue remained. 
Most likely adapter related. I have created an issue for the adapter as well. 
https://github.com/ioBroker/ioBroker.b-control-em/issues/13

`
<html><body>

host.RR-DEB-iOB | 2023-06-18 21:52:33.681 | error | instance system.adapter.b-control-em.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | --
host.RR-DEB-iOB | 2023-06-18 21:52:33.680 | error | Caught by controller[0]: Node.js v18.16.0
host.RR-DEB-iOB | 2023-06-18 21:52:33.680 | error | Caught by controller[0]: }
host.RR-DEB-iOB | 2023-06-18 21:52:33.680 | error | Caught by controller[0]: ]
host.RR-DEB-iOB | 2023-06-18 21:52:33.680 | error | Caught by controller[0]: '/opt/iobroker/node_modules/iobroker.b-control-em/main.js'
host.RR-DEB-iOB | 2023-06-18 21:52:33.680 | error | Caught by controller[0]: '/opt/iobroker/node_modules/iobroker.b-control-em/lib/utils.js',
host.RR-DEB-iOB | 2023-06-18 21:52:33.680 | error | Caught by controller[0]: requireStack: [
host.RR-DEB-iOB | 2023-06-18 21:52:33.680 | error | Caught by controller[0]: code: 'MODULE_NOT_FOUND',
host.RR-DEB-iOB | 2023-06-18 21:52:33.680 | error | Caught by controller[0]: at Module.require (node:internal/modules/cjs/loader:1141:19) {
host.RR-DEB-iOB | 2023-06-18 21:52:33.680 | error | Caught by controller[0]: at Module._load (node:internal/modules/cjs/loader:958:12)
host.RR-DEB-iOB | 2023-06-18 21:52:33.680 | error | Caught by controller[0]: at Module.load (node:internal/modules/cjs/loader:1117:32)
host.RR-DEB-iOB | 2023-06-18 21:52:33.680 | error | Caught by controller[0]: at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
host.RR-DEB-iOB | 2023-06-18 21:52:33.680 | error | Caught by controller[0]: at Module._compile (node:internal/modules/cjs/loader:1254:14)
host.RR-DEB-iOB | 2023-06-18 21:52:33.680 | error | Caught by controller[0]: at Object. (/opt/iobroker/node_modules/iobroker.b-control-em/lib/utils.js:60:25)
host.RR-DEB-iOB | 2023-06-18 21:52:33.680 | error | Caught by controller[0]: at require (node:internal/modules/cjs/helpers:110:18)
host.RR-DEB-iOB | 2023-06-18 21:52:33.680 | error | Caught by controller[0]: at Module.require (node:internal/modules/cjs/loader:1141:19)
host.RR-DEB-iOB | 2023-06-18 21:52:33.680 | error | Caught by controller[0]: at Module._load (node:internal/modules/cjs/loader:920:27)
host.RR-DEB-iOB | 2023-06-18 21:52:33.680 | error | Caught by controller[0]: at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
host.RR-DEB-iOB | 2023-06-18 21:52:33.680 | error | Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.b-control-em/main.js
host.RR-DEB-iOB | 2023-06-18 21:52:33.680 | error | Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.b-control-em/lib/utils.js
host.RR-DEB-iOB | 2023-06-18 21:52:33.680 | error | Caught by controller[0]: Require stack:
host.RR-DEB-iOB | 2023-06-18 21:52:33.680 | error | Caught by controller[0]: Error: Cannot find module '/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js'
host.RR-DEB-iOB | 2023-06-18 21:52:33.680 | error | Caught by controller[0]: ^
host.RR-DEB-iOB | 2023-06-18 21:52:33.680 | error | Caught by controller[0]: throw err;
host.RR-DEB-iOB | 2023-06-18 21:52:33.680 | error | Caught by controller[0]: node:internal/modules/cjs/loader:1078
host.RR-DEB-iOB | 2023-06-18 21:52:33.523 | info | instance system.adapter.b-control-em.0 started with pid 4103188

</body>
</html>
`

**Comment by Apollon77** [comment]
Adapter needs to update adapter-code dep
