### ISSUE TITLE
Probleme mit UI Upgrade und inoffiziellem Docker Container

### ISSUE THREAD

**Issue by dontobi** [ioBroker/ioBroker.js-controller#2309]
Mit dem Update auf JS-Controller 5.0.5 startet mein Docker Container nicht mehr. Folgende Fehlermeldung wird im Log angezeigt: 
```
/opt/iobroker/node_modules/@iobroker/js-controller-common/node_modules/semver/classes/semver.js:38
--
  | throw new TypeError(`Invalid Version: ${version}`)
  | ^
  | TypeError: Invalid Version:
  | at new SemVer (/opt/iobroker/node_modules/@iobroker/js-controller-common/node_modules/semver/classes/semver.js:38:13)
  | at compare (/opt/iobroker/node_modules/@iobroker/js-controller-common/node_modules/semver/functions/compare.js:3:3)
  | at Object.lt (/opt/iobroker/node_modules/@iobroker/js-controller-common/node_modules/semver/functions/lt.js:2:29)
  | at isControllerUiUpgradeSupported (/opt/iobroker/node_modules/@iobroker/js-controller-common/build/lib/common/tools.js:364:30)
  | at getSupportedFeatures (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/utils.js:23:53)
  | at new AdapterClass (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:104:68)
  | at startAdapter (/opt/iobroker/node_modules/iobroker.admin/main.js:55:15)
  | at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.admin/main.js:1208:5)
  | at Module._compile (node:internal/modules/cjs/loader:1254:14)
  | at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
  | Node.js v18.16.0
  | ================================== > LOG REDIRECT system.adapter.admin.0 => false
```

**Comment by foxriver76** [comment]
Ist das die Fehlermeldung die du bekommst nachdem du manuell das .thisisdocker File angelegt hast oder ist das die Initiale ohne Veränderung?

**Comment by dontobi** [comment]
Das müsste die ohne Veränderung gewesen sein.

**Comment by foxriver76** [comment]
Kannst du das bitte nochmal sicherstellen? Wäre sehr unerwartet codeseitig ...

**Comment by dontobi** [comment]
Ich prüfe es die Tage nochmal. Möglicherweise gab es auch einen Code Rest, als ich Mal den offiziellen Container genutzt habe. Das müsste zu Zeiten von Version 6 gewesen sein.

**Comment by dontobi** [comment]
Ich habe das noch einmal nachgestellt. Die Datei "/opt/scripts/.docker_config/.thisisdocker" war angelegt und es stand der Wert v7.0 darin.

Ich hatte die Datei dann mit v8.0 überschrieben und schon ging alles.

**Comment by buanet** [comment]
@dontobi
Statt den offiziellen Docker Container zu kopieren, zu modifizieren und unter mind. 90% unveränderten Codes deinen Namen zu schreiben, hättest du lieber forken sollen. Das wäre nicht nur ehrlicher sondern würde auch dafür sorgen, dass du Weiterentwicklungen einfach im Code verfolgen könntest...

Es wird auch in Zukunft immer Entwicklungen geben, die du neu "erfinden" oder manuell aus dem offiziellen Image klauen müsstest. So wie es jetzt mit dem Feature zum Update des js-controllers aus der Admin UI heraus ist bzw. sein wird. 

Außerdem würde ein Fork nicht nur in eine Richtung funktionieren, sodass ggf. auch das offizielle Image und all seine rund 11.000 User von deinen Verbesserungen im Code oder neuen Features profitieren könnten. 


MfG,
André

PS: Wäre übrigens auch schick wenn du Issues schließt, wenn wieder alles funktioniert. Danke.

**Comment by buanet** [comment]
@foxriver76 
Wie im Dev Chat besprochen.
js-controller crasht wenn das Format der Version nicht passt. Ich schlage vor dass wir eventuelle Fehler von semver abfangen und behandeln als sei die version zu klein. Was meinst du?

MfG,
André

**Comment by dontobi** [comment]
@buanet Mir tut es leid, dass es für dich danach aussieht, dass ich Code klaue und ja, ein Fork ist besser. Zur damaligen Zeit wusste ich es einfach nicht besser, da ich nicht so viel Ahnung über GitHub hatte. Ich werde daher heute einen Fork anlegen und meine Änderungen einpflegen. Ob ich dann einen PR durchführe, stelle ich noch in Frage. Denn vor etwas mehr als 2 Jahren hatte ich mit dir in Discord über ein paar Änderungen am Docker Container geschrieben und du hattest mir damals das Gefühl gegeben, dass meine Änderungen nicht erwünscht sind. Daher habe ich auch an meiner Container Variante weiter gemacht. Inzwischen hast du einen Teil meiner damaligen Vorschläge hinzugefügt und der Container ist daher auch so ziemlich deckungsgleich.

Die Frage aus deinem PS musst du mir allerdings erklären. Meinst du dieses Issue oder ein anderes?

**Comment by buanet** [comment]
@dontobi
Das PS hat sich mittlerweile erledigt und war auf diesen Issue bezogen. Es ist zwar so, dass das Problem auftrat, weil das Format der Version im .thisisdocker-File in deinem speziellen Fall nicht gestimmt hat (kein Semantic Versioning), aber dass der js-controller deshalb nicht startet ist in der Tat verbesserungswürdig...

Wenn das übrigens damals im persönlichen Gespräch so rüber gekommen ist, dass ich deine Verbesserungsvorschläge ablehne, dann tut es mir leid. Ich hatte nicht das Gefühl und habe es nach überfliegen unserer alten Konversation im Discord auch heute nicht. Grundsätzlich finde ich von dir aber auch kein Issue oder PR im Repo des Docker Images, den wir in der Community hätten besprechen können...

MfG,
André

**Comment by dontobi** [comment]
@buanet Okay. Dann war es ein Missverständnis auf beiden Seiten. Ich bin gerade dabei den Fork zu bespielen und würde dann ggf. ein paar PR's einstellen. Und ich möchte dich und auch das ioBroker Projekt unterstützen!
