### ISSUE TITLE
SyntaxError: Unexpected token '<', "<!doctype "... is not valid JSON

### ISSUE THREAD

**Issue by Anzic23** [ioBroker/ioBroker.js-controller#2310]
when updating via admin. The current version of js controller is 5.0.3. The controller version I am updating to is 5.0.5
Admin - 6.5.8
docker container v8.0.1
web ui works through reverse proxy

**Comment by foxriver76** [comment]
Ui Upgrades for official iobroker Docker will only work correctly from 5.0.5 on

**Comment by rovo89** [comment]
Still getting the same issue when attempting to upgrade from 5.0.5 to 5.0.7. Also behind a reverse proxy. Official Docker image v8.0.1 from 2023-04-26T23:45:44+00:00. Can I get logs somehow?

Unfortunately, I can't reopen this issue myself, so pinging @foxriver76 @buanet.

**Comment by ice987987** [comment]
please wait for ioBroker.js-controller v5.0.8 (with pre-installed ioBroker.admin v6.6.0, ioBroker.js-controller v5.0.7 and ioBroker.docker v8.1.0-beta.3).

reference: https://forum.iobroker.net/topic/66108/js-controller-5-0-x-jetzt-in-der-beta/381?_=1689075561330

**Comment by buanet** [comment]
What @ice987987 said.

minimal Docker Image v8.1.0-beta.3
minimal js-controller v5.0.7
minimal admin (not sure)

So first working update will be js-controller  v5.0.7 > v5.0.8.

Regards,
André

**Comment by rovo89** [comment]
Thanks! Should have checked the forum before ;) I'll manually upgrade again and see if it works for the 5.0.8 upgrade.
