### ISSUE TITLE
js-controller beta nicht erkennbar - wie geht ein Downgrade?

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.js-controller#2313]
Hallo allerseits,
ich habe zwar das Beta-Repo installiert hätte aber vermutlich vom js-controller die Finger gelassen, wenn ich erkannt hätte, das es eine Beta ist. Nun gehen einge Adapter nicht mehr - am meisten schmerzt Zigbee. Ich bin auf 5.05

Es soll einen Fix geben .. aber auch beim durchscrollen hab ich diesen nicht erkannt.

Wie könnte ich denn ein Downgrade zurück zur stable machen?

VG

**Comment by mcm1957** [comment]
Schau mal ins Forum. Im entsprechenden Thread hat Ingo alles sehr ausführlich beschrieben.

Und LATEST IST BETA. Das gilt für alle Adapter und wird dir beim Aktivieren auch angezeigt. Was überrascht dichvdass etwas im Latest = Beta Repo im Ststus Beta ist ???

**Comment by daniel-lo** [comment]
Naja .. den Haken hatte ich vor Jahren gesetzt und nie probleme damit gemacht. Wenn hinter der Version ein B gestanden hätte .. hätte ich den JS-Controller vermutlich nicht geupdated. Downgrade schau ich mir an .. danke!

**Comment by mcm1957** [comment]
Auch wenn du das Repo vor Jahren auf latest gesetzt hast, solltest du derzeit bei jedem Öffnen der Admin Seite eine Wanrung sehen:
![image](https://github.com/ioBroker/ioBroker.js-controller/assets/28575778/f7537d21-4af9-47e8-99b4-6fcad994d5b1)

**Comment by daniel-lo** [comment]
Die Zeile ist da .. aber irgendwann sieht man sie nicht mehr. Bei Adaptern ist mir das auch egal .. die kann ich selbst zurückrollen wenn es mal hakt. Risiko bei Adaptern also akzeptiert.

**Comment by Apollon77** [comment]
So oder so ... beta Repo === Beta tester. Sorry, bitte dann selbst auch beim js.controller daran denken!

**Comment by daniel-lo** [comment]
Hab's ja schon verstanden.

**Comment by daniel-lo** [comment]
@mcm1957 

Hi all .. ihr schreibt alle sowas wie "steht doch alles im Forum" (diesmal Downgrade) und ich suche mich immer blöd. Finde auf oben verlinkter Seite die Info wie man nochmalinstalliert und dass beim Downgrade einige Adapter vielleicht nicht mehr kompatibel sind .. aber zum eigentlichen Downgrade nichts. Dit hier hat auch nicht gefunzt:

npm i iobroker.js-controller@4.0.24 --production

Sobald mein Zigbee wieder läuft stelle ich gerne auf stable.

Help .. bitte

**Comment by foxriver76** [comment]
Hat nicht gefunzt ist keine Fehlermeldung, da kann leider keiner helfen und Support bitte eher im Forum thread falls du einen Account hast ;-)

**Comment by daniel-lo** [comment]
npm install iobroker.js-controller@4.0.24

Hat funktioniert (hab die Stelle in Ingos Text gefunden)

danke!
