### ISSUE TITLE
TypeScript STATE_QUALITY has missing values

### ISSUE THREAD

**Issue by jpawlowski** [ioBroker/ioBroker.js-controller#2319]
The values for STATE_QUALITY in `packages/types-dev/index.d.ts` seem outdated, for example, one could receive the following TypeScript error:

`Type '64' is not assignable to type 'StateQuality | undefined'.`

I think the values in

https://github.com/ioBroker/ioBroker.js-controller/blob/cb37f861bad680e99f9d340f2e77b7543f5d6af8/packages/types-dev/index.d.ts#L17-L48

shall be updated with values from

https://github.com/ioBroker/ioBroker.docs/blob/6cf3906bc43bd3b31821902c78abd8babe4f93d3/docs/en/dev/objectsschema.md?plain=1#L133-L153

As an example, I had to ignore the TS errors like this https://github.com/jpawlowski/ioBroker.residents/commit/71d2e5db07039c1eb2d5f2031caee885eb64b9a4

**Edit:**
I noticed that the value `0x41` I am using in my adapter is already in there, but it is not available to TypeScript during my development it seems. I had updated js-controller to version 5.0.5, what else is missing here?

**Comment by foxriver76** [comment]
Thanks for the report. The types are currently still used from official `@types` package. During the next days, we will try to publish the types for the new controller version. I will let you know as soon as this is the case.

**Comment by foxriver76** [comment]
fixed with `@iobroker/adapter-core` v3
