### ISSUE TITLE
type failure: await this.mkdirAsync()

### ISSUE THREAD

**Issue by Schmakus** [ioBroker/ioBroker.js-controller#2321]
type failure: await this.mkdirAsync()
=> Die Eigenschaft "mkdirAsync" existiert nicht für Typ "Doorbird". Meinten Sie "mkDirAsync"?
but, it works! Only IDE failure.
mk**D**irAsync not working!

controller 5.x

**Comment by foxriver76** [comment]
Wird auch da sein nach types Umstellung. Ist bereits korrekt im Controller

**Comment by foxriver76** [comment]
fixed with `@iobroker/adapter-core` v3
