### ISSUE TITLE
[2.0.0] Make NPM warning MORE DRAMATIC!

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.js-controller#233]
:ghost: https://forum.iobroker.net/viewtopic.php?p=166453#p166453 :ghost: 

When I read this, I believe the warning for an unsupported npm version should be more dramatic and outline what happens when continuing to work with that unsupported version.

**Comment by AlCalzone** [comment]
Actually, the installation should be prevented. Not sure atm why it isn't.

**Comment by foxriver76** [comment]
Isn't this already implemented for adapters in https://github.com/ioBroker/ioBroker.js-controller
/blob/c8dd935eb683f6708c27d51f0034b01dc03c8352/lib/setup/setupInstall.js#L308 to prevent adapter installation and upgrades via iobroker CLI (and admin).
![bildschirmfoto von 2018-10-17 22-10-52](https://user-images.githubusercontent.com/25484431/47113520-921b8700-d259-11e8-819b-dd029252c474.png)
![bildschirmfoto von 2018-10-17 22-07-43](https://user-images.githubusercontent.com/25484431/47113523-947de100-d259-11e8-8809-4389d4bbff5b.png)

Just should exit the process on the js-controller installation ttps://github.com/ioBroker/ioBroker.js-controller/blob/c8dd935eb683f6708c27d51f0034b01dc03c8352/lib/preinstallCheck.js#L52 and installation of adapters via github (https://github.com/ioBroker/ioBroker.js-controller/blob/c8dd935eb683f6708c27d51f0034b01dc03c8352/lib/setup.js#L697) isn't prevented yet.

I would implement it, but I am not familiar with the process exit codes. Can I read somewhere about them?

**Comment by GermanBluefox** [comment]
https://github.com/ioBroker/ioBroker.js-controller/blob/master/controller.js#L53

If you case is not described, just create new exit code and place it there.


Max Hauser <notifications@github.com> schrieb am Mi., 17. Okt. 2018, 22:18:

**Comment by foxriver76** [comment]
Thanks, 25 was already used for unsupported NPM version. So I would have to add a lot of empty entries to increment up to 25. But I've seen that it's also on the agenda to add the meanings of the error codes in https://github.com/ioBroker/ioBroker.js-controller/issues/236
