### ISSUE TITLE
Updating js-controller from 5.0.8 to 5.0.10 seems to crash iOBroker

### ISSUE THREAD

**Issue by MichaelSchaaf999** [ioBroker/ioBroker.js-controller#2369]
Systems stops and looks like on hold or frozen

<img width="698" alt="grafik" src="https://github.com/ioBroker/ioBroker.js-controller/assets/53481090/6f3eff4e-ffeb-4a4b-a829-faab68a29765">

Only a reboot of the iOBroker fixes this and iOBroker then is restarting and running as normal.
But no update to 5.0.10 has happened.
What else can I provide?

**Comment by foxriver76** [comment]
How has the upgrade been started? UI upgrade from 5.08/5.0.9 to xx won’t work

**Comment by MichaelSchaaf999** [comment]
Upgrade is offered here:
<img width="885" alt="grafik" src="https://github.com/ioBroker/ioBroker.js-controller/assets/53481090/f30e54e4-e9ba-4756-a8f3-f22d7bb54d6c">

**Comment by foxriver76** [comment]
Yes won’t work. Use classical way via cli

**Comment by MichaelSchaaf999** [comment]
Is Theresa description somewhere, Max?
And: Is it a known bug or something new? Just asking. IOB kind of invites to start the „elegant“ way of upgrade.

Michael Schaaf | +49 172 5233633 | ***@***.***
________________________________
Von: Max Hauser ***@***.***>
Gesendet: Sunday, July 30, 2023 2:57:12 PM
An: ioBroker/ioBroker.js-controller ***@***.***>
Cc: MichaelSchaaf999 ***@***.***>; Author ***@***.***>
Betreff: Re: [ioBroker/ioBroker.js-controller] Updating js-controller from 5.0.8 to 5.0.10 seems to crash iOBroker (Issue #2369)


Yes won’t work. Use classical way via cli

**Comment by foxriver76** [comment]
No. It is broken in 5.0.8/5.0.9 will work with 5.0.10 again.

**Comment by foxriver76** [comment]
Ah Description is not shown in admin when it detects the ui upgrade support. So yes here https://forum.iobroker.net/topic/66108/js-controller-5-0-x-jetzt-in-der-beta


Basically stop the iobroker and `iob upgrade self`

**Comment by MichaelSchaaf999** [comment]
Thanks a lot Max!

I went for npm install iobroker.js-controller@5.0.10
and after that executed
iobroker stop
cd /opt/iobroker
iob upgrade self
iobroker start

and the result was:
<img width="989" alt="image" src="https://github.com/ioBroker/ioBroker.js-controller/assets/53481090/102cd85f-3eea-4b96-b6d1-2cce55049513">

Then I went for the 5.0.11:
<img width="989" alt="image" src="https://github.com/ioBroker/ioBroker.js-controller/assets/53481090/cc57c0a3-5da9-488c-9680-86b927328e8c">

and the UI upgrade was fine then:
<img width="670" alt="image" src="https://github.com/ioBroker/ioBroker.js-controller/assets/53481090/50ea4820-b26a-4182-ad26-41a3b160877d">

<img width="991" alt="image" src="https://github.com/ioBroker/ioBroker.js-controller/assets/53481090/58a1845b-50ab-4d90-80dd-333fa2e205c5">

So thanx a lot for your support here!
