### ISSUE TITLE
ioBroker Controller now needs a file extension

### ISSUE THREAD

**Issue by jogibear9988** [ioBroker/ioBroker.js-controller#2381]
I used "writeFile64" from frontend with a filename without extension. this worked in older versions, now it does not any more. 

think cause of this: https://github.com/ioBroker/ioBroker.js-controller/blob/9e43acaaca6df81d5d098812898d743fddb329c3/packages/db-objects-redis/src/lib/objects/objectsInRedisClient.ts#L1056

the readFile api works also without extension (so I could still read my old written files)

Maybe both Apis shold behave the same?

Maybe a better error would be nice, wich indicates that you miss a file name extension?
Maybe remove the check, so it also works without a extension?

Also if I add a extension to the filename ('.screen'), the current reading code breaks, cause the data is transfered diffeently:
<img width="1018" alt="image" src="https://github.com/ioBroker/ioBroker.js-controller/assets/364896/ed62fa28-ec4e-4708-926e-5140b99519af">
(Array index 1 is the file now with extension...)

**Comment by jogibear9988** [comment]
My code (wich worked in a older controller, i think version 4):

[        const screenPromises = screenNames.map(x => this.connection.readFile(this.adapterName, this.configPath + "screens/" + x, false))](https://github.com/iobroker-community-adapters/ioBroker.webui/blob/45243fd9c8c86457847f43de29bde1f025ff81df/src/IobrokerHandler.ts#L46)

**Comment by Apollon77** [comment]
according to @jogibear9988 it works with this change: https://github.com/iobroker-community-adapters/ioBroker.webui/commit/efb9238c5742f83e863181cc2775c6000d1569a9

So @foxriver76: Is enforcing an extension on write a bug or a feature? ;-)

**Comment by foxriver76** [comment]
> now it does not any more

Does it throw or log any error? At least in backend the read write api should be compatible to each other. But maybe we have no tests without file extension I can look next week.

**Comment by mcm1957** [comment]
See tg discussion here
https://t.me/ioBroker_development/29745

**Comment by foxriver76** [comment]
> See tg discussion here
> https://t.me/ioBroker_development/29745

Please relevant details here in issue I don’t want to read through 50 messages to get one line of information which issue creator already knows 😬

**Comment by jogibear9988** [comment]
Without a extension you get an error on the write, you get exactly the error I linked: Invalid name "${name}" on _writeFile

**Comment by jogibear9988** [comment]
If you use a extension, the read api behaves complete differently. Befor I got back a string in the "file" property, wich I could bas64 decode. If I now use a extension, the file property is now a object, containing a buffer in the data property of the file object

**Comment by foxriver76** [comment]
> Without a extension you get an error on the write, you get exactly the error I linked: Invalid name "${name}" on _writeFile

Ah thanks one line below the preview. I will check

**Comment by foxriver76** [comment]
> If you use a extension, the read api behaves complete differently. Befor I got back a string in the "file" property, wich I could bas64 decode. If I now use a extension, the file property is now a object, containing a buffer in the data property of the file object

Yes, basically the mine type is determined from the extension and this is now a bit more fine granular. AFAIK The logic is that for non text types binary data is returned if mime type ist text, then string, this is intended.
