### ISSUE TITLE
[docu] packages/controller/doc/classes/AdapterClass.md is broken near setstate

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker.js-controller#2385]
Documentation  is OK until setObject
https://github.com/ioBroker/ioBroker.js-controller/blob/master/packages/controller/doc/classes/AdapterClass.md#setobject

Bute after this everything is part of an code example. So i.e. setState id not reachable using index

As I assume this docu is generated, I created this issue. If a simple docu PR is useful, please let me know, I can check whats wrong with md file.

**Comment by foxriver76** [comment]
Thanks, yes is generated I see the problem will fix it tomorrow
