### ISSUE TITLE
backup error - Invalid string length..

### ISSUE THREAD

**Issue by Ilovegym66** [ioBroker/ioBroker.js-controller#2391]
iobroker js-controller 5.0.11, Admin 6.7.2, Node 18.17.0, NPM 9, all at latest, Debian Bookworm LXC. 
System Redis/Redis 
since 2 days ( I think come with updates of Admin-Adapter, because it works with js-controller 5.0.11 ).. it's no backup more possible:

`
ilovegym@iobrokerS2:/opt/iobroker$ iob backup 
host.iobrokerS2 101433 states saved
host.iobrokerS2 121811 objects saved
host.iobrokerS2 Backup not created: Invalid string length
Backup created: undefined
This backup can only be restored with js-controller version up from 4.1
ilovegym@iobrokerS2:/opt/iobroker$

`

system running still fine, no other issues or problems.. but a backup was really nice to have.. :-)
any hints to debug or get more infos?

**Comment by foxriver76** [comment]
in the end it is controller which performs the backup code, so transfered

**Comment by foxriver76** [comment]
Also the logging that backup is created even it is not, is not optimal, will fix this

**Comment by foxriver76** [comment]
How many states and objects do you have in your system?

**Comment by Ilovegym66** [comment]
Today:
`
ilovegym@iobrokerS2:/opt/iobroker$ iob backup
host.iobrokerS2 101185 states saved
host.iobrokerS2 121866 objects saved
host.iobrokerS2 Backup not created: Invalid string length
Backup created: undefined
This backup can only be restored with js-controller version up from 4.1
ilovegym@iobrokerS2:/opt/iobroker$
`
this is what is shown in Admin / Objects, it's different :(
![image](https://github.com/ioBroker/ioBroker.js-controller/assets/36229898/a56f0d55-84d3-44db-b01c-7cc76ede4cb1)

**Comment by Apollon77** [comment]
@Ilovegym66 Wie gross ist denn das backup? wenn du das backup file enpackst - wie gross ist das json was da drin ist?

**Comment by Ilovegym66** [comment]
es wird keins angelegt, das ist ja das Problem.. :(  zumindest wuesste ich nicht, wo es sein soll.. im /opt/iobroker/backups und /opt/iobroker/backup-objects ist nichts.. 
iob fix hab ich schon laufen lassen. 
Ist meine Redis-DB crashed?

**Comment by Apollon77** [comment]
Ahh passiert beim backup erstellen. ok Wieviele objekte und wieviele states?

**Comment by Apollon77** [comment]
Der Fehler kommt an sich nur (nach aktuellem Stand) wenn das Backup "zu gross" wird. was das bei dir heisst müssen wir rausfinden.
Wie gross ist die redis db?

**Comment by Apollon77** [comment]
ooh ok gesehen ... soll das system >100.000 States/Objkete hben oder hast du dir die ggf pber ble eingefangen?

**Comment by Ilovegym66** [comment]
Redis-DB:
![image](https://github.com/ioBroker/ioBroker.js-controller/assets/36229898/d9c9011a-3a59-40ff-bc2d-3dc5fdd6fbf3)

Admin zeigt mehr States an als beim Backup wohl gefunden werden, siehe oben.. 
was mich wundert ist auch das iob -> /opt/iobroker/iobroker vom 9.8... muss das so oder hab ich da mal am Ipad mit den dicken fingern falsch gedrueckt??
![image](https://github.com/ioBroker/ioBroker.js-controller/assets/36229898/23e3d04e-4337-4a4b-9e01-046a874b7ec6)

**Comment by Apollon77** [comment]
Daten alle ok ... Redis "nur "300MB" (ist aber halt binär) ... also zurück zu: soll das so mit 100k States/Objekten?

**Comment by Ilovegym66** [comment]
ja auf jeden fall mehr.. ist schon laenger so.. hab halt viel Zeugs..

**Comment by Apollon77** [comment]
also ich hab auf viel zeug aber nur 20k :-)

Nutzt du ble adapter?

**Comment by foxriver76** [comment]
Hast du da zufällig Instanzen, die man mal wegräumen könnte weil eh nur mal aus Jucks installiert? Dann könnte man mal checken ob er es mit weniger Objekten schafft.

**Comment by Ilovegym66** [comment]
nee kein ble adapter.. 
hab 110 Tuya-Devices, 200 Sonoff, 220 Zigbee, usw.. insgesamt 80 Adapter installiert..  
das einzige was ich loeschen kann, waere ws, vis und socketio, die brauch ich nicht.. arbeite nur mit minuvis.

Ich schau mal durch, halte mein System aber schon von den Objekten her sauber, gerade wegen der Anzahl..

**Comment by Apollon77** [comment]
Ok, dann schauen wir mal wie wir wieder ein backup kriegen . Danke für den Referenzfall :-))

**Comment by Ilovegym66** [comment]
hab was gefunden... unifi-adapter loescht gerade 77000 objects.. :-) ich hab eh den unpoller als docker laufen der mir die daten in die flux beamt.. bei 380 Netzwerk devices hat der sich wohl ausgetobt..  mal sehen wenn die objects geloescht sind, ob es dann geht.. ansonsten ist der auch schnell wieder installiert, zum testen.. :-) 
Hab zwar taeglich backup von dem lxc aber ein iobroker backup ist ja was anderes.. und mit dem schlaf ich ruhiger.. 

![image](https://github.com/ioBroker/ioBroker.js-controller/assets/36229898/79b16de0-f8a5-49e3-905f-7a976a429e76)

**Comment by Ilovegym66** [comment]
hmpff.. nee die Anzahl war es nicht... :( da muss was anderes sein.. 
![image](https://github.com/ioBroker/ioBroker.js-controller/assets/36229898/981ba3b1-b1d0-432a-b7ee-ba3e92cf28c6)

**Comment by foxriver76** [comment]
Kannst du mal in `/opt/iobroker/node_modules/@iobroker/js-controller-cli/build/lib/setup/setupBackup.js` die Zeile `372` müsste es sein von

```js
console.error(`host.${hostname} Backup not created: ${err.message}`);
```

in 

```js
console.error(`host.${hostname} Backup not created: ${err.stack}`);
```

ändern und dann Controller neu starten und nochmal Backup triggern

**Comment by Ilovegym66** [comment]
hmm nach der Aenderung (und wirklich nur das message auf stack geaendert, die Rechte sind noch iobroker:iobroker ) startet iobroker mit 99% cpu.. das hatte ich in der Version noch nie.. nach einem reboot immer nur 30-50%.. 
jetzt hats ewig gedauert und etliche Adapter sind gecrashed.. (influx, konnte states nicht finden..erklaert wohl auch die verschiedene Anzahl von states in backup und admin..?)  
Ich hatte die Tage n paar neue Tuya devices eingebunden und dann die Influx mit tuya.0. neu gesetzt, wobei er haengen geblieben ist.. vielleicht hat hier ja was meine states geschossen..  
Jetzt kann ich, wenn ich in den objects auf tuya.0. filtere, keine aenderungen mehr machen.. er haengt und verliert dann die connection.. 
Da das System produktiv ist, muss ich erstmal wieder das Backup vom Montag von lxc iobroker und redis wieder einspielen.
Kann spaeter dann nochmal versuchen, alles nachzuvollziehen..

Hier mal die Ausgabe vom Backup: 
`
ilovegym@iobrokerS2:/opt/iobroker$ iob start
ilovegym@iobrokerS2:/opt/iobroker$ iob status
iobroker is running on this host.

At least one iobroker host is running.

Objects type: redis
States  type: redis
ilovegym@iobrokerS2:/opt/iobroker$ iob backup
host.iobrokerS2 37163 states saved
host.iobrokerS2 43945 objects saved
host.iobrokerS2 Backup not created: RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at BackupRestore.createBackup (/opt/iobroker/node_modules/@iobroker/js-controller-cli/src/lib/setup/setupBackup.ts:437:67)
    at /opt/iobroker/node_modules/@iobroker/js-controller-cli/src/lib/setup.ts:1330:38
Backup created: undefined
This backup can only be restored with js-controller version up from 4.1
ilovegym@iobrokerS2:/opt/iobroker$

`

**Comment by foxriver76** [comment]
An der Zeile sollte es nicht liegen.

Du kannst mal noch 

Zeile `367` die aktuell 


```js
            fs_extra_1.default.writeFileSync(`${tmpDir}/backup/backup.json`, JSON.stringify(result, null, 2));
```

enthält, durch

```js
            await fs_extra_1.default.writeJSON(`${tmpDir}/backup/backup.json`, result, { spaces: 2 });
```

ersetzen. Wobei ich vermute das wir in einem anderen Fehler enden.

**Comment by Ilovegym66** [comment]
sorry, musste wieder zurueck mit iobroker und redis auf Montag, das laeuft und backup geht auch. 
Aenderungen gab es von Adaptern:
`
2023-08-10 11:45:25.545  - info: javascript.0 (455) script.js.common.Nuki.mqtt2log: NUKI Hub WT: Querying lock state: Querying lock state: Querying lock state: unlocked
^Cilovegym@iobrokerS2:/opt/iobroker$ iob backup
host.iobrokerS2 100934 states saved
host.iobrokerS2 121584 objects saved
Backup created: /opt/iobroker/backups/2023_08_10-11_45_34_backupiobroker.tar.gz
This backup can only be restored with js-controller version up from 4.1
ilovegym@iobrokerS2:/opt/iobroker$ iob update
Used repository: beta
Adapter    "acme"         : 0.1.0    , installed 0.1.0
Adapter    "admin"        : 6.7.2    , installed 6.7.0  [Updatable]
Adapter    "alarm"        : 3.3.12   , installed 3.3.12
Adapter    "alexa-shoppinglist": 0.1.5, installed 0.1.5
Adapter    "alexa-timer-vis": 0.2.0  , installed 0.2.0
Adapter    "alexa2"       : 3.24.1   , installed 3.23.2 [Updatable]
Adapter    "apple-find-me": 0.0.15   , installed 0.0.15
Adapter    "backitup"     : 2.6.23   , installed 2.6.23
Adapter    "bluelink"     : 2.3.6    , installed 2.3.6
Adapter    "cloud"        : 4.4.1    , installed 4.4.1
Adapter    "countdown"    : 2.1.0    , installed 2.1.0
Adapter    "device-watcher": 2.9.3   , installed 2.9.3
Adapter    "devices"      : 1.1.5    , installed 1.1.5
Adapter    "discovery"    : 3.2.0    , installed 3.2.0
Adapter    "dwd"          : 2.8.5    , installed 2.8.5
Adapter    "email"        : 1.2.0    , installed 1.2.0
Adapter    "eventlist"    : 1.2.3    , installed 1.2.3
Adapter    "feiertage"    : 1.1.0    , installed 1.1.0
Adapter    "fitbit-fitness": 0.4.10  , installed 0.4.10
Adapter    "fritzdect"    : 2.3.1    , installed 2.3.1
Adapter    "go-e"         : 1.0.27   , installed 1.0.27
Adapter    "heizoel"      : 1.0.3    , installed 1.0.3
Adapter    "hp-ilo"       : 1.0.6    , installed 1.0.6
Adapter    "ical"         : 1.13.3   , installed 1.13.3
Adapter    "iceroad"      : 1.2.1    , installed 1.2.1
Adapter    "influxdb"     : 3.2.0    , installed 3.2.0
Adapter    "iot"          : 2.0.11   , installed 2.0.11
Adapter    "javascript"   : 7.1.4    , installed 7.1.1  [Updatable]
Controller "js-controller": 5.0.11   , installed 5.0.11
Adapter    "lightcontrol" : 0.3.0    , installed 0.3.0
Adapter    "linux-control": 1.1.5    , installed 1.1.5
Adapter    "lovelace"     : 3.0.1    , installed 3.0.1
Adapter    "meteoalarm"   : 2.3.7    , installed 2.3.7
Adapter    "mihome-vacuum": 3.11.0   , installed 3.11.0
Adapter    "minuaru"      : 1.1.0    , installed 1.1.0
Adapter    "minuvis"      : 2.3.3    , installed 2.3.3
Adapter    "mqtt"         : 4.1.1    , installed 4.1.1
Adapter    "notification-manager": 0.1.1, installed 0.1.1
Adapter    "nut"          : 1.6.0    , installed 1.6.0
Adapter    "octoprint"    : 5.0.1    , installed 5.0.1
Adapter    "odl"          : 2.0.5    , installed 2.0.5
Adapter    "oilfox"       : 4.1.2    , installed 4.1.2
Adapter    "openligadb"   : 1.3.4    , installed 1.3.4
Adapter    "openweathermap": 0.3.11  , installed 0.3.11
Adapter    "operating-hours": 1.0.4  , installed 1.0.4
Adapter    "ping"         : 1.6.2    , installed 1.6.2
Adapter    "pollenflug"   : 1.0.6    , installed 1.0.6
Adapter    "proxmox"      : 1.3.5    , installed 1.3.5
Adapter    "puppeteer"    : 0.2.7    , installed 0.2.7
Adapter    "rest-api"     : 1.1.0    , installed 1.1.0
Adapter    "shuttercontrol": 1.6.1   , installed 1.6.1
Adapter    "simple-api"   : 2.7.2    , installed 2.7.2
Adapter    "snmp"         : 2.4.11   , installed 2.4.11
Adapter    "socketio"     : 6.5.2    , installed 6.5.2
Adapter    "solarmanpv"   : 0.5.0    , installed 0.5.0
Adapter    "sonoff"       : 2.5.7    , installed 2.5.7
Adapter    "synochat"     : 1.3.0    , installed 1.3.0
Adapter    "synology"     : 2.1.13   , installed 2.1.13
Adapter    "text2command" : 3.0.2    , installed 3.0.2
Adapter    "tr-064"       : 4.2.18   , installed 4.2.18
Adapter    "trashschedule": 2.2.0    , installed 2.2.0
Adapter    "tuya"         : 3.14.2   , installed 3.14.2
Adapter    "unifi"        : 0.6.6    , installed 0.6.6
Adapter    "viessmannapi" : 2.1.1    , installed 2.1.1
Adapter    "vis"          : 1.4.16   , installed 1.4.16
Adapter    "wallpanel"    : 0.3.11   , installed 0.3.11
Adapter    "weatherunderground": 3.4.2, installed 3.4.2
Adapter    "web"          : 6.1.0    , installed 6.1.0
Adapter    "whatsapp-cmb" : 0.2.3    , installed 0.2.3
Adapter    "wifilight"    : 1.1.4    , installed 1.1.4
Adapter    "windows-control": 0.1.5  , installed 0.1.5
Adapter    "wireguard"    : 1.5.7    , installed 1.5.0  [Updatable]
Adapter    "wled"         : 0.7.0    , installed 0.7.0
Adapter    "worx"         : 2.3.2    , installed 2.3.2
Adapter    "ws"           : 2.5.3    , installed 2.5.3
Adapter    "yahka"        : 1.0.3    , installed 1.0.3
Adapter    "yeelight-2"   : 1.2.1    , installed 1.2.1
Adapter    "zigbee"       : 1.8.22   , installed 1.8.22
ilovegym@iobrokerS2:/opt/iobroker$

`
Seit dienstag abend ging das backup nicht mehr, und Dienstag hab ich "nur" Admin 6.7.1 gehabt, die anderen Updates von Alexa / Wireguard / Javascript kamen spaeter.. 
Und am Dienstag hab ich mit Tuya / Objects rumgespielt.. ich denke mir hat da was die States geschossen gehabt..

Ich teste mit dem kaputten lxc dann noch weiter, aber habt beide hier mal keine Prio, bitte.. investiert eure Ressourcen in andere tasks.. :-) danke :-)

**Comment by Ilovegym66** [comment]
hmpff da war die Freude nicht lange..  jetzt gehts wieder nicht mehr.. bin auf Montag zurueck, backup ging, dann hab ich einfach nur ein paar Scripte bearbeitet, den Alexa2 geupdated, alle anderen Updates ausgelassen, bei den Tuya die Influx gesetzt, und jetzt ist der gleiche Fehler wieder da.. und wieder Unterschiede zwischen States beim Backup 99205, objects 119535 und in der Objects-Anzeige beim Admin Objekte: 119534, Zustände: 100733

Hab das Gefuehl, mir schiesst da irgendwas die DB.. ? Soll ich mal auf json umstellen? Dann konvertiert er ja .. gibts ne Moeglichkeit, die Datenbank zu checken..? Muss jetzt weg, kann heute abend dann weiter testen..

**Comment by foxriver76** [comment]
Okay letzte einfache Idee, wäre:

```js
            await fs_extra_1.default.writeJSON(`${tmpDir}/backup/backup.json`, result, { spaces: 0 });
```

das spart im erzeugten File in meinen Tests ca 33 % Speicher. Würde uns zumindest Zeit verschaffen. ;-)

**Comment by Ilovegym66** [comment]
Guten Morgen,
jetzt findet er nicht die function dazu:
`
ilovegym@iobrokerS2:/opt/iobroker$ iob backup
host.iobrokerS2 99213 states saved
host.iobrokerS2 119547 objects saved
host.iobrokerS2 Backup not created: TypeError: fs_extra_1.default.writeFileJSON is not a function
    at BackupRestore.createBackup (/opt/iobroker/node_modules/@iobroker/js-controller-cli/src/lib/setup/setupBackup.ts:437:16)
    at /opt/iobroker/node_modules/@iobroker/js-controller-cli/src/lib/setup.ts:1330:38
Backup created: undefined
This backup can only be restored with js-controller version up from 4.1
ilovegym@iobrokerS2:/opt/iobroker$

`

hab gesehen, dass in der nightly-release mehr backup-debug options eingebaut wurden.. ?

**Comment by foxriver76** [comment]
`writeJSON` nicht `writeFileJSON` dann sollte er sie finden

**Comment by Ilovegym66** [comment]
hmpff klar.. der 2.te Kaffee ist noch nicht durch, sorry.. :(
Ergebnis.. was soll ich sagen.. kaum macht man's richtisch..funktionierts.. :-)
`
ilovegym@iobrokerS2:/opt/iobroker$ iob backup
host.iobrokerS2 99213 states saved
host.iobrokerS2 119547 objects saved
Backup created: /opt/iobroker/backups/2023_08_11-09_07_49_backupiobroker.tar.gz
This backup can only be restored with js-controller version up from 4.1
ilovegym@iobrokerS2:/opt/iobroker$

`

DANKE !!

**Comment by foxriver76** [comment]
Okay, ist auch so in der nächsten Version drin. Allerdings dann wohl echt das Problem, dass das Backup zu groß ist. Langfristig müssten wir uns da dann doch was einfallen lassen, wobei Ideen existieren, aber potentiell wieder dann nur mit neuen Versionen restore möglich.

**Comment by Ilovegym66** [comment]
ja, gar nicht so einfach.. vielleicht erstmal n Schalter in den Host-Settings fuer grosse DB ? 
Hier mal das Verzeichnis:
`
ilovegym@iobrokerS2:/opt/iobroker$ ls backups -la
total 28392
drwxrwxr-x+ 2 iobroker iobroker     4096 Aug 11 09:08 .
drwxrwxr-x+ 6 iobroker iobroker     4096 Jul 31 09:58 ..
-rw-rw-r--+ 1 iobroker iobroker 29064567 Aug 11 09:08 2023_08_11-09_07_49_backupiobroker.tar.gz
ilovegym@iobrokerS2:/opt/iobroker$

`

**Comment by Ilovegym66** [comment]
hab n update auf Node 18.17.1 gemacht, und iobroker neu gestartet.. das ist der Unterschied zu vorher...

**Comment by foxriver76** [comment]
Proxmox? Und die Maschine hat 4 GB RAM?

**Comment by Ilovegym66** [comment]
ja, Proxmox, der LXC hat 32GB Ram, 8 CPU Core.. sollte doch reichen.. ich versteh's gerade nicht.. 
![image](https://github.com/ioBroker/ioBroker.js-controller/assets/36229898/d7e4b6ad-eded-4a03-bdb5-c7cdec86f145)

**Comment by Ilovegym66** [comment]
![image](https://github.com/ioBroker/ioBroker.js-controller/assets/36229898/5b4eb0b1-86fe-4407-ac0f-014838056f8e)

**Comment by foxriver76** [comment]
Ne, denke wenn dann liegts am Limit für den Nodejs Prozess, ich schaue mal nach ob wir da iob spezifische Einstellungsmöglichkeiten hatten.

**Comment by foxriver76** [comment]
Hm klingt irgendwie nach Memory leak nach node update. 

Ansonsten kann man hier Memory Limit für Host festlegen: 
![IMG_2909](https://github.com/ioBroker/ioBroker.js-controller/assets/25484431/df70c78b-e805-4b2e-adf0-4a6336c7737e)

**Comment by Ilovegym66** [comment]
hmm hab ich schon so eingestellt:
![image](https://github.com/ioBroker/ioBroker.js-controller/assets/36229898/61a31f64-4b93-497d-9a5a-d1983b6b80a9)

dann mal Node komplett geloescht, und wieder neu installiert, iob fix, und kiste neu gestartet... 
ging solange, bis ich die backup Funktion auf gerufen habe, dann wieder das gleiche, und dann dauernd...

Ich spiel das Backup von heute Nacht wieder ein, und geh damit auf die Node 18.17.0 und lass das mit dem Update von Node erstmal...

**Comment by foxriver76** [comment]
Hm.. na villt werden dann unsere Backupoptimierungspläne etwas vorgezogen und es kommt noch eine optimierte Variante in Controller v5.

**Comment by Ilovegym66** [comment]
ja, ich hab leider kein Plan was mit Node 18.17.1 anders ist, als mit 18.17.0, aber anscheinend wird bei der .1 nur 4GB Ram verwendet, und das reicht nicht.. wenn ich die Fehlermeldungen richtig interpretiere.
Deshalb geht nicht nur das Backup nicht, sondern auch der Javascript-Adapter ebenso nicht.. solange ich den abschalte, und kein Backup mache, laeufts.. 

Die Node Installation hab ich gerade, bin da immer nach Thomas Brauns Hinweisen im forum gegangen, hatte nie Probleme..

Was mich wundert, auch wenn ich z.b. den Unifi-Adapter loesche und mit weniger als 40000 States und Objects arbeite, geht's genauso wenig.. 
Hab das letzte Backup vom Container in Proxmox wieder eingespielt, das laeuft prima. 

Auch die Einstellmoeglichkeit im Host wie in deinem Screenshot ist ne gute Idee, aber in meinem Fall hat das nichts genutzt..
Vielleicht ist es auch ein Fehler in Node 18.17.1..

**Comment by foxriver76** [comment]
Ach so, javascript Adapter läuft jetzt auch OOM die ganze Zeit, unabhängig vom Backup..

**Comment by Ilovegym66** [comment]
hatte nur Probleme mit beiden nach update auf 18.17.1, mit 18.17.0 alles fine.. 
Ich weiss auch garnicht, ob das hier noch das richtige Issue dazu ist.. ??

**Comment by foxriver76** [comment]
Sieht eher nach einem individuellen Problem mit der Node Version aus - ja.

Das der Controller Prozess nicht mehr memLimitMB respektiert, dafür habe ich hier ein Issue erstellt https://github.com/ioBroker/ioBroker/issues/461

**Comment by Ilovegym66** [comment]
ok, dann schließen wir hier endgültig, Danke fuer die Aufmerksamkeit und schnelle Hilfe! 
Das andere Issue hab ich im Blick.. ich les den Kram morgens wie andere die Zeitung.. :-)
solange iob backup funktioniert, ist der iob auch mal schnell woanders hin gezogen..
