### ISSUE TITLE
Type error by setState => StateQuality

### ISSUE THREAD

**Issue by Schmakus** [ioBroker/ioBroker.js-controller#2411]
js-controller v5.0.12

`
await this.setStateAsync(id, {
    val: value,
    ack: true,
    q: 0x40,
});`

`Keine Überladung stimmt mit diesem Aufruf überein.
  Die Überladung 1 von 3 ((id: string, state: State | StateValue | SettableState, ack?: boolean | undefined): SetStatePromise) hat den folgenden Fehler verursacht.
    Der Typ "64" kann dem Typ "StateQuality | undefined" nicht zugewiesen werden.
  Die Überladung 2 von 3 ((id: string, state: State | StateValue | SettableState, options?: unknown): SetStatePromise) hat den folgenden Fehler verursacht.
    Der Typ "64" kann dem Typ "StateQuality | undefined" nicht zugewiesen werden.`

`0x1` and `0x01` is working.

**Comment by foxriver76** [comment]
Example Repo?

**Comment by Schmakus** [comment]
[https://github.com/Schmakus/ioBroker.lightcontrol/tree/v1.0.0](https://github.com/Schmakus/ioBroker.lightcontrol/tree/v1.0.0)

**Comment by foxriver76** [comment]
cannot replicate this with your v1.0.0 branch. My assumption is, that npm has not cleaned up your node_modules folder and that their is still a `@types/iobroker` package. If this is the case, delete your `node_modules` and `npm i` afterwards. Then it should be fixed.
