### ISSUE TITLE
[Feature Request] Allow a return value in alias read functions which won't change the state value

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.js-controller#2412]
It would be useful, if a read function of an alias could return a predefined value which indicates that the alias state should not be changed (e.g. in error cases).

At the moment, nothing can stop the execution. Even returning `null` or throwing an exception will set the alias state to `null`.

-----

e.g. `undefined`.

Example:

`val.length >= 10 ? val.substr(9) : undefined`

https://github.com/ioBroker/ioBroker.js-controller/blob/01a349adf18e7f17f77c94e3f384106b5df11e95/packages/common/src/lib/common/tools.ts#L2705-L2739

**Comment by foxriver76** [comment]
Do you mean this? -> https://github.com/ioBroker/ioBroker.js-controller/issues/529

**Comment by foxriver76** [comment]
The problem is, that aliases are not stored in a database, they are just links + these transformer functions.

**Comment by klein0r** [comment]
> The problem is, that aliases are not stored in a database

Thanks, I didn't know that. So it's just a conversion and you need the original value. But it looks like the discussion isn't new 😄 Feel free to close this issue (since the other issue covers all thoughts).

**Comment by Diginix** [comment]
I've tried to prevent getting null from the source in the alias but without success. My current workaround is this rule:
`val == null ? '' : val`
Is there a way to have no value change of alias for specific values of source e.g. null

**Comment by foxriver76** [comment]
duplicate of #529
