### ISSUE TITLE
Permission of alias

### ISSUE THREAD

**Issue by Scrounger** [ioBroker/ioBroker.js-controller#2413]
**Describe the bug**  
changed permission of an alias will be ignored. You have to set the needed permission to the source.

**To Reproduce**  
1. create an alias and set the source 
2. change permission of the alias e.g. changing owner group
3. try to access the alias e.g. with simple api and an user of the owner group configured. Access is not possible, You will get a warning like this `simple-api.0 (1023) Permission error for user "system.user.proxmox" on "sureflap.0.Wir.pets.Mojo.inside": setState`

**Expected behavior**  
changing permission of an alias independent from the source.

**Versions:**  
 - Adapter version: 6.8.0
 - JS-Controller version: 4.0.24
 - Node version: 16.x
 - Operating system: ubuntu 22.04.

**Additional context**  
Don't know if this is really a bug, but i expected an other behaviour. Also don't know if this is a topic for admin or js-controller

**Comment by foxriver76** [comment]
We would need to discuss, what we want as intended behavior, currently as you already noticed, both objects are checked for permissions.

**Comment by Scrounger** [comment]
any news on this?

**Comment by foxriver76** [comment]
No will be topic for next controller

**Comment by foxriver76** [comment]
We decided that the alias permissions should be the only permissions that matter when interacting with alias states/objects, hence next controller will respect this. 

https://github.com/ioBroker/ioBroker.js-controller/pull/2666
