### ISSUE TITLE
[2.0.0] Remove jscs and grunt-jscs related tasks

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#242]
jscs is discontinued and introduces deprecation infos and warnings. Can we remove it?

@GermanBluefox  ??

**Comment by Apollon77** [comment]
Parent: #223

**Comment by Apollon77** [comment]
@GermanBluefox Done also or ?!

**Comment by GermanBluefox** [comment]
Done

ср, 29 авг. 2018 г., 9:12 Ingo Fischer <notifications@github.com>:
