### ISSUE TITLE
Missing key "uk" in type definition of StringOrTranslated

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.js-controller#2426]
see

https://github.com/ioBroker/ioBroker.js-controller/blob/ff6975303d61f04653686fcde3284baab3f62485/packages/types-dev/objects.d.ts#L148

**Comment by winnyschuster** [comment]
sorry, i seem to be a bit late here but `uk` is not common use, if en is not good enough i'd change it to be `gb`. in ISO 639-1 there is no such thing like en_UK for example.

**Comment by mcm1957** [comment]
as discussed at telegram:
https://www.loc.gov/standards/iso639-2/php/langcodes_name.php?iso_639_1=uk
ukrain
