### ISSUE TITLE
Error: Invalid pattern on subscribe

### ISSUE THREAD

**Issue by Scrounger** [ioBroker/ioBroker.js-controller#2431]
After installing 5.0.12 i get the following error from web instance:
`Invalid pattern on subscribe: The pattern "0_userdata.0.vis.control{a:local_client; a ? ".Client_" + a : ""}.Dialogs.Kamera.trigger" is not a valid ID pattern`

I use this in my vis (1) project and it is valid. So at my point of view this error is wrong.
This pattern use a local variable to genrate the object using as binding - makes it possible to have a client safe vis.

**Comment by foxriver76** [comment]
Hm you cannot subscribe on such patterns it will do nothing so this is if at all an issue at web adapter.

**Comment by foxriver76** [comment]
So maybe the binding is correct but it should not be subscribed on this pattern by the adapter. Because there cannot be an id like this ;-)

**Comment by Joppevilla** [comment]
I have the same problem after upgrading from 4.0.24 to 5.0.12.
The web adapter will then automatically stop and restart
I also use bindings
I received the following error message:

Error The pattern "http://192.168.188.204:10090/image1.jpg?resolution=1280x720&fps=1" is not a valid ID pattern

<html><body>


  | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
-- | --



</body>
</html>
<html><body>


  | host.iobroker-Server  States 127.0.0.1:53926 Error from InMemDB: Error: The pattern  "http://192.168.188.204:10090/image1.jpg?resolution=1280x720&fps=1"  is not a valid ID pattern     at Object.pattern2RegEx  (/opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/tools.ts:2497:15)     at StatesInMemoryServer.handleSubscribe  (/opt/iobroker/node_modules/@iobroker/db-base/src/lib/inMemFileDB.ts:324:59)     at StatesInMemoryServer._subscribeForClient  (/opt/iobroker/node_modules/@iobroker/db-states-file/src/lib/states/statesInMemFileDB.js:258:14)     at RedisHandler.<anonymous>  (/opt/iobroker/node_modules/@iobroker/db-states-jsonl/src/lib/states/statesInMemServerRedis.js:395:26)     at RedisHandler.emit (node:events:514:28)     at RedisHandler.emit (node:domain:489:12)     at Immediate._onImmediate  (/opt/iobroker/node_modules/@iobroker/db-base/src/lib/redisHandler.ts:209:37)     at processImmediate (node:internal/timers:476:21)
-- | --



</body>
</html>

**Comment by Joppevilla** [comment]
Binding background:
I have a String-Objekt "0_userdata.0.Video.Cam01" with the value "http://192.168.188.204:10090/image1.jpg?resolution=1280x720&fps=1". This Objekt is used via binding in an basic-image Widget with {0_userdata.0.Video.Cam01}.

**Comment by Joppevilla** [comment]
By the way, the error doesn't always occur, only when the binding is used frequently (about 3 - 5 times)

**Comment by foxriver76** [comment]
Should not crash with newest stable version (6.1.2) of web but just log an error

**Comment by foxriver76** [comment]
But can you maybe post a screenshot of your binding @Scrounger

**Comment by Scrounger** [comment]
> But can you maybe post a screenshot of your binding @Scrounger

why a screenshot?
Binding is
´0_userdata.0.vis.control{a:local_client; a ? ".Client_" + a : ""}.Dialogs.Kamera.trigger´ and will be translated to this e.g:
`0_userdata.0.vis.control.Client_1.Dialogs.Kamera.trigger`

**Comment by foxriver76** [comment]
Okay but then via tries to (as well) subscribe to the raw binding to and not only to the evaluated, so please open up an issue there

**Comment by Scrounger** [comment]
thought vis 1 is no longer being developed?
Therefore, in my opinion, a solution should be provided where the log entry occurs or?

E.g. check if the pattern comes from the vis and ignore it if necessary or check the binding structure

**Comment by mcm1957** [comment]
As far as I know:
vis 1 will not get new features
vis 1 will still get bugs fixed

**Comment by foxriver76** [comment]
And you are really sure that you can use a binding on the object id field of the widget? Never seen this. So from my perspective vis blindly subscribes what you pass there. But if you are a 100 % sure that your binding works, please open the issue at vis as Stated. And also state the used widget to allow for reproducing.

**Comment by Scrounger** [comment]
> And you are really sure that you can use a binding on the object id field of the widget? Never seen this. So from my perspective vis blindly subscribes what you pass there. 

Definitely I use for years on several systems and vis, otherwise I would not report it as a bug.

> But if you are a 100 % sure that your binding works, please open the issue at vis as Stated. And also state the used widget to allow for reproducing.

Everything about this including working examples are described in this topic:
https://forum.iobroker.net/topic/26578/vis-dynamische-object-id-feldreferenz

**Comment by Apollon77** [comment]
@Scrounger In fact yes it works ... but in fact vis is dopinfg something which should not be done :-)

My assumption is the following: In favt the "value" of the provided Object ID is displayed. With the binding you change the logic so that not "that single onbject id" is being read but the binding logic is executed to get the value to display.

But (most likely then a vis bug) then vis also "subscribes" to the "object id" (aka "the text you entered in the field") because it should be an object id and no binding ... seems like this was never changed as bindings were added there.

So options:
* fix vis to "detect" is an object id is a binding ad then not subscribe
* lower loglevel of the message so that it can be suppressed
* suppress the error message in web/socket-classes when it looks like a binding *gg*

**Comment by Scrounger** [comment]
@Apollon77 
ok, but then we should reopen this issue?
