### ISSUE TITLE
Use state system.host.<host>.diskWarning (to log message when level is reached) and ack new values

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.js-controller#2432]
The js-controller creates a state `diskWarning` for each host:

https://github.com/ioBroker/ioBroker.js-controller/blob/f40b69380d6fa685e3296be3d631f3d1ca2393e9/packages/controller/src/main.ts#L2124-L2138

When setting this (writeable) state with `ack: false` the value isn't acknowledged.

After searching the complete js-controller code for occurrences, I found nothing.

**Comment by klein0r** [comment]
Also searched tag `v4.0.24` and `v3.3.22` - also no occurrences.

**Comment by foxriver76** [comment]
It is only used by admin at the moment.

**Comment by klein0r** [comment]
Ah okay, thank you!
Then it's a feature request to implement the function of this state to raise a warning in the log when warning level is reached.
