### ISSUE TITLE
Fehlermeldung cannot call visUtils: Not exists

### ISSUE THREAD

**Issue by Trunks1982** [ioBroker/ioBroker.js-controller#2434]
js Controller 5.0.12
Nodejs 18.17.1
NPM 9.6.7
Iobroker 6.8.0

Habe vorgestern auf die neuste js Version geupdatet und seid dem bekomme ich immer die Fehlermeldung cannot call visUtils: Not exists.
Über google habe ich nur rausfinden können das es mal in der Version 5.0.3 vorkam.Habe aber keine Lösung gefunden warum dies so ist.Benutze auch keine VIS.

**Comment by foxriver76** [comment]
Entweder vis löschen wenn eh nicht genutzt oder `iob upload vis`

**Comment by Trunks1982** [comment]
> Entweder vis löschen wenn eh nicht genutzt oder `iob upload vis`

Hi Vis ist leider gar nicht installiert.Aber könnte gerne mal versuchen einmal zu installieren und dann wieder deinstallieren ob es dann weg ist.

**Comment by foxriver76** [comment]
Ja immer wenn Statistiken kalkuliert werden, versucht er vis datenpunkte zu zählen etc. 

Im Endeffekt passiert dass wenn es ein system.adapter.vis Objekt gibt was heißt Adapter installiert oder es gab früher ein Bug o.ä. Dass das Objekt übrig geblieben ist

**Comment by Trunks1982** [comment]
Jap so war es auch unter Datenpunkt System war noch vis drin.Hab diesen gelöscht und Fehler war weg.
Issue kann geschlossen werden.

**Comment by mcm1957** [comment]
@foxriver
Sollte der Fehler nicht besser im controller abgefangen werden?

**Comment by foxriver76** [comment]
Welcher Fehler? Das ist nur ein Problem wenn Systeme nicht sauber aufgeräumt sind, vis Adapter ist nicht drauf aber zugehöriges Adapter Objekt existiert. Und dann ist’s nur ein warn log, hat sonst keinen Einfluss

**Comment by mcm1957** [comment]
Ok,hab übersehn dass es nur warn log ist.
