### ISSUE TITLE
iobroker crashes while proceeding backitup job

### ISSUE THREAD

**Issue by UrsKobler** [ioBroker/ioBroker.js-controller#2439]
**Describe the bug**
Since updating js-controller 4.0.24 to 5.0.12, calling backitup backup leads to a total system crash.

**Current used system components**
[iob_diag_js-controller 5_0_12.txt](https://github.com/ioBroker/ioBroker.js-controller/files/12647995/iob_diag_js-controller.5_0_12.txt)

**To Reproduce**

1. Start the backup using the backitup adapter.
2. The backitup process begins to run until only hiroglyphs are displayed in the backitup LOG window.
3. The iobroker then crashes and the system has to be rebooted.

**Comment by foxriver76** [comment]
> The backitup process begins to run until only hiroglyphs are displayed in the backitup LOG window.

Would be great if you can share this Log with us

My assumption is, that there is something wrong with binary states.

**Comment by UrsKobler** [comment]
> > The backitup process begins to run until only hiroglyphs are displayed in the backitup LOG window.
> 
> Would be great if you can share this Log with us
> 
> My assumption is, that there is something wrong with binary states.

Unfortunately, I was only able to take the following screenshot before iobroker crashed. I already posted it to **[forum.iobroker.net](https://forum.iobroker.net/topic/68290/js-controller-5-0-x-jetzt-f%C3%BCr-alle-user-im-stable/132?_=1695047047471)**

I hope you can make something of the sparse information.

I would like to continue working with the latest js controller.

Please let me know how I can help you find the error?

**Comment by foxriver76** [comment]
So is it Sonos adapter which creates the problem? Can you maybe extract the binary state, or provide me with a backup of your system if you have one from pre controller v5, then I could try to reproduce it.

**Comment by UrsKobler** [comment]
Dear Max

I would be happy to support you and send you the problematic image with
js-controller version 5.0.12.

Please let me know how and where can I transfer the 32GB image?

I'll be happy if you can successfully locate the error as quickly as
possible.

Thank you for your support.

Sincerely,
Kobi

Am Mo., 18. Sept. 2023 um 19:37 Uhr schrieb Max Hauser <
***@***.***>:

**Comment by foxriver76** [comment]
It would be enough to provide just the database file, if you are using jsonl it is `cat /opt/iobroker/iobroker-data/states.jsonl`

**Comment by UrsKobler** [comment]
Dear Max

As requested, you can find iobroker-data from the image with js-controller version 4.0.24 under the following **[link](https://drive.google.com/drive/folders/1HgYokR4nwx86f8cbnpLZzJVjA4YLLgYp?usp=drive_link)**, where the described problem with backitup did not yet occur.

Thank you for your support.

Sincerely,
Kobi

**Comment by foxriver76** [comment]
Can you also provide the one from the current installation? Strangely with this one the backup is successful and shows no log about the binary states, even-though they are existing.

**Comment by UrsKobler** [comment]
Dear Max

As requested, you can find **iobroker-data-v5** from the image with js-controller version 5.0.12 under the following [link](https://drive.google.com/drive/folders/1I6oNf63uQ9IRmic5q7LOMyN4f8nRPDN6?usp=sharing), where the described problem with backitup did occur.

Thank you for your support.

Sincerely,
Kobi

**Comment by foxriver76** [comment]
Can you try the Sonos Adapter GitHub version? And Test if backup is possible with that and that everything is working as expected. Especially using the cover image with the url state if you are using it.

**Comment by foxriver76** [comment]
Should work with sonos 2.3.2

**Comment by UrsKobler** [comment]
Dear Max

**_Congratulations_**!

You have located the problem that caused the backitup adapter to crash.

The error was successfully resolved with the correction in the **SONOS Adapter V2.3.2**.

The backup job was successfully logged in [LOG-Backitup.txt](https://github.com/ioBroker/ioBroker.js-controller/files/12670458/LOG-Backitup.txt).

Interestingly, I noticed that the backup source is set to **Local** on manual startup. With version 5.0.12 of the js-controller, the backup source always remained on **WebDAV**.

![image](https://github.com/ioBroker/ioBroker.js-controller/assets/67915344/646327d3-680a-4d56-9797-b58f9097977c)

If I manually set the backitup source to WebDAV, no error appears in [LOG-Backitup-WevDAV.txt](https://github.com/ioBroker/ioBroker.js-controller/files/12670825/LOG-Backitup-WevDAV.txt).

![image](https://github.com/ioBroker/ioBroker.js-controller/assets/67915344/3abf5722-08d5-4959-bf19-7d2f442389b5)

I'm not sure if I misunderstood something when using backitup?

I will now test my productive system with js-controller 5.0.12 and then post my experiences.

Thank you for your professional support.

Sincerely,
Kobi

**Comment by UrsKobler** [comment]
Dear Max

In the meantime, I have successfully installed the current version 5.0.12 of js-controller on my productive system.

It looks like all adapters installed in my environment are currently working perfectly under js-controller V 5.0.12.

Thank you again for your valuable support.

Best regards
Kobi
