### ISSUE TITLE
[2.0.0] Should we add a way to automatically solve code 7?

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.js-controller#247]
It sometimes happens that two processes for an adapter instance are running and the 2nd one is restarted in a loop with code 7. Currently the only way to get rid of that as a user is restarting the host machine. I think we should handle that case better:
* and add a way to (or automatically) kill the first process we no longer have control over
* Or realize that the already running process is the instance we try to start all the time and control that one instead of restarting a second process in a loop

**Comment by GermanBluefox** [comment]
controller starts the process and saves it PID in the table.

If controller dies and starts anew it tries to start the new instance.
Instance realize, that other instance still exists and dies too.

The solution could be only that controller before the start checks if the
instance is running (system.adapter.xxx.0.alive) and must say somehow to it
that it must be stopped.

It is only possible via additional state (system.adapter.xxx.0.*kill?*) if
instance gets this signal it must set kill to false and die..... something
like this.
Or just controller should write into kill the desired PID and every
instance must die that is not equal to this PID.




пт, 24 авг. 2018 г. в 15:14, AlCalzone <notifications@github.com>:

**Comment by Apollon77** [comment]
Do we want to add this in 2.0.0?

**Comment by AlCalzone** [comment]
@Apollon77 I think it should definitely be handled by the controller or Adapter class. Devs shouldn’t have to do anything. 

@Bluefox I guess the processes are still running normally. So giving the adapters the command to stop themselves would probably be a good way to solve it.

**Comment by AlCalzone** [comment]
Or is there a way to “connect” to the old process instead?

**Comment by Apollon77** [comment]
Controller has no real connection to Adapter process. Only adapter have the state/objects DB connection. 

So a kill flag would be cool, unless Adapter process Hangs in endless loop or so and can not react on the signal... but for most other cases it can work.

**Comment by stabilostick** [comment]
If js-controller dies, the adapters are still running. Scenario: js-controller restarts automatically. Are the substriptions of all adapters are still valid? Question: Should an adapter kill itself, when the object-db connection is lost? Perhaps using a kind of watchdog event. This mechanism could also be used to destroy specific adapters - by supressing the watchdog event in the js-controller for an suspicious adapter.

**Comment by Apollon77** [comment]
to test: commit b90da14bcfc66a157663ac6a871ff485f86f9f6d
