### ISSUE TITLE
js-controller spams syslog

### ISSUE THREAD

**Issue by Eistee82** [ioBroker/ioBroker.js-controller#2470]
Hi,

my /var/log/syslog file is 18GB every day so my disk is full of logs. I see that js-controller redirects messages to syslog and I don't know how to stop this. I had logging to file enabled before and now I have no logging in js-controller enabled. no changes to the redirected logging to syslog.

/var/log/syslog:
![image](https://github.com/ioBroker/ioBroker.js-controller/assets/1881217/3e9c9dda-f095-4c0e-a8c9-cead5977a1cf)

js-controller no logging:
![image](https://github.com/ioBroker/ioBroker.js-controller/assets/1881217/1a73f8e0-0e21-4fd7-84d2-3b1806121c57)

js-controller: 5.0.12
node: v18.18.0
npm: 9.8.1
os: debian bookworm current updates installed

**Comment by Diginix** [comment]
My syslog is clean and my settings looks different:

![image](https://github.com/ioBroker/ioBroker.js-controller/assets/39678667/7425e6c4-9d2a-4781-aa79-97257faa0e7e)

**Comment by Apollon77** [comment]
@Eistee82 DO you have admin open in browser all the time or closed?

**Comment by Eistee82** [comment]
> @Eistee82 DO you have admin open in browser all the time or closed?
admin is closed most time. vis2 is open on a smartphone all time.

**Comment by Eistee82** [comment]
maybe this is the problem:
https://github.com/ioBroker/ioBroker.js-controller/blob/6d30dbec85ed21a7a94853e5ceb5055aaf81ebf5/packages/controller/src/main.ts#L441

there should be an option to disable this.

**Comment by foxriver76** [comment]
I think you found a nice issue, controller assumed since forever, that all states ending with `.logging` are actual log subscribers. It will be fixed in the next version.
