### ISSUE TITLE
Multihost doesn´t work with v5.0.12

### ISSUE THREAD

**Issue by aDabbelju** [ioBroker/ioBroker.js-controller#2471]
With js-controller v5.0.12 there are some problems with multihost-systems. 

More informations in the ioBroker-forum.
https://forum.iobroker.net/topic/68802/gel%C3%B6st-hilfe-bei-multihost/18 

Workaround: Downgrade js-controller to version 4.0.24 via 
```
# cd /opt/iobroker/
# npm install iobroker.js-controller@4.0.24 --production
```

**Comment by Apollon77** [comment]
Can you please summarize the issue here, because in fact no issues known so far. And to read 50+ posts to sort out the details might be a bit time consuming

**Comment by Apollon77** [comment]
... especially ... because the Forum thread is "solved"?

**Comment by innriver** [comment]
auch bei mir geht es nicht!

Habe heute versuchsweise einen Raspi 3b komplett neu aufgesetzt und wollte ihn als zweiten Slave in in ein bestehendes Master-Slave-System einfügen.
Auf dem Master: iobroker multihost enable

pi@iobroker01:~ $ iobroker multihost enable
Multihost discovery server activated on this host. If iobroker is currently not running please start befeore trying to discover this host.
Important: Multihost discovery works with UDP packets. Make sure they are routed correctly in your network. If you use Docker you also need to configure this correctly.
Multihost discovery will be automatically deactivated after 15 minutes. If you want to activate it permanently use the --persist flag
Discovery authentication activated.
Enter secret phrase for connection:
Repeat secret phrase for connection:
Please check the binding of the configured jsonl server to allow remote connections.
Please restart ioBroker for the changes to take effect: "iobroker restart"


Multihost discovery server: enabled
Discovery authentication:   enabled
Persistent activation:      disabled
Objects:                    jsonl on 0.0.0.0
States:                     jsonl on 0.0.0.0

hier bleibt der Master hängen
im Log vom Master steht: Multi-host discovery server: service started on 0.0.0.0:50005

Auf dem Slave: iobroker multihost connect
der Slave bleibt hängen!

iobroker multihost browse bleibt ebenfalls hängen.

Ich habe jetzt kein Downgrade auf js-controller 4.0.24 gemacht, weil ich mein Produktivsystem am Laufen halten wollte.
Werde die Tage mal noch einen Spiele-Master aufsetzen und testen!

**Comment by Apollon77** [comment]
SO is it omnly the browse and enable commands that are not working or mutlihost in general? SO if you configure manualyl in iobroker.json does it work?

**Comment by Apollon77** [comment]
Ok , @foxriver76 found the reason, fill wiill be in next version

**Comment by aDabbelju** [comment]
> SO is it omnly the browse and enable commands that are not working or mutlihost in general? SO if you configure manualyl in iobroker.json does it work?

My multihost system didn't work after the update from 4.0.24 to 5.0.12. A manual configuration with 'iobroker setup custom' didn't help and the commamds didn't work properly.

**Comment by TJHooker** [comment]
have the same with multihost  if js-controller 5.0.17
downgrade with 
# cd /opt/iobroker/
# npm install iobroker.js-controller@4.0.24 --production
and connect works 
after that  update again

**Comment by Apollon77** [comment]
@TJHooker That should be long fixed

**Comment by TJHooker** [comment]
and why do i have to press strg +c  in row 5 
and after downgrade it works 

![image](https://github.com/ioBroker/ioBroker.js-controller/assets/60543505/6509abdb-386d-41d8-994c-61e01e21056a)

my old master has benn replaced bullseye with bookworm so i have to reconnect the slave

**Comment by mcm1957** [comment]
**This issue has been closed since ctober 2023.**

If you still encounter a problem with the actual js-controller version, please open a new issue describing your problem and listing all involved releases.

**Comment by foxriver76** [comment]
There was indeed another problem with the enable/disable commands. However a new issue is appreciated in such cases, especially as this one is also not well documented. However, it will be fixed with https://github.com/ioBroker/ioBroker.js-controller/pull/2557
