### ISSUE TITLE
Execute "apt list --upgradable" on Linux systems and inform on updates

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#2488]
We could execute "apt list --upgradable" (when apt is the package manager, maybe yum has a comparable command?) e.g. once a day and report uphradeable packages in anotification with "max 1 message" to always have that up to date.

We could also parse the response to see ifg "nodejs" is part of the list and generate another notification just so know if node.js is updateable.
Additionally this could be used to show updateable node.js in admin just then when also the distribuation package is available.

**Comment by Grothesk242** [comment]
Okay. But please do not execute any package updates/upgrade from within ioBroker.
