### ISSUE TITLE
Allow to execute "apt update/upgrade" including restart

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#2489]
We should allow triggering Linux package updates (all or "just nodejs") from controller. This can happen while controller is running and finishs with a js-controller restart (maybe allow to choose?)

**Comment by Eistee82** [comment]
Tomething like:
apt update && apt full-upgrade && n lts && iob restart

**Comment by Apollon77** [comment]
@Eistee82 I think "full-upgrade" we should not do ... maybe really just "upgrade". No idea if we want to install kernel updates. Additionally : what is "n lts"? ;-)

**Comment by Eistee82** [comment]
this is n: https://github.com/tj/n

**Comment by Apollon77** [comment]
Yes and this is not compatible with iobroker, or? Same as nvm

**Comment by Eistee82** [comment]
I use this in my iobroker lxc container (debian 12)

**Comment by Apollon77** [comment]
Might work but because of the fact that iobroker processes run as user iobroker each solution that uses user directories can only NOT work, unless you do it for ionbroker suer. Maybe it is ok when you do globally, but then mostly PATH needs to be correct to ...  But too offtopic for here

**Comment by Grothesk242** [comment]
I'd strongly disadvise to trigger these kind of actions from js-controller. 
(And I also STRONGLY disadvise to use 'n' or 'nvm' oder any other nodejs-Installation-Manager)

It should be completely the admins task to keep his system up to date, it's not the responsibilty of a third party!
nodejs-update should be the one (and only) BIG exception of interfering into the admins responsibilities. 

If something goes wrong with the system updates it will ultimately fall back to ioBroker and we will be blamed for having crashed the users system!

**Comment by Ilovegym66** [comment]
too dangerous, if someone would like to do this, he can install linux-control-adapter and start with this the upgrade... 
we don't need this in the controller..

**Comment by foxriver76** [comment]
So basically, just support for `sudo apt upgrade nodejs=<version>` for non major upgrades + `iob nodejs-update [major-version]` for major upgrades. And restart controller afterwards.

**Comment by Apollon77** [comment]
I would not allow upgrading top a special nodejs version ... just to "the ltest available one" in the corurrent version schema
