### ISSUE TITLE
DP für die aktuelle und nächste JS Version

### ISSUE THREAD

**Issue by bambi-arch** [ioBroker/ioBroker.js-controller#2502]
Hallo,
gibt es die Datenpunkte analog Node oder NPM, um die aktuelle Version und die nächste Version auf dem jeweiligen Host auszuwerten? Konnte in System leider nichts finden. Würde mir gerne eine Erinnerung per Telegramm senden, wenn Updates anstehen. Danke

**Comment by klein0r** [comment]
- `system.host.<host>.versions.nodeCurrent`
- `system.host.<host>.versions.nodeNewest`
- `system.host.<host>.versions.nodeNewestNext`
- `system.host.<host>.versions.npmCurrent`
- `system.host.<host>.versions.npmNewest`
- `system.host.<host>.versions.npmNewestNext`

*Das ist aber eigentlich eine Support-Frage und kein Issue - gehört hier nicht hin.*

**Comment by bambi-arch** [comment]
@klein0r 
Danke Matthias für die Antwort. Node und NPM hatte ich bereits gefunden. Ich suche diese für die JS Version. Dachte wenn es diese nicht gibt, dass es vielleicht in einer nächsten Version eingebaut werden könnte.

**Comment by klein0r** [comment]
Du meinst die js-controller Version? Die kannst Du vom Admin-Adapter bekommen unter `admin.0.info.updatesJson`. Inhalt ist z.B. bei mir gerade:

```json
{
    "js-controller": {
        "availableVersion": "5.0.14",
        "installedVersion": "4.0.24"
    },
    "socketio": {
        "availableVersion": "6.6.0",
        "installedVersion": "6.3.3"
    },
    "web": {
        "availableVersion": "6.1.10",
        "installedVersion": "5.4.3"
    },
    "ws": {
        "availableVersion": "2.5.8",
        "installedVersion": "2.3.5"
    }
}
```

Du müsstest also schauen, ob es `val['js-controller'].availableVersion` gibt. Könnte man auch per Alias lösen:

<img width="460" alt="Screenshot 2023-10-25 at 13 22 34" src="https://github.com/ioBroker/ioBroker.js-controller/assets/1959049/2ba1f14d-3351-427e-ab10-1733a2fe7588">

Lese-Funktion:

`JSON.parse(val)?.['js-controller'].availableVersion`

Aber: Das wird Offtopic hier. Bitte Issue schließen.
