### ISSUE TITLE
Reset instance states to 0 when instance is stopped (system.adapter.x.y.*)

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.js-controller#2503]
When an instance is stopped, values like memRss keep the last value. Which should be changed to 0.

- cpu
- cputime
- inputCount
- outputCount
- memHeapTotal
- memHeapUsed
- memRss
- ...

<img width="1197" alt="Screenshot 2023-10-25 at 10 29 49" src="https://github.com/ioBroker/ioBroker.js-controller/assets/1959049/19959969-7728-435b-a5a8-cb29dcc24688">

**Comment by Apollon77** [comment]
or we set them all with a expiry timeframe? because else they would still stay on a crash case

**Comment by klein0r** [comment]
@Apollon77 Sounds good!

https://github.com/ioBroker/ioBroker.js-controller/blob/c3eb295d965fc8b28a48426790021fe34b594227/packages/controller/src/main.ts#L973

Something like `config.system.statisticsInterval + x`
