### ISSUE TITLE
Request add Text in update instruction

### ISSUE THREAD

**Issue by Curtis777** [ioBroker/ioBroker.js-controller#2517]
Hey Guys, I love the work you do,
im using a Docker (unraid) so it would be nice to add the instructions how to update the JS-Controller.
this is missing in the update instructions.
thanks:

1 pkill io
2 iobroker update
3 iobroker upgrade self
4 iobroker start

**Comment by buanet** [comment]
These are not the correct instructions! See https://docs.buanet.de/iobroker-docker-image/docs/#iobroker-adapter-updates

Regards, 
André

**Comment by foxriver76** [comment]
closing due to missing information
