### ISSUE TITLE
[2.0.0] Declare a module (or property of Adapter) that can be used by adapters, e.g. "system"

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.js-controller#252]
Currently, we have a lot of helper functions inside `lib/tools.js`. Some of these are desirable to be used by adapters directly in the future, for example:
* `getSystemNpmVersion`
* `createUuid`
* the upcoming `npmCommand` (https://github.com/AlCalzone/ioBroker.js-controller/tree/tools-npmCommand) and its variants

while others should not be exposed to adapters. I propose that we add a clearly defined way to access these via adapters, which could be one of the following:
* A new property on the adapter instance, e.g. `adapter.system`, which has all these public utility methods
* Or another module we expose via `utils.js` which is included in every adapter. This has the advantage that we don't need an adapter instance and can do stuff during initialization.

This `"system"` module could just import and re-export some methods from `tools.js`. This way, the "external" names of methods could be kept the same while we're free to rename stuff in `tools.js`.

**Comment by AlCalzone** [comment]
We should move this into `iobroker.adapter-core`

**Comment by Apollon77** [comment]
yes

**Comment by Apollon77** [comment]
done
