### ISSUE TITLE
CLI iobroker upgrade adapterName from file

### ISSUE THREAD

**Issue by MK-2001** [ioBroker/ioBroker.js-controller#2520]
Hello, 

currently i am see in the documentation only that I am able to upgrade an adapter from a repository URL with the CLI.
Is it possible to enable it as well to install with the CLI an adapter from a file? 

It would help me to enable during development to test the adapter wit a CI/CD.

Thanks in advance
Marcus

**Comment by foxriver76** [comment]
I think you are most likely searching for [dev-server](https://github.com/ioBroker/dev-server) when its about development.

Else yes, afair `iob url <path>` is also able to install your adapter when previously packed with `npm pack`.

**Comment by MK-2001** [comment]
May be it is the command 
`iobroker url [URL]`
but it is currently not documented here: https://iobroker.readthedocs.io/de/latest/basics/cli.html
