### ISSUE TITLE
[TypeDefinition-Dev] Type  { statusStates: { onlineId: string; }; }  is not assignable to type  Partial<DeviceCommon> 

### ISSUE THREAD

**Issue by DutchmanNL** [ioBroker/ioBroker.js-controller#2534]
### No existing issues.

- [X] There is no existing issue for my problem.

### Description

When I use extendObject with type device and add statusStates, IDE gives an error:
"Type  { statusStates: { onlineId: string; }; }  is not assignable to type  Partial<DeviceCommon> "

example:

```
				// Extend online state to device (to ensure migration of version < 0.3.1
				await this.extendObjectAsync(_devices.rows[currDevice].id, {
					type: 'device',
					common: {
						statusStates: {
							onlineId: `${_devices.rows[currDevice].id}.info._online`
						}
					},
				});
```

![Screenshot 2023-11-11 at 14 52 42](https://github.com/ioBroker/ioBroker.js-controller/assets/7318445/397a64e0-a29f-40a0-ae4f-bd0a82dd40b7)

just using extendObject an adding this common part is no issue, so this happens only if you provide the object type 'device'

```
				// Extend online state to device (to ensure migration of version < 0.3.1
				await this.extendObjectAsync(_devices.rows[currDevice].id, {
					common: {
						statusStates: {
							onlineId: `${_devices.rows[currDevice].id}.info._online`
						}
					},
				});
```

**Comment by foxriver76** [comment]
So from admin code we can have `onlineId`, `offlineId`, and `errorId`

**Comment by Apollon77** [comment]
Yes I think we defined these
