### ISSUE TITLE
[bug]: Version 5.0.14 breaks iobroker.node-red node 'ioBroker get'

### ISSUE THREAD

**Issue by TheRealArthurDent** [ioBroker/ioBroker.js-controller#2539]
### No existing issues.

- [X] There is no existing issue for my problem.

### Description

Version 5.0.14 of the js-controller is breaking the node 'ioBroker get' of iobroker.node-red when referencing a non-existent value.

I assume it's more of a bug in iobroker.node-red but still raise the issue here since an update to the js-controller made it apparent (see reproduction).
Looking through the changes in 5.0.14 I am pretty sure I can pinpoint the root cause on [this change](https://github.com/ioBroker/ioBroker.js-controller/commit/965d186bf003bdd825a4429a406aece31e24f56d).
However, maybe it's more about how to handle this error [here](https://github.com/ioBroker/ioBroker.node-red/blob/master/nodes/ioBroker.js#L722C21-L722C31).  

### Reproduction instruction

The issue is easily reproducable, executing the trigger in the following reproducer flow.

```
[
    {
        "id": "bc1156160d508add",
        "type": "tab",
        "label": "Reproducer",
        "disabled": false,
        "info": "",
        "env": []
    },
    {
        "id": "4da89144d3e046bb",
        "type": "ioBroker get",
        "z": "bc1156160d508add",
        "name": "Test",
        "topic": "a.value.that.does.not.exist",
        "attrname": "payload",
        "payloadType": "value",
        "errOnInvalidState": "false",
        "x": 430,
        "y": 120,
        "wires": [
            [
                "e243184c8d6c7b8e"
            ]
        ]
    },
    {
        "id": "615b37e54a9f199d",
        "type": "inject",
        "z": "bc1156160d508add",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 220,
        "y": 120,
        "wires": [
            [
                "4da89144d3e046bb"
            ]
        ]
    },
    {
        "id": "e243184c8d6c7b8e",
        "type": "debug",
        "z": "bc1156160d508add",
        "name": "I survived!",
        "active": true,
        "tosidebar": true,
        "console": true,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "statusVal": "",
        "statusType": "auto",
        "x": 650,
        "y": 120,
        "wires": []
    }
]
```

It'll succeed with every js-controller until including 5.0.13 but fail with 5.0.14 through 5.0.16 (latest at the time creating this issue).

# Pre 5.0.14
> 2023-11-19 14:27:25.603 - info: node-red.0 (196) 19 Nov 14:27:25 - [info] [debug:I survived!]
> {
> _msgid: '2f0552a68066d20c',
> payload: '',
> topic: 'node-red.0.a.value.that.does.not.exist'
> }

# 5.0.14 through 5.0.16
> 2023-11-19 14:19:49.749 - error: node-red.0 (202) 19 Nov 14:19:49 - [error] TypeError: Cannot read private member from an object whose class did not declare it
> at __classPrivateFieldGet (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:27:94)
> at getObject (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:2498:14)
> at Immediate. (/opt/iobroker/node_modules/iobroker.node-red/nodes/ioBroker.js:722:21)
> at process.processImmediate (node:internal/timers:478:21)
> 2023-11-19 14:19:49.768 - info: node-red.0 (202) node-red exited with 1

**Comment by foxriver76** [comment]
From controller persepctive everything looks good, it seems like the `this` context is messed up as the functions are assigned.

https://github.com/ioBroker/ioBroker.node-red/blob/cb3aafe83518628fe422aca5db7d75032bf3a43c/nodes/ioBroker.js#L721 probably needs to bind the adapter.

**Comment by foxriver76** [comment]
You could try to replace the line by

```js
 const getObjFunc = isForeignState(id) ? adapter.getForeignObject.bind(adapter): adapter.getObject.bind(adapter);
 ```

**Comment by foxriver76** [comment]
Please create a PR or issue at node-red

**Comment by foxriver76** [comment]
And thanks for the well defined issue, really appreciate this one.

**Comment by TheRealArthurDent** [comment]
> You could try to replace the line by
> 
> ```js
>  const getObjFunc = isForeignState(id) ? adapter.getForeignObject.bind(adapter) : adapter.getObject.bind(adapter);
> ```

Thx. Works like a charm, as mentioned in the related PR.
