### ISSUE TITLE
[1.5] Vis Fehler seit update  Empty ID

### ISSUE THREAD

**Issue by sigi2345** [ioBroker/ioBroker.js-controller#254]
Hallo,
Ich komme nur bis zu VIS.0 dann zurück geht nicht mehr.
![screenshot 651](https://user-images.githubusercontent.com/41079106/45443634-8f130100-b6c5-11e8-928e-f17f3f8b0246.png)
![screenshot 643](https://user-images.githubusercontent.com/41079106/45443672-a9e57580-b6c5-11e8-8429-572d91216fe0.png)

DETAILS:
[https://forum.iobroker.net/viewtopic.php?f=30&t=16802](url)

![screenshot 655](https://user-images.githubusercontent.com/41079106/45445484-a86a7c00-b6ca-11e8-9cc2-548b439b523f.png)

**Comment by arteck** [comment]
bei mir ist alles gut
![grafik](https://user-images.githubusercontent.com/6681528/45444879-0007e800-b6c9-11e8-9ba5-abc040e02d48.png)

**Comment by Apollon77** [comment]
browser cache empty?

**Comment by sigi2345** [comment]
Alles versucht, wird nicht.
Habe ja das selbe Problem an 2 verschiedenen Systemen:  WIN 10 + PI3

**Comment by sigi2345** [comment]
Nach einen downgrade des js-controller von 1.5.0 auf 1.4.2 und einen Neustart von ioBroker und einer Neuinstallation von icons-mfd-svg mit anschließender Leerung des Browser Cache geht es wieder. 

Ist das Windows System, auf den PI3 geht es noch nicht. Ich werde es dort auch so machen.

**Comment by sigi2345** [comment]
Nach update auf Version 1.5.1 selber Fehler!

**Comment by GermanBluefox** [comment]
Ich kann das nicht reproduzieren :(

**Comment by sigi2345** [comment]
Vielleicht hilft dir das:

`Create inner vis object hm-rpc.0.xxxxxxxxxx.4.MANU_MODE
vis.js:2970 Create inner vis object ping.0.MedionPc.192_xxxxxxxxxxx
vis.js:2970 Create inner vis object kodi.0.previous
vis.js:2970 Create inner vis object 127.0.0.1:80
vis.js:2970 Create inner vis object kodi.0.clear
vis.js:2970 Create inner vis object kodi.0.system.Reboot
vis.js:2970 Create inner vis object kodi.0.system.Shutdown
vis.js:2970 Create inner vis object hm-rpc.0.OEQxxxxxxxxx.1.STATE
vis.js:2970 Create inner vis object hue.0.Philips_hue.WC.on
vis.js:2970 Create inner vis object 125
vis.js:2970 Create inner vis object 100
vis.js:2970 Create inner vis object 50
vis.js:2970 Create inner vis object ping.0.MedionPc.192_16xxxx_22
vis.js:2970 Create inner vis object hm-rpc.0.Nxxxxxxxx.1.LOWBAT
vis.js:2970 Create inner vis object ping.0.MedionPc.192_168_178
s.js:2970 Create inner vis object ping.0.MedionPc.192_168_
vis.js:2970 Create inner vis object 0
vis.js:2970 Create inner vis object system.adapter.javascript.0.alive
vis.js:2970 Create inner vis object javascript.0.HWInfo.MedionPc.CPU.Load
vis.js:2970 Create inner vis object javascript.0.HWInfo.MedionPc.CPU.Speed
vis.js:2970 Create inner vis object javascript.0.HWInfo.MedionPc.CPU.Temp
vis.js:2970 Create inner vis object musiccast.0.RX-V481_08125F03.netusb.next
vis.js:2970 Create inner vis object musiccast.0.RX-V481_08125F03.netusb.prev
vis.js:2970 Create inner vis object musiccast.0.RX-V481_08125F03.netusb.playPause
vis.js:2970 Create inner vis object ping.0.Medion.192_168_178_51
vis.js:2970 Create inner vis object ping.0.MedionPc.192_168_178_35
vis.js:2970 Create inner vis object vis.0.Huawai.battery.level
vis.js:2970 Create inner vis object hm-rpc.0.NEQ1xxxxxxxxxxxUNREACH
vis.js:2970 Create inner vis object hm-rpc.0.NExxxxxxxxxxxxx.STICKY_UNREACH
vis.js:2970 Create inner vis object hm-rpc.0.xxxxxxxxxxxxxx0.UNREACH
vis.js:2970 Create inner vis object system.adapter.hue.0.connected
vis.js:2970 Create inner vis object javascript.0.scriptEnabled.Ansage_Temperatur
vis.js:2970 Create inner vis object javascript.0.scriptEnabled.Ansage_Wind
vis.js:2970 Create inner vis object javascript.0.scriptEnabled.
vis.js:2970 Create inner vis object javascript.0.scriptEnabled.Ansage_alles
vis.js:2970 Create inner vis object javascript.0.scriptEnabled.Ansage_Hausmüll
vis.js:2970 Create inner vis object javascript.0.scriptEnabled.Ansage_Geburtstag
vis.js:2970 Create inner vis object http://192.168.178.27:50000/tts=test
vis.js:2970 Create inner vis object http://192.168.178.27:50000/tts=
vis.js:2970 Create inner vis object http://192.168.178.27:50000/tts
vis.js:2970 Create inner vis object http://192.168.178.27:50000/t
vis.js:2970 Create inner vis object http://192.168.178.27:50000/tts=
vis.js:2970 Create inner vis object http://192.168.178.27:50000/tts=
vis.js:2970 Create inner vis object http://192.168.178.27:50000/tts=
vis.js:2970 Create inner vis object http://192.168.178.27:50000/tts=
vis.js:2970 Create inner vis object http://192.168.178.27:50000/tts=
vis.js:2970 Create inner vis object http://192.168.178.27:50000/tts=
vis.js:2970 Create inner vis object http://192.168.178.27:50000/tts=
vis.js:2970 Create inner vis object javascript.0.Status.Lichter.State
vis.js:2970 Create inner vis object hm-rpc.0.NEQ1xxxxxxxxxxx.POWER
vis.js:2970 Create inner vis object 150
vis.js:2970 Create inner vis object 962
vis.js:2970 Create inner vis object 940
vis.js:2970 Create inner vis object 1200
vis.js:2970 Create inner vis object 200
vis.js:2970 Create inner vis object dwd.0.warning.text
vis.js:2970 Create inner vis object dwd.0.warning.severity
vis.js:2970 Create inner vis object javascript.2.Grafana.DashboardURL
vis.js:2970 Create inner vis object daswetter.0.NextDaysDetailed.Location
vis.js:2970 Create inner vis object daswetter.0.NextDaysDetailed.0d.4h.Clouds
vis.js:2970 Create inner vis object tun
vis.js:2970 Create inner vis object yamaha.0.Realtime.BT.DEVICENAME
translate.js:20 "Use background": {"en": "Use background", "de": "Use background", "ru": "Use background"},
7translate.js:20 "ctrl - Bool": {"en": "ctrl - Bool", "de": "ctrl - Bool", "ru": "ctrl - Bool"},
edit.html:18038 Version vis-timeandweather: 1.1.7
jquery.zweatherfeed.js:555 w01297
bars.js:55 Version vis-bars:0.1.4
selectID.js:771 Error: Assertion failed 
    at Function.error (jquery-1.11.2.min.js:2)
    at d (jquery.fancytree-all.min.js:40)
    at g (jquery.fancytree-all.min.js:40)
    at r.nodeRender (jquery.fancytree-all.min.js:40)
    at r.nodeRender (jquery.fancytree-all.min.js:12)
    at r._callHook (jquery.fancytree-all.min.js:12)
    at f (jquery.fancytree-all.min.js:13)
    at r.nodeSetExpanded (jquery.fancytree-all.min.js:13)
    at r.h (jquery.fancytree-all.min.js:12)
    at r.nodeSetExpanded (jquery.fancytree-all.min.js:40)
(anonymous) @ selectID.js:771
visit @ jquery.fancytree-all.min.js:12
visit @ jquery.fancytree-all.min.js:12
visit @ jquery.fancytree-all.min.js:12
visit @ jquery.fancytree-all.min.js:12
visit @ jquery.fancytree-all.min.js:12
visit @ jquery.fancytree-all.min.js:12
showActive @ selectID.js:764
initTreeDialog @ selectID.js:3178
show @ selectID.js:3541
$.fn.selectId @ selectID.js:3921
click @ visEditInspect.js:109
dispatch @ jquery-1.11.2.min.js:3
r.handle @ jquery-1.11.2.min.js:3
selectID.js:417 Error: Assertion failed 
    at Function.error (jquery-1.11.2.min.js:2)
    at d (jquery.fancytree-all.min.js:40)
    at g (jquery.fancytree-all.min.js:40)
    at r.nodeRender (jquery.fancytree-all.min.js:40)
    at r.nodeRender (jquery.fancytree-all.min.js:12)
    at r._callHook (jquery.fancytree-all.min.js:12)
    at q.render (jquery.fancytree-all.min.js:12)
    at q.sortChildren (jquery.fancytree-all.min.js:12)
    at sort (selectID.js:415)
    at sort (selectID.js:421)
selectID.js:417 Error: Assertion failed prev. row must have a tr, or is system root
    at Function.error (jquery-1.11.2.min.js:2)
    at d (jquery.fancytree-all.min.js:40)
    at r.nodeRender (jquery.fancytree-all.min.js:40)
    at r.nodeRender (jquery.fancytree-all.min.js:12)
    at r._callHook (jquery.fancytree-all.min.js:12)
    at q.render (jquery.fancytree-all.min.js:12)
    at q.sortChildren (jquery.fancytree-all.min.js:12)
    at sort (selectID.js:415)
    at sort (selectID.js:421)
    at sort (selectID.js:421)`

**Comment by sigi2345** [comment]
Das Problem tritt nicht nur bei mir auf.........
Es haben schon mehrere User davon berichtet....

[https://forum.iobroker.net/viewtopic.php?p=177732#p177717](url)

**Comment by Apollon77** [comment]
Code wise there is an "Empty ID" callback in https://github.com/ioBroker/ioBroker.js-controller/blob/master/lib/objects/objectsInMemServer.js#L681 and yes sanitizing path's and stuff was part of 1.5.x ... so in this case the question is why the ID is empty.

According to infos here I would expect that it is the ID hand over to "readDir" ...

@GermanBluefox may this as hint? What is the ID here? maybe ok to be empty?

because multiple user report this I reopen here

**Comment by sigi2345** [comment]
Hallo, Fehler ist bei mir mit Version 1.5.3 weg.

![screenshot 1499](https://user-images.githubusercontent.com/41079106/50734198-de60ce00-119b-11e9-942b-9974347d6b1e.png)

**Comment by intruder7777** [comment]
also bei mir kommt der Fehler noch. sigi... sobald ich vom Pfad /icons-mfd-svg/ einen zurück gehen will kommt der Fehler.

**Comment by Apollon77** [comment]
Nochmal Rückfrage. Kommt nur bei / als Ziel korrekt? Wenn du was valides eingibst manuell geht es wieder. Korrekt?

**Comment by intruder7777** [comment]
und wenn ich /opt/iobroker/iobroker-data/files/ direkt eingebe bei Pfad geht es auch nicht.

**Comment by Apollon77** [comment]
Letzteres war klar. ;-)

**Comment by GermanBluefox** [comment]
That should be fixed with https://github.com/ioBroker/ioBroker.vis/commit/c84717a2e1e26d24ee7566a0a367bf5ab7ab46d5#diff-58e34cd01c5cdc8d24b9ac016744040dR90

**Comment by Apollon77** [comment]
so vis 1.1.8 ...

**Comment by Apollon77** [comment]
1.5.7 is released, so I close here
