### ISSUE TITLE
HTTPS not works after update 1.5

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.js-controller#255]
i have here a white site... 
![grafik](https://user-images.githubusercontent.com/6681528/45443912-57588900-b6c6-11e8-8ac8-b18e8d489b3b.png)

without Authentification its ok.... 

with auth
![grafik](https://user-images.githubusercontent.com/6681528/45446398-13b54d80-b6cd-11e8-9aa8-743c5302f53f.png)

**Comment by AlCalzone** [comment]
Some investigation:
https://github.com/ioBroker/ioBroker.admin/blob/master/lib/web.js#L426
`adapter.config.certificates` is probably `undefined`, which means that in
https://github.com/ioBroker/ioBroker.js-controller/blob/master/lib/letsencrypt.js#L173
`certificates` is undefined.

Seems to be the same error as https://forum.iobroker.net/viewtopic.php?p=134532#p134532, what fixed it then?

**Comment by arteck** [comment]
no its other problem.

![grafik](https://user-images.githubusercontent.com/6681528/45472985-08e2d300-b736-11e8-82c5-283373053dc2.png)

**Comment by AlCalzone** [comment]
But the root cause is the same if I belive your post in the forums:
```
2018-09-12 20:31:51.974  - [31merror[39m: admin.0 TypeError: Cannot read property 'NPNProtocols' of undefined
    at new Server (https.js:15:40)
    at Object.exports.createServer (https.js:47:10)
    at Object.createServer (/opt/iobroker/node_modules/iobroker.js-controller/lib/letsencrypt.js:173:39)
    at __construct (/opt/iobroker/node_modules/iobroker.admin/lib/web.js:426:32)
    at new Web (/opt/iobroker/node_modules/iobroker.admin/lib/web.js:457:7)
    at /opt/iobroker/node_modules/iobroker.admin/main.js:292:29
```
This means the https server is never started.

**Comment by arteck** [comment]
so.  admin works with auth.. vis not ..

**Comment by AlCalzone** [comment]
What did you change?

**Comment by arteck** [comment]
das Problem bestand schon mal nachwechsel zu 1.4.2.. bluefox hat das dann korrigiert.. 
so wie es aussieht geht die session verloren.. ich kann keine VIS Editieren wenn ich auth eingeschaltet lasse und mich auch nicht einlogen (das login kommt garnicht mit den Fehlern von oben)

[forum](https://forum.iobroker.net/viewtopic.php?f=8&t=14056&hilit=login)

kontrolliere einfach bei dir obs geht.. https an und auth an..
nimm die schon vorhanden zertifikate

**Comment by BuZZy1337** [comment]
https://github.com/ioBroker/ioBroker.telegram/issues/70#issuecomment-421114660

Gibt's hier vielleicht ein Zusammenhang?!

**Comment by vr6syncro** [comment]
> [ioBroker/ioBroker.telegram#70 (comment)](https://github.com/ioBroker/ioBroker.telegram/issues/70#issuecomment-421114660)
> 
> Gibt's hier vielleicht ein Zusammenhang?!

Auch mit 1.5.2 geht es nicht mit SSL

**Comment by arteck** [comment]
mit 1.5.3 auch nicht.. da stimmt mit den sessions was nicht.. die werden nicht durchgereicht habe ich das gefühl..
vom Admin mit auth in der version 1.5.3 lädt garnichts. ich komme auf kein Tab drauf.. 
Visu Edit läuft garnicht.. 
geschweige denn das Login

**Comment by Apollon77** [comment]
Sicher das alles sauber nach Update neu gestartet wurde und wirklich die 1.5.3 läuft?

**Comment by arteck** [comment]
aber sowas von.. :-) mach es ja nicht zum ersten mal..

**Comment by Ilovegym66** [comment]
Hi, hab mal rumgespielt.. kann man nachvollziehen, wenn man im Webadapter Auth einschaltet, aber bei socket.io nicht. Es muss beides auf Auth stehen, dann geht es - ABER:
 es werden nicht die vorhandenen Configs von Vis, Habpanel und Material übernommen, sondern neue erzeugt.. also irgendwo ist da noch was... 
@arteck hast du den Socket.io installiert? Was hast du da eingestellt?

js-controller 1.5.3, npm 6.4.0, node 8.11.4

**Comment by arteck** [comment]
ja ich habe socket.io auch am laufen.. nur hier benötige ich den auth nicht..

**Comment by arteck** [comment]
geht
