### ISSUE TITLE
[Types]: common.desc is missing in type=device

### ISSUE THREAD

**Issue by ticaki** [ioBroker/ioBroker.js-controller#2558]
### No existing issues.

- [X] There is no existing issue for my problem.

### Description

The description should be allowed everywhere.

vscode:
`Das Objektliteral kann nur bekannte Eigenschaften angeben, und "desc" ist im Typ "Partial<DeviceCommon>" nicht vorhanden.`

**Comment by foxriver76** [comment]
Have we ever defined, if devices can have an attribute `desc` @Apollon77? According to types it has never been allowed. Only for States.

**Comment by Apollon77** [comment]
I think we never thought. Unwound allow dead for all types. A typical "why not?" ;-)

**Comment by foxriver76** [comment]
Okay, ChannelCommon also has it, so it should be allowed for device too. And maybe just like name allow for all.
