### ISSUE TITLE
web stopped delivering some files

### ISSUE THREAD

**Issue by goko** [ioBroker/ioBroker.js-controller#256]
today after upgrading js-controller to 1.5.0 the io.web stopped delivering some files with error "CONTENT_LENGTH_MISMATCH". see failed state in second column.
tried with different browsers, cleared credentials etc...
no useful logs on iobroker level

![auswahl_014](https://user-images.githubusercontent.com/3899424/45479493-f0c77f80-b746-11e8-91c0-b4e2cecccea7.png)

**Comment by arteck** [comment]
done

**Comment by GermanBluefox** [comment]
Is there some PR to fix it? Or is this error fixed in 1.5.3?

Am Fr., 16. Nov. 2018, 18:43 hat arteck <notifications@github.com>
geschrieben:

**Comment by Apollon77** [comment]
Done meaned „fixed in 1.5.3“
