### ISSUE TITLE
[enhancement]: Automatically replace protected attribute values in log messages

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.js-controller#2560]
### No existing issues.

- [X] There is no existing issue for my request.

### Description

It is possible to protect some information via io-package in `protectedNative`.

**It would be nice if those information would never leave the instance (e.g. in log messages).**

The idea is, to replace all sensitive information in the log message (e.g. with `******`). If someone uses `this.log.info(this.config.secretPassword)` the value should be replaced.

Possible issues: "Simple" passwords / values could replace other information in the log.

### Why?

No sensitive / protected information should be logged.

**Comment by foxriver76** [comment]
I have no idea how we should detect if the passed value is coming from the native etc, maybe I am thinking in a wrong direction but it seems technically not possible or at maximum possible as a heuristic

**Comment by mcm1957** [comment]
First: The idea to block all sensitive information is really desireable, but:

I do not think thats there any possibility to detect for sure at which places a password is logged. This could be a plain text but also part of an url or within the dump of some data and much more. In many cases I've seen debug logs of urls called which contain the password.

The only idea I have is to retrieve the values of all protected fields and replace all such strings in all logging. This would for sure block logging a password but could have funny sideeffects whenever a user i.e. uses 'ioBroker' (or i.e. '123456', 'error', ....) as password.

**Comment by klein0r** [comment]
> This would for sure block logging a password but could have funny sideeffects whenever a user i.e. uses 'ioBroker' (or i.e. '123456', 'error', ....) as password.

Yes, that's the problem. Maybe the log function can get an additional parameter (like "sensitive: true"). A general replacement in every `.log`-call can lead to weird effects.

**Comment by mcm1957** [comment]
I don't thing that an option to .log* will improve anything. Incorrect replacements would occure in this case too. An most likely devs simply would not care to set it. If a dev is aware of critical data within the logs he can filter them out already. If he is not aware I doubt that he would set the flag.

From review I saw very seldom direkt logs containing a password explicitly. Most likely passwords are logged as part of urls or as part of error messages and dumps. And prohibiting them in error messages and dumps is a extra problem und less you know the format of the dump in detail.

**Comment by foxriver76** [comment]
After talking with @Apollon77 we all have no idea how to do this reliable exactly due to the reasons @mcm1957 mentioned. 

If you have already an idea in mind @klein0r, let us know. Else we would reject this request as it seems technically not possible to us.

**Comment by klein0r** [comment]
@foxriver76 I've also no idea how to implement that reliable. Because it's just a string which will be received... of any source. I've implemented a simple function for `pvforecast` to solve that right now:

https://github.com/iobroker-community-adapters/ioBroker.pvforecast/commit/3f0898159f22828289e626122ef6da352ef28b8c

**Comment by mcm1957** [comment]
Well, thats whats implemented at pvforeast is some heuristic still. If the token value matches some otehr data, this data will be destroyed too; although the risk is minimal at tokens. Passwords are much more critical to be some "real text" in my oppinion.

And as the logs at pvforecast contain an explicitly created url part conatainig theaccess token, I would have simply logged a seperate string where **** is inserted instead of the real data. (= used one string for logging and a seperate for sending; the risct that those differ due to a copy and paset error exists, but should be minimal when coding seriously). Scanning the whole config loks like an overhead - but this is up to the code maintainer of course.

see i.e. https://github.com/iobroker-community-adapters/ioBroker.pvforecast/blob/3f0898159f22828289e626122ef6da352ef28b8c/main.js#L626-L627

Anyway - using the function requires that the developer is aware of the problem. A real benefit would exist if the masking occures without explicit action by the dev - but that seems to be impossible.

**Comment by mcm1957** [comment]
And THANKs for hiding the token at pvforecast in such a short time. I noticed this improvemnt possibility at forum discussion and asked the user to create a Issue -at the adapters repo.  This was only a few days ago if I remember correctly.

**Comment by mcm1957** [comment]
@foxriver76 
@klein0r 
@Apollon77 

I suggest to reopen this ssue.

I just analyzed what github does to protect secrets. And it looks like that github replaces all strings at logging which match one of the secrets by ***. So maybe we should really consider to replace every string at logging (or logging output if this is easier)  which matches a secret (protected parameter) by *** and wait if any problems are reported. The security enhancement would be sufficient to rectify such a modification of logs. In some future version we could even think about displaying the full text on manual demand if theres really a need for it if we filter on output.

**Comment by foxriver76** [comment]
GitHub secrets are normally much more unique than some user password etc I am still against this.

**Comment by Apollon77** [comment]
I agree to not reopen, also because the amount of logging in iobroker (and also the kind of hardware platforms it runs on!!) can not being compared to GitHub
