### ISSUE TITLE
enum `STATE_QUALITY` does not exist at runtime

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.js-controller#2571]
https://github.com/ioBroker/ioBroker.js-controller/blob/5c68c593a86f333597a4506cf6e8c9c301a8ebe0/packages/types-dev/index.d.ts#L17

...but the type definitions suggest it does. We should make it an actual enum at runtime and/or export it from adapter-core

**Comment by foxriver76** [comment]
yes, indeed it should not be an enum here, maybe an interface or remove entirely.

At runtime it is available at `adapter.constants.STATE_QUALITY`

https://github.com/ioBroker/ioBroker.js-controller/blob/5c68c593a86f333597a4506cf6e8c9c301a8ebe0/packages/adapter/src/lib/adapter/adapter.ts#L722-L724
