### ISSUE TITLE
VIS-problem with alias

### ISSUE THREAD

**Issue by Wildbill-Z** [ioBroker/ioBroker.js-controller#2579]
### No existing issues.

- [X] There is no existing issue for my problem.

### Description

As written in [forum thread](https://forum.iobroker.net/post/1106445) since js-controller 5.x there seems to be a problem in VIS (1), when using objects with alias. Without these objects, vis is working fine, after changing one or more widgets to link to alias objects, other widgets are showing "null" or "nan" an only show the values, when the object got a new value or at least got actualized. Switching back to 4.0.24 of js-controller seems to "solve" the problem, so it seems to have to do with js-controller 5+.

**Comment by foxriver76** [comment]
Unfortunately this is very vague. Are only the widgets showing null and the alias values are correct when determined via getState, then it would be "maybe" something in constellation between web/socket adapters and js-controller.

**Comment by Wildbill-Z** [comment]
It is not the alias-widget, which is showing the wrong value. The alias-widgets are always working correct. Values within the objects and alias are always showing the correct values, when I look to objects-site in second window.
Widgets linked to "real" datapoints (not to alias) are the problem.
This is my new Test-view with 3 widgets. The above one in this picture is linked directly to an object in deconz.0...
<img width="249" alt="image" src="https://github.com/ioBroker/ioBroker.js-controller/assets/35911150/5fd5e240-93a4-43ac-abb9-e47a5dc0e911">
The other two are number widgest, which show an outtemp and humidity under javascript.0...
All is working fine.

Now, this is, when I change the first widget to link to an ALIAS of the deconz.0-object:
<img width="249" alt="image" src="https://github.com/ioBroker/ioBroker.js-controller/assets/35911150/6d8f50ce-24d3-49a2-9c8e-8396c985ad93">

After waiting a minute or so until the values of the other two have changed, they show the values as expected.
<img width="249" alt="image" src="https://github.com/ioBroker/ioBroker.js-controller/assets/35911150/79a25064-c396-4a6f-aeb2-ca77bf51d29d">
 
After page refresh they just start again showing 0 / nan.

In vis editor after doing changes the values are always show correctly, even after hard page refresh. It's just the View. It is the same if using on Mac (Safari), Linux (Firefox) or ipad/iphone.

**Comment by Wildbill-Z** [comment]
How should I provide you a backup of my whole system?

**Comment by foxriver76** [comment]
`iob backup` and provide me the generated `tar.gz` file. If not too large via mail `moritz.heusinger@gmail.com`

**Comment by foxriver76** [comment]
Check versions of `socketio`, `ws` and web` if installed separately as well as settings of `web`

Especially these options 

![grafik](https://github.com/ioBroker/ioBroker.js-controller/assets/25484431/6635694c-4fdd-4064-b50d-0230fe550970)

**Comment by foxriver76** [comment]
Then really, no idea what the difference between our setups is which could have influence on this topic. Not sure how technically savvy and motivated you are. If running on proxmox this would be easy. You could do the backup procedure, restore on a different machine get rid of all critical adapters and provide me the export or maybe someone has the problem too and can provide one.

**Comment by Wildbill-Z** [comment]
Yes, running within Proxmox as a VM. Despite of time, it would not be a problem to install into a second VM, get rid of the critical adapters and do an export. Do you mean an export with the backup-tool within iobroker or of whole VM within Proxmox? Which adapters will be essential for debugging this problem?

**Comment by foxriver76** [comment]
Yeah, time is always the problem :D

Backup via cli will be better for me, it will contain the states and objects database. As I probably need to debug which is better on my local machine then inside Proxmox.

**Comment by Wildbill-Z** [comment]
I'll see, if I can ran this parallel to my work. :-)
How should I send the backup to you? I don't know if there is something like PM in Github?!

**Comment by foxriver76** [comment]
No, there is not. Really depends on the size of the backup, mail to `moritz.heusinger@gmail.com` is fine if file size lets you. Or use something like https://easyupload.io/ and send me the password via mail.

**Comment by jogibear9988** [comment]
@Wildbill-Z 

Maybe you could reproduce in my test installation?
http://129.159.205.3:8081/

I could give you access if you would try to.

Maybe if you could reproduce it @foxriver76 could look there?

**Comment by Wildbill-Z** [comment]
@jogibear9988 You just could test by yourself. Just mak a vis-view with some widgets and check if they show the correct values. Then change one of them to an alias-object. If the others no more show the correct value until they are actualized, you have the problem within your system. As in forum thread, even those with the problem don't habe the problem after a clean test install, I bother, if it would change anything, if the issue occurs on your test system.

@foxriver76 Clone of VM is running, I'll send it via E-Mail after removing the critical adapters (and some more...)

**Comment by jogibear9988** [comment]
@Wildbill-Z 
I've never used vis.
If you'd like to, I could give you access, if not, also okay.

**Comment by Wildbill-Z** [comment]
Let‘s just check my backup, which I will send to @foxriver76 hopefully today. If he nedds something more to play, you can grant him access,

**Comment by Wildbill-Z** [comment]
Sent my e-mail to @foxriver76 . Hopefully he gets it as it was nearly 21MB. Had problems first as I use redis and influx on different hosts, but I got it. :-)

**Comment by foxriver76** [comment]
received, thanks will look into it.

**Comment by foxriver76** [comment]
quickfix: 

delete this object
![grafik](https://github.com/ioBroker/ioBroker.js-controller/assets/25484431/896751db-61f1-4bb1-b77f-371c7d0cd009)

**Comment by Wildbill-Z** [comment]
Just deleted the object and BINGO. Vis is working as expected with alias-objects. Many thanks.

**Comment by foxriver76** [comment]
Thanks for confirming, will let it open here, still the behavior should not be like this by controller if such an object exists.

**Comment by gBonfire** [comment]
Same Problem and same solution here. Works fine. Thank you very much !!!

**Comment by gBonfire** [comment]
> Just deleted the object and BINGO. Vis is working as expected with alias-objects. Many thanks.

Same Problem and same solution here. Works fine. Thank you very much !!!
