### ISSUE TITLE
[enhancement]: Allow selective backup restore

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker.js-controller#2588]
### No existing issues.

- [X] There is no existing issue for my request.

### Description

ioBroker currently saves all information regulary. But currently only a restauration of the complet system is possible.

Please consider to selectivly restore the configuration of a single adapter from backup.

Use cases:
- unwanted changes of configuraton
- loss of configuration due to an adapter error / upgrade failure

### Why?

Currently the complete backup needs to be restored into dummy system to be able to extract the configuration of an adapter. This information can then be imported into the real system

The configuration infomation of all adapters is saved at backup. So it should be able to extract the config of a single adapter and restore it. This would be much more useable for normal users than using a dummy system and manipulati ng objects in expert mode.

**Comment by foxriver76** [comment]
Related or maybe duplicate of https://github.com/ioBroker/ioBroker.js-controller/issues/1203

**Comment by mcm1957** [comment]
Yes that's a duplicate
Sorry - didnt pop up for me.
