### ISSUE TITLE
Starting instance triggers all states

### ISSUE THREAD

**Issue by BuZZy1337** [ioBroker/ioBroker.js-controller#259]
Kurz & schnell auf Deutsch:
Beim Start von einem Adapter wird jeder state getriggert.
```js
adapter.on('stateChange', function (id, state) {
    if (!state || state.ack) return;
    //rest of code
}
```
`rest of code` wird nach jedem Adapterstart ausgeführt ohne dass ein State vom User aktiv getriggert wurde!

@Apollon77 sagt es hat etwas mit "quality check" zu tun?

**Comment by Apollon77** [comment]
I have commented the reasoning commit and needed fixes .. will do later

https://github.com/ioBroker/ioBroker.js-controller/commit/3767b1482b68fa73dcc54ece07a8e573423ac07c#commitcomment-30511649
