### ISSUE TITLE
[bug]: no Changelog for 5.0.18 ?

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.js-controller#2596]
### No existing issues.

- [X] There is no existing issue for my problem.

### Description

Changelog is missing for 5.0.18

Leads to

<img width="660" alt="Screenshot 2024-01-30 at 08 53 13" src="https://github.com/ioBroker/ioBroker.js-controller/assets/1959049/23ae7245-c478-4b8a-8e2b-36f512949733">

**Comment by foxriver76** [comment]
ah thanks, of course only on the 5.0.x branch, we need to sync
