### ISSUE TITLE
[enhancement]: Log some info if adapter is not started due to unusual mode setting

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker.js-controller#2607]
### No existing issues.

- [X] There is no existing issue for my request.

### Description

Please indicate why an adapter is stopped especially if cause by soime unusal mode settings.

### Why?

An adapter had mode:subcribe set for whatever reason. (Note: subcribe is a valid mode value!) This resulted in the fact that the adapter worked normally when executing with dev-server. The installed adapter did not start at all, only the follwing lines have been logged:

```
host.Envy | 2024-02-01 12:24:34.129 | info | stopInstance system.adapter.waterkotte-easycon.0 (force=false, process=false)
```

In addition NO icon was shown at instance tab indicating the unusal setting. 

This resulted in aome hours looking for a reason with up to 3 des :-(.

So please consider logging the fact that this adapter das not start "normally" either by setting an icon, logging something at startup (I would suggest to log the process start + mode) or at shutdown, 

Same might be useful for all other modes besides scheduled and daemon as this could lead to the same surprise,

**Comment by foxriver76** [comment]
I would more like with check that the mode is one of the allowed modes as one of the first steps of instance start

https://github.com/ioBroker/ioBroker.js-controller/blob/cc1106e9dee91e438065696623483bf20c1830ed/packages/controller/src/main.ts#L4094

Else log a line like `Cannot start instance XY because it has configured the invalid mode "XY"` and abort the adapter start.

**Comment by mcm1957** [comment]
Subscribe IS a valid mode ...

**Comment by foxriver76** [comment]
After some internal discussions we decided, that subscribe has no purpose anymore and will be removed.

**Comment by mcm1957** [comment]
Thats okfor me to of course.
Thanks for Info.

**Comment by theknut** [comment]
Just a note: please also remove in adapter creator template. That's how I
accidentally selected it. The adapter worked using dev server but would not
start when used in production. It seems like the adapters are started
differently depending on the environment.

Martin M. ***@***.***> schrieb am Sa., 3. Feb. 2024, 17:21:

**Comment by mcm1957** [comment]
Thanks for reminder.
A related issue at creator exists. I'll adapt it.
And Repochecker must be adapted too. I'll take care if I do not forget
