### ISSUE TITLE
[enhancement]: add (optional?) central logging

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker.js-controller#2608]
### No existing issues.

- [X] There is no existing issue for my request.

### Description

Currently logs are processed per host. Everything logged at a slve is visible at admin of the slave (or after switching the admin on master to the slave host.)

Please consider - eventually optional - to send all loggs to the master and store them at the master too. (Local storage is required as long as there is not secured transport to avoid loss if master is down)

### Why?

Currently logs and errors are easily missed as one does not regulary switch admin displays.

### How?

js-controller could send the log to a receiver at master.

As an alternative admin (!) could connect to all slaves and retrieve / show their logs merged into one tab. (If this is prefered the issue should be moved to admin). Minimum solution would be to display number of errors / warnings of all hosts so that one gets triggered to explicitly lokk into slave logs

**Comment by mcm1957** [comment]
OK one addition

Admin already can question all hosts. But this requires hiost switching. which is incomfortable and - must be done :-)
So maybe this issue could really be handled at admin and potenially this the same mechanis as the requested central adpter update display mechanism

**Comment by Apollon77** [comment]
we support syslog as logging option. Setup a syslog server and configurre al slaves to send logs to this amnd you have what you want.

**Comment by mcm1957** [comment]
Syslog is no replacement for a  central view of a ioBroker System status.

Syslog is nor an option for non experuenced users and I m not dure whether it exists at winfoes and mac

The overall goal should be to have a central view directly inside ioBroker to give the user the impression of ONE system asthis has already bben critized.

But I accept the decision

**Comment by foxriver76** [comment]
But then it would be better to have in the selection in Admin like host1, host2 and all. From controller side this is all possible, but in all scenarios it will be ugly “someone" needs to merge log messages eg for log tab on adapter tab you can have different versions on different hosts and maybe more, so more like a feature request for admin.

**Comment by mcm1957** [comment]
Yes your correct.
Should be admin
