### ISSUE TITLE
[enhancement]: Changelog should be reachable during / before update of js-controller

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker.js-controller#2616]
### No existing issues.

- [X] There is no existing issue for my request.

### Description

Wehn updateing js-controller via web page (hists page in admin) the following is displayed:

![image](https://github.com/ioBroker/ioBroker.js-controller/assets/28575778/31d0b04e-6a26-4f08-9eae-634c207091b7)

The Information "Änderungen" - see changelog is not the best a user could expect. 

Its NOT required to list the infomation at this point, but it should be provided by a clickable link or at least as a complete url which can be copied into a browser. Users should not be required to know the github structure of ioBroker / js-controller.

Update perfomed was from 5.0.7 to 5.0.19 on PI 4 

### Why?

Users should be able to read information what has changed and potentially what must be considered before an update

### How?

provide a clickable link if possible
provide a full specified url if adding a link is not possible

**Comment by foxriver76** [comment]
isn't this a feature for admin to make this button more prominent, maybe one level higher
![image](https://github.com/ioBroker/ioBroker.js-controller/assets/25484431/905ccd40-ae42-4636-a166-06f82e0a8e6d)

**Comment by mcm1957** [comment]
sorry, your correct of course.
Should be admin.

**Comment by mcm1957** [comment]
see https://github.com/ioBroker/ioBroker.admin/issues/2379
