### ISSUE TITLE
[enhancement]: Adapt Update Instructions test to make clear that web based update is possible with js-controller 5

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker.js-controller#2617]
### No existing issues.

- [X] There is no existing issue for my request.

### Description

When updating js-controller 5.x.x to newer release the button "Anweisungen zeigen"

![image](https://github.com/ioBroker/ioBroker.js-controller/assets/28575778/971b4a0c-bc2d-4231-991f-d3d8f5f6112c)

displays this page

![image](https://github.com/ioBroker/ioBroker.js-controller/assets/28575778/33f1cdd2-7270-4b71-8d33-632924ebaedd)

Users with less experiance might think that the manual steps listed there are required for an update while starting with js-controller 5 an web based update should be possible in most cases.

I suggest to adapt the text.

### Why?

see description

**Comment by foxriver76** [comment]
this also does not come from controller

**Comment by mcm1957** [comment]
sorry, your correct of course.
Should be admin.

**Comment by mcm1957** [comment]
see https://github.com/ioBroker/ioBroker.admin/issues/2379
