### ISSUE TITLE
Provide encrypt/decrypt methods (incl. preloading from secret) as adapter.js methods

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#262]
... so that we have the same functionality available without the need to duplicate methods :-)

**Comment by Apollon77** [comment]
Or maybe allow to config in io.-package which fields are encrypted and everything is handled automatically?

**Comment by GermanBluefox** [comment]
Added to js-controller/lib/tools.js
Now must be added to adapter.js

**Comment by Zefau** [comment]
Is this implemented already? If not, I have made a class for encryption for one of my adapters, see https://github.com/Zefau/ioBroker.roomba/blob/master/lib/encryption.js.

Usage:
```
var encryptor = new Encryption(adapter); // adapter is current running adapter instance

var cleartext = "foobar";
var password= encryptor.encrypt(adapter.config.encryptionKey, cleartext);
var cleartext = encryptor.decrypt(adapter.config.encryptionKey, password);
```

**Comment by foxriver76** [comment]
The idea of io-pack seems very dev friendly. 
Should we use the en- decryption mechanism which is used in many iobroker adapters until now, e. g. In alexa2? 
And how we integrate it in io-pack. An additional array as introduced for protectedNative a few months ago?

**Comment by AlCalzone** [comment]
> Added to js-controller/lib/tools.js
Now must be added to adapter.js

Alternatively we could expose it through `@iobroker/adapter-core`

**Comment by foxriver76** [comment]
> Alternatively we could expose it through `@iobroker/adapter-core`

Basically that also makes sense. On the other hand the dev still needs to use the methods in front and backend by itself. While just defining an additional attribute in io-pack is less effort especially for new devs. Maybe it makes sense to implement the io-pack option + add en- and decryption to adapter-core.

**Comment by Apollon77** [comment]
We already implemented in io-package the definition of secured native values that are only allowed to be read as "the adapter "or "admin. maybe we really can add a second config for "encryptedFields" for that and do it completely under the hood

**Comment by AlCalzone** [comment]
That would make even more sense IMO and it would be in line with the other behavior.

**Comment by foxriver76** [comment]
I would implement this, but there is one question left. When admin stores the settings, it has to check if the native attribute has to be encrypted. I don't see a chance to do it in js-controller only, because admin stores the initial settings in system.adapter.x object directly:
https://github.com/ioBroker/ioBroker.admin/blob/1b471596b76620f28c0262c445c397e526e1f5b6/src/js/adapter-settings.js#L255

Thus, the new functionality would only work with a new js-c and a new admin version. That could cause some problems. Any ideas on this?

**Comment by Zefau** [comment]
> 
> 
> The idea of io-pack seems very dev friendly.
> Should we use the en- decryption mechanism which is used in many iobroker adapters until now, e. g. In alexa2?
> And how we integrate it in io-pack. An additional array as introduced for protectedNative a few months ago?

```
function encrypt(key, value) {
   var result = '';
   for (var i = 0; i < value.length; ++i) {
      result += String.fromCharCode(key[i % key.length].charCodeAt(0) ^ value.charCodeAt(i));
   }
   return result;
}
```

This doesn't look like a proper encryption to me. Is that based on a best practice that can be found somewhere?

**Comment by Apollon77** [comment]
@foxriver76 DO oyu have an overview on implementation status of this for controller?

**Comment by foxriver76** [comment]
Nothing done here in the form of code, because of the open questions above. We could e. g. say that all `protectedNative` (these are the attributes which can only be accessed by own adapter in js-c ) attributes will be automatically stored encrypted and will be automatically decrypted for adapter runtime. But the problem is, storing the (encrypted) value would be done by admin w/o involving js-c. And providing the decrypted values would be done by js-c. So there would be a strong dependency between admin and js-c version. Maybe there is a more elegant way, which I do not see atm. Thoughts?

**Comment by Apollon77** [comment]
It seems Bluefiox fif something here ...  https://github.com/ioBroker/ioBroker.js-controller/commit/7f0897339b3794488bbeeb67c46ec9df6ea4f979

I would like to rename the Feture Flag to use ENCRYPT instead of ENCODE ... and in factit shuld be DECRYPT or ?! ;-)

**Comment by Apollon77** [comment]
I would rename the Feature flag to ADAPTER_AUTO_DECRYPT if noone sees a better name

**Comment by Zefau** [comment]
Still - in my point of view - not a proper encryption method. It is only moving around chars, thus an "encoding".

**Comment by foxriver76** [comment]
@Zefau Due to the fact, that a key (unique user secret) is used to encrypt the data I would call it an encryption by definition. However, we should strive for a state-of-the-art algorithm in the long term. Afaik @AlCalzone had a first look on using alternative encryption algorithms and faced issues.

**Comment by AlCalzone** [comment]
I did not attempt anything yet, but AFAIK the browser crypto API is quite good in terms of cipher support. So this should not be too much of an issue.

**Comment by AlCalzone** [comment]
Regarding the feature flag and consistency (yes, I'm **that** guy...)
We have an option `protectedNative` where we list the config options that may not be read by other adapters. IMO we should do the same for encrypted options (`encryptedNative`) instead of adding yet another (undocumented) magic feature (`enc_` prefix). Thoughts?
@Apollon77 @GermanBluefox

**Comment by foxriver76** [comment]
> We have an option `protectedNative` where we list the config options that may not be read by other adapters. IMO we should do the same for encrypted options (`encryptedNative`) instead of adding yet another (undocumented) magic feature (`enc_` prefix). Thoughts?
> @Apollon77 @GermanBluefox

I thought about the same, to keep it consistent, so +1 for this.

**Comment by foxriver76** [comment]
Seems like it would be easy to switch to e. g. AES 256 (see below), but I am absolutely no expert regarding security topics. 

```javascript
const crypto = require('crypto');

const ENCRYPTION_KEY = '...'; // Must be 256 bits (32 characters)
const IV_LENGTH = 16; // For AES, this is always 16

function encrypt(text) {
    let iv = crypto.randomBytes(IV_LENGTH);
    let cipher = crypto.createCipheriv('aes-256-cbc', Buffer.from(ENCRYPTION_KEY), iv);
    let encrypted = cipher.update(text);

    encrypted = Buffer.concat([encrypted, cipher.final()]);

    return iv.toString('hex') + ':' + encrypted.toString('hex');
}

function decrypt(text) {
    let textParts = text.split(':');
    let iv = Buffer.from(textParts.shift(), 'hex');
    let encryptedText = Buffer.from(textParts.join(':'), 'hex');
    let decipher = crypto.createDecipheriv('aes-256-cbc', Buffer.from(ENCRYPTION_KEY), iv);
    let decrypted = decipher.update(encryptedText);

    decrypted = Buffer.concat([decrypted, decipher.final()]);

    return decrypted.toString();
}
```

Crypto is a built-in node module, thus no extra deps.

**Comment by AlCalzone** [comment]
Two questions we need to think about:
1. Should users be able to read encrypted values in the browser or only write? In the latter case we might need an asymmetric encryption (browser can only encrypt, ioBroker can encrypt and decrypt).
If the data is encrypted and decrypted on the client, the client needs the encryption key, which makes it all just a more sophisticated encoding.

2. Should devs be able to set default values for encrypted config options in io-package.json? If so, how?

**Comment by foxriver76** [comment]
1. I guess admin needs to decrypt too, due to the fact, that devs could like to store e. g. a username encrypted but show them in clear text in frontend. Also you wont be able to modify a value if its only available encrypted. So Admin loads adapter config, and has to decrypt values which were stored encrypted. That's also the way we are handling it now. Other thoughts?

2. I would enable devs to do so. I guess js-c could use the clear text default and encrypt it with the key when creating the system.adapter.<adapter-name>.<inst-numb> object. So some extra mechanic would be necessary, but does not seem to be a problem.

**Comment by Apollon77** [comment]
Maybe we mix two things here?

Topic 1 which is addressed by the change from Bluefox is to  make it easier for adapter developrs to encrypt relevant data - especially for not that experienced developers. So the ide was to automate this as best as possible.
I agree that also an "encryptedNative" couod be a good idea and more in line with the othe rfeature ... maybe better then this automatic stuff with "enc_" prefix. This would be the topic in my eyes for this issue.
(After this is available we need to make sure it is adopten into all adapters.
After this we can think about topic 2)

2.) Replace encryption by a real encryption to increase security ... because then all is automatic and we can change the encryption on controller/adapter level. So this would be likely a second issue in my eyes.

Ok, to answer @AlCalzone's questions:
1.) See it the same as foxriver
2.) I would go with "frontend driven defaults" if needed and do not allowe backend side defazlts in this case because then it is far more easy

**Comment by Apollon77** [comment]
> We have an option protectedNative where we list the config options that may not be read by other adapters. IMO we should do the same for encrypted options (encryptedNative) instead of adding yet another (undocumented) magic feature (enc_ prefix). Thoughts?

Ths only problem here (and I think this is one of the reasons Bluefox choose to go this way) its that this way the "auto migration by adapter "is not that easy" because you can not really "delect" if the value is encrypted or simply that way ... What would be the solution for this for the dev/controller tooling?

**Comment by foxriver76** [comment]
> Maybe we mix two things here?
Yes, its definitely a separate topic/enhancement. ;-)

**Comment by foxriver76** [comment]
> > We have an option protectedNative where we list the config options that may not be read by other adapters. IMO we should do the same for encrypted options (encryptedNative) instead of adding yet another (undocumented) magic feature (enc_ prefix). Thoughts?
> 
> Ths only problem here (and I think this is one of the reasons Bluefox choose to go this way) its that this way the "auto migration by adapter "is not that easy" because you can not really "delect" if the value is encrypted or simply that way ... What would be the solution for this for the dev/controller tooling?

If I get you right, there is currently a separate method for this, called `getEncryptedConfig`.

**Comment by AlCalzone** [comment]
> because you can not really "delect" if the value is encrypted or simply that way ... What would be the solution for this for the dev/controller tooling?

Solution A: if the config value is mentioned in `encryptedNative`, assume it is encrypted. That's it.
Solution B: Use a special formatting for these values, e.g. `"$/32-byte-IV-as-hex/n-bytes-ciphertext-as-hex"`
Solution C: Change the name of the encrypted variables and transparently decrypt and store them under the normal name into the config object that is passed to the adapter instance. *This might be similar to what the code already does*

**Comment by Apollon77** [comment]
Basically with the "Naming convention" from Bluefox you can identify encrspted fields ... When the same name can contain encrypted content or not it gets problematic ... this would be the case with an "declaration only" approach using an encryptedNative-Array

**Comment by Apollon77** [comment]
> Solution A: if the config value is mentioned in encryptedNative, assume it is encrypted. That's it.
Solution B: Use a special formatting for these values, e.g. "$/32-byte-IV-as-hex/n-bytes-ciphertext-as-hex"
Solution C: Change the name of the encrypted variables and transparently decrypt and store them under the normal name into the config object that is passed to the adapter instance. This might be similar to what the code already does

* Solution A is breaking for the data and all users need to reenter the data ... this will be a mess :-(
* Solution B would change encryption and so also already encrypted values needs to be reentered, so breaking or same problem again
* Solution C would be an idea ... in fact it is the same as the current solution as you said but with "the field list which is a parameter right now comes from io-package"  :-)

> 

    I would go with "frontend driven defaults" if needed and do not allowe backend side defazlts in this case because then it is far more easy

I measn: If you need to provide a default value you can check in index_m.html on load ifg the value is empty and then set the default value directly in the Frontend

**Comment by AlCalzone** [comment]
> I measn: If you need to provide a default value you can check in index_m.html on load ifg the value is empty and then set the default value directly in the Frontend

So there will be no way to provide a default value without requiring the user to save the configuration first?

> Solution B would change encryption and so also already encrypted values needs to be reentered, so breaking or same problem again

But this would allow ioBroker to detect that the value is decrypted with an old encryption scheme (e.g. the one we currently have) and transparently update the encrypted value: detect old encryption scheme from the value format, decrypt using old scheme, encrypt using new scheme, store with information about the new scheme.

**Comment by GermanBluefox** [comment]
Does anyone knows the code for encode/decode in browser and then in node.js?

**Comment by GermanBluefox** [comment]
An I am for 
```
{
   common: {},
   native: {
       encrypted: {
           password: '2829362628',
           key: '982798273498273492'
      }
    }
```
Solution.

**Comment by foxriver76** [comment]
> Does anyone knows the code for encode/decode in browser and then in node.js?

As mentioned before for AES256 the backend could be implemented like

```javascript
const crypto = require('crypto');

const ENCRYPTION_KEY = '...'; // Must be 256 bits (32 characters)

function encrypt(text) {
    const iv = crypto.randomBytes(16);
    const cipher = crypto.createCipheriv('aes-256-cbc', Buffer.from(ENCRYPTION_KEY), iv);
    let encrypted = cipher.update(text);

    encrypted = Buffer.concat([encrypted, cipher.final()]);

    return iv.toString('hex') + ':' + encrypted.toString('hex');
}

function decrypt(text) {
    const textParts = text.split(':');
    const iv = Buffer.from(textParts.shift(), 'hex');
    const encryptedText = Buffer.from(textParts.join(':'), 'hex');
    const decipher = crypto.createDecipheriv('aes-256-cbc', Buffer.from(ENCRYPTION_KEY), iv);
    let decrypted = decipher.update(encryptedText);

    decrypted = Buffer.concat([decrypted, decipher.final()]);

    return decrypted.toString();
}
```

`ENCRYPTION_KEY` could be first 32 digits of `system.config.secret` or something else.
Frontend encryption could look like (using `<script src="https://cdnjs.cloudflare.com/ajax/libs/crypto-js/3.1.9-1/crypto-js.js"></script>`):

```javascript
    // Encrypt our data
    var ENCRYPTION_KEY = '...'; // Must be 256 bits (32 characters)

    var encrypted = CryptoJS.AES.encrypt(plaintext, CryptoJS.enc.Utf8.parse(ENCRYPTION_KEY), {
        iv: CryptoJS.lib.WordArray.random(16)
    });

    // This is our encrypted value to store in db
    var storeEncrypted = encrypted.iv + ':' + encrypted.ciphertext;
```

Decrypt in FE:
```javascript
    var textParts = storeEncrypted.split(':');
    var decrypted = CryptoJS.AES.decrypt(textParts[1], CryptoJS.enc.Utf8.parse(ENCRYPTION_KEY), {
        iv: CryptoJS.enc.Hex.parse(textParts[0]),
        mode: CryptoJS.mode.CBC,
        format: CryptoJS.format.Hex
    }).toString(CryptoJS.enc.Utf8);
```

But I would prefer to further discuss this in https://github.com/ioBroker/ioBroker.js-controller/issues/660 with you and @AlCalzone @Apollon77 before implementing anything. Also we should first finish the basic of auto en/decryption with the current methods (topic of this issue).

**Comment by AlCalzone** [comment]
I don't think we need an external crypto library for the browser:
https://github.com/diafygi/webcrypto-examples

**Comment by foxriver76** [comment]
Browser support could be a problem https://caniuse.com/#feat=cryptography

**Comment by AlCalzone** [comment]
Well... everything but IE11 works.

**Comment by foxriver76** [comment]
Thats true, I don't know if we have to support it..  but probably yes.

**Comment by foxriver76** [comment]
@GermanBluefox does the current implemented mechanic store the encryption type, e. g. by starting with $/`<encryptionType`>: which would it make it possible to detect the method in the future and switch to another encryption type? Otherwise it will be hard if we switch to detect if something is not encrypted yet or encrypted with the old mechanic.

Also I have to cite @AlCalzone again:
> Regarding the feature flag and consistency (yes, I'm **that** guy...)
> We have an option `protectedNative` where we list the config options that may not be read by other adapters. IMO we should do the same for encrypted options (`encryptedNative`) instead of adding yet another (undocumented) magic feature (`enc_` prefix). Thoughts?
> @Apollon77 @GermanBluefox

I would still prefer this for consistency reasons. This `_enc` style is super easy to detect for us in frontend but on the other side we have nothing like that and it introduces further magic stuff..

**Comment by Apollon77** [comment]
I had a sync with @GermanBluefox and he agrees on changing the enc_ idea again.

On one hand we have the idea from this thread with "encryptedNative".
Pro:
* consistent with  protectedNative idea with is already implemented
* the values do not change and are configured as usual in native
* transparent for developer

Cons:
* We have one place to configure and the variables are localted on a second place

Another idea @GermanBluefox had is the idea to structure that in native by introducing "native.secrets" as storage place for encrypted values. This would mean that the developer defines his stuff in native as usual and additional the "native.secrets" object also with the keys that should be encrypted and empty values (for adapter native). The adapter.js decrypts the values and provides the decrypted value in common-name directly.

Pro:
* everything in one place
* transparent for developer

Contra:
* "secret" would be a reserved config name from now on (ok currently no adapter uses it)
* double configuration (or if we define only in "secrets" then inconsistent because not defined in native directly

What all of you think about those otpions? Lets discuss and agree on one to implement in 3.0.

Additionally we should decide about the idea (especially in direction of an alternative later encryption format) to not decrypt values in admin in general and just encrypt values. So Admin would only knwo "value existing or not" and we would display all those fields as "password" fields.

To the question about "prefixing current encryption": there is no prefix, but I think it should be possible (because of the limited encryption method) to find something to use as "magic prefix" for a future encryption format.

**Comment by foxriver76** [comment]
I stick to the `encryptedNative` idea for the above mentioned pros.

**Comment by AlCalzone** [comment]
> To the question about "prefixing current encryption": there is no prefix, but I think it should be possible (because of the limited encryption method) to find something to use as "magic prefix" for a future encryption format.

There is already precedent for this:
https://en.wikipedia.org/wiki/Bcrypt --> See *Description*
Bcrypt-hashed passwords are stored like this: `<algorithm><salt><hash>`.

**Comment by foxriver76** [comment]
I guess, what @Apollon77 means here, is, that we have to find a prefix or a name to use as a prefix for our current algorithm, which is just a nameless algorithm and no standardized encryption.  More important would be to get your opinion on the above mentioned possible implementations listed by @Apollon77.

**Comment by Apollon77** [comment]
On question came into my mind: we also have protectedNative which is a separate object. Should we "automatically protect all encrypted values" too or would an adapter developer configure both the same.
When I remember we introduced protectedNative mainly to prevent reading of encrypted values ...
What do you think?

**Comment by AlCalzone** [comment]
Makes sense to imply encrypted is also protected. If not, possible attackers could just read the encrypted values using the CLI.

**Comment by Apollon77** [comment]
protectedNative is currently not CLI protected as I know ... protectedNative is currently only implemented for adapter.js

**Comment by AlCalzone** [comment]
Uhhhh

**Comment by Apollon77** [comment]
We could easiely add that into cli get object

**Comment by foxriver76** [comment]
It's only protected by all adapter methods, but admin is an exception and will get it. The question is, where do we draw the line, we could block via iobroker cli, however attackers could read the value out of file db by executing simple bash commands and also out of redis, e.g. via redis-cli

**Comment by Apollon77** [comment]
If I'm deep enough for CLI (or can use js adapter to execute system execs to do that) then the user has another problem

**Comment by Apollon77** [comment]
I would leave protected and encrypted separated for now. there might be cases whre adapters could shae credentials. I documented it as "best practice" to add encrypted fieldnames also to protected
