### ISSUE TITLE
[bug]: Unknown objects type: jsonl after update from 5.0.17 to 5.0.19

### ISSUE THREAD

**Issue by Martin-Stein** [ioBroker/ioBroker.js-controller#2652]
### No existing issues.

- [X] There is no existing issue for my problem.

### Description

on my win 11 machine, I receive the error message: 

C:\ioBroker\node_modules\iobroker.js-controller\lib\objects.js:12
    throw 'Unknown objects type: ' + config.objects.type;
    ^
Unknown objects type: jsonl
(Use `node --trace-uncaught ...` to show where the exception was thrown)

this will be thrown for every iobroker command.
How can I fix it?

Kind regards,
Martin

### Reproduction instruction

iobroker stop
iobroker update
iobroker upgrade self
iobroker start

**Comment by foxriver76** [comment]
Seems like npm destroyed your installation, likely someone in Forum can help you better with windows. Normally just reinstall controller.

**Comment by mcm1957** [comment]
Not sure whether windows installer can fix installations but I would give it a try.
Otherwise I suggest to ask at this topic and mention @gaspode.
https://forum.iobroker.net/topic/63610/test-iobroker-unter-windows-installieren-2023-edition

**Comment by Martin-Stein** [comment]
the windows installer was able to fix it!
Now it is working again!
