### ISSUE TITLE
[enhancement]: improve reinstall of existing adapter release

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker.js-controller#2667]
### No existing issues.

- [X] There is no existing issue for my request.

### Description

Reinstalling an adapter (install the existing release once more) is possible using 
`iob upgrade adapter@version`

In this case iob asks
```
pi@pi4:/opt/iobroker/node_modules $ iob upgrade tuya@3.15.0
Would you like to reinstall version 3.15.0 of tuya now? [(y)es, (n)o]:
```

When selecting yes, a reinstallation seems to occure. BUT this is no real reinstallation, npm does not install files from adapter again, any changes performed at the adpter files will not be overridden and reset to the state of the official pacakge.

So either:
try a TRUE reinstall - files from package should be installed and local modification removed
OR
give a clear indication, that the reinstall will not do what expected

### Why?

When executing something name "reinstall" one would expect that this does a reset except local configuration data.

### How?

I think it should be possible to to do npm uninstall followed by a normal npm install to do the trick and to cleanup the files provided by the adapter. ioBroker configuration and data files should not be effected by npm.

**Comment by foxriver76** [comment]
Upgrade always performs a npm install and reinstall is just the term used if it is detected that the version to install is the already installed one. I don’t see the use case for this delete stuff.

**Comment by mcm1957** [comment]
The use case is that any change to files of the adapter should be reverted to the version deliverd with the version.

npm install of the installed version is simply a nop, it does NOT replace the files installed.

Example:
Edit main.js of adapter and add some this.log.info('hello world');
reinstall the adapter version
Main.js still contains the debug log while I (and most likely many user) would expect the the main.js is again the file provided by the release at npmjs.

This is no ioBroker failure, npm simply "optimizes". Searching for reinstalling an installed package suggests to du uninstall followed by new install. There seems to be no qualifier to force npm to do a real refresh (/ replace.

Note:
Deinstall / Install using iob commands would delete the config / states - so this is no alternative. Using native npm commands would do the trick but should be avoided as they are a little bit risky (default dir, username, ...).

**Comment by Apollon77** [comment]
We could try if https://stackoverflow.com/a/43974600 works ... so using "npm install --force"

**Comment by mcm1957** [comment]
> We could try if https://stackoverflow.com/a/43974600 works ... so using "npm install --force"

I do not find the articel now, but I read that --force is strongly discouraged to force a reinstallation as --force ignors ANY problems and will install the pacakge even tehre are incompatibilities otherwise detected by npm. So in my oppinion --force must be investigataed in detail before considered as a solution,
