### ISSUE TITLE
[enhancement]: Warn on too many adapter subscribes

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#2696]
### No existing issues.

- [X] There is no existing issue for my request.

### Description

 We should add a warning/info log when subscriptions in an adapter exceed 50/100 with the usual "please report to developer".

### Why?

When adapters do too many subscribes this could lead to a bad jscontroller performance.

### How?

Count local subscriptions (+ and - - maybe db class already knows the number?) and log on new subscribes when number >50/100

**Comment by mcm1957** [comment]
As we are about adding more and more such warnings we should consider sending such warnings to sentry or some other service too (if user has not disabled statistics) to get a centralized overview of problems and are able to contact developers if required.

**Comment by Apollon77** [comment]
I think the way we did in the past was working ... First we log and users will open issues ... that worked really well in the past generally. Then before we really plan to remove a functionality (which will not be a topic in this case) we will use Sentry to catch the rest stuff.

With ideas in #2695 we could even think about handling such mass stuff in adapter.js and protect the devs for themself ...

**Comment by Apollon77** [comment]
As discussed we need to make sure that many single subscribes works the best possible way. We might revise this when we have real world reports of issues.
