### ISSUE TITLE
Do we still need the 2nd execution of npm install for adapters?

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.js-controller#270]
I'm talking about the one run in the adapter dir **after** it has been `npm install`ed:
```
npm install --production (System call) in "/opt/iobroker/node_modules/iobroker.adapter-name"
```

With the newer npm versions this shouldn't be necessary and for certain adapters, especially the ones compiling native modules, it is quite a waste of time. For example an installation of `zwave` compiles `openzwave` and `node-openzwave-shared` twice, which can take around 30 minutes on a RPi 2.

**Comment by Apollon77** [comment]
I think 2.0.0 is a great target for this to change

**Comment by Apollon77** [comment]
I basically found out why the second call is done and 1.5.x already optimize this.

ioBroker supports to install adapter from a ZIP file and in this case this is "unpacked" in the node_modules directory and so "npm install" needs to be executed in order to really install this.

The current normal install process writes a file into the installed directory of a normal adapter to indicate this additional install is not needed. We need to check if all cases are handled correctly

**Comment by AlCalzone** [comment]
So we need to create this file after the first install and check before the 2nd one if the file exists, right?

**Comment by AlCalzone** [comment]
And I think npm can install from zip files

**Comment by Apollon77** [comment]
The file stuff should be already that way in 1.5.11. maybe needs a check again.

**Comment by Apollon77** [comment]
The double install will also happen on new installationsbecazse the default packages are istalled via npm, so the file is not there ... so setup first should "create the file and trust npm process if directories are existing"

**Comment by AlCalzone** [comment]
I wonder if there's a better way to find out if the packages are installed, aside from putting our own file there.

**Comment by Apollon77** [comment]
good question ... if a package was completely installed by npm the package.json looks different. but if you copied something to the dir and executed npm install this is not the case because if leaves package.json untouched from what I remember ... :-(

**Comment by Apollon77** [comment]
I again fixed a case where the touch-file was not written correctly ... so it should happen not that often anymore

**Comment by Apollon77** [comment]
First of alll we should check if this is still an issue at all ... ALl places where npm imnstall is executed write the "iob_npm.done" file and also check if it exists where relevant .. so basically there should be no case where the second install is still unnecessary executed

**Comment by AlCalzone** [comment]
> but if you copied something to the dir and executed npm install this is not the case because if leaves package.json untouched from what I remember ... :-(

I think this will cause npm to mess things up anyways when the next install happens.

**Comment by Apollon77** [comment]
@AlCalzone Did you had that removed in your "pak" PR?

**Comment by AlCalzone** [comment]
I did. https://github.com/ioBroker/ioBroker.js-controller/pull/1339 -> point 2.
