### ISSUE TITLE
[bug]: dependencies not checked at atsrtaup

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker.js-controller#2701]
### No existing issues.

- [X] There is no existing issue for my problem.

### Description

I had an typo within the dependency section of an adapter:

```
"dependencies": [
      {
        "js-controller": ">=35.0.0"
      }
    ],
    "globalDependencies": [
      {
        "admin": ">=5.1.13"
      }
    ]
```

This adapter passed all standard github tests as test:integration started the aapter without any error.

It looks like js-controller does not ensure that the dependencies are met when starting an adapter.

If this is a bug, please fix.
If this is not yet implemented please retagg as enhancement.
If this has already been discussed and the decision was not to check, please close issue

### Reproduction instruction

Add the dependency listed above to io-package.json and try to start the adapter or execute test:integration

### Environment
js-controller 5.0.19
node 18

P.S:
The BUG template does not ask for versions. Is this intended?

**Comment by foxriver76** [comment]
Are you sure it was all uploaded? The information is taken from `system.adapter.xy.instanceNo`

In a small test it works well

![grafik](https://github.com/ioBroker/ioBroker.js-controller/assets/25484431/a600a92a-06c4-4b74-9ef3-b9164d0fd450)
also tested with controller
![grafik](https://github.com/ioBroker/ioBroker.js-controller/assets/25484431/ab74f994-6e19-4baa-9dc7-53d3bd33bb4f)

**Comment by mcm1957** [comment]
Ok, then it might be a problem with tests only.

During adapter installation it is blocked. But thats an admin feature. I was wondering why this broken release got throgh the tests.

With your information I suppose that the js-server used during testing (@iobroker/testing) maybe does not do an upload. Il will do some tests. Running npm run test:integration did NOT fail but I would expect as this also starts an js-controller.
