### ISSUE TITLE
[bug]: Mulithost Slave can't connect to Master (5.0.19)

### ISSUE THREAD

**Issue by bjoernbusch** [ioBroker/ioBroker.js-controller#2706]
### No existing issues.

- [X] There is no existing issue for my problem.

### Description

As a follow up to #2471, where it was requested to create a new issue, I'm still facing issues with joining a Slave to a Master when both are on 5.0.19. My master is running iobroker for several years now, but besides the OS all components are up to date. I tried joining a brand new Rpi4 to that Master, but was failing all the the time. After downgrading to 4.0.24. on the Slave it worked flawlessly and I could upgrade to 5.0.19 and the connection kept working.

Master:
```
======================= SUMMARY =======================
			v.2023-10-10


   Static hostname: homepi
         Icon name: computer
  Operating System: Raspbian GNU/Linux 10 (buster)
            Kernel: Linux 6.1.31-v8+
      Architecture: arm64

Installation: 		native
Kernel: 		aarch64
Userland: 		armhf
Timezone: 		Europe/Zurich (CEST, +0200)
User-ID: 		1000
X-Server: 		false
Boot Target: 		multi-user.target

Pending OS-Updates: 	0
Pending iob updates: 	0

Nodejs-Installation: 	/usr/bin/nodejs 	v18.20.2
			/usr/bin/node 		v18.20.2
			/usr/bin/npm 		10.5.0
			/usr/bin/npx 		10.5.0
			/usr/bin/corepack 	0.25.2

Recommended versions are nodejs 18.20.2 and npm 10.5.0
Your nodejs installation is correct

MEMORY: 
              total        used        free      shared  buff/cache   available
Mem:           3.8G        1.7G        529M        135M        1.5G        1.8G
Swap:           99M          0B         99M
Total:         3.9G        1.7G        629M

Active iob-Instances: 	23
Active repo(s): stable

ioBroker Core: 		js-controller 		5.0.19
			admin 			6.13.16

ioBroker Status: 	iobroker is running on this host.


Objects type: jsonl
States  type: jsonl

Status admin and web instance:
+ system.adapter.admin.0                  : admin                 : homepi                                   -  enabled, port: 8081, bind: 0.0.0.0, run as: admin
+ system.adapter.web.0                    : web                   : homepi                                   -  enabled, port: 8082, bind: 0.0.0.0, run as: admin

Objects: 		3563
States: 		2686

Size of iob-Database:

21M	/opt/iobroker/iobroker-data/objects.jsonl
1.3M	/opt/iobroker/iobroker-data/states.jsonl
=================== END OF SUMMARY ====================
```

The new Slave was a fresh Rpi4, 2 GB RAM, debian lite 64bit, only nodejs and iobroker installed.  I enabled multihost discovery on the host several times, restarted the master iobroker after enabling discovery, and the slave always reported on browse and connect that it couldn't find any master. 

I logged into the Slave then, went to /opt/iobroker, shut down iobroker and ran `sudo -u iobroker npm install iobroker.js-controller@4.0.24 --production`. After starting iobroker again, multihost browse immediately found the master and I could join the master with connect. I then upgraded the Slave again to 5.0.19.

### Reproduction instruction

- Master on Rpi4
- js-controller with 5.0.19

- Slave on Rpi4
- js-controller with 5.0.19

- Enable multihost on Master
- Restart master
- Try discovery of multihost, discovery fails
- downgrade js-controller on Slave to 4.0.24
- Try discovery of multihost, discovery and connect is successful
- Upgrade js-controller back to 5.0.19.

**Comment by foxriver76** [comment]
Discovery fails meand with an error log or just not disocvering?

**Comment by bjoernbusch** [comment]
It just returned with the message: `No Multihost server found. Make sure iobroker is running on the host where you enabled multihost discovery (and it is not this host)!`

**Comment by foxriver76** [comment]
okay I will try to reproduce thanks

**Comment by foxriver76** [comment]
yep, confirmed there is a bug in the code. You can get it working anyhow if you use `--debug` flag

So `iob mh browse --debug` should work now, we will fix the bug for next version

**Comment by bjoernbusch** [comment]
awesome, thanks for confirming on a Sunday!

**Comment by bahnuhr** [comment]
iob mh browse --debug
funktioniert nicht.
vgl. auch
https://forum.iobroker.net/topic/75298/slave-start-nicht-mehr-nach-nodejs-update-20/54?_=1719043317556

**Comment by bahnuhr** [comment]
--debug klappt doch.
Musste im master das Häkchen setzen.

**Comment by GWehst** [comment]
Guten Tag,
ich habe ein Problem mit Master/Slave.
Nach der Umstellung auf Bookwurm und Nodejs v20.18.0 bekomme ich keine Kopplung hin.
Es sind beide Rpi4 mit 8Gb(Master und 4Gb(Slave)
der Master sagt:
Please check the binding of the configured jsonl server to allow remote connections.
Please restart ioBroker for the changes to take effect: "iobroker restart"


Multihost discovery server: enabled
Discovery authentication:   enabled
Persistent activation:      disabled
Objects:                    jsonl on 0.0.0.0
States:                     jsonl on 0.0.0.0

DerSlave antwortet:
Error: No configuration received!
    at file:///opt/iobroker/node_modules/@iobroker/js-controller-cli/src/lib/setup/setupMultihost.ts:339:26
    at onFinished (file:///opt/iobroker/node_modules/@iobroker/js-controller-cli/src/lib/setup/multihostClient.ts:267:21)
    at Timeout.<anonymous> (file:///opt/iobroker/node_modules/@iobroker/js-controller-cli/src/lib/setup/multihostClient.ts:98:17)
    at listOnTimeout (node:internal/timers:581:17)
    at processTimers (node:internal/timers:519:7)

Ich komme nicht wirklich weiter. 
MfG

**Comment by mcm1957** [comment]
I suggest to asknsuchvquestions at our forum. https://forum.iobtoker.net

This issuecis closed dince june.

Please add version infobat forum when asking.
