### ISSUE TITLE
Enhance the `iobroker object get/set ...` commands

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.js-controller#271]
AFAIK there is no way to update objects using the CLI, only retrieve them.

For a project of mine - specifically for the automation of image creation using docker - I need a way to set specific parts of an object using the CLI. It would be nice to add a coammand where we can specify an object and a "path" to the property that should be changed.  
For example `iobroker object set adaptername.0.objectname common.foo.bar=true` - changes `foo.bar` in `object.common` of `adaptername.0.objectname` to `true`

The same logic could apply to `iobroker object get ...` so we can get *just the value* instead of the entire object:  
For example `iobroker object get adaptername.0.objectname common.foo.bar` - returns the value of `foo.bar` in `object.common` of `adaptername.0.objectname`

**Comment by AlCalzone** [comment]
I'll be happy to provide PRs if that is something we want to support. @GermanBluefox @Apollon77

**Comment by Apollon77** [comment]
I would support that. I also missed that some time ago ;-)
Just on set I more would prefer a json string as value that you can specify multiple values to overwrite/set at once. And this is also much easier to "verify" (because JSON.parse make shure it is valid :-) ) Only bad because of shell escaping or such :-(

iobroker set adaptername.0.objectname {common: {foo: {"bar": true}}}

**Comment by AlCalzone** [comment]
> `iobroker set adaptername.0.objectname {common: {foo: {"bar": true}}}`

We need to differentiate between extending objects and setting objects (think `{set,extend}Object()`), or we won't have a way to overwrite an entire object. So I'd propose:
1. ```iobroker object {set,extend} id [propertypath=]value```
where `set` overrides an existing object or creates a new one and `extend` merges properties into a new one.  
If `propertypath` is not given, then the overwriting/extending starts with the root object. If it is given, only the selected property (and its subproperties).
`value` can either be a `string`, `boolean`, `number` or an array or object serialized as valid `JSON`.

2. ```iobroker object get id [propertypath]```
would return the entire object as a JSON string if no propertypath is given or the requested property.

Examples for `propertypath`:
* `"common.foo.bar"` - selects `foo.bar` of `object.common`
* `"native.something[2].onething"` - selects `onething` of the 3rd array element of `object.native.something`.

If any sub-path of those paths does not exist, return `undefined` (`get`) or throw an error in case of `set/extend`.

**Comment by AlCalzone** [comment]
Do we need some form of authentication?

**Comment by AlCalzone** [comment]
PR #272 created for `get/set`. `extend` is still missing.

**Comment by Apollon77** [comment]
@AlCalzone Do you want to finish in 3.1? :-)

**Comment by AlCalzone** [comment]
I'll need to find the time, but would be good.

**Comment by AlCalzone** [comment]
I think I'll leave the property path thing out of extendObject. So it will basically work just like adapter.extendObject.
