### ISSUE TITLE
[bug]: packageUpdates - list is empty?

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.js-controller#2722]
### No existing issues.

- [X] There is no existing issue for my problem.

### Description

https://github.com/ioBroker/ioBroker.js-controller/blob/31d1cb4929f3bd250ce60d6f1c67e4cbc0e0773d/packages/controller/src/main.ts#L5674

<img width="1021" alt="Screenshot 2024-05-03 at 20 50 56" src="https://github.com/ioBroker/ioBroker.js-controller/assets/1959049/b948030c-99a8-43b3-bbfc-55d2276491c4">

`system.host.dev-javascript-iobroker-dev.notifications.system`:

```
{"packageUpdates":{"count":1}}
```

```
mkleine@iobroker-dev:~$ apt list --upgradeable
Auflistung… Fertig
```

**Comment by klein0r** [comment]
`system.host.dev-javascript-iobroker-dev.osPackageUpdates`: `[""]`

**Comment by foxriver76** [comment]
Seems like apt has an additional empty line on your setup. We filter them out in the future.
