### ISSUE TITLE
fix travis tests

### ISSUE THREAD

**Issue by foxriver76** [ioBroker/ioBroker.js-controller#274]
Since https://github.com/ioBroker/ioBroker.js-controller/commit/3963fc682b804a8eefa53f017008befd4ec59c77 tests are broken due to exceeding the maximum log length. 

With this commit the Travis server started to log the io-package.json of all adapters.

**Comment by foxriver76** [comment]
successful tests do not seem to use 
```
  "after_success": [
    "npm install -g npm@latest",
    "npm install --package-lock-only --production",
    "npm audit",
    "npm ls"
  ]
```

example: 
pass: https://travis-ci.org/ioBroker/ioBroker.js-controller/jobs/428955983/config
fail: https://travis-ci.org/ioBroker/ioBroker.js-controller/jobs/428999825/config

**Comment by Apollon77** [comment]
Is something different I think because it logs the repo ... so it seems to be a test where "iobroker update" is tested

**Comment by Apollon77** [comment]
and the reason is basically that redis objects are logging too much

**Comment by foxriver76** [comment]
yes problem is that repos are logged e.g. https://travis-ci.org/ioBroker/ioBroker.js-controller/jobs/428999825#L2986 leads to enormous logging output

**Comment by Apollon77** [comment]
But only Bluefox can currently fix that because objectsInRedis is an additional npm package ...

**Comment by Apollon77** [comment]
I get access tomorrow ... maybe I can have look

**Comment by Apollon77** [comment]
objects-redis paket 0.2.4 in Arbeit . Dort werden redis get erfolge nicht mehr geloggt ...

**Comment by Apollon77** [comment]
Reason found for additional port number that breaks socket tests. 

https://github.com/ioBroker/ioBroker.js-controller/blob/1.6.0-dev/test/lib/setup4controller.js

Object Setup for Port needs to be like in states ;-)

On the road so will fix tomorrrow

**Comment by Apollon77** [comment]
fixed by https://github.com/ioBroker/ioBroker.js-controller/commit/f3d5959e0ec8a3be83727dfc9b1629b211a0ad4a

**Comment by Apollon77** [comment]
Hm .. now other errors appear ... continuing

**Comment by Apollon77** [comment]
now finally fixed :-)

**Comment by GermanBluefox** [comment]
Hurra 😀

**Comment by Apollon77** [comment]
Hehe brokering again directly afterwards with Windows Tests on Travis ... but will be fixed later ;-)
