### ISSUE TITLE
[bug]: common.disableDataReporting is missing in schema

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.js-controller#2745]
### No existing issues.

- [X] There is no existing issue for my problem.

### Description

Sounds like a very "general" flag in the sentry-plugin code:

https://github.com/ioBroker/plugin-sentry/blob/b4ffa9b120a09e4e276c76a03156c5cf2f7135b7/index.js#L31-L34

**Comment by klein0r** [comment]
Maybe related to https://github.com/ioBroker/ioBroker.js-controller/issues/870

**Comment by foxriver76** [comment]
From my point of view, at some point this was introduced redundantly and undocumented to the existing plugin state e.g. `system.adapter.admin.0.plugins.sentry.enabled`, from my site and the latest discussions it makes no sense to have reundant flags thus also created this https://github.com/ioBroker/ioBroker.admin/issues/2409 recently. 

If we don't see any benefit having an additional property, I would tend to deprecated the use of this and hint to the plugin enabled state. Note, that the `system.config` `common.disableDataReporting` of course stays and will have an effect for system wide reporting (also like sending statistics).
