### ISSUE TITLE
[bug]: Double onChnage Event on alias, if subscribed twice

### ISSUE THREAD

**Issue by BenAhrdt** [ioBroker/ioBroker.js-controller#2753]
### No existing issues.

- [X] There is no existing issue for my problem.

### Description

if a adapter subscribs a foreign id more times thant one evyting is ok.
if this id is an alias eg. "alias.o.example" the change of this id trigges the onChange Method of the Adapter twice.

### Reproduction instruction

Subscribe in an adapter an alias id more than one time. => the onChange Event will triggers more than one time

**Comment by foxriver76** [comment]
is there code to reproduce this?

**Comment by BenAhrdt** [comment]
> is there code to reproduce this?

maby:
`this.adapter.subscribeForeignStatesAsync(config.id);
this.adapter.subscribeForeignStatesAsync(config.id);`

now this id triggers an onChange event and if the id is an alias the event will be triggert twice.

i solved the problem with writing subscribtion in an internal object and only subscribe if the id isnt subscibed yet

**Comment by foxriver76** [comment]
Okay can reproduce this

**Comment by BenAhrdt** [comment]
Ok. In wich Version it is online?
So i can remove my workaround in the Adapter?

**Comment by foxriver76** [comment]
Controller v6 currently in alpha test

**Comment by mcm1957** [comment]
>  So i can remove my workaround in the Adapter?

As already answered at telegram: js-controller should not be used as filter api. If the adapter can handle, reduce the load at js-controller it should do it.
