### ISSUE TITLE
Replace the magic numbers in /lib/setup.js with named constants

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.js-controller#276]
The several CLI commands in `/lib/setup.js` return several exit codes but their meaning is unclear. For example:
```js
if (err) {
    console.error('Cannot read host info: '+ err);
    if (!data) {
        return callback(20);
    }
}
```

I'm sure they are defined somewhere, but using named constants or some form of enum like
```js
const returnCodes = {
    errorTheUserIsDumb: 76,
    // ...
}
```
and then doing
```js
if (err) {
    console.error('Cannot read host info: '+ err);
    if (!data) {
        return callback(returnCodes.errorReadingHostInfo);
    }
}
```
would be beneficial.

**Comment by AlCalzone** [comment]
Note: Before changing something, we should merge #277 or we get chaos

**Comment by GermanBluefox** [comment]
But, "Work in progress, do not merge!" ?

ср, 21 нояб. 2018 г. в 16:44, AlCalzone <notifications@github.com>:

**Comment by AlCalzone** [comment]
Yes, you are right. I just wanted to say that we should not work on this issue before #277 is merged.

**Comment by Apollon77** [comment]
Did we worked on it or not? still 2.0.0 relevant or postpone to 2.1?

**Comment by Apollon77** [comment]
@AlCalzone @GermanBluefox

**Comment by AlCalzone** [comment]
Not done yet:
https://github.com/ioBroker/ioBroker.js-controller/blob/45e1e27e4b877c0855deb6bb601ee1aad6735a23/lib/setup.js#L313
and many other locations

Seems like a minor refactor that should be done after 2.0 to me

**Comment by Apollon77** [comment]
@AlCalzone Still plan for it ? :-)

**Comment by foxriver76** [comment]
Should we use and enhance https://github.com/ioBroker/ioBroker.js-controller/blob/master/lib/exitCodes.js or define the needed exit codes in setup.js?

**Comment by foxriver76** [comment]
seems like we already use named constants now

**Comment by foxriver76** [comment]
okay only partially when calling processExit..
