### ISSUE TITLE
Give adapters a starting priority

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.js-controller#279]
When starting iobroker, it would be nice if we could prioitize certain adapters. For example zwave takes a long time to load and uses a bunch of CPU time while doing so. If the admin is started afterwards, it may take a while until one can access the admin UI

**Comment by Apollon77** [comment]
Good idea. Currently order is „ instance added to host order“

**Comment by GermanBluefox** [comment]
Admin will be started ALWAYS as first one

Am Do., 22. Nov. 2018, 20:11 hat Ingo Fischer <notifications@github.com>
geschrieben:

**Comment by GermanBluefox** [comment]
https://github.com/ioBroker/ioBroker.js-controller/blob/master/controller.js#L1859

Am Fr., 23. Nov. 2018, 10:05 hat Smart Home - ioBroker <
dogafox@googlemail.com> geschrieben:

**Comment by AlCalzone** [comment]
That was not the case yesterday while testing 1.6

**Comment by GermanBluefox** [comment]
> That was not the case yesterday while testing 1.6
> 
> I could see in the log that zwave was almost done initializing when the start of the admin adapter was finally logged.

Cannot explain it. From the code I just can see, that admin will start as first and then in 2 seconds other adapters.

**Comment by Apollon77** [comment]
But being able to define a start order is a good idea

**Comment by foxriver76** [comment]
Where to store this information? new `system.host` state, `system.config` object or iobroker.json?

**Comment by Mic-M** [comment]
Thank you @foxriver76 for identification of this duplicate issue - https://github.com/ioBroker/ioBroker.js-controller/issues/1054
This enhancement request is currently a discussion at Discord.

This is a citation of my first thoughts:
> Nur mal so als Idee in den Raum geworfen: Man könnte auch engl. "Tiers", also quasi "Ränge / Stufen" einfügen. Beispiel: Tier 1: Admin-Adapter, Tier 2: Alles was nötig ist für die restlichen Adapter (z.B. Logging, usw.). Tier 3: Der Rest - und im Idealfall kann hier in "Tier 3" der User noch sagen "Homematic" brauch ich als erstes, das Wetter zum Schluss.
Adapter, die in "Tier 2" kommen möchten, müssen in der io-package.json ein Flag setzen, und das wird beim Review für Latest verifiziert. 

Idea is: Implementing "Tiers", so adapters in tier 1 start first, tier 2 second, and then all tier 3 adapters (the remaining ones).
 * **Tier 1:** Admin-Adapter
 * **Tier 2:** Adapters required for Tier 3 adapters, e.g. which require Logging (like https://github.com/o0shojo0o/ioBroker.seq or https://github.com/Mic-M/ioBroker.logparser)
* **Tier 3:** All other adapters. Ideally, the start sequence of tier 3 adapters can be adjusted by user, like "Homematic first", "Weather last".

**Comment by foxriver76** [comment]
Sounds like a good approach, and this Tier logic can be handled by io-pack flag only. 

Only for the sort functionality of Tier 3, we would need to store the starting order of each host in an appropriate object.

>Adapter, die in "Tier 2" kommen möchten, müssen in der io-package.json ein Flag setzen, und das wird beim Review für Latest verifiziert.

Someone could still change Tiers after beeing added to latest, but repo checker could be enhanced when updating stable version and detect if the flag has been added between two versions.

**Comment by AlCalzone** [comment]
Some thoughts:
Each tier should be started completely until the next tier begins. I've seen it in the past that the built-in webserver of admin was not ready yet when other adapters (e.g. javascript with expensive TS compilation) start and stole all resources. As the result, the web server only started listening after the expensive startups were done.

If we store a user-editable sort order in the instance objects, it must be updated in all instance objects when it changes. I guess that leads to all adapters restarting? Also there will be gaps in the sort order when an instance is removed.
I would prefer an array with the instance IDs on the config object or similar. Any instance that is not in here will be started at the end. We just need to remember to add new instances and to remove uninstalled ones from there.

**Comment by Mic-M** [comment]
@AlCalzone 
> If we store a user-editable sort order in the instance objects, it must be updated in all instance objects when it changes

Or maybe instance-based and not adapter-based logic:
Like in this example for Tier 3: javascript will start first, HMs second, then hue.0, then iqontrol.0, and then the rest. Would be nice e.g. for adapters like javascript, where users may have test instances, which don't have a start priority.

![image](https://user-images.githubusercontent.com/39859059/95363690-13013c80-08d0-11eb-9c03-e11578b24baa.png)

Also, maybe instance-approach also for Tier 2 by just adding 0 instances to Tier 2, like: `seq.0` or `logparser.0`, but not `logparser.2`

**Comment by Apollon77** [comment]
In fact th" tier" is not different from "order as number" with allowing instances having the same number? ;-) And yes 0 should be reserved for "Internal stuff". In io-package we should add a "defaultTier" property in common to propose this for the instance creation dialog?!

**Comment by foxriver76** [comment]
Hm as I understood the idea is having three tiers defined by the developers and inside this tiers the user can define a priority via numbers.


So admin is Tier 1 and thus always starts first - user cannot change it.

Tier 2 is defiend by developers via io-pack flag. Inside Tier 2 the user can prioritize adapters which should start previously to others.

Tier 3 are all other adapters which are not 1 or 2. Inside this Tier, the user can also prioritize adapters, but they will only start after all Tier 2 adapter have been started.

So having a Tier 2 e.g. logparser adapter with user prio `9` and a Tier 3 adapter, e. g. hm-rpc with user given prio `1`, logparser will still start previously to hm-rpc.

I like this idea, but as mentioned by AlCalzone I would not store the user-defiend priority inside the object, because this will always end in a instance restart. Where would be a good palce to store this information @Apollon77? If we don't find a suitable object, we could store the information in a newly introduced state like `system.adapter.hm-rpc.0.startingPriority`?

**Comment by Apollon77** [comment]
But the admin zu idea above is not reflecting this - or?! The challenge is on how to make User understand that.

**Comment by Apollon77** [comment]
For storage: A state is an idea but then the controller needs to always read all these states on startup :-( for now everything is done with one getObjectView ...

Maybe one system.startup object?! This contains startup relevant data and first is this prio.

**Comment by DutchmanNL** [comment]
@foxriver76 @Apollon77 we should Adress this n next Dev meeting to agree on some progress here :) 
will put it on agenda

**Comment by foxriver76** [comment]
Assuming we go for the Tier Logic, my implementation proposal would be the following

Each instances `system.adapter...instance` object (+ io-pack of adapter of course) has a numeric `common.startupPriority` and `common.startupTier` attribute. Tier is defined by the dev, priority can be added by user via admin.

We create a new module e.g. `instanceHandler` in `lib` which will be used by `main.js` with the following methods

- `ensureSetup` - create startup object + read-only state, like, `system.host.hostname.startupOrder` and add instances from this host to it, also check if anything has been added/removed/changed while not running, so basically set state val anew everytime
and store info in RAM
-> called once at js-c start

- `addInstance` - takes instance, tier, prio
Adds the instance to the startup object and ensures the correct priority and tier
Has to be called on instance creation if js-c running and when moving adapter to this host while running ->
Do this everytime, system.adapter.instance object changed, also priority could have changed if we store it here we will get it too

- `removeInstance` -  takes instance
Remove instance from startup object, called if deleted while controller running

- `startAllInstances` - starts all instances in the defined order (outsource some logic which is correctly in main.js)
if no tier given - assume Tier 3
if no priority given - start at last in random order with other instances missing a priority

- maybe also `stopAllInstances` but can also be outsourced later, however would belong there by logic

We could do basically the same w/o Tier logic. So just having priority.

**Comment by DutchmanNL** [comment]
Is it whise to have Tier always defined by dev? tier 1 (like controller, admin, should maybe be reserved for ioBroker-Core and only >= tier 2 supported for dev input ?

**Comment by foxriver76** [comment]
Controller doesn’t need a tier ;-)

I would not hard code adapters in Controller. EG Script Engine should be a tier 1, however there could be a dev who also likes to implement a rules adapter or something like that which should also start at tier 1. However, we can discuss this on the next meeting.

**Comment by foxriver76** [comment]
Needs documentation and needs to be used ;-)

**Comment by Apollon77** [comment]
both done
