### ISSUE TITLE
[bug]: common.title and title.lang are not preserverd on upload again

### ISSUE THREAD

**Issue by Bannsaenger** [ioBroker/ioBroker.js-controller#2790]
### No existing issues.

- [X] There is no existing issue for my problem.

### Description

When you edit the instance title in admin on instances tab, the new title will be written in title.lang of the instance object.
The title.lang which is a object with several languages will be overtritten with a string.
If you upload the adapter, the title.land will be overwitten with teh object again.
This behavior was fixed in issue #1448 and is now open again.

### Reproduction instruction

Change a instance title and upload the adapter. The title is overwritten with the original content from package.json

### JS-controller version

5.0.19

### Node version

20.12.2

**Comment by foxriver76** [comment]
Already fixed in 6.0.0 coming beta next week
