### ISSUE TITLE
[enhancement]: get available update/upgrades via cli

### ISSUE THREAD

**Issue by Sen5ation** [ioBroker/ioBroker.js-controller#2791]
### No existing issues.

- [X] There is no existing issue for my request.

### Description

Is there a possibility to check if there are any updates to iobroker itself and the installed adapters via cli? I did not find it. The only thing I found was the `iobroker upgrade all` command, but there is no "-no" Option to force alö answers to now, so that I could parse the output ro something..

### Why?

I what to automaticly monitor the update status of my iobroker status without the need to browe to the webgui

### How?

A possible way could be the mentioned `iobroker upgrade all` command with a --no option.
Alternativly there could be a separate subcommand e.g.: `iobroker check-upgrades` which could printout a list of available upgrade/updates.

**Comment by foxriver76** [comment]
`iobroker  --help` gives you an overview and source are looking for `iob update`

**Comment by Sen5ation** [comment]
Thank you!

**Comment by mcm1957** [comment]
@Sen5ation 
If you want to monitor using js-adapter you could use the state admin.0.info.updatesList or updatesJson too.
