### ISSUE TITLE
[bug]: asterisk-adapter does not work with 6.01

### ISSUE THREAD

**Issue by sv-hjo** [ioBroker/ioBroker.js-controller#2798]
### No existing issues.

- [X] There is no existing issue for my problem.

### Description

the asterisk-adapter does not work after update.
Unfortunately this is the only SIP / VOIP-adapter that can be used for alarming-calls.
OK, the adapter is "old", but there is no alternative.
the adapter works with 5.0.19

### Reproduction instruction

just start the asterisk adapter and you get the errors in the log file.

### JS-controller version

6.01

### Node version

18.20.3

**Comment by mcm1957** [comment]
This issue should be created at adapter repository
