### ISSUE TITLE
Collection of misc CLI issues

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.js-controller#280]
Just a reminder for me, so I don't forget them. Found while working on #277. 

- [x] `iobroker status` should have a 3rd argument so one can check if a specific adapter or instance is running
- [ ] The list of commands (`showHelp`)  could use some basic explanation what the commands do.

**Comment by Apollon77** [comment]
@foxriver76 #1 is done, correct?, #2 feels too ...

**Comment by foxriver76** [comment]
Yes, second only partial

**Comment by AlCalzone** [comment]
1st is done. 2nd partially yes. If we want to go all out we could build the help menu like shown here:
http://yargs.js.org/

**Comment by Apollon77** [comment]
@AlCalzone @foxriver76 move to 3.3 for completion?
