### ISSUE TITLE
[enhancement]: add version info to startup info

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker.js-controller#2805]
### No existing issues.

- [X] There is no existing issue for my request.

### Description

Whenever an instance is started theres some message logged like

`2024-06-13 19:00:36.950	info	instance system.adapter.daikin.0 started with pid 2779``

This message is missing one (or two) importent infos. Please add
- version of the adapter
- information whether it is installed normally or from github 

### Why?

In many cases one has to ask provider of log to specify the aapter version although a complete log has been provided.

**Comment by Apollon77** [comment]
Hm ... the adapter itself will outoput these infos .. do we really need to duplicate that?

**Comment by foxriver76** [comment]
The Problem is if Adapter cannot start eg with the latest Adapter core Version or anything you don’t get the Information from log, that was @mcm1957 intention I guess

**Comment by mcm1957** [comment]
My Intention was to avoid repeating to ask the User which adapterversuon from which source he has onstalled. Several reports has a clear error log but did not contain the adapter version.  
I think I did post an example at the issue.
Duplicating app 8 chars should not flood log.
