### ISSUE TITLE
Multihost funktioniert nicht

### ISSUE THREAD

**Issue by bahnuhr** [ioBroker/ioBroker.js-controller#2808]
### No existing issues.

- [X] There is no existing issue for my problem.

### Description

Multihost scheint ab nodejs V20 nicht mehr zu funktionieren.
vgl. thread:
https://forum.iobroker.net/topic/75298/slave-start-nicht-mehr-nach-nodejs-update-20/34?_=1718517535980

Die Befehle "iob mulihost browse" und "iob multihost connect" zeigen:
`dieter@stromwasser:~ $ iob multihost browse
No Multihost server found. Make sure iobroker is running on the host where you enabled multihost discovery (and it is not this host)!
`
trotz Einstellung bei hosts:
![image](https://github.com/ioBroker/ioBroker.js-controller/assets/25694404/1f19fbcd-5589-4ad0-90be-b54cf4dd0bdc)

Aus meiner Sicht ist dies ein bug den man sich einmal anschauen sollte.

### JS-controller version

5.0.19

### Node version

Versuch mit 20

**Comment by foxriver76** [comment]
Ich denke es ist dieser Bug der mit v6 gefixt ist https://github.com/ioBroker/ioBroker.js-controller/issues/2706#issuecomment-2081438015
