### ISSUE TITLE
[bug]: incorrect schema for io-package.json

### ISSUE THREAD

**Issue by oweitman** [ioBroker/ioBroker.js-controller#2818]
### No existing issues.

- [X] There is no existing issue for my problem.

### Description

the property ignoreInVersions is at the wrong position/hierychy

### Reproduction instruction

see wrong/versus right object
https://forum.iobroker.net/topic/71786/vis2-ab-morgen-im-stable/337?_=1719335514744

reproduction in vscode. there is a warning, what ignoreInVersions should be an object and not an array

no further errors in log

### JS-controller version

6.05

### Node version

v20.13.1

**Comment by foxriver76** [comment]
I think we had this discussion started internally but not finished, we will take it into the next meeting.

**Comment by oweitman** [comment]
Ok,
The best thing would be to set the property at the widget set level, as it is currently defined in the schema.
The advantage would be that within an adapter you could allow or prohibit a widget set for vis1 and a widget set for vis 2, etc.

**Comment by foxriver76** [comment]
Yes, that was also my idea and why I started the discussion and did not change schema right away, will discuss with @GermanBluefox  and @Apollon77 next week.

**Comment by Apollon77** [comment]
Ok, we will move it into the widget object, so schema is correct. Implementation will be adjusted next.

**Comment by foxriver76** [comment]
IF not yet working as intended please raise an issue at https://github.com/ioBroker/ioBroker.vis-2

**Comment by oweitman** [comment]
cant find the commit where the issue is fixed?
at the moment in npm the latest version is set to 2.9.64
Versions >2.10 cannot currently be tested regularly. only install per npm and explizit name the version.
When will things continue here?

**Comment by foxriver76** [comment]
Then please open the issue at vis 2 repo because implementation needs to be done there. Schema is correct as stated so nothing we can do in controller

**Comment by oweitman** [comment]
also den kindergarten unterstütze ich nicht.
das problem wurde erkannt,
im devmeeting besprochen
https://forum.iobroker.net/topic/75449/meeting-f%C3%BCr-iobroker-core-dev-admin-17-07-24-20-30?_=1725104975740
und von den devs entschieden, das die implementierung angepasst wird. es hätte ja auch sein können, das das schema angepasst werden muss.
problem ist erkannt, ich glaube die todos sind auch bekannt.
wenn es jetzt nur noch daran hängt, das der issue nicht im richtigen repo hängt????
du wärst doch auch der, der es anpassen könnte, neben bluefox?

dann lasst es so wie es ist. mein herz hängt da nicht dran. dann halt erst, wenn der nächste dev dann bereit ist das problem im richtigen repo zu erfassen.

**Comment by foxriver76** [comment]
@oweitman nein bluefox muss es anpassen und was die reaction soll verstehe ich nicht. Du fragst auch gerne den Vis 2 PR erstellen
