### ISSUE TITLE
[bug]: js-controller is unable to update system packages, but restarts (no error)

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.js-controller#2819]
### No existing issues.

- [X] There is no existing issue for my problem.

### Description

*I'm not sure if this is an admin issue, socket issue or js-controller issue.*

When using the nodejs upgrade dialog in admin 7.0.6 the js-controller restarts but I don't get any error message or feedback (and node is not updated). The following message has been executed (socket debug in browser):

```
[3,52,"sendToHost",["system.host.iobroker","upgradeOsPackages",{"packages":[{"name":"nodejs"}],"restart":true}]]	1719424766.620813
```

Permissions should be fine:

```
sudo cat /etc/sudoers.d/iobroker 
[sudo] Passwort für mkleine: 
iobroker ALL=(ALL) ALL
iobroker ALL=(ALL) NOPASSWD: /usr/sbin/shutdown
iobroker ALL=(ALL) NOPASSWD: /usr/sbin/halt
iobroker ALL=(ALL) NOPASSWD: /usr/sbin/poweroff
iobroker ALL=(ALL) NOPASSWD: /usr/sbin/reboot
iobroker ALL=(ALL) NOPASSWD: /usr/bin/systemctl start
iobroker ALL=(ALL) NOPASSWD: /usr/bin/systemctl stop
iobroker ALL=(ALL) NOPASSWD: /usr/bin/mount
iobroker ALL=(ALL) NOPASSWD: /usr/bin/umount
iobroker ALL=(ALL) NOPASSWD: /usr/bin/systemd-run
iobroker ALL=(ALL) NOPASSWD: /usr/bin/apt-get
iobroker ALL=(ALL) NOPASSWD: /usr/bin/apt
iobroker ALL=(ALL) NOPASSWD: /usr/bin/dpkg
iobroker ALL=(ALL) NOPASSWD: /usr/bin/make
iobroker ALL=(ALL) NOPASSWD: /usr/bin/ping
iobroker ALL=(ALL) NOPASSWD: /usr/sbin/setcap
iobroker ALL=(ALL) NOPASSWD: /usr/bin/cat
iobroker ALL=(ALL) NOPASSWD: /usr/bin/df
iobroker ALL=(ALL) NOPASSWD: /usr/sbin/ldconfig
ALL ALL=NOPASSWD: /usr/bin/systemctl start iobroker
ALL ALL=NOPASSWD: /usr/bin/systemctl stop iobroker
ALL ALL=NOPASSWD: /usr/bin/systemctl restart iobroker
ALL ALL=(iobroker) NOPASSWD: /usr/bin/node /opt/iobroker/node_modules/iobroker.js-controller/iobroker.js *
```

### JS-controller version

6.0.5

### Node version

20.14.0

**Comment by klein0r** [comment]
The sendToHost action executes the "restart" action in any case. Even if the command failed:

https://github.com/ioBroker/ioBroker.js-controller/blob/0e2b4e4dfe3c3d18b57b0e214d65897b7cf1ae1f/packages/controller/src/main.ts#L2998-L3001

**Comment by foxriver76** [comment]
But yes on fail we should simply stop, so admin can show the error

**Comment by Apollon77** [comment]
The installer already add apt to sudoers so should be allowed https://github.com/ioBroker/ioBroker/blob/master/installer_library.sh#L647

**Comment by klein0r** [comment]
> Yes I think the problem is more that admin is not showing the version which is available in the sources but the newest one according to nodejs website

No, there is a newer version available:

```
mkleine@iobroker:~$ sudo apt list --upgradeable
[sudo] Passwort für mkleine: 
Auflistung… Fertig
nodejs/nodistro 20.15.0-1nodesource1 amd64 [aktualisierbar von: 20.14.0-1nodesource1]
```

**Comment by foxriver76** [comment]
Still only on mobile but -y should be added https://github.com/ioBroker/ioBroker.js-controller/blob/0e2b4e4dfe3c3d18b57b0e214d65897b7cf1ae1f/packages/cli/src/lib/setup/setupPacketManager.ts#L217

**Comment by klein0r** [comment]
@foxriver76 Should I create a PR?
