### ISSUE TITLE
Problems with function getForeignObjectAsync

### ISSUE THREAD

**Issue by schmupu** [ioBroker/ioBroker.js-controller#282]
@AlCalzone , I tried to use the promise function getForeignObjectAsync in the adapter.js. The return value in result is  null and no error ist thrown. If I call the same function as callback function getForeignObject I got in result values back.  I am using js-controller 1.4.2

```
adapter.getForeignObjectAsync('system.config').then(result => {　
   // do something with the result　
}).catch(e => {　
   // something went wrong　
});
```

**Comment by Steiger04** [comment]
Same problem with

`adapter.createDeviceAsync(...).then(_id => adapter.console.log(JSON.stringify(_id))`

versus

`adapter.createDevice(..., (err, _id) => adapter.console.log(JSON.stringify(_id)))`

If you use the callback you will get an object {id: 'your ID'} or an Error , in the Promise variant you get undefined. It looks as if there is a fundamental problem with promisification.

**Comment by AlCalzone** [comment]
The original example works for me, but I'm also on the `dev-1.6.0` branch. I'll take a look if something changed:
![tempsnip](https://user-images.githubusercontent.com/17641229/50689416-f87a9f00-1029-11e9-97c6-cd796b233b60.png)

**Comment by AlCalzone** [comment]
Oh... I see. You guys mean you are not getting an error, but instead the result `undefined`.

**Comment by AlCalzone** [comment]
I'm debugging where the problem is. `promisify()` as such does what it should:
![unbenannt](https://user-images.githubusercontent.com/17641229/50690590-26fa7900-102e-11e9-933d-d6b7ade6bb05.PNG)

**Comment by Steiger04** [comment]
@AlCalzone: Nicht ganz. Es ist so, wie ich es oben beschrieben habe. Wenn ich adapter.createDevice aufrufe ist alles fein und ich bekomme das Objekt mit der id aus _setObject(..).

`if (typeof callback === 'function') {
            setImmediate(function () {
                callback(null, {id: id});
            });
}`

 Wenn ich adapter.createDeviceAsync aufrufe kommt immer nur ein undefined zurück und zwar im then-Part nicht im catch-Part.

Vielleicht hängt das mit setImmediate() zusammen?

**Comment by AlCalzone** [comment]
@Steiger04 Ich kann das Problem reproduzieren, indem ich `getForeignObject` mit einem nicht existierenden Objekt aufrufe. Da gibt es soweit ich es bisher gesehen habe kein setImmediate.

**Comment by AlCalzone** [comment]
@Steiger04 kannst du bitte mal deinen exakten Code posten (ohne "...")?

**Comment by schmupu** [comment]
Ich bekomme null in meinem Beispiel in result zurück. Error ist nicht gesetzt.

**Comment by AlCalzone** [comment]
@schmupu Und du bist sicher, dass das Objekt existiert? Kannst du bitte mal testen mit einem anderen Objekt das ganz sicher da ist?

@Steiger04 Dein Problem liegt nicht an promisify - zumindest soweit ich das nachvollziehen kann. Kannst du bitte mal mit einer Funktion testen, die ganz sicher einen Wert liefern müsste? Z.B. getStateAsync

https://github.com/ioBroker/ioBroker.js-controller/pull/273 hat das Verhalten von setState und setForeignState verändert, was intern von createDevice verwendet wird. Damals ist uns nicht aufgefallen, dass der Rückgabewert fehlt. Das kann dann aber nicht in 1.4.2 sein.

**Comment by Steiger04** [comment]
@AlCalzone ich habe jetzt ioBroker neu gestartet, der Quellcode des Adapters ist exakt der Gleiche und nun bekomme ich den erwarteten Rückgabewert. Ich vermute mal durch die ganze Testerei ist da irgendetwas in node.js schiefgelaufen. Jetzt scheint es aber zu funktionieren. Wenn sich der Fehler wieder einstellt und sich reproduzieren lässt, melde ich mich wieder. Erstmal Danke für Deine Bemühungen.

**Comment by AlCalzone** [comment]
Ok dann schieben wir es auf User-Fehler ;)

**Comment by Steiger04** [comment]
Ja müssen wir wohl leider, solange das Gegenteil nicht bewiesen wurden ;). Die Einführung der async-Funktionen ist übrigens eine geniale Sache. Ich konnte bluebird rauswerfen und mit async und await macht es deutlich mehr Freude, als wie mit diesen elendig verschachtelten callbacks ;)

**Comment by schmupu** [comment]
Leider geht es bei mir nicht. Hier mal mein Testprogramm um die Koordinaten auszulesen.

`
function getCoordnates(callback) {

  adapter.getForeignStateAsync('system.config').then(result => {
    adapter.log.info("getForeignStateAsync: " + JSON.stringify(result));
  }).catch(e => {
    adapter.log.info(JSON.stringify(e));
  });



  adapter.getForeignObject('system.config', (error, states) => {
    if (!error) {
      adapter.log.info("getForeignState: " + JSON.stringify(states));
      callback && callback({ latitude: states.common.latitude, longitude: states.common.longitude });
    } else {
      adapter.log.info(JSON.stringify(error));
      callback && callback();
    }
  });
}
`
Hier der Output:
`
getForeignStateAsync: null

getForeignState: {"common":{"name":"System configuration","city":"Hamburg","country":"Germany","longitude":"10.084","latitude":"53.655347","language":"de","tempUnit":"°C","currency":"€","dateFormat":", ... } }
`
