### ISSUE TITLE
[enhancement]: Add "upgrade policy" to cli adapter list output

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.js-controller#2825]
### No existing issues.

- [X] There is no existing issue for my request.

### Description

e.g.

<img width="1232" alt="Screenshot 2024-07-01 at 10 22 24" src="https://github.com/ioBroker/ioBroker.js-controller/assets/1959049/f180900f-5e17-4772-aad4-66f63c974a54">

```js
const text = `${id.padEnd(39)}: ${name.padEnd(21)} - v${obj.value.common.version.padEnd(8)} - ${obj.value.common?.automaticUpgrade ?? 'none'}`;
```

### Why?

To see directly which adapters are upgraded with which semver policy

**Comment by foxriver76** [comment]
Same would also make sense for `repo show` if we touch it anyways.
