### ISSUE TITLE
[bug]: iob beendet sich nicht immer unter Windows

### ISSUE THREAD

**Issue by UweRP** [ioBroker/ioBroker.js-controller#2834]
### No existing issues.

- [X] There is no existing issue for my problem.

### Description

Sorry das ich hier deutsch schreibe, aber mit englisch wird das nichts :-)

iobroker beendet sich nicht immer nach einem iob stop bzw. iobroker stop

"[@apollon77](https://forum.iobroker.net/uid/271) Leider nicht wirklich mehr Details.
Ich habe den Eindruck, dass der javascript Adapter (ja meine den Script Adapter) beendet wird bei iob stop aber dann wieder neu startet. Ist dies der Fall dann werden auch die anderen Adapter nicht gestoppt. Kann man sehr schön über den Windows Taskmanager verfolgen, die Auslastung des Systems geht dann auch hoch.
Wenn ich nach einem iob stop feststelle, dass sich ioBroker nicht beendet dann schicke ich einen iob stop javascript hinterher, dann werden auch alle anderen Adapter beendet.
Leider passiert das häufig aber nicht immer, gerade habe ich ioBroker gestoppt und dieser wurde einwandfrei beendet.
Welches Log ist dann für dich interessant? Wenn ich nächstes mal auf das Problem stoße werde ich in GitHub ein Issue auf machen."

Bezugnehmen auf https://forum.iobroker.net/post/1178567 hier ein Log

[iobroker.2024-07-09.log](https://github.com/user-attachments/files/16141016/iobroker.2024-07-09.log)

### JS-controller version

6.0.6

### Node version

20.15.0

**Comment by foxriver76** [comment]
Unfortunately the shutdown process is not executed like on Linux see https://github.com/ioBroker/ioBroker.js-controller/issues/2764

So, we would need to look into what `iob stop` exactly does on Windows, which is part of installer.

https://github.com/ioBroker/ioBroker/blob/2cf859a3a7b4e3414e4e01efe6d5e045b57e7e81/install/windows/serviceIoBroker.bat#L43

Any idea what this does under the hood @Gaspode69

Maybe it stops all processes and adapters are maybe stopped before controller and controller then has a few ms to restart adapters ..

**Comment by Gaspode69** [comment]
> Any idea what this does under the hood

Not really. ioBroker uses node-windows to wrap the js-controller script as a Windows service.
As far as I understand, the according node process is killed if the service is stopped, so the normal exit handlers of js-controller should be triggered.

**Comment by mcm1957** [comment]
According to log adapters are restarted.

**Comment by mcm1957** [comment]
I just Trier to search for the eror Code. Error 4294967295 (0xfffffffff) seems to be ralated to some timouts of Linux subsystem or Service. Well that could Match.

Maybe we should check this error code at js-controller and do not restart Adapter in thus case ?

Note that i did not check complere mobile. But if all adapters terminate with this Code we ciukd try to handle it. Eventually at Windows OS only.

**Comment by Gaspode69** [comment]
> Maybe we should check this error code at js-controller and do not restart Adapter in thus case ?

I don't think that this would be a proper solution.

If you start controller.js in a cmd window and stop it using Ctrl+C, the exit handlers are executed properly. If it has been started as a service and the service is stopped, it behaves differently.

Attached are two logfiles, the cleanshutdown was started in a ioBroker cmd Window manually, the other as a service:

[iobroker.2024-07-09_service.log](https://github.com/user-attachments/files/16144392/iobroker.2024-07-09_service.log)
[iobroker.2024-07-09_cleanshutdown.log](https://github.com/user-attachments/files/16144398/iobroker.2024-07-09_cleanshutdown.log)

> But ioBroker on Windows is normally not running in WSL or is it running in WSL

No, ioBroker is running under native Node.js under Windows, not under WSL.

**Comment by Gaspode69** [comment]
I guess there are some additional parameters to control how the Node process has to be ended in node-windows.
I'll have a look and do some tests, but I don't kow if I'll manage to do it before the weekend.

**Comment by mcm1957** [comment]
> > Maybe we should check this error code at js-controller and do not restart Adapter in thus case ?
> 
> I don't think that this would be a proper solution.
> 
> If you start controller.js in a cmd window and stop it using Ctrl+C, the exit handlers are executed properly. If it has been started as a service and the service is stopped, it behaves differently.
> 
> Attached are two logfiles, the cleanshutdown was started in a ioBroker cmd Window manually, the other as a service:
> 
> [iobroker.2024-07-09_service.log](https://github.com/user-attachments/files/16144392/iobroker.2024-07-09_service.log) [iobroker.2024-07-09_cleanshutdown.log](https://github.com/user-attachments/files/16144398/iobroker.2024-07-09_cleanshutdown.log)
> 
> > But ioBroker on Windows is normally not running in WSL or is it running in WSL
> 
> No, ioBroker is running under native Node.js under Windows, not under WSL.

If you can get the adapter Prozesses to stop with a "correct" exit code this would be best of course.

I suggested to handle the special exit code if one cannot get the Prozesses to terminate with normal Codes.

**Comment by UweRP** [comment]
> Interesting. But ioBroker on Windows is normally not running in WSL or is it running in WSL @UweRP

Ich benutze WSL nicht.
NodeJS https://nodejs.org/dist/latest-v20.x/node-v20.15.1-x64.msi ist installiert.

**Comment by mcm1957** [comment]
Code -1 seems to be some general error code for all unhandlich errors. Its mentioned at several Situations.

So lets wait what Garfonso detects at node-windows investigation

**Comment by Gaspode69** [comment]
OK, forget about it. There is a "new" version of winsw which seems to solve the problem.
I'll try to find out how to integrate that.

**Comment by Gaspode69** [comment]
Please test:
https://forum.iobroker.net/post/1180037

**Comment by foxriver76** [comment]
can this be closed or are there still existing issues?

**Comment by Gaspode69** [comment]
Issue still exists, will be fixed with this PR:
https://github.com/ioBroker/ioBroker/pull/537

**Comment by Gaspode69** [comment]
https://github.com/ioBroker/ioBroker/pull/537 merged and published.
@UweRP 
Please verify and close issue if solved.
