### ISSUE TITLE
[bug]: SyntaxError: Unexpected token '<', "<!doctype "... is not valid JSON

### ISSUE THREAD

**Issue by Horgul123** [ioBroker/ioBroker.js-controller#2841]
### No existing issues.

- [X] There is no existing issue for my problem.

### Description

When trying to update js-controller I get a
`SyntaxError: Unexpected token '<', "<!doctype "... is not valid JSON`

Happens since several version.
At the moment tried to update from 6.0.6 to 6.08

In the past the commands to do the manuell upgrade where shown, but now I only get this error message.

### Reproduction instruction

Start update js-controller

### JS-controller version

6.0.6

### Node version

v20.15.1

**Comment by foxriver76** [comment]
It is an Admin Issue please Open issue there if not existing
