### ISSUE TITLE
[enhancement]: Provide methods to translate text using the provided i18n json files.

### ISSUE THREAD

**Issue by MiSchroe** [ioBroker/ioBroker.js-controller#2843]
### No existing issues.

- [X] There is no existing issue for my request.

### Description

As an adapter developer I would like to provide translations to the end user wherever meaningful and possible. For the settings dialog this is already possible and the translation is managed by Weblate.

As the backend for translations is already in place it would make sense to me, to use the same principles for translating other stuff, like state names and descriptions, device manager integration, but not limited to the mentioned uses cases.

Thus it would be helpful to the adapter developer to have some methods in place that return either a translated string (including parameter replacement) or an `Translated` object. The translations themselves should be stored in i18n json files and managed through Weblate as it is already done for the Admin settings.

### Why?

Advantages:

- Thoroughly tested method to use.
- Adapter developers don't have to "reinvent the wheel".
- Translations can be managed from outside of the adapter development.

### How?

Here are some possible methods:

```typescript
/**
 * Interface for translation functions.
 */
export interface Translate {
	/**
	 * Returns the translated text of the given textKey in the given language.
	 *
	 * @param language Target language into which the text should be translated.
	 * @param textKey Key of the text in the i18n json files that should be translated.
	 * @param Context Context object that should be used for substitutions in the translation.
	 *
	 * @example
	 * // ./admin/i18n/de/translations.json:
	 * // {
	 * //     "helloworld": "Hallo Welt!"
	 * // }
	 * // returns 'Hallo Welt!'
	 * await translateTo('de', 'helloworld');
	 *
	 * @example
	 * // ./admin/i18n/de/translations.json:
	 * // {
	 * //     "helloworld-parameter": "Hallo {who}!"
	 * // }
	 * // returns 'Hallo Welt!'
	 * await translateTo('de', 'helloworld-parameter', { who: 'Welt' });
	 */
	translateTo(language: ioBroker.Languages, textKey: string, context?: Record<string, string>): Promise<string>;

	/**
	 * Returns the translated text of the given textKey in the system language.
	 *
	 * @param textKey Key of the text in the i18n json files that should be translated.
	 * @param context Context object that should be used for substitutions in the translation.
	 *
	 * @example
	 * // ./admin/i18n/de/translations.json:
	 * // {
	 * //     "helloworld": "Hallo Welt!"
	 * // }
	 * // returns 'Hallo Welt!'
	 * await translate('helloworld');
	 *
	 * @example
	 * // ./admin/i18n/de/translations.json:
	 * // {
	 * //     "helloworld-parameter": "Hallo {who}!"
	 * // }
	 * // returns 'Hallo Welt!'
	 * await translate('helloworld-parameter', { who: 'Welt' });
	 */
	translate(textKey: string, context?: Record<string, string>): Promise<string>;

	/**
	 * Returns an object containing all translations of the given textKey.
	 *
	 * @param textKey Key of the text in the i18n json files that should be translated.
	 * @param context Context object that should be used for substitutions in the translation.
	 *
	 * @example
	 * // ./admin/i18n/en/translations.json:
	 * // {
	 * //     "helloworld": "Hello World!"
	 * // }
	 * // ./admin/i18n/de/translations.json:
	 * // {
	 * //     "helloworld": "Hallo Welt!"
	 * // }
	 * // returns {
	 * //     en: 'Hello World!',
	 * //     de: 'Hallo Welt!'
	 * // }
	 * await getTranslatedObject('helloworld');
	 *
	 * @example
	 * // ./admin/i18n/en/translations.json:
	 * // {
	 * //     "helloname-parameter": "Hello, {who}!"
	 * // }
	 * // ./admin/i18n/de/translations.json:
	 * // {
	 * //     "helloname-parameter": "Hallo, {who}!"
	 * // }
	 * // returns {
	 * //     en: 'Hello, Jane Doe!',
	 * //     de: 'Hallo, Jane Doe!'
	 * // }
	 * await getTranslatedObject('helloname-parameter', { who: 'Jane Doe' });
	 */
	getTranslatedObject(textKey: string, context?: Record<string, string>): Promise<ioBroker.Translated>;
}
```

**Comment by foxriver76** [comment]
Do you have an example where it would be feasible to translate things in the backend?

**Comment by mcm1957** [comment]
Not my issue but I do already translate the descriptions of states using the json files at one Adapter.

In addition messages sent to user ( i.e. via telegram etc) are at least nice to be translated. Only Log Entries should NEVER be translated.

**Comment by MiSchroe** [comment]
> Do you have an example where it would be feasible to translate things in the backend?

Whenever I create a new object in an adapter, I have a property `code` in the `common` object defined as `ioBroker.ObjectCommon.desc?: ioBroker.StringOrTranslated | undefined`. For the end user it would help to read at least the description in *his* language. And the quality of the translation would be better if it would be managed by Weblate. Today, I can only hard-code the translation or just leave it at english.

Another example:
I'm currently implementing the support for the device manager. In the device manager you can show messages to the end user, like "Searching for devices...", "5 new devices found." etc. It would lower the barrier for the user if the user could read it in a language she/he knows.

**Comment by mcm1957** [comment]
Original discussion at telegram
https://t.me/ioBroker_development/38508

Related to device manager

**Comment by MiSchroe** [comment]
Ok, I have changed my proposal of the interface a little bit:
* Promises as return values
* Placeholder replacement: instead $1, $2, ... we should use a context object (`Record<string, string>`), e.g. "Product {productId} doesn't exist.". That makes it easier for the translation to unterstand the context of the parameters. Example "$1 doesn't exist in $2." vs. "{product} doesn't exist in {room}."

**Comment by MiSchroe** [comment]
I have implemented a first draft in my adapter at https://github.com/MiSchroe/ioBroker.klf200/blob/70365ace4d04d976e2e1f94c667144e157571ddc/src/klf200Adapter.ts#L181-L377

Actual caveats:
* The context replacement uses a naïve regular expression without the possibility to escape the replacement.

**Comment by mcm1957** [comment]
If implementing a generalbadapter feature please consider that i18nbfiles mit be located at i18n root and named en.json, ... too.

**Comment by mcm1957** [comment]
> Ok, I have changed my proposal of the interface a little bit:
> 
> * Promises as return values
> * Placeholder replacement: instead $1, $2, ... we should use a context object (`Record<string, string>`), e.g. "Product {productId} doesn't exist.". That makes it easier for the translation to unterstand the context of the parameters. Example "$1 doesn't exist in $2." vs. "{product} doesn't exist in {room}."

I think promises are a little bit of Overkill. Im mist cases the translation should return the string with translationni desired language. If this falls the translation in english. And ufcthis dails too the pssed key. I do not think there are nany places whete a more complex error handling makes sense.

And personally I would prefer flat parameters instead of an object. Thisxway one or strings vould be passed without Overheadprojektor of an object. But js woukd allow both. Code could check whether one or mor strings sie passed or  one object.

**Comment by foxriver76** [comment]
Will be inplemented by https://github.com/ioBroker/adapter-core/pull/585 will be the same Module as frontend
