### ISSUE TITLE
[usability bug]: Allow disabling "OS package updates available" popups

### ISSUE THREAD

**Issue by agross** [ioBroker/ioBroker.js-controller#2849]
### No existing issues.

- [X] There is no existing issue for my problem.

### Description

Every time I open ioBroker's admin interface I am presented with this dialog:

<img width="543" alt="2024-07-25_22-11-00" src="https://github.com/user-attachments/assets/56d7ea11-969c-4de1-b21b-1d5593d8c35e">

I've acknowledged and closed the information several times, they pop up again - every time I refresh the page. 

Since I use docker I'm not that much interested updating those base files. Perhaps there is no updated base image available. I'd argue in the context of docker, showing this message does not make much sense.

### Reproduction instruction

Upgrade to js-controller 6.x

### JS-controller version

6.x

### Node version

18

**Comment by foxriver76** [comment]
For disabling (suppressing) notifications in general please use https://github.com/foxriver76/ioBroker.notification-manager/blob/main/src/main.ts

For docker it might be useful to just disable the check. Checking for new docker images would be more like a feature request.

**Comment by foxriver76** [comment]
@buanet do you think it makes sense to disable the notification in general for Docker? Then we can bring this change in before going to stable.

**Comment by buanet** [comment]
@foxriver76  I think we should switch from checking for packages to checking for new Docker image.

As i figured out, the best way would be to integrate a env with build date (already a Docker label) so js-controller could access the information and check docker hub for a new version of the image....

Would be a small change to the Doockerfile only.

**Comment by foxriver76** [comment]
Then open an admin issue to not automatically open it or better provide a PR there

**Comment by agross** [comment]
The notification manager is an absolute life-saver! Didn't know about it yet, thank you.
