### ISSUE TITLE
iobroker host this not (fully) working

### ISSUE THREAD

**Issue by buanet** [ioBroker/ioBroker.js-controller#286]
Hallo,
wie [hier](https://github.com/ioBroker/ioBroker/issues/40) bereits einmal beschrieben wurde gibt es Probleme mit "iobroker host this" oder "iobroker hots [hostname]" beim generieren eines Docker-Images.

Zur Erläuterung: 
Beim generieren eines Docker-Images werden nacheinander die Befehle aus dem Dockerfile abgearbeitet. Jeder einzelne Befehl wird dabei in einem temporären Container ausgeführt. Ist der Befehl abgearbeitet wird ein neuer temporärer Container (inkl. temporären, cryptischem Hostname) erstellt und der nächste Befehl abgearbeitet. Am Ende entsteht so ein Image dass dann die Grundlage für den "produktiv-container" bildet. 

Einer der Befehle, die in einem temporären Container abgearbeitet werden ist dabei natürlich auch die Installation von iobroker inkl. der vorinstallierten Adapter "admin" und "discovery". Dabei wird der temporäre Hostname des Build-Containers verwendet und in den Tiefen von iobroker als hostname gesetzt. 

Bisher habe ich das Ganze mit einem Script, welches beim Erstellen des Produktiv-Containers läuft abfangen können und über ein "iobroker host [hostname]" den Namenseintrag auf den letztendlichen Hostname des Produktiv-Containers umgeschlüsselt. Leider funktioniert das seit ein paar Tagen so nicht mehr. 
Die beiden vorinstallierten Adapter "admin" und "discovery" bleiben trotz "iobroker host [hostname]" auf den temporären Hostname geschlüsselt und lassen sich so dann später nicht starten.

Mein Workaround ist derzeit, dass ich die vorinstallierten Adapter nach dem Setzen des Hostnames per  "iobroker host this" einmal entferne (iobroker del admin.0 && iobroker del discovery.0) und wieder hinzu füge (iobroker add admin && iobroker add discovery). Dann laufen sie auch mit dem neuen Hostnamen. Ist natürlich keine besonders saubere Lösung...

Ich hoffe ich konnte das Problem einigermaßen beschreiben. :)

**Comment by Apollon77** [comment]
Can you try to reproduce it and maybe use debug logging to get more details what exactly wents wrong?

**Comment by AlCalzone** [comment]
Kann ich zuverlässig bestätigen. Dockerfiles und ioBroker 1.6+ arbeiten nicht gut zusammen.

My workaround includes editing all objects directly - this has to happen last in every Dockerfile that installs adapters/instances:
```Dockerfile
# We will be using the hostname "iobroker" later, so configure all instances to run on host "iobroker"
RUN iobroker list instances | grep -o -P "system\.adapter\.[^\.]+\.\d+" | awk '{system("iobroker object set " $1 " common.host=iobroker")}'
```
(requires the dev-branch of JS-Controller 1.6)

**Comment by resper** [comment]
Bekomme es unter unRaid + Docker auch nicht zu laufen. Letzter Eintrag in der Log-File:

> host.89e10be87413 does not start any instances on this host

**Comment by AlCalzone** [comment]
@buanet Kannst du bitte mal schauen, was in den einzelnen Instanz-Objekten `system.adapter.adaptername.0` als Host (`common.host`) steht, wie das Objekt `system.host......` heißt und was der tatsächliche Hostname ist?

**Comment by resper** [comment]
@AlCalzone wie genau mache ich das?

**Comment by AlCalzone** [comment]
Im admin in der Objekte Liste den Expertenmodus aktivieren und bei den genannten Objekten auf den Bleistift klicken. Dort müsstest du es sehen

**Comment by resper** [comment]
@AlCalzone Die Weboberfläche startet ja erst gar nicht.

**Comment by AlCalzone** [comment]
Uuups. Auf der Konsole:
`iobroker object get system.adapter.admin.0 --pretty`
Und analog für discovery, sowie `system.host.?????`

**Comment by resper** [comment]
iobroker object get system.adapter.admin.0 --pretty:
"host": "4b57c88c0ac7"

iobroker object get system.adapter.discovery.0 --pretty:
"host": "4b57c88c0ac7"

iobroker object get system.host.4b57c88c0ac7 -pretty
not found

LogFile:

> 2019-01-10 07:48:08.401  - info: host.89e10be87413 iobroker.js-controller version 1.2.3 js-controller starting
> 2019-01-10 07:48:08.404  - info: host.89e10be87413 Copyright (c) 2014-2017 bluefox, 2014 hobbyquaker
> 2019-01-10 07:48:08.404  - info: host.89e10be87413 hostname: 89e10be87413, node: v6.14.3
> 2019-01-10 07:48:08.404  - info: host.89e10be87413 ip addresses: 172.17.0.7
> 2019-01-10 07:48:08.412  - info: host.89e10be87413  inMem-states listening on port 9000
> 2019-01-10 07:48:08.419  - info: host.89e10be87413  inMem-objects listening on port 9001
> 2019-01-10 07:48:08.425  - info: host.89e10be87413 InMemoryDB connected
> 2019-01-10 07:48:08.429  - info: host.89e10be87413 2 instances found
> 2019-01-10 07:48:08.431  - warn: host.89e10be87413 does not start any instances on this host

**Comment by buanet** [comment]
Kann ich bestätigen. Bei mir ist es zwar ein anderer "temporärer" Host, aber es sieht genauso aus. 
Mache ich in diesem Zustand ein "iobroker host this" sagt er keine Instanzen gefunden:

`root@iobroker:/opt/iobroker# iobroker host this`
`No instances found for host "this".`
`root@iobroker:/opt/iobroker# iobroker host iobroker`
`No instances found for host "iobroker".`

**Comment by AlCalzone** [comment]
@Apollon77 The problem is that Docker executes its build scripts (Dockerfiles) command by command. And every command has its own temporary VM with a random hostname.
So the iobroker host is created in one VM (hostname no 1), the instances are created in a second VM (hostname no 2) and the final installation is run in a third VM (hostname no 3).

`iobroker host this` sets the hostname of the host (no 1) to the current hostname (no 3), but fails to update the instances because they neither belong to host no1 nor to host no 3.

Maybe `iobroker host this` should check if the current host is in `multihost mode` and if it isn't, also update all instances to use the current hostname?

**Comment by AlCalzone** [comment]
Eigentlich können wir bei Deutsch bleiben - Englisch ist ein Reflex :laughing: 

@buanet kannst du auch noch die Objekte zeigen wie [hier](https://github.com/ioBroker/ioBroker.js-controller/issues/286#issuecomment-453001694), am besten vor und nach `iobroker host this`?

**Comment by buanet** [comment]
Kann ich, aber im Moment ist es so, dass `iobroker host this` gar nichts tut. Der Output ist vor- und nachher gleich. Der Befehl selbst gibt dieses hier: 
`root@iobroker:/opt/iobroker# iobroker host this`
`No instances found for host "this".`

Ich habe jetzt eben aber mal per "try and error" folgendes gemacht:
`root@iobroker:/opt/iobroker# iobroker host 39ecf4674c72`
`Instance host changed for "system.adapter.admin.0" from "39ecf4674c72" to "iobroker".`
`Instance host changed for "system.adapter.discovery.0" from "39ecf4674c72" to "iobroker".`

Das Funktioniert. "39ecf4674c72" ist der temporäre Hostname der in den Objekten stand. Die Adapter werden auf auf den aktuellen hostnamen geschlüsselt und nach dem Start des iobroker laufen sie auch.

Für mich sieht das danach aus, dass iobroker die "this" option irgendwie nicht erkennt oder flasch interpretiert und dann "this" als hostname verwendet... Dazu gibt es natürlich keine Instanzen die er mit dem neuen hostnamen versorgen kann. Kann das sein?

**Comment by AlCalzone** [comment]
> Für mich sieht das danach aus, dass iobroker die "this" option irgendwie nicht erkennt oder flasch interpretiert und dann "this" als hostname verwendet... Dazu gibt es natürlich keine Instanzen die er mit dem neuen hostnamen versorgen kann. Kann das sein?

Mag durchaus sein, scheinbar wird die Option beim Anpassen der Instanzen nicht richtig berücksichtigt:
https://github.com/ioBroker/ioBroker.js-controller/blob/1.6.0-dev/lib/setup.js#L1665
Das wurde (soweit ich das sehe) lange nicht mehr verändert.

**Comment by Apollon77** [comment]
Re: https://github.com/ioBroker/ioBroker.js-controller/issues/286#issuecomment-453056360

not when you call iobroker host iobroker, then this would be the exected result

**Comment by Apollon77** [comment]
Ok, Deutsch :-)

Ich verstehe den Build Prozess. Ich würde halt idealerweise gern mal mit silly sehen was das "iobroker host this" genau tut wenn es dann ausgeführt wird zum start des containers. Dann sehen wir mal mindestens vllt besser was er tut.

Mit den "iobroker host this" laäuft er hier rein:

https://github.com/ioBroker/ioBroker.js-controller/blob/1.6.0-dev/lib/setup.js#L1552
dann holt er alle Host einträge und landet an sich hier https://github.com/ioBroker/ioBroker.js-controller/blob/1.6.0-dev/lib/setup.js#L1566 und setzt so den alten Hostnamen zu einem Host-Eintrag den er findet. Bei mehreren gibts nen fehler.
Danach landet er in https://github.com/ioBroker/ioBroker.js-controller/blob/1.6.0-dev/lib/setup.js#L1612


PS: wenn ich mir https://github.com/ioBroker/ioBroker.js-controller/blob/1.6.0-dev/lib/setup.js#L1582 ansehe dann wäre am Anfang ein "iobroker hist set iobroker" eure lösung weil der name damit auf "iobroekr "festgepinnt wird und nicht mehr der dynamische hostname genommen wird ?!?!

**Comment by buanet** [comment]
> Ok, Deutsch :-)
> 
> Ich verstehe den Build Prozess. Ich würde halt idealerweise gern mal mit silly sehen was das "iobroker host this" genau tut wenn es dann ausgeführt wird zum start des containers. Dann sehen wir mal mindestens vllt besser was er tut.
> 
Ich hab jetzt den js-controller auf silly gesetzt. Wohin sollte er das log schreiben? In /opt/iobroker/log ist nichts.

> Mit den "iobroker host this" laäuft er hier rein:
> 
> https://github.com/ioBroker/ioBroker.js-controller/blob/1.6.0-dev/lib/setup.js#L1552
> dann holt er alle Host einträge und landet an sich hier https://github.com/ioBroker/ioBroker.js-controller/blob/1.6.0-dev/lib/setup.js#L1566 und setzt so den alten Hostnamen zu einem Host-Eintrag den er findet. Bei mehreren gibts nen fehler.
> Danach landet er in https://github.com/ioBroker/ioBroker.js-controller/blob/1.6.0-dev/lib/setup.js#L1612

Also zum Verständnis: `iobroker host this` sucht alle Hosteinträge und ändert sie auf den aktuellen. Woher bezieht er den neuen Hostnamen?
Wie arbeitet `iobroker host [hostname]`? Von der Logik her sollte das ja alle Hosteinträge auf den als [hostname] angegebenen namen ändern. Wenn das so ein soll, dann wäre das verhalten wie es hier https://github.com/ioBroker/ioBroker.js-controller/issues/286#issuecomment-453050070  funktioniert ja verkehrt herum... dann müsste ein `iobroker host 39ecf4674c72` die Hosteinträge ja auf 39ecf4674c72 setzen...

> PS: wenn ich mir https://github.com/ioBroker/ioBroker.js-controller/blob/1.6.0-dev/lib/setup.js#L1582 ansehe dann wäre am Anfang ein "iobroker hist set iobroker" eure lösung weil der name damit auf "iobroekr "festgepinnt wird und nicht mehr der dynamische hostname genommen wird ?!?!

Das wäre wohl keine gute Lösung. Der Hostname des containers sollte dynamisch bleiben da er beim starten des Containers frei gewählt werden kann.

**Comment by Apollon77** [comment]
der aktuelle hostname ist der der für den host "systemseitig" gesetzt ist.

Und zu der Idee: NEIN du setzt damit nicht den hostnamen des Containers, sondern nur den internen namen der ioboker instanz und damit wie der "Hist" iobroker.intern heisst.

geht nur kaputt wenn man aus zwei solchen Containern ein Master-Slave baut weil der Name nicht gleich sein darf

**Comment by Apollon77** [comment]
>Wie arbeitet iobroker host [hostname]?

Das sollte so arbeiten das er den "hostname" sucht und auf den aktuellen umstellt. Das willst Du also nicht.
Das ist der Weg um im Multihost umfeld dinge zu tun wie hostnameänderungen. (Umziehen dann "iobroker host altername" eingeben und es wird mit dem neuen ersetzt

**Comment by AlCalzone** [comment]
> (Umziehen dann "iobroker host altername" eingeben und es wird mit dem neuen ersetzt

Ahh das macht Sinn, dass es dann anders herum funktioniert.

Zu `this`:  
`iobroker host this` sorgt dafür, dass `oldHostname = undefined` ist. An den meisten Stellen wird darauf geprüft und entsprechend gehandelt.
https://github.com/ioBroker/ioBroker.js-controller/blob/1.6.0-dev/lib/setup.js#L1665 (hier werden die Instanzen aktualisiert) ändert aber nur die Instanzen, deren host `=== oldHostname` ist. Diese kann es nicht geben, da alle Hostnamen ungleich `undefined` sind.

**Comment by AlCalzone** [comment]
Soll `iobroker host this` im Single-Host Modus **alle** möglicherweise existierenden Hostnamen auf den aktuellen setzen oder nur den, der auch im Host-Objekt steht?

**Comment by resper** [comment]
> PS: wenn ich mir https://github.com/ioBroker/ioBroker.js-controller/blob/1.6.0-dev/lib/setup.js#L1582 ansehe dann wäre am Anfang ein "iobroker hist set iobroker" eure lösung weil der name damit auf "iobroekr "festgepinnt wird und nicht mehr der dynamische hostname genommen wird ?!?!

Kann ich testen, an welcher Stelle soll ich die Zeile einfügen?

**Comment by Apollon77** [comment]
Ne bessere Idee wäre vllt ein zufälliger Name anstelle „iobroker“ weil das dann die oben beschriebenen Probleme mit multihost nicht haben sollte. 

Wo? Direkt mach der Installation.

Vllt kann man es sogar im gleichen Container wie install ausführen als zwei Kommandos mit && verknüpft?!

**Comment by buanet** [comment]
Ich bin immer davon ausgegangen, dass der iobroker instanz name nach der Erstinstallation dem systemseitigen hostnamen entspricht bzw. entsprechen sollte. War bei mir auch bisher immer so.
Das ioBroker Setup macht es ja eigentlich unter normalen Umständen auch. 
Nur im Docker wird bei der Installation halt der temporäre Hostname genommen. Das kann ich aber mit einem Script abfangen, dass beim ersten Start des Containers `iobroker host [temporärer hostname]`aufruft. Damit wird (wie ich gelernt habe) dann der neue systemseitige hostname fürdie instanzen übernommen. Und ich vermeide "iobroker host this" komplett. :)

Die Option `iobroker host this` ist allerdings einfacher, wenn man wie vorgeschlagen umsetzt, dass sie im single host modus einfach alle Adapter und den Host auf den systemseitigen hostnamen schlüsselt/ umbenennt... Macht meiner Meinung nach auch Sinn.

Wie auch immer, ich muss im Docker beim Start des Containers die Instanznamen gerade ziehen.

Habe ich das jetzt so richtig verstanden bzw. wiedergegeben?

**Comment by AlCalzone** [comment]
Es sollte am Ende des dockerfiles einmalig den host und die Instanz auf den gleichen Hostnamen festzulegen. Danach sollte iobroker in der Lage sein es beim Start zu korrigieren.

**Comment by resper** [comment]
Leider ist das bei mir, glaube ich, nicht ganz so einfach. Ich nutte unRaid mit seinem internen Docker System, irgendwie ist das da alles anders und man kommt nicht wirklich an die laufenden Docker Instanzen ran. Ich versuche es gerade über einen eigene Fork und Dockerhub hin zu bekommen,

Offtopic:
@buanet wir kommen aus der gleichen Gegend, habe Dich mal bei FB angeschrieben. Evtl. kann man ja mal Ideen austauschen.

**Comment by duffbeer2000** [comment]
@resper Wenn du mal Frage zum Container von buanet auf unRaid hast dann kannst dich bei mir melden. Habe das selbst auf unRaid in Betrieb ;)

**Comment by Apollon77** [comment]
Ok, I close here because feels solved ... If this is wrong please add comment with details and we can reopen
