### ISSUE TITLE
[bug]: multiple Events for single state Changes

### ISSUE THREAD

**Issue by Karkas66** [ioBroker/ioBroker.js-controller#2861]
### No existing issues.

- [X] There is no existing issue for my problem.

### Description

Seit dem Update auf 6.0.9 hab ich für jede auf State Änderung basierende Logzeile gleich diverse Einträge... Konnte zu dem Problem nichts finden. Sieht so aus:

![image](https://github.com/user-attachments/assets/e9b6acd4-fc35-4871-9d02-583e52937615)

### JS-controller version

6.0.9

### Node version

v18.20.4

**Comment by foxriver76** [comment]
First time this being reported please provide a valid example how you tested this and came to this conclusion. I cannot reproduce this at my installation.

**Comment by Karkas66** [comment]
Did a Node.js Update to v20.16.0 - Problem still remains.

I can not give you a guide on how to reproduce. As you can see in the screenshot there are several Adapters reporting the same thing over and over again in a short timeframe and with only ms between each Log line. But there are other adapters that do not log multiple times. I dont have a clue what is going on. Here is another screenshot showing normal behaviour of shelly and Tankerkonig instances. But Hue, zwave2 and Javascript do log multiple times:

![image](https://github.com/user-attachments/assets/6f7a6bc9-7c02-406c-997e-eed6319befb8)

**Comment by Karkas66** [comment]
Here are some log lines befor the update:

`2024-07-31 21:48:50.295 - info: javascript.0 (2266) script.js.Hausautomation.Buero-Licht: === Debug: Flur Motion Sensor aktualisierung: true
2024-07-31 21:50:18.821 - warn: zwave2.0 (2880) State value to set for "zwave2.0.Node_026.Basic.currentValue" has value "255" greater than max "99"
2024-07-31 21:50:19.524 - info: hue.0 (2399) Started scene: Scene Büro Nacht Licht
2024-07-31 21:51:53.811 - info: javascript.0 (2266) script.js.Alarm.Alarmanlage_Hauptfunktion: ==== DEBUG Haustür wurde geöffnet
2024-07-31 21:51:57.387 - info: javascript.0 (2266) script.js.Alarm.Alarmanlage_Hauptfunktion: ==== DEBUG Haustür wurde geschlossen
`

**Comment by foxriver76** [comment]
Better try to trace the problem down in the forum first. As it is the only report it is currently likely that it is not a general js-c problem and with these information alone it is hard to find anything reliable.

**Comment by Karkas66** [comment]
k, wil do

**Comment by foxriver76** [comment]
Were you able to find out what the problem was @Karkas66 or do you have a link to the forum post?
