### ISSUE TITLE
[enhancement]: Show system updates less often (unable to clear packageUpdate notification)

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.js-controller#2864]
### No existing issues.

- [X] There is no existing issue for my request.

### Description

At the moment, every `getRepository` or `upgradeOsPackages` host message leads to a new notification:

https://github.com/ioBroker/ioBroker.js-controller/blob/67b30398d81095c7f7038134676ca8c5b54c8b88/packages/controller/src/main.ts#L2190-L2194

https://github.com/ioBroker/ioBroker.js-controller/blob/67b30398d81095c7f7038134676ca8c5b54c8b88/packages/controller/src/main.ts#L2988-L2992

https://github.com/ioBroker/ioBroker.js-controller/blob/67b30398d81095c7f7038134676ca8c5b54c8b88/packages/controller/src/main.ts#L5724-L5732

So there's a new notification every day (if the repo has changed) - even if the notification has been confirmed already.

### Why?

I'm doing updates about once a week. So I cannot remove that notification for a few days. When using admin 7.0.23 it is not possible to remove those notifications:

![asd](https://github.com/user-attachments/assets/1ec6fea5-f794-4e2b-b259-b51e8a331806)

Looks like the notifications are cleared correctly (`system.host.iobroker.notifications.system` is `{}` afterwards) but a page reload re-generates the notification: `{"packageUpdates":{"count":1}}`

```
[3,70,"sendToHost",["system.host.iobroker","clearNotifications",{"category":"packageUpdates"}]]	1723533804.2533119
```

**Comment by klein0r** [comment]
Looks like the admin is running `sendToHost(... 'getRepository')` on each startup (when auto update is active):

https://github.com/ioBroker/ioBroker.admin/blob/17371fee520c498da86ce96bf95d9707243e1b70/packages/admin/src/main.ts#L1527-L1551

https://github.com/ioBroker/ioBroker.admin/blob/17371fee520c498da86ce96bf95d9707243e1b70/packages/admin/src/main.ts#L1620-L1622

**Comment by foxriver76** [comment]
We could persist the current updates in a state or object and if nothing changed, do not re-generate + always re-generate on controller restart? 

Or yes if written in state anyway we could use ts (if we only write when generating notification) to determine that last notification is (maybe) 7 days old or changed -> generate notification.

**Comment by klein0r** [comment]
> We could persist the current updates in a state or object and if nothing changed, do not re-generate + always re-generate on controller restart?

Sounds good, since that state already exists:

https://github.com/ioBroker/ioBroker.js-controller/blob/67b30398d81095c7f7038134676ca8c5b54c8b88/packages/controller/src/main.ts#L5732

**Comment by klein0r** [comment]
e.g.

```ts
/**
 * Check for updatable OS packages and register them as notification
 */
async function listUpdatableOsPackages(): Promise<void> {
    if (tools.isDocker()) {
        return;
    }

    const packManager = new PacketManager();
    await packManager.ready();

    const packages = await packManager.listUpgradeablePackages();
    const osPackageUpdatesId = `${hostObjectPrefix}.osPackageUpdates`;

    if (!packages.length) {
        await notificationHandler.clearNotifications('system', 'packageUpdates', `system.host.${hostname}`);
        await states!.setState(osPackageUpdatesId, { val: JSON.stringify([]), ack: true });
    } else {
        const osPackageUpdatesState = await states!.getState(osPackageUpdatesId);
        const packagesJson = JSON.stringify(packages);

        if (!osPackageUpdatesState || osPackageUpdatesState.val !== packagesJson) {
            await notificationHandler.addMessage('system', 'packageUpdates', packages.join('\n'), `system.host.${hostname}`);
            await states!.setState(osPackageUpdatesId, { val: packagesJson, ack: true });
        }
    }
}
```

**Comment by anton-hystrix** [comment]
Can we please also exclude system updates that were kept back? I'm annoyed to see the notification about debian version every time I open the page in browser. It also would be good if we could turn off these notifications completely. I update the server whenever I want to. Why do I need ioBroker to annoy me with this?

**Comment by foxriver76** [comment]
You can turn them off, simply use the notification manager adapter.

And yes we probably will do this in the next version but there is not backport planned as this needs to change from simply listing to simulating the run.

**Comment by mcm1957** [comment]
> Can we please also exclude system updates that were kept back? I'm annoyed to see the notification about debian version every time I open the page in browser. It also would be good if we could turn off these notifications completely. I update the server whenever I want to. Why do I need ioBroker to annoy me with this?

take a look at adapter iobroker.notification-manager

**Comment by anton-hystrix** [comment]
> take a look at adapter iobroker.notification-manager

I will, thanks. But anyway, it would be cool if "Aknowledge" button simply allowed to mark specific notification as read.

**Comment by foxriver76** [comment]
> > take a look at adapter iobroker.notification-manager
> 
> I will, thanks. But anyway, it would be cool if "Aknowledge" button simply allowed to mark specific notification as read.

That is what this issue is about, after PR is merged it will only be re-generated if new updates are available the user was not informed about eralier and likely this will relax the whole situation around people being annoyed on every admin reload by the notification + newest admin version should no longer auto open the notifications on reload if no warning is present.
