### ISSUE TITLE
[enhancement]: Explain difference of "noDiskSpace" and "diskSpaceIssues" notifications / improve name and description

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.js-controller#2866]
### No existing issues.

- [X] There is no existing issue for my request.

### Description

https://github.com/ioBroker/ioBroker.js-controller/blob/67b30398d81095c7f7038134676ca8c5b54c8b88/packages/controller/io-package.json#L715-L746

https://github.com/ioBroker/ioBroker.js-controller/blob/67b30398d81095c7f7038134676ca8c5b54c8b88/packages/controller/io-package.json#L822-L855

### Why?

The current descriptions are nearly identical and a bit confusing - e. g. when configuring the notification manager

**Comment by foxriver76** [comment]
One is parsed from the log by ENOSPC the other I think is generated actively if the User-defined threshold is exceeded, I will Check this and add it to the description when I am back from vacation
