### ISSUE TITLE
[1.5] iobroker stop is not working if it was started as systemd service

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#289]
According to Forum we have the topic that when started with "iobroker start" it can also stopped by "iobroker stop" command. But when started via "systemctl"/on boot then this is not working and you also need to use systemtl.

There should be at least a message

**Comment by Apollon77** [comment]
needs to be in 1.5 :-(

**Comment by Apollon77** [comment]
And also that PID files are stored in different locations?

**Comment by AlCalzone** [comment]
Might be too

**Comment by Apollon77** [comment]
@AlCalzone can we close this and refer to newest installer?

**Comment by AlCalzone** [comment]
I guess so. We can also solve this for old installations with the planned repair script based on the new installer.
