### ISSUE TITLE
[2.0.0] Compact Mode

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#290]
Compact Mode allows to run multiple Adapters in one nodejs process. This mainly saves memory

**Comment by AlCalzone** [comment]
How can I test/debug the problem?

**Comment by Apollon77** [comment]
Admin, Web and socketio Adapters on GitHub are changed to run as compact. So in theory: Use 1.6.0-dev latest and install these 3 from GitHub ...

**Comment by Apollon77** [comment]
More Details:

Activate in js-controller: 
edit iobroker.json => system.compact = true

The following Adapters are prepared for Compact mde as of 2019-01-04: Admin, Web, Socketio (GitHub versions)

**Comment by Apollon77** [comment]
Finding: It seems that the process name is set by the "last" of the adapters started in compact ... so this renames then js.controller to one of the other adapters  that run in compact mode :-)

**Comment by Apollon77** [comment]
Update: more adapters available:

![image 2019-01-04 18 14 27](https://user-images.githubusercontent.com/11976694/50701031-93847080-104c-11e9-86b3-de945a412918.jpg)

and sonos and simple-api

**Comment by Apollon77** [comment]
Also see: https://forum.iobroker.net/viewtopic.php?f=24&t=20387

**Comment by AlCalzone** [comment]
> 
> 
> Finding: It seems that the process name is set by the "last" of the adapters started in compact ... so this renames then js.controller to one of the other adapters that run in compact mode :-)

We should change that

**Comment by AlCalzone** [comment]
Also: All adapters running in compact mode claim they are using the full RAM of the process - even when that should just be assigned to JS-Controller.

**Comment by Apollon77** [comment]
Also noticed that ;-)

**Comment by angelnu** [comment]
Added support for the iobroker.chromecast adapter with version 2.0.1

**Comment by AlCalzone** [comment]
Tradfri @github/master has support aswell

**Comment by AlCalzone** [comment]
The upcoming version of the adapter creator too 😃

**Comment by Apollon77** [comment]
Further status of adapter compact mode adaption can be shown at https://docs.google.com/spreadsheets/d/1OaimQZV-CbMHYNfBWwICe6qXgGxq2Mr2ec-kNMsUyvg/edit?usp=sharing ... please also use this to coordinate. mark yourself an adapter as "Planned" when you plan to implement it there so that not two work on the same adapter
