### ISSUE TITLE
Check-Fehler nach Update script engine auf 4.0.6

### ISSUE THREAD

**Issue by fs-plugins** [ioBroker/ioBroker.js-controller#291]
bei Verwendung von getState(xy).val erhalte ich Check-Fehler wenn diese Variablen in Berechnung, Vergleich usw. verwendet werden

var test1 = getState('javascript.0.test.var1').val*60;

Fehler tritt nicht auf wenn
var test1 = parseInt(JSON.stringify(getState('javascript.0.test.var1').val))*60;

**Comment by Apollon77** [comment]
AlCalzone already created it in JavaScript adapter repository.

**Comment by Apollon77** [comment]
Thank you!! But I close it here a duplixate
