### ISSUE TITLE
[bug]: Changed message handling results in error iobroker-community-adapter/iobroker.samsung 

### ISSUE THREAD

**Issue by marian-t-web-de** [ioBroker/ioBroker.js-controller#2923]
### No existing issues.

- [X] There is no existing issue for my problem.

### Description

The analysis is already done in Issue [#202](https://github.com/iobroker-community-adapters/ioBroker.samsung/issues/202)  
It seems that between js-controller 5.0.19 and 6.0.9 changed message handling results in error in above adapter. 

Other changes in iobroker.samsung itself seems not to be a reason that this Adapter using API-Type SamsungHJ breaks the processing after succesfully hanshake, details see above Issue (and its predecessor [#201](https://github.com/iobroker-community-adapters/ioBroker.samsung/issues/201))

There are no resources in iobroker-community-adapters team to analyse errors deep in system so maybe somebody here can help to fix the error.

So far I can I'll help testing it.   

### Reproduction instruction

Start the  iobroker-community-adapter/iobroker.samsung v.0.6.0 using API-Type SamsungHJ and accordingly TV, see into ioB logs.
The processing ends by "Connection to TV initialised", the next message "Successfully connected to your Samsung HJ TV" is not listed any more.
This message and working API is given using iobroker.samsung adapter v.0.5.0 under js-controller 5.0.19. 
Under js-controller 6.0.9 is this adapter not working at all and adapter v.0.6.0 not connecting.

### JS-controller version

6.0.9

### Node version

18.19.0

**Comment by mcm1957** [comment]
And which changes telated to js-controller do you think break the adapter? And if any changes rellated to js-controller do you think are a BUG at hs-controlker?

**Comment by Apollon77** [comment]
There should be no changes in js-controller that are relevant here because all stuff I saw so far is Websocket or such? Or what exactly is the connection to the js-controller?

**Comment by marian-t-web-de** [comment]
I can only say that the above Adapter is after update of js-controller no more working. I don't have enough expierience to  say if this update  cause dependencies in other core modules as websocket as said above. As You can see in '#202' the bug seems to be somewhere in modules handling messages received via websocket and not in the adapter. So I think only one person which is familiar with js-controller, 
websocket and other 'core' modules is capable to solve this problem.

I hope'd to find him here, in js-controller vicinity.

If you know a better way to solve it, please tell me.

**Comment by mcm1957** [comment]
I still cannot see any problem with js-controller. Websocket data communication between Adapter an device is not handled by js-controller. 

Js-controller  6requires an up to date adapter-core so your several years old samsung-community Adapter release is no longer compatible with js-controller 6. This is no Bug but a documented breaking change. This must be fixed (and is fixed) with samsung 0.6.0 and will not require any changes to js-controller.

Yes it seems that the Support of your devicetype is brocken between  the old samsung-community code aka 0.5.0 an current code. But this is covered by issue at samsung Adapter and "only" needs to be investigated by some dev having time and internet to do so. 

It"s no core problem as far as I can see.

**Comment by marian-t-web-de** [comment]
We can discuss where the bug is or try to solve the problem. 
As one can see in '#202' the call after the hanshake is the same in Adapter in both versions: 5.0.0 and 6.0.0, but the answer/message  in the first will be accepted, in the second not. For the first, different is only js-controller. I don' t see what is in Adapter to do to get the answer via websocket accepted. Do You?

**Comment by marian-t-web-de** [comment]
Hello, You can close this issue, see [#202](https://github.com/iobroker-community-adapters/ioBroker.samsung/issues/202)
:-)
