### ISSUE TITLE
[1.5] Limit the memory size for systems with low RAM and force earlier GC

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.js-controller#293]
This can be done with the `--max-old-space-size=<size-in-mb>` of the `node` executable. By default, node expects to be able to use about 1.5 GB of RAM. As a result Raspberry Pi frequently crashes due to GC happening to late.

We need:
* Sane memory limits for memory-intensive processes (JS-Controller and JS-Adapter). ~300 MB should be okay
* Sane memory limits for simpler adapters. ~128 MB should be okay.
* A way to detect whether those restrictions should be applied (config flag?)
* Maybe a way to configure those limits
* A way to configure which adapters require the higher limit (in io-package.json maybe?)

**Comment by Apollon77** [comment]
And only set if System has less then 2gb ram?

**Comment by Apollon77** [comment]
My idea would be a seperate default for js-controller and for adapters and a setting in adapter io-package to set it adapter specific too.

**Comment by Apollon77** [comment]
And if this works I would include it in 1.5.x!!

**Comment by AlCalzone** [comment]
After upgrading node I'm not sure we still need this. Not having a limit allows single adapters to temporarily use more resources.
![prasentation1](https://user-images.githubusercontent.com/17641229/50686912-7f764a00-101f-11e9-83a8-4da22a4f5058.png)

**Comment by Apollon77** [comment]
it may still be an issue for node 6 users, but I would also feel ok with
- a troubleshooting article with details how to activate the limit (@Homoran is about to write one)
- instaler declines node <8.12

So we still have the option and know that we can use it if needed. Maybe we can postpone bigger changes then

**Comment by GermanBluefox** [comment]
Every instance support yet common.memoryLimitMB and this limit will be set.
The user can set this value actual only via the objects editor
I would cancel this feature or at least shift to 2.0

**Comment by Apollon77** [comment]
Yes I think in the meantime we can cancel it ... it appeared to be a memory leak in nodejs <8.12 ... is the common.memoryLimitMB on instance level documented?

**Comment by GermanBluefox** [comment]
> Yes I think in the meantime we can cancel it ... it appeared to be a memory leak in nodejs <8.12 ... is the common.memoryLimitMB on instance level documented?

@AlCalzone ?

**Comment by AlCalzone** [comment]
I didn't document anything. Where's the best place for that? SCHEMA.md?

**Comment by Apollon77** [comment]
I think so ... maybe https://github.com/ioBroker/ioBroker/blob/master/doc/SCHEMA.md#adapter or https://github.com/ioBroker/ioBroker/blob/master/doc/SCHEMA.md#instance !?

**Comment by GermanBluefox** [comment]
That was workaround. And admin2 had even that configurable, but it does not more actual any more.

And yes this should be right place for that: [https://github.com/ioBroker/ioBroker/blob/master/doc/SCHEMA.md#adapter](https://github.com/ioBroker/ioBroker/blob/master/doc/SCHEMA.md#adapter)

**Comment by Apollon77** [comment]
1.5.7 is released, so I close here
