### ISSUE TITLE
[bug]: Docker UI Upgrade 7.0.2 -> 7.0.3 fails

### ISSUE THREAD

**Issue by schnitzel14** [ioBroker/ioBroker.js-controller#2964]
### No existing issues.

- [X] There is no existing issue for my problem.

### Description

Running as docker container. When updating this error occurs:

`SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data`

![grafik](https://github.com/user-attachments/assets/4e4bd2ca-73a1-4903-a59c-e91cb811afdc)

### JS-controller version

7.0.2

### Node version

v20.18.0

**Comment by McR1983** [comment]
Bei mir das gleiche
Schönes Wochenende

**Comment by FlySmack** [comment]
Similar issue on my side since release of js-controller 7.0.3 Just the error message is slightly different:

Description

Running as docker container. When updating this error occurs:

SyntaxError: JSON Parse error: Unrecognized token '<'

Reproduction instruction

Happens during update of js-controller from 7.0.2 to 7.0.3

JS-controller version

7.0.2

Node version

v20.18.0

Docker image version:
docker (official image - v10.0.0)

**Comment by Apollon77** [comment]
Which Admin version is used? Current one?

**Comment by schnitzel14** [comment]
My installations was running Admin v7.4.1.
Now it's running the actual Admin v7.4.2 and the same error occurs.

**Comment by foxriver76** [comment]
And it is official Docker by @buanet?

**Comment by schnitzel14** [comment]
Yes, it‘s from buanet and up to date.

**Comment by foxriver76** [comment]
@buanet any chance you could validate if you find some time? Maybe we broke Docker when we fixed the linux permissions. I unfortunately have no test setup for Docker.

**Comment by FlySmack** [comment]
For me the issue still exists for the update to 7.0.4. But I understood, that the cause might be in the docker image?!

**Comment by Seven1969** [comment]
> For me the issue still exists for the update to 7.0.4. But I understood, that the cause might be in the docker image?! I just tried it with the latest docker image update (tag v10.0.0-build.20241205.234336) with the same result.

Can approve this, same here.

**Comment by foxriver76** [comment]
I guess `setuid` is not available or throws on Docker. But this should generate a message in the log…

**Comment by foxriver76** [comment]
Ah guess I see the problem now..

**Comment by foxriver76** [comment]
7.0.6 from which version

**Comment by foxriver76** [comment]
The admin error message brings nothing please show logfile instead

**Comment by schnitzel14** [comment]
Hey!

Ich habe versucht, unter Docker von 7.0.2 auf 7.0.6 zu aktualisieren.
Welches Log benötigst Du?

```
2024-12-10 18:30:05.519  - [34mdebug[39m: host.f452c579f2d3 Incoming Host message getLogs
2024-12-10 18:30:19.593  - [34mdebug[39m: host.f452c579f2d3 Incoming Host message readBaseSettings
2024-12-10 18:30:19.602  - [34mdebug[39m: host.f452c579f2d3 Incoming Host message upgradeController
2024-12-10 18:30:19.603  - [32minfo[39m: host.f452c579f2d3 Controller will upgrade itself to version 7.0.6
2024-12-10 18:30:37.029  - [32minfo[39m: host.f452c579f2d3 instance system.adapter.dwd.1 in version "2.8.5" started with pid 1451
2024-12-10 18:30:40.294  - [32minfo[39m: host.f452c579f2d3 instance system.adapter.dwd.1 having pid 1451 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
2024-12-10 18:30:46.018  - [32minfo[39m: host.f452c579f2d3 instance system.adapter.dwd.0 in version "2.8.5" started with pid 1466
2024-12-10 18:30:48.823  - [32minfo[39m: host.f452c579f2d3 instance system.adapter.dwd.0 having pid 1466 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
2024-12-10 18:31:12.490  - [34mdebug[39m: host.f452c579f2d3 Incoming Host message readBaseSettings
```

**Comment by foxriver76** [comment]
Ja das ist klar du kannst erst ab 7.0.5 wieder mit Docker ein UI Upgrade machen

**Comment by schnitzel14** [comment]
Wenn ich mich recht erinnere, habe ich 7.0.5 auch nicht installiert bekommen.
Aber das ist jetzt egal. Der ganze Container startet inzwischen nicht mehr. Mal sehen, wünsch das gefixt bekomme. :-/

**Comment by Seven1969** [comment]
> Ja das ist klar du kannst erst ab 7.0.5 wieder mit Docker ein UI Upgrade machen

Und wie komme ich auf 7.0.5

**Comment by foxriver76** [comment]
Geh einfach auf 7.0.6 über den alten weg?

**Comment by Seven1969** [comment]
> Geh einfach auf 7.0.6 über den alten weg?

Bisher habe ich ausschließlich über den Admin das  Update gemacht, wie geht der "alte" Weg? Wenn es einen Link zu einer Beschreibung gibt, reicht der denke ich aus....

**Comment by Seven1969** [comment]
> > Geh einfach auf 7.0.6 über den alten weg?
> 
> Bisher habe ich ausschließlich über den Admin das Update gemacht, wie geht der "alte" Weg? Wenn es einen Link zu einer Beschreibung gibt, reicht der denke ich aus....

Habs gefunden https://docs.buanet.de/iobroker-docker-image/docs/#updates-upgrades

**Comment by huemmip** [comment]
Guten Morgen, ich habe das selbe Problem beim Update von JS-Controller 7.0.3 auf 7.0.6
Hat jemand schon neue Erkenntnisse für eine Lösung?

**Comment by mcm1957** [comment]
ja
https://github.com/ioBroker/ioBroker.js-controller/issues/2964#issuecomment-2541244402

**Comment by huemmip** [comment]
Danke schön hat jetzt geklappt 👍
