### ISSUE TITLE
[bug]: Docker js-contoller update from 7.0.2 to 7.0.x fails - SyntaxError: JSON Parse error: Unrecognized token '<'

### ISSUE THREAD

**Issue by FlySmack** [ioBroker/ioBroker.js-controller#2988]
### No existing issues.

- [X] There is no existing issue for my problem.

### Description

Running as docker container. When updating js-controller this error occurs:
`SyntaxError: JSON Parse error: Unrecognized token '<'`
Happens since 7.0.3 (7.0.2 is the actual installed version)
<img width="1212" alt="Screenshot 2024-12-09 at 06 56 05" src="https://github.com/user-attachments/assets/98166fbd-eaab-4bd5-8016-33e3795c77ca">

### JS-controller version

7.0.2

### Node version

v20.18.1

**Comment by mcm1957** [comment]
Siehe ev. https://github.com/ioBroker/ioBroker.js-controller/issues/2964

**Comment by FlySmack** [comment]
The manual procedure was working. Thanks a lot.

**Comment by TheMoonlightkid** [comment]
Hi,
ich habe es bei mir wie folgt lösen können (ioBroker läuft bei mir im Docker auf einer Synology DS):

Zuerst ins Dockervezeichnis, bei mir
`/volume1/docker/iobroker_data/ `
Dann die JSON-Dateien prüfen, ob fehlerhaft
```
jq empty package.json
jq empty package-lock.json
```

ioBroke stoppen und als Benutzer iobroker anmelden, das Update starten,
```
su - iobroker
npm install iobroker.js-controller@7.0.6 --production
```
IoBroker neu starten. Das war es bei mir und es läuft :)

**Comment by ScumbagSteve** [comment]
Same issue here, but the steps above fixed it.
Thanks @TheMoonlightkid
