### ISSUE TITLE
[bug]: Dateien können nicht gelöscht werden

### ISSUE THREAD

**Issue by Bernd9000** [ioBroker/ioBroker.js-controller#2992]
### No existing issues.

- [X] There is no existing issue for my problem.

### Description

IOB ist hier unter Windows 11 installiert.
Beim Versuch mit dem Dateimanager aus vis oder vis-2 irgendeine Datei zu löschen kommt es beim js-controller zum Fehler.
Im Editor erscheint die Fehlermeldung `Socket Error : Error: websocket error`

Auffällig für mich sind folgende Zeilen:
`'cfg.f.vis-2.0$%$main/im/Kalender.png/*'`
`ENOTDIR: not a directory, scandir  'C:\Software\ioBroker\iobroker-data\files\vis-2.0\main\im\Kalender.png'`

Wird hier eine Datei mit einem Ordner verwechselt ?
Die Datei existiert wirklich und ich kann Sie auch manuell löschen.
Eventuell sind nur Windows Installationen betroffen.
Im Dateimanager der Admin Oberfläche klappt es mit dem löschen, dort kommt kein Fehler

IOB Log:

`<html><body>

host.Server(SmartHome) | 2024-12-24 02:09:19.718 | error | instance system.adapter.web.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | --
host.Server(SmartHome) | 2024-12-24 02:09:19.718 | error | Caught by controller[0]: }
host.Server(SmartHome) | 2024-12-24 02:09:19.718 | error | Caught by controller[0]:   }
host.Server(SmartHome) | 2024-12-24 02:09:19.718 | error | Caught by controller[0]:     ]
host.Server(SmartHome) | 2024-12-24 02:09:19.718 | error | Caught by controller[0]:       '250'
host.Server(SmartHome) | 2024-12-24 02:09:19.718 | error | Caught by controller[0]:       'COUNT',
host.Server(SmartHome) | 2024-12-24 02:09:19.718 | error | Caught by controller[0]:       'cfg.f.vis-2.0$%$main/im/Kalender.png/*',
host.Server(SmartHome) | 2024-12-24 02:09:19.718 | error | Caught by controller[0]:       'MATCH',
host.Server(SmartHome) | 2024-12-24 02:09:19.718 | error | Caught by controller[0]:       '0',
host.Server(SmartHome) | 2024-12-24 02:09:19.718 | error | Caught by controller[0]:     args: [
host.Server(SmartHome) | 2024-12-24 02:09:19.718 | error | Caught by controller[0]:     name: 'scan',
host.Server(SmartHome) | 2024-12-24 02:09:19.717 | error | Caught by controller[0]:   command: {
host.Server(SmartHome) | 2024-12-24 02:09:19.717 | error | Caught by controller[0]:     at parseType (C:\Software\ioBroker\node_modules\redis-parser\lib\parser.js:302:14) {
host.Server(SmartHome) | 2024-12-24 02:09:19.717 | error | Caught by controller[0]:     at parseError (C:\Software\ioBroker\node_modules\redis-parser\lib\parser.js:179:12)
host.Server(SmartHome) | 2024-12-24 02:09:19.717 | error | Caught  by controller[0]: ReplyError: Error ERROR readDir id=vis-2.0: ENOTDIR:  not a directory, scandir  'C:\Software\ioBroker\iobroker-data\files\vis-2.0\main\im\Kalender.png'
web.0 | 2024-12-24 02:09:19.366 | warn | setTimeout called, but adapter is shutting down
web.0 | 2024-12-24 02:09:19.353 | error | Error  ERROR readDir id=vis-2.0: ENOTDIR: not a directory, scandir  'C:\Software\ioBroker\iobroker-data\files\vis-2.0\main\im\Kalender.png'
web.0 | 2024-12-24 02:09:19.353 | error | ReplyError:  Error ERROR readDir id=vis-2.0: ENOTDIR: not a directory, scandir  'C:\Software\ioBroker\iobroker-data\files\vis-2.0\main\im\Kalender.png'     at parseError  (C:\Software\ioBroker\node_modules\redis-parser\lib\parser.js:179:12)     at parseType  (C:\Software\ioBroker\node_modules\redis-parser\lib\parser.js:302:14)
web.0 | 2024-12-24 02:09:19.353 | error | uncaught  exception: Error ERROR readDir id=vis-2.0: ENOTDIR: not a directory,  scandir  'C:\Software\ioBroker\iobroker-data\files\vis-2.0\main\im\Kalender.png'
host.Server(SmartHome) | 2024-12-24 02:09:19.341 | warn | host.Server(SmartHome)-Server  Objects 127.0.0.1:57100 Error from InMemDB: Error: ERROR readDir  id=vis-2.0: ENOTDIR: not a directory, scandir  'C:\Software\ioBroker\iobroker-data\files\vis-2.0\main\im\Kalender.png'     at ObjectsInMemoryServer._handleScanOrKeys  (file:///C:/Software/ioBroker/node_modules/@iobroker/db-objects-jsonl/src/lib/objects/objectsInMemServerRedis.js:930:67)     at RedisHandler.<anonymous>  (file:///C:/Software/ioBroker/node_modules/@iobroker/db-objects-jsonl/src/lib/objects/objectsInMemServerRedis.js:728:25)     at RedisHandler.emit (node:events:518:28)     at RedisHandler.emit (node:domain:489:12)     at Immediate._onImmediate  (file:///C:/Software/ioBroker/node_modules/@iobroker/db-base/src/lib/redisHandler.ts:210:37)     at processImmediate (node:internal/timers:483:21)

</body>
</html>`

### Reproduction instruction

1.) Irgendeine Datei mit dem Dateimanager in vis oder vis-2 hochladen
2.) Die Datei wieder löschen

### JS-controller version

7.0.6

### Node version

v20.18.1

**Comment by foxriver76** [comment]
Ich denke das ist ein Vis issue kein Controller issue

**Comment by Bernd9000** [comment]
Nachtag:
Funktioniert wieder mit Vorschlag aus [#2993](https://github.com/ioBroker/ioBroker.js-controller/pull/2993)

**Comment by foxriver76** [comment]
Sollte aber im Kern trotzdem im Adapter gefixt werden. Vis scheint da `adapter.readDir` auf einem einzelnen File aufzurufen.
