### ISSUE TITLE
[2.0.0] Restarting or Stopping adapters does not seem to work 

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.js-controller#300]
I've added experimental support for compact mode into tradfri. It doesn't seem to be possible to restart stop the adapter now. This happens in the log
![unbenannt](https://user-images.githubusercontent.com/17641229/50708613-3812ac80-1065-11e9-90f5-ef2bf881edaf.PNG)
and when I push my remote, the objects in ioBroker are still updated, even if the instance is disabled.

**Comment by Apollon77** [comment]
relates #290

**Comment by GermanBluefox** [comment]
Should be fixed by https://github.com/ioBroker/ioBroker.js-controller/commit/c5910e438b80dd7361cc200790b8d5507320aa02

**Comment by foxriver76** [comment]
Verified :+1:
