### ISSUE TITLE
[2.0.0] The RAM usage of the "compact" process is shown for every adapter, which is running inside it

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.js-controller#301]
I think they should not have their own RAM statistics

**Comment by Apollon77** [comment]
relates #290

**Comment by Apollon77** [comment]
question is: What we should write there? just a 0? or null?

**Comment by AlCalzone** [comment]
Empty probably, at least in the instances tab
As for the states, maybe 0

**Comment by Apollon77** [comment]
-1 to "show" an invalid value?

**Comment by AlCalzone** [comment]
I'm still for empty (or `null` if that's the way to not show a value for the state). -1 has a less clear meaning than just nothing.

**Comment by Apollon77** [comment]
It think null will be shown in admin as null.  Will check it
