### ISSUE TITLE
Start compact mode adapters in separate processes from js-controller and allow grouping

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#303]
Compact mode adapters are currently started in js.controller and so share ressources of the single thread also with the state/object DB and such.

It would maybe be better to start the compact mode adapters in an extra process and have the connect to js.controller. Yes footprint is then 30-50MB higher but maybe still a good idea.

To enhance the idea it could be possible to allow "compact groups" where the idea is that you can group several adapters in single compact proceses. You cnfigure in Admin a number and all adapters with the same numbers are started in the same compact-process. So you could optimize the workload and split if needed (e,g. because 100% CPU is reached.

**Comment by Apollon77** [comment]
Ok, I made some thoughts and it is not that problematic. Here a short idea/concept:
* Each Instance gets an optional "compactmode-Group", undefined eaquals 0
* "Group 0" means that the instance will run in the js.controller main process as it is now
* main.js gets a commandline parameter "--compact-group <number>" to start a new controller process for a special compact mode group. When set it only starts adapter processes that are compact and have the correct group (alternatively own compact.js file and move some functions and logic in own file to include ... we can see)
  * On some places we need to prevent some things to happen for these processes (e.g. failing back to start DBs or such) But these should not too many
  * Add a logic to kill himself as an adapter process on request
  * The "start adapter" logic is enhanced to start a new main.js with the compact-group parameter for the first instance on this host with a certain compact-group and remember this to monitor and restart the process as for ther adapters too
  * This special process uses "<hostname>-compactgroup.0" or such as hostname and stores his stats there

**Comment by AlCalzone** [comment]
Some thoughts:
- I don't like having multiple host names for a single host
- do we need the full main.js in each process or could it be a minimal compact.js that only starts, stops and monitors the adapters?
- what do you mean with the self kill logic? Shut down if all adapters are stopped?

**Comment by Apollon77** [comment]
> I don't like having multiple host names for a single host

I only saw that neded for the statistics (mem usage and such), but could also create systemhost.name.compact-0.xxx then it is "in the structure" ?!

 > do we need the full main.js in each process or could it be a minimal compact.js that only starts, stops and monitors the adapters?

As written this is one idea, but needs restructuring of code or else have much duplicated code, but maybe a good way to get that restructuring happening :-)

> what do you mean with the self kill logic? Shut down if all adapters are stopped?
In my idea these sub-processes for compact are handled by the main cvontroller like an adapter process and adapters support a "self killing" feature if jscontroller detected a second process running for the same ... but this is easy to implement (+ one state that we need, but easy)
