### ISSUE TITLE
New user added to admin group cannot be used (no permission)

### ISSUE THREAD

**Issue by LymanZerga** [ioBroker/ioBroker.js-controller#306]
When adding a new user and add them to the admin group, the user cannot be used. When enabling authentication and using the previously created user i always get permission restrictions like.

`admin.0	2019-01-04 17:29:24.521	warn	No permission for "system.user.mynewuser" to call getObjects. Need "object"."list"`

When creating a completely new group having the same access writes as the admin group and putting the new user into that group, everthing works as expected.

**Comment by Apollon77** [comment]
duplicate closed: https://github.com/ioBroker/ioBroker.admin/issues/352

Current workaround is to create a new group with the same rights as displayed for Administratir group and then it works

**Comment by foxriver76** [comment]
Is this still an issue @Apollon77? I can't reproduce this:

created new user via `iob user add tom --ingroup administrator --password tom` and was able to log in to admin, see objects and able to change them. Restart of controller or admin was also not necessary. User has been created and added to admin group via
`iob user add tom --ingroup administrator --password tom`

**Comment by Apollon77** [comment]
Good question ... in 2.2. we did one "if admin group then ... "chnage in the code, so this might have fixed this as well ... if it woprks now as described above I would also consider it as fixed

**Comment by foxriver76** [comment]
Also tried the procedure via admin instead of cli and worked flawlessly too

**Comment by funky4t** [comment]
Hi guys,
I tried to create a new user and add him to admin group. Unfortunately that user had NO permissions after login. Then I tried the workaround with a "admin2" group giving it all rights the original admingroup has and adding the new user into that group. Still no change, user had no permission to change anything.

Okay I deleted the new user and the new admin2 group and created the same user and same password again via the `iob user add tom --ingroup administrator --password tom` command over terminal. Unfortunately again no change, no permission again.

Then I tried to use the terminal command to create a completely new user and used the old password of the user before. And here we go, that worked perfectly!

So I guess the user created in Iobroker via the user menu seems to stay "consistent" somewhere although already deleted and then newly generated via terminal. Especially some new iobroker users might be confused that adding a user should be done by terminal and not the user menu inside iobroker. The setup I was working on was a nearly fresh setup with all updates (stable) on a Raspberry Pi 3.

Just wanted to leave an update and some information about what happened on my system and how I solved it.
Sunny greetings
Sven

**Comment by Apollon77** [comment]
@funky4t WHich js.controller you used? The new 3.3.12? If not can you try please with this again

**Comment by funky4t** [comment]
Hi @Apollon77,
ich erlaub mir mal das Ganze in Deutsch zusammen zu fassen, damit weniger "Missverständnisse" entstehen, zumal ich mich eher als Anwender verstehe und mir die Details zum Wissen "unter der Haube" fehlen:

1. Ich war auf 3.2.16 aus dem Stable repository.
2. Ich hab auf 3.3.12 upgedatet und neu gestartet
3. Ich hab den "alten" und vorab wieder gelöschten User mit dem gleichen PW aus der User Verwaltung angelegt und in die Systemgruppe Administrators gepackt.
4. Ausgeloggt, mit User eingelogt, versucht einen DP zu ändern, "Zugriffsverweigerung"
5. User in selbst erstellte Gruppe "Admin" (gleiche Rechte wie Systemgruppe "Administratoren") gepackt, Log Out, Log In, DP ändern: "Zugriffsverweigerung"
6. Völlig neuen "User2" per Webinterface USER angelegt, in Administratoren gepackt, Log OUT, Log IN, DP ändern: "Zugriffsverweigerung"
7. Mit Verschiebung in Gruppe "Admin" versucht: "Zugriffsverweigerung"
8. Zwischendurch mal nen Reboot des Raspberry, keine Veränderung!
9. Neuen "User3" per SSH erstellt, dann im USER Bereich in Administratorengruppe verschoben: Zugriff auf DP möglich!

Da hat sich bei mir also nix hinsichtlich der Anlage von neuen Admins verändert, leider.

Dummerweise hab ich seit dem Update auf 3.3.12 nun aber das gesamte Log File voll mit Fehlermeldungen meiner Adapter wie diesem hier. Da kommen richtig Meldungen zusammen. Generell scheint das System zu laufen, aber allein die Erstellung der tausenden von Log einträgen kann der Performance ja nicht förderlich sein, oder?

![grafik](https://user-images.githubusercontent.com/57875762/122019818-79761d00-cdc4-11eb-9288-24a34473751e.png)

![grafik](https://user-images.githubusercontent.com/57875762/122020720-50a25780-cdc5-11eb-9893-cce106538226.png)

Ich bin was da "unter der Haube passiert" eher wenig versiert, deswegen auch Stable repository ;) Hast du einen Tip, ob es was bringt, wieder auf die 3.2.16 zu gehen und wie ich als 90% Anwender wieder zurück dahin komme? Ein spezielle Version installieren kenne ich bei den Adaptern, aber beim Controller finde ich die Option nicht. Gibt es einen Weg über SSH die Stable wieder rein zu bekommen?

Backitup von heute Nacht hätte ich notfalls auch noch, wird die Controller Version damit auch zurück gesetzt? Der Pi steht leider 400km entfernt... :( 
Danke für deien Hilfe und VG aus Oberfranken

funky4t

**Comment by funky4t** [comment]
Okay Googlen kann ich :)

`iobroker stop`
`npm i iobroker.js-controller@3.2.16 --production`
`iobroker start`

Das hat bei mir geklappt, Controller ist zurück auf 3.2.16 und das Logfile hat wieder "überschaubare" und "übliche" Einträge.

**Comment by foxriver76** [comment]
> 9\. Neuen "User3" per SSH erstellt, dann im USER Bereich in Administratorengruppe verschoben: Zugriff auf DP möglich!

Heißt per cli `ìob user add User3` und dann per Admin den user in die Gruppe geschoben oder auch per cli?

Evtl. macht controller da was sauberer als der Admin Adapter.

**Comment by funky4t** [comment]
`iob user add User3 --ingroup administrator --password User3` also direkt per terminal den User erstellt und als Admin definiert, also ohne dann nochmal über das Webinterface zu verschieben.
Das ist der einzige Weg, wie ich einen neuen Admin erstellen kann.

Hatte gestern erst einen über Webinterface angelegt, der leider keien Zugriff hatte, den hab ich dann per Webinterface wieder gelöscht und selbst als ich den dann nochmal per `iob user add tom --ingroup administrator --password tom` neu angelegt habe, kein Zugriff auf Datenpunkte. Erst ein völlig neuer Admin per terminal funktioniert!

Scheint als würde es Probleme mit der Useranlage im Webinterface geben und User die dort angelegt wurden, werden scheinbar auch nicht sauber gelöscht. Aber das ist nur mein Gefühl aufgrund der gestern und heute gemachten Erfahrungen...bin halt "nur" Anwender.
