### ISSUE TITLE
Removing an Object does not remove the linkage to an enum

### ISSUE THREAD

**Issue by foxriver76** [ioBroker/ioBroker.js-controller#313]
Issue came up in https://github.com/ioBroker/ioBroker.hm-rega/issues/34

Tested by deleting an object via admin

**Comment by foxriver76** [comment]
It’s because https://github.com/ioBroker/ioBroker.js-controller/blob/2e3ea9dece6d8a77fff6e965b5620958b007fe8b/lib/adapter.js#L3440 and similar methods are only called on special functions like `deleteChannel` or `deleteState` I would implement the logic directly in `delObject`. Also the existing methods only seem to work with correct device, channel, obj structure. If we implement it in `delObject` We could probably get rid of the other methods if they are not used. What’s your opinion? @Apollon77 @GermanBluefox (maybe there are historical reasons for the current logic?)

**Comment by Apollon77** [comment]
if the result in the end the same I would like the refactor idea

**Comment by foxriver76** [comment]
The result will be the same + this issue will be fixed. Currently the behavior is.

1. Object `0_userdata.0.test` gets added to an enum, lets say `enum.rooms.livingRoom`
2. the Object `enum.rooms.livingRoom` get a new entry in the `common.members` array
3. user deletes the `0_userdata.0.test` via admin, cli or whatever
4. the entry of `common.members` wont be deleted because its not deleted via `delteState/Channel` instead it will be deleted by `delForeignObject` https://github.com/ioBroker/ioBroker.js-controller/blob/2e3ea9dece6d8a77fff6e965b5620958b007fe8b/lib/adapter.js#L2624
5. user creates a new object with the same name as the deleted one `0_userdata.0.test`
6. the new object is still a member of the `enum.rooms.livingRoom`, which should not be the case IMHO and also see pot issues like https://github.com/ioBroker/ioBroker.hm-rega/issues/34

**Comment by Apollon77** [comment]
Understood it exactly that way, so completely fine with me!!
