### ISSUE TITLE
state set console command does not accept blanks within a string, instead it is treated as a second value (ack flag)

### ISSUE THREAD

**Issue by Pony5dotzero** [ioBroker/ioBroker.js-controller#319]
Example:
pi@ioBroker-RasPi:/opt/iobroker $ iobroker state set lgtv.0.popup "Hallo"
Set "lgtv.0.popup" with value: Hallo

pi@ioBroker-RasPi:/opt/iobroker $ iobroker state set lgtv.0.popup "Hallo Welt"
Set "lgtv.0.popup" with value: Hallo and ack flag Welt

Even if send with double apostrophe like iobroker state set ""Hallo Welt"" it shows:
Set "lgtv.0.popup" with value: Hallo and ack flag Welt

**Comment by Apollon77** [comment]
It seems that yargs is not parsing Strings correctly, there are several issues fixed and some still open :-( Maybe we can workaround somehow or need to "minimize" the problem to send in a bug report with them

**Comment by Apollon77** [comment]
For now I would expect it to work when no spaces are in the parameter. @Pony5dotzero could you please verify this?

**Comment by Pony5dotzero** [comment]
Yes, if you use a dot instead of a blank it works as expected. e.g. "Hallo.Welt"

**Comment by AlCalzone** [comment]
@Apollon77 it would be good to know which os the users have.

**Comment by Apollon77** [comment]
relatesd to https://github.com/yargs/yargs-parser/issues/180

**Comment by volkerverkamp** [comment]
I am suffering from this issue as well - any new status on this?

**Comment by foxriver76** [comment]
I've pushed a fix to the installer and fixer, will most likely be in the next fixer version

**Comment by foxriver76** [comment]
I guess OS is linux where the problem occurs? For @AlCalzone it worked on Windows

**Comment by AlCalzone** [comment]
> I guess OS is linux where the problem occurs? For @AlCalzone it worked on Windows

I think so, yes
