### ISSUE TITLE
Bash Script message

### ISSUE THREAD

**Issue by Obsthaendler** [ioBroker/ioBroker.js-controller#323]
Beim Senden an einen Adapter (z.B. Pushover) via Bash Script wird die Nachricht nach dem ersten Leerzeichen abgeschnitten. Versucht wurden unterschiedliche " ' Kombinationen

Befehl:
`iobroker message <adapter>[.instanceid] <command> [<message>]`

Test: 
`iobroker message pushover.0 send '{"message": "Hallo wie gehts" }'`

Ergebnis: {"message":

**Comment by Apollon77** [comment]
Duplicate to #319 ... please provide Infos on your is and used shell there please
