### ISSUE TITLE
Idea: Add editor for system config

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.js-controller#331]
The system config (iobroker.json) can currently only be edited by hand. It would be nice if we could do that with some kind of editor. Maybe in the hosts tab in admin?

**Comment by Apollon77** [comment]
But then add this to Admin repo? :-)

**Comment by AlCalzone** [comment]
Yeah probably. The question is if we need to add something to js-controller for this, too?

**Comment by GermanBluefox** [comment]
> Yeah probably. The question is if we need to add something to js-controller for this, too?

in iobroker.json are all settings, that cannot be used dynamically and for that the restart of js-controller (and all adapters) is required. As far I know we do not need anything in js-controller except working restart. I am still not sure if it works. Especially with systemd

**Comment by AlCalzone** [comment]
>  [GermanBluefox](/GermanBluefox) added the [fixed](/ioBroker/ioBroker.js-controller/labels/fixed) label [10 minutes ago](#event-2142612837)

Fixed? How?

The systemd restart should be working if we just execute `iobroker restart`. But I would be fine with asking the user to exec `iobroker restart` on the console.
