### ISSUE TITLE
Idea: add command `iobroker debug <adaptername>`

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.js-controller#334]
With the new installation routine, it has become hard to execute an adapter as the `iobroker` for debugging purposes. We used to be able to just disable the adapter and then run it using `node path/to/main.js --force`.

Now we need to do `sudo -u iobroker node path/to/main.js --force` and even that can be forbidden because running commands as iobroker is currently limited to the main entry point `iobroker.js`.

Thus I propose a new command `iobroker debug <adaptername>`, which basically just executes `node path/to/adapter/main.js --force` and passes along all other arguments like `--console` and so on.

**Comment by AlCalzone** [comment]
Optionally, we could add some easy-to remember options for `--inspekt-brk` and `--inspect=0.0.0.0:9229` for remote debugging.

**Comment by GermanBluefox** [comment]
There is a `--debug` flag now (combination of `--logs --force`), but yes, it could be interesting.

**Comment by Apollon77** [comment]
I also like the idea

**Comment by Apollon77** [comment]
I solve this here, If someone sees it not solved please comment and reopen

**Comment by AlCalzone** [comment]
Only thing missing is my previous comment:

> Optionally, we could add some easy-to remember options for `--inspekt-brk` and `--inspect=0.0.0.0:9229` for remote debugging.
