### ISSUE TITLE
No "killall.sh" script found

### ISSUE THREAD

**Issue by Mr-REM-Esq** [ioBroker/ioBroker.js-controller#337]
root@iobroker:/home/roman# iobroker stop

Stopping iobroker controller daemon...
iobroker controller daemon stopped.
No "killall.sh" script found. Just stop.

Why the script is not found?

**Comment by Mr-REM-Esq** [comment]
Oh, sorry. I understood my mistake.

**Comment by Mr-REM-Esq** [comment]
I tried to run ioBroker in different ways, but the script was not found when I stopped it.

**Comment by AlCalzone** [comment]
Is there any actual problem besides the message? AFAIK it is OK if that message appears.

**Comment by Mr-REM-Esq** [comment]
I don't observe problems. But it is somehow strange that the script, which should unload all processes, doesn't run.

**Comment by Apollon77** [comment]
Is this still a problem with js controller 1.5.7 in  latest?

**Comment by Mr-REM-Esq** [comment]
There is no problem. Thank you.

**Comment by stmiko** [comment]
Hallo, habe das problem mit der version 1.5.11 immer noch. Das script wird nicht gefunden, obwohl es vorhanden ist.

**Comment by stmiko** [comment]
Noch ein Hinweis: Ich betreibe iobroker in einem Docker-Container, vlt. hat das damit was zu tun?
