### ISSUE TITLE
nach update auf 1.5.7 keine ioT geräte mehr hinzuzufügen und im log fehler: Terminated: warn 11

### ISSUE THREAD

**Issue by ltsalvatore** [ioBroker/ioBroker.js-controller#338]
so, ich bin jetzt auch hingegangen und habe den js-controller auf meine produktiven und test maschine auf 1.5.7 aktualisiert und den iobroker sicherheitshalber neugestartet. 

im ioT adapter habe ich nun das problem, dass ich keine neuen geräte mehr hinzufügen kann. 
ich kann auf gerät hinzufügen klicken, das entsprechende objekt selektieren, das anschließende fenster zum benennen des geräts erscheint leider nicht. 
stattdessen bekomme ich folgende fehlermeldung im log angezeigt.

```
Terminated:	2019-02-17 18:26:06.156	warn	11
```

**Comment by Apollon77** [comment]
hast Du bitte die Logzeile komplett bzw mehr drum herum? An sich sollte js.controller mit iot Adapter keine Probleme verursachen

**Comment by AlCalzone** [comment]
Code 11 ist "desired termination", und tritt z.B. als Neustart bei Speicherung der Optionen auf.
