### ISSUE TITLE
[bug] FORBIDDEN_CHARS without whitespaces

### ISSUE THREAD

**Issue by Steiger04** [ioBroker/ioBroker.js-controller#341]
@GermanBluefox https://github.com/ioBroker/ioBroker.js-controller/commit/2e5ab00e4cc00a242dabc2bf17962e9560ef0c64

**Comment by Apollon77** [comment]
Yes, the plan was to also disallow spaces ... but finally we decided against it because too many adapters would have problems else ... Thats way it was removed again.

**Comment by Steiger04** [comment]
@Apollon77 Please take a look again.

https://github.com/ioBroker/ioBroker.js-controller/commit/2e5ab00e4cc00a242dabc2bf17962e9560ef0c64

**Comment by Apollon77** [comment]
Commented. Short: sure that it was 1.4.2? And not an early 1.5.x?

**Comment by Apollon77** [comment]
Ok, I will close this. spaces are allowed. If we have adapters that also forbid spaces they stay with their code :-(
