### ISSUE TITLE
[Tracking] js-controller 1.5.x for stable

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#346]
Finalize and bring js-controller 1.5 to stable
(Changelog till 1.5.7 see https://github.com/ioBroker/ioBroker.js-controller/issues/288)
(Changelog incl. 1.5.8 see https://forum.iobroker.net/topic/20316/js-controller-1-5-7-im-latest-repository-verf%C3%BCgbar/2 )

[x] Publish javascript 3.6.5 to stable
[x] Publish upnp 1.0.0 to stable
[x] Publish dasWetter 2.7.1 to stable
[x] Decide on backports for #357

**Comment by GermanBluefox** [comment]
Done

**Comment by Apollon77** [comment]
Do we want to backport  the "other adapters are deleted to when name starts the same" issue to 1.5.x befrore releasing it?

**Comment by foxriver76** [comment]
Can be closed IMHO

**Comment by Apollon77** [comment]
I will as soon 1.5.13 is out in stable too :-)

**Comment by Stabilostick** [comment]
Perhaps add PR #410 to 1.5.13/14 before stable? ;-)

**Comment by Apollon77** [comment]
1.5.13 is out so we would need a 1.5.14 only for that .... what exactly is the problem with the old version?

**Comment by Stabilostick** [comment]
Answered in #410. 1.5.14 is released to latest repository including #410.
