### ISSUE TITLE
setState expire does not reset state to NULL in case no unit is present

### ISSUE THREAD

**Issue by DutchmanNL** [ioBroker/ioBroker.js-controller#349]
js-controller : 1.5.7
code : `					this.setState(stateCreateName, { val: 20 ,ack: true, expire: (received_data.c["Interval"].v *3) + 2 });
`

current situation :
When state has a unit defined, after expire value = NULL
When state has not a unit defined, after expire value = ""

wanted situation :
always reset state value to NULL to clearly understand state is expired in all scenarios (with or without unit defined

**Comment by foxriver76** [comment]
How is this tested? Before diving deeper into the problem, my assumption is, that it’s just a front end bug in admin.

**Comment by foxriver76** [comment]
When I set a states value to null, in admin it shows an empty field w/o unit and null °C when setting °C as unit. But when getting the state, both are correctly null.

**Comment by Apollon77** [comment]
Then it is just the way ow Admin  displays a "null" value. So is it then really an issue?

**Comment by foxriver76** [comment]
Could be an issue for admin. It‘s a little bit inconsistent to sometimes tell the user it’s null and to sometimes show nothing, which could be an empty string as well.

**Comment by DutchmanNL** [comment]
for logic (scripting etc) its fine, but not showing the proper "NULL" value in admin can be confusing

**Comment by Apollon77** [comment]
Dann wäre es ein Admin ticket

**Comment by DutchmanNL** [comment]
https://github.com/ioBroker/ioBroker.admin/issues/391
