### ISSUE TITLE
[Multihost] Verify when upgrading JS-controller on master that slave has the newest version

### ISSUE THREAD

**Issue by DutchmanNL** [ioBroker/ioBroker.js-controller#350]
JS-Controller : 1.5.7

current situation :
controller can be upgraded on Master AND slaves without verification which versions runs on master

wanted situation :
When executing iObroker upgrade self on master :
a) verify if installation is a multicast setup
b) check JS-controller versions on slave
c) if JS-Controller on slave < JS-Controller on master after upgrade ==> deny upgrade of master

reason : in multihost setup the slave should be updated first always before the master will be upgraded to prevent issue in communication

**Comment by Apollon77** [comment]
So idea would be:
In Upgrade Self Checks the role of current host.
If Slave: execute upgrade
If master: check versions of all Slave Hosts )active ones?) and if they are lower then new version decline the upgrade
A force parameter may be added to upgrade also with this version conflict.

**Comment by DutchmanNL** [comment]
sounds like a plan

**Comment by Apollon77** [comment]
It did not made it into 1.5.8 ...

**Comment by foxriver76** [comment]
Does it make sense in all cases, this time (3.2) the upgrade logic is vice versa isn't it @Apollon77?

**Comment by Apollon77** [comment]
In 3.2 the maste rneeds to be updated first ... need to see how we handle in . In fact we should have planned more

**Comment by Apollon77** [comment]
we close because it depends :(
