### ISSUE TITLE
Issue when binding adapter to specific network interface

### ISSUE THREAD

**Issue by Caprico85** [ioBroker/ioBroker.js-controller#351]
### Issue

You can set the web adapter to bind to a specific network interface (e.g. only to 127.0.0.1). If another process listens on the same port on another network interface the adapter refuses to start and shows the error message "port 1234 already in use" in the log.

Normally this should not be a problem. Different processes can use the same port, if they listen on different network interfaces. E.g. one process listens to port 1234 on localhost (127.0.0.1) and another process also listens to port 1234 but on the wifi or LAN interface.

### Steps to reproduce:

1. Configure ioBroker.web to bind to 127.0.0.1 on port 8082 and start it.
1. Start another server process (e.g. Apache) on port 8082 on the LAN interface.  You can use netcat as a simple test server. Run "nc -l 192.168.178.10 8082" (replace with the IP address of your LAN/wifi interface).
1. iobroker and netcat will start normally. Using "netstat -tulpn  | grep 8082" you can see both processes listening on their network interfaces.

Now try it the other way around:
1. Stop iobroker and netcat (Ctrl+C).
1. Start netcat first ("nc -l 192.168.178.10 8082").
1. Then start iobroker (again on 127.0.0.1 port 8082).
1. You will get the error message "port 8082 already in use" in iobroker log.

As we see running iobroker and netcat in parallel does work. It should not depend on the order both processes are started.

### Possible reason:
I guess the problem is that the web adapter calls getPort() in lib/adapter.js. getPort() only knows about the port but not the network interface to bind to. So it checks if the port is available on **all** network interfaces.  Obviously this will fail if the port is already bound on another interface. If I comment out the call to getPort() it will work.

**Comment by Ilovegym66** [comment]
perfect written issue!

**Comment by Caprico85** [comment]
Same thing happens to the admin adapter (and maybe other adapter using getPort()).

**Comment by Apollon77** [comment]
Do you have an idea how getPort would need to change? Is it enough to allow to also set the Network interface to only check this?

**Comment by mc-0815** [comment]
Yes, only a minor change would be needed, by adding an option parameter to provide getPort() also the IP to be checked for ports.

**Comment by Apollon77** [comment]
Can you do a PR? ;-)

**Comment by Stabilostick** [comment]
server.listen(port, "192.168.100.1") ;

**Comment by mc-0815** [comment]
I am actually new to github, so would need to read some documentatino regardings pull requests. In essence the server.listener call in getPort() would needed to be changed from

server.listen(port, function (/* err */)
server.listen(port, host, function (/* err */)

where host is the IP where the server shall be bind to. And thats it

best regards

**Comment by Apollon77** [comment]
fixed in js-controller 2.0.0, the following feature flag can be used to check if it is supported:
ADAPTER_GETPORT_BIND
