### ISSUE TITLE
"host set this" An unknown error occured: TypeError: Cannot read property 'changeInstanceHost' of undefined

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#355]
I have done a "set host this" and got the following output:

```
Host "GF0586MAC.local" successfully renamed to "this".
An unknown error occured: TypeError: Cannot read property 'changeInstanceHost' of undefined
```

After checking code only two places are existing where this cound happen in cliHost.js and inside a 
```
tools.poorMansAsync(function* () {
```

Can this be the reason why "this" is not set?!

**Comment by AlCalzone** [comment]
> Can this be the reason why "this" is not set?!

Maybe... I'll have to check.
Are we still supporting node 6? If not, we can change that construct to async/await.

**Comment by AlCalzone** [comment]
Actually... `changeInstanceHost` is only used from inside the class and needs no this reference. We could just move it outside the class and call it without `this.`.

**Comment by AlCalzone** [comment]
> I have done a "set host this" and got the following output:

I think you wanted to do `host this`, not `set host this`.

**Comment by AlCalzone** [comment]
Fix is up at #356

**Comment by Apollon77** [comment]
for 2.0.0 we can kill node6, only if we plan to backport we need to be compatible.

**Comment by AlCalzone** [comment]
With the proposed fix, using `async/await` should not be necessary.
