### ISSUE TITLE
1.5.x Backport Summary List

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#357]
We identified the following topics that we should backport in 1.5.x Line:
[x] #354 
[x] #328 
[-] update unix_dgram dep to 2.0.2 (node10 compat - not possible)

**Comment by Apollon77** [comment]
Changes from https://github.com/ioBroker/ioBroker.js-controller/commit/20a24d47341bd1299e7929bddc59a9ed0aec93e1 basically reviewed

**Comment by Apollon77** [comment]
I also backported https://github.com/ioBroker/ioBroker.js-controller/commit/ec3a8bec4da91d097d48c6237435876532bbbb0c via https://github.com/ioBroker/ioBroker.js-controller/commit/0f6f4d14c8da138c0273e911ea33d4672921f3ff

**Comment by Apollon77** [comment]
@arteck: how to test this :-)
1.) Now also Custom-Installs that end in an "Npm error code 1" (mostly happening when there are optional dependecy errors while installing, so everything works, but there were errors) should always do an upload
2.) deletion (and also other operations, but easiely testable via installs) of adapters that start with same name part should not delete the other. Detail: install an instance of mqtt and mqtt-client and then delete "mqtt" ... in 1.5.7 also mqtt-client was removed which is wrong. 1.5.8 should correctly only remove mqtt
3.) When moving an adapter between hosts (multihost environment) or an adapter needs to get installed because started and not installed automatically the version which is installed is the one from the local repo (and not latest from npm). Can be checked whiel checking the command line for the npm install command in log - in 1.5.7 no version was provided with the npm package, in 1.5.8 a version should be in the commandline (npm install paket@version)
4.) repo should not be downloaded when not changed

**Comment by AlCalzone** [comment]
> update unix_dgram dep to 2.0.2 (node10 compat - not possible)

In case we ask ourselves this question again in the future: **Why** is it not possible?

**Comment by Apollon77** [comment]
;-) Why: unix_dgram is a dep of winston-syslog and was upgraded to 2.x in winston-syslog release 2.0; but this version needs winston 3 to work and we are still at winston 2 ion 1.5.x branch.
This will be fixed with js-controller 2.0 because there winston 3 is used.

BTW: As solution you can simply install unix-dgram@2.0.2 manually and it will work basically, but I do not ant to add such a dep to js.controller, also because winston-syslog is a optional dep as of now

**Comment by Apollon77** [comment]
Released
