### ISSUE TITLE
Crash in objectsInMemServer

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.js-controller#365]
See log:
```
error: TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
at Function.Buffer.from (buffer.js:183:11)
at Buffer (buffer.js:158:17)
at clone (/opt/iobroker/node_modules/iobroker.js-controller/lib/objects/objectsInMemServer.js:1936:24)
at clone (/opt/iobroker/node_modules/iobroker.js-controller/lib/objects/objectsInMemServer.js:1940:29)
at clone (/opt/iobroker/node_modules/iobroker.js-controller/lib/objects/objectsInMemServer.js:1940:29)
at clone (/opt/iobroker/node_modules/iobroker.js-controller/lib/objects/objectsInMemServer.js:1940:29)
at _getObjectList (/opt/iobroker/node_modules/iobroker.js-controller/lib/objects/objectsInMemServer.js:2863:39)
at checkObjectRights (/opt/iobroker/node_modules/iobroker.js-controller/lib/objects/objectsInMemServer.js:2912:28)
at checkObjectRights (/opt/iobroker/node_modules/iobroker.js-controller/lib/objects/objectsInMemServer.js:1869:20)
at ObjectsInMemServer.getObjectList (/opt/iobroker/node_modules/iobroker.js-controller/lib/objects/objectsInMemServer.js:2908:13)
```

I'm not sure where it comes from. Might have to do with the JavaScript adapter:
https://forum.iobroker.net/topic/21516/iobroker-js-controller-st%C3%BCrzt-alle-6-8-tage-ab/13

**Comment by Ilovegym66** [comment]
I've the same issue since some days..  looks like Javascript Adapter, I've a script that looks for the imap account, and if there is a Mail ( sometimes from iobroker-forum ) the system fucked up with this error.
( iobroker stops and is not running any more ) manually start is needed..
My workaround was, the imap-javascript to disable..

**Comment by Ilovegym66** [comment]
add: my iobroker run in a proxmox vm on linux mint 18.3, Node 8.15.1, NPM 6.9, system have 6GB Memory, no swap.

**Comment by AlCalzone** [comment]
Could you please post the code of that script, so we can check out what exactly goes wrong?

**Comment by Ilovegym66** [comment]
here it is, I've adopt it from iobroker-forum, link is here:
https://forum.iobroker.net/post/18501

Script:
`createState("Email.Reception");
createState("Email.from_address");
createState("Email.from_name");
createState("Email.mail_subject");
createState("Email.mail_text");
        
schedule("*/2 * * * *", function (obj) {
    var MailListener = require("mail-listener2");
    var mailListener = new MailListener({
      username: "user@hot.com",    // hier Email Adresse eintragen
      password: "topsecretineverforgot",	      // hier Passwort eintragen	
      host: "imap.gmail.com",
      port: 993, // imap port
      tls: true,
      connTimeout: 10000, // Default by node-imap
      authTimeout: 5000, // Default by node-imap,
      debug: null, // Or your custom function with only one incoming argument. Default: null
      tlsOptions: { rejectUnauthorized: false },
      mailbox: "INBOX", // mailbox to monitor
      searchFilter: ["UNSEEN"], // the search filter being used after an IDLE notification has been retrieved
      markSeen: true, // all fetched email willbe marked as seen and not fetched next time
      fetchUnreadOnStart: true, // use it only if you want to get all unread email on lib start. Default is `false`,
      mailParserOptions: {streamAttachments: true}, // options to be passed to mailParser lib.
      attachments: false, // download attachments as they are encountered to the project directory
      attachmentOptions: { directory: "attachments/" } // specify a download directory for attachments
    });

    mailListener.start();
    mailListener.on("server:connected", function(){console.log("imapconconnected");});
    mailListener.on("server:disconnected", function(){console.log("imapDisconnected");});
    mailListener.on("error", function(err){console.log(err);});
    mailListener.on("mail", function(mail, seqno, attributes){
        log(mail.from[0].address);
        log(mail.from[0].name);
        log(mail.subject);
        log( mail.text);
        var mailobj = {val:
                {
                    from:  mail.from[0].name,
                    topic: mail.subject,
                    text:  mail.text
                }
            };
        setState("Email.Reception", mailobj);
        setState("Email.from_address", mail.from[0].address);
        setState("Email.from_name", mail.from[0].name);
        setState("Email.mail_subject", mail.subject);
        setState("Email.mail_text", mail.text);

    });
    mailListener.on("attachment", function(attachment){console.log(attachment.path);});
    setTimeout(function(){mailListener.stop();},20000);
});
 
`

**Comment by Ilovegym66** [comment]
@AlCalzone habs gefunden, der Javascript-Adapter schmiert ab, wenn vom iobroker-Forum diese Email kommt mit diesem Betreff kommt:
[ ioBroker Community] Zusammenfassung für....

Er mag anscheinend die eckigen Klammern nicht... !! ( wer hat denn das auch erfunden, in ner Betreffzeile die Klammern zu setzen... ??? )

**Comment by Apollon77** [comment]
which js-controller version?  ELs eit is hard to find the place in the code here

**Comment by Ilovegym66** [comment]
js-controller 1.57, javascript 4.1.12

**Comment by Apollon77** [comment]
Was legt der denn dann an? Also der Fehler kommt in einer Funktion wo eine Objektliste geladen wird und dabei werden Objekte gecloned und ein Objekt ist da komisch.

Versuch mal https://github.com/ioBroker/ioBroker.js-controller/blob/master/lib/objects/objectsInMemFileDB.js#L1261 noch ein "new" rein zu bauen, also 

const temp = new obj.constructor();

Bringt das was?

**Comment by Apollon77** [comment]
Any news here?

**Comment by Apollon77** [comment]
verify?
