### ISSUE TITLE
Deleting and renaming files an folders via socket.emit does not work

### ISSUE THREAD

**Issue by sbormann** [ioBroker/ioBroker.js-controller#370]
In index_m.htm socket.emit ignores the 'unlink' and 'rename' command, whereas 'writeFile' works well.

Has anyone any idea?

This is not working (deleting and renamig files and folders):

function deleteFile(path, callback) {
	socket.emit('unlink', adapter, path, function (err) {
		if (callback) callback(err);
	});
}

function renameFile(oldPath, newPath, callback) {
	socket.emit('rename', adapter, oldPath, newPath, function (err) {
		if (callback) callback(err);
	});
}
Whereas this works (Image-Upload):

function uploadFile(file, path, callback) {
	if(typeof path == 'function') {
		callback = path;
		path = null;
	}
	var reader = new FileReader();
	reader.onload = function(e) { // Closure to capture the file information.
		socket.emit('writeFile', adapter, (path ? path + "/" : "") + file.name, e.target.result, function () {
			if (callback) callback(file.name);
		});
	};
	reader.readAsArrayBuffer(file);
}

Taken from https://github.com/sbormann/ioBroker.iqontrol

Many thanks!

**Comment by Apollon77** [comment]
Can you please recreate that in socketio adapter please because this is no controller issue (and I can not transfer it)

**Comment by sbormann** [comment]
Hi Ingo, i think it is controller-related - because when using socket.io it is working fine. But using socket.emit - wich uses the built-in socket of the controller (as far as i understood) it doesn't work.

**Comment by Apollon77** [comment]
When then it is admin ... js.controller is not offering any socket.io other then the states/objects DBs and I can not think that you mean those ;-)

**Comment by sbormann** [comment]
I mean the socket when using the command socket.emit in index_m.html. (it is used in index_m.html of admin adapter itsself to upload background image for example).

**Comment by Apollon77** [comment]
This socket.io connection is provided by admin adapter

**Comment by sbormann** [comment]
Allright, thank you!

**Comment by Apollon77** [comment]
Sure, any time.
