### ISSUE TITLE
Neuinstallation und Probleme mit Versionen und Redis

### ISSUE THREAD

**Issue by frankjoke** [ioBroker/ioBroker.js-controller#371]
Habe heute einen Opi2+E neu installiert und dabei folgendes bemerkt:

Mit script vom web installiert, 
js.controller 1.4.2 wurde inmstalliert
Admin 3.6.0 wurde installiert

Hat geklappt, aber warum so alte Versionen???

iobroker update oder upghrade verändert nichts!
Dann iobroker stop,  redis-server und tools installiert und mit redis-cli getestet (könntet ihr auch ins unix-install aufnehmen).

Dann iobroker start und er läft wieder!

Wollte iobroker status checken mit
iobroker status
und krieg dann:
```
iobroker is running
 Ready check failed: Connection forcefully ended and command aborted. It might have been processed.
 AbortError: Ready check failed: Connection forcefully ended and command aborted. It might have been processed.
    at RedisClient.flush_and_error (/opt/iobroker/node_modules/redis/index.js:362:23)
    at RedisClient.end (/opt/iobroker/node_modules/redis/lib/extendedApi.js:52:14)
    at StateRedis.destroy (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInRedis.js:272:20)
    at processExit (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup.js:2820:44)
    at /opt/iobroker/node_modules/iobroker.js-controller/lib/setup.js:312:25
    at Object.connected (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup.js:3124:70)
    at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/objects/objectsInMemClient.js:120:68)
    at Socket.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/component-emitter/index.js:133:20)
    at Socket.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:138:10)
    at Socket.onconnect (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:335:8)

```
iobroker läuft (am web inklusive Adapter).

Vor einiger Zeit hatte ich VM's installiert und da bekam ich js-controller 1.5.x und keine Fehler bei redis/status!

**Comment by AlCalzone** [comment]
> Hat geklappt, aber warum so alte Versionen???

Ganz einfach: weil die die derzeitigen stable-Versionen sind.

Bezüglich des redis-Fehlers weiß ggf. @Apollon77 oder @GermanBluefox mehr.

**Comment by Apollon77** [comment]
Der Fehler bei iobroker Status mit redis ist „Knoten issue in js-Controller 1.4.2 und mit de 1.5 gefixt. 

Von daher, hier alles beantwortet?

**Comment by frankjoke** [comment]
hmm, nur noch die Frage warum wirklich so alte Versionen installiert werden wo doch anscheinend bekannt ist dass Fehler in den neuen behoben worden sind und auch warum dann mit iobroker upgrade self dann nicht auf neuere Version upgegraded wird.

Wie schon gesagt, bei einer Installation vor einigen Wochen bekam ich neuere Versionen geliefert.

**Comment by AlCalzone** [comment]
> warum dann mit iobroker upgrade self dann nicht auf neuere Version upgegraded wird.

Weil du das stable-Repo eingestellt hast, nicht latest.

**Comment by Apollon77** [comment]
> Wie schon gesagt, bei einer Installation vor einigen Wochen bekam ich neuere Versionen geliefert.
Vor ein paar vielen Wochen (so 2-3 Monate her denke ich) gab es einen Bug im Repo und stable hatte teilweise latest versionen drin anstelle den Stable Versionen. Also ja ... in dem Fall kann das mal gewesen sein ... Das war aber ein Bug.

Korrekt ist: Neuinstallationen nutzen Stable Repo und nur die dortigen versionen werden installiert. Man kann manuell auf latest umstellen.

js-controller 1.5.7 ist aktuell getestet, wir haben aber noch 1.5.8 nachgeschoben um ua noch das Problem mit dem "es werden zuviele instanzen erwischt beim löschen" (radar vs radar2 und so) zu beheben. Seit Anfang der Woche ist jetzt die 1.5.8 im latest und soll aber zeitnah dann ins stable kommen in nächsten 1-2 Wochen

**Comment by frankjoke** [comment]
Danke Ingo, hsb suf lstest gestellt und bin jetzt auf 1.5.8.

Vergesst nicht discovery auch auf 1.3 in der repo upzudaten, 1.2.4 war schon sehr alt und hat praktich nichts gefunden ausser den Fritzboxen und homematic.
