### ISSUE TITLE
getState regex does not working after update to 1.5.x

### ISSUE THREAD

**Issue by Jey-Cee** [ioBroker/ioBroker.js-controller#388]
With js-controller 1.4.2 
`getState('*' + z + '.', function(err, states)`
has worked as expected, since 1.5.x it is delivering always undefined.

**Comment by AlCalzone** [comment]
@Jey-Cee Does `err` contain an error?

**Comment by Apollon77** [comment]
@AlCalzone do you still plan to work on this? For 2.0.0?

**Comment by AlCalzone** [comment]
Not sure if I find the time, thats why I unassigned me a while ago

**Comment by Apollon77** [comment]
@Jey-Cee Could you try with a current js.controller 2.0.0 if it is still the case there or fixed?

**Comment by Apollon77** [comment]
Please use getStates
