### ISSUE TITLE
Error 'No "killall.sh" script found. Just stop.' after "iobroker stop"

### ISSUE THREAD

**Issue by justr1** [ioBroker/ioBroker.js-controller#392]
Zumindest bei mir (Installation von 2016 auf MacOS) liegt das Script "killall.sh" im iobroker-Verzeichnis und nicht im Unterverzeichnis "/usr/local/iobroker/node_modules/iobroker.js-controller". Könnte mir aber vorstellen, dass das bei aktuelleren Installationen anders aussieht. Also es gibt jetzt vermutlich zwei Möglichkeiten:

1. Das Shell-Script "killall.sh" ins Unterverzeichnis "<iobroker>/node_modules/iobroker.js-controller" kopieren/verschieben.
2. Oder in der Datei <iobroker>/node_modules/iobroker.js-controller/lib/setup.js in den drei Zeilen 287 bis 289 das "/../killall.sh" gegen "/../../../killall.sh" ersetzen, also zwei Verzeichnisse höher referenzieren.

Unschön ist dann auch, dass danach immer das root-Passwort abgefragt wird. Sollte mittlerweile ja auch nicht mehr nötig sein, solange keine Instanzen mehr unter root laufen. Also vermutlich könnte man generell im "killall.sh" die vier 'sudo' löschen.

**Comment by Apollon77** [comment]
Linux? Dann bitte mal Installation-Fixer nutzen, dann sollte das File kommen. Das es root braucht gibt es ein zweites Issue #363
