### ISSUE TITLE
Create new adapter info states (CPU and so) on upgrade or adapter start

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.js-controller#397]
Currently the new states that were added in 1.5.x like (`system.adapter.0.cpu`) are only created on fresh installations of an adapter. Upgrades don't create those states.

IMO those adapter meta states should either be checked for and created when an adapter is started (this way we don't have to create them during the installation) - or at least when it is upgraded.

Thoughts?
@GermanBluefox @Apollon77

**Comment by AlCalzone** [comment]
Here's the relevant changelog portion https://github.com/ioBroker/ioBroker.js-controller/blob/ba45ad48b668dc02c55cecad2870e9333c9b57f9/CHANGELOG.md#151-2018-09-14-evolution-release-ann

**Comment by Apollon77** [comment]
There may be an overhead for "scheduled" adapters because they are started that often ... maybe only once after js-controller start for each adapter (and on install)?
