### ISSUE TITLE
[1.5.12] Error: Command failed: npm -v

### ISSUE THREAD

**Issue by truegreyhound** [ioBroker/ioBroker.js-controller#406]
With this update I get the following error:
`2019-07-17 11:27:21.863  - error: host.XXX cannot get getHostInfo: Error: Command failed: npm -v
/bin/sh: 1: npm: not found`

This is locatated in ./lib/tools.js

My installation run under the user iobroker with restricted rights.

Further problems (think with the same cause):
- It's not possible to update an adapter via admin (hangs).
When I do this as user iobroker, I can do this on commandline.
- When starting the javascript adapter additional modules can not be installed.

In older versions that was not a problem.

**Under root, npm and node not installed / accessable!**

OS: debian Jessie 8.11
npm: 6.4.1
node: v8.15.1

**Comment by Apollon77** [comment]
What you mean with "Under root, npm and node not installed / accessable!"?? Please check your PATH variable if it contains the locations of node and npm ... I think this is the base reason

**Comment by truegreyhound** [comment]
I installed node and npm in user mode, so they are only accessible to the user iobroker

**Comment by Apollon77** [comment]
what and how is that possible? The official guide installs it globally and this is the supported way.

**Comment by AlCalzone** [comment]
The last time I saw this error was on MacOS when the path env variable was missing some paths

**Comment by truegreyhound** [comment]
I looked at the script a little closer, it runs in the context of the user, here iobroker. The difference to previous versions is probably how the shell environment is initialized. In the present it is incomplete because it does not take .profiles.

**login-env:**
`MANPATH=/opt/iobroker/.nvm/versions/node/v8.15.1/share/man:/usr/local/man:/usr/local/share/man:/usr/share/man
COMP_WORDBREAKS=
"'><;|&(:
NVM_CD_FLAGS=
SHELL=/bin/bash
TERM=xterm
NVM_DIR=/opt/iobroker/.nvm
USER=iobroker
MAIL=/var/mail/iobroker
PATH=/opt/iobroker/.nvm/versions/node/v8.15.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
NVM_NODEJS_ORG_MIRROR=https://nodejs.org/dist
PWD=/opt/iobroker/node_modules/iobroker.js-controller
LANG=en_US.UTF-8
NODE_PATH=/usr/lib/nodejs:/usr/lib/node_modules:/usr/share/javascript
SHLVL=1
HOME=/opt/iobroker
LOGNAME=iobroker
NVM_BIN=/opt/iobroker/.nvm/versions/node/v8.15.1/bin
NVM_IOJS_ORG_MIRROR=https://iojs.org/dist
OLDPWD=/opt/iobroker
_=/usr/bin/env`

**exec-env:**
`USER=iobroker
SHLVL=1
HOME=/opt/iobroker
LOGNAME=iobroker
_=/opt/iobroker/.nvm/versions/node/v8.15.1/bin/node
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
NODE=/opt/iobroker/.nvm/versions/node/v8.15.1/bin/node
LANG=en_US.UTF-8
SHELL=/bin/bash
PWD=/`

> what and how is that possible? The official guide installs it globally and this is the supported way.

There are enough recommendations for security reasons not to install as root and various pages that describe how it works, has been running for me for over a year.

**Comment by Apollon77** [comment]
In 1.5.12 nothing was changed in the way how "npm" is executed, so in my eyes it can not be ioBroker as the reason.
may it be npm or nodejs? 

I also see "nvm" in your lines above ... could it be that that's why npm is not found in the "path" or such?

What could be the fix and where?

**Comment by truegreyhound** [comment]
I think I'm getting closer. The reason is probably the execution of the fix.sh script and the change from _xinit_ to _systemctl_. With xinit script the iobroker environment is started with 
`sudo -i -u ${IOBROKERUSER} $NODECMD $IOBROKERCMD`
_systemctl_ systemctl controls the user environment itself and does not run any user environment scripts.

I have no experience with systemctl and user environments. But I think here would be the approach that the /opt/iobroker/.profile or .baschrc or possibly a special environment file is loaded.

**Comment by truegreyhound** [comment]
now I have found a solution that  works for me

/lib/systemd/system/iobroker.service
`ExecStart=/bin/bash -c '/opt/iobroker/iobroker_start.sh'`

create a file 
/opt/iobroker/iobroker_start.sh
`#!/bin/bash`
`source /opt/iobroker/.profile`
`node /opt/iobroker/node_modules/iobroker.js-controller/controller.js`

 and set execution flag
`$ chmod u+x,g+x iobroker_start.sh`

![image](https://user-images.githubusercontent.com/24899637/72016856-d6cb7d80-3264-11ea-8057-d02058f9c92d.png)

The solution shows that this is a problem with the user environment.
