### ISSUE TITLE
Add Compact mode CLI commands

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#409]
I propose the following:
* `iobroker compact status`: shows the status if compact mode is enabled or not for this host
* `iobroker compact enable/on/disable/off`: set status for compact mode, only works when not running (?)
* `iobroker compact <instance> status`: output the status if this instance is using compact mode or not
* `iobroker compact <instance> enable/on/disable/off`: set status for compact mode for this instance. Instance will restart

**Comment by Apollon77** [comment]
tools.appName + ' compact status\n' +
                tools.appName + ' compact <enable|on|disable|off>\n' +
                tools.appName + ' compact <adapter>.<instance> status\n' +
                tools.appName + ' compact <adapter>.<instance> group <group>\n' +
                tools.appName + ' compact <adapter>.<instance> <enable|on|disable|off> [group]\n' +

**Comment by AlCalzone** [comment]
Some questions:
* `compact <adapter>.<instance> group <group>` - Is group a name or a number like the instance number? Can I list the groups them with one command (like `list instances`)?
* `compact <adapter>.<instance> <enable|on|disable|off> [group]` - I guess it is `compact admin.0 enable group5` to enable and set group at the same time?

**Comment by Apollon77** [comment]
Group is a number. Incan write groupId in the Infos?

List instances is enhanced too to show compact info when compact mode is enabled. 

Other make sense. I will adopt it. 
In fact command would allow to change group also while setting to off ;-) why not

**Comment by Apollon77** [comment]
Update
                tools.appName + ' compact status\n' +
                tools.appName + ' compact <enable|on|disable|off>\n' +
                tools.appName + ' compact <adapter>.<instance> status\n' +
                tools.appName + ' compact <adapter>.<instance> group <group-id>\n' +
                tools.appName + ' compact <adapter>.<instance> <disable|off>\n' +
                tools.appName + ' compact <adapter>.<instance> <enable|on> [group-id]\n' +
