### ISSUE TITLE
Proposal: Add `step` attribute to numeric states

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.js-controller#424]
This would require `min` to also be set. When the `step` attribute is present and not 0, values will be rounded to the nearest matching `min + n * step`.

Example:
`min = 5, step = 10`: Valid values are `5, 15, 25, 35, ...`. If the user tries to enter 17, the value is automatically rounded to 15.

**Comment by Apollon77** [comment]
If min not set consider it 0 ?

**Comment by Apollon77** [comment]
And we need to consider max ... so if reounded result is higher then max set to max.

In general I think this is a good idea to have "step" supported naturally.
When rounding logic changes the value makes it sense to set with "ack=false" again or is that needed to come back from device with the real value with ack= true?

**Comment by AlCalzone** [comment]
> If min not set consider it 0 ?

Hmmm.. if min is not set, we could support all values `n * step`, where n is a whole number (negative or positive).

> And we need to consider max ... so if reounded result is higher then max set to max.

Sure, but that logic is already there

> When rounding logic changes the value makes it sense to set with "ack=false" again 

How is it currently done when values are < min or > max?

**Comment by Apollon77** [comment]
> Hmmm.. if min is not set, we could support all values n * step, where n is a whole number (negative or positive).

this basically means min=0 ;-)

> How is it currently done when values are < min or > max?

From my knowledge min/max is not enforced at the moment in general by controller/adapter base class. It is present for Visualizations to make sure only correct values can be entered/choose needed UI elements and if it should be enforced the respecive adapter is responsible.

**Comment by AlCalzone** [comment]
> this basically means min=0 ;-)

No, `min=0` means negative values are not allowed. For example, `step = 5` would allow the following values: `..., -10, -5, 0, 5, 10, ...`

> From my knowledge min/max is not enforced at the moment in general

Oh, then it's only the admin. But that would be fine for me.

**Comment by Apollon77** [comment]
Re min=0 ... yes you are right.

**Comment by GermanBluefox** [comment]
Step is good. And by default min=0, max=100 and step=(min-max)/100.
I even used common.step somewhere, but now cannot find it.

**Comment by AlCalzone** [comment]
@GermanBluefox What would one have to do if there should be no step? set `step` to 0?

**Comment by Apollon77** [comment]
I would not use a default step because of backward compatibility. Else the proposed default will break things like thermostats or other states. Thermostates allow 0.5 normally and would have a min and a max and the above formula could generate weird effects I think.

**Comment by Stabilostick** [comment]
Two ideals in one: Are there two values stored, like on processed one (why not use a multipurpose function field for calculation rounding, linearity correction, value conversion etc.  instead of lots of specific parameter fields) and in addition the raw value?

**Comment by Apollon77** [comment]
Min, Max, step are Standard fields in iot area. And that’s why we should support that as generic as possible to also be able to integrate with other iot schemes. Your idea would be Iobroker specific and so mich more effort for each and every adapter. So yes the idea may be good (and alias will have such read/write functions) but is a separate topic.

**Comment by foxriver76** [comment]
Hm if this is added does it belong to controller or more to documentation + usage in admin, vis etc? Controller currently does not respect anything like that. Problem would again be the performance, because we need object information on every setState. If it should be checked on controller it is related to https://github.com/ioBroker/ioBroker.js-controller/issues/698 and could be an extension of the `strictObjectChecks` flag.

**Comment by Apollon77** [comment]
I would see it as "lets document it after we have decided we want to allow it", but in the end it needs to be supported then mainly by Javascript adapter and the visualization adapters and Admin, or?!

**Comment by Apollon77** [comment]
If we take in the min/max checkin in controlelr 3.3 we could also introduce step and do value rounding (https://github.com/iobroker-community-adapters/ioBroker.hmip/blob/master/main.js#L188-L192) ... incl logging

**Comment by foxriver76** [comment]
> If we take in the min/max checkin in controller 3.3 we could also introduce step and do value rounding (https://github.com/iobroker-community-adapters/ioBroker.hmip/blob/master/main.js#L188-L192) ... incl logging

Then we would need to always get the object also on adapters that set `strictObjectChecks=false`  otherwise, it would lead to inconsistencies

**Comment by Apollon77** [comment]
I fear that too. We could think about "optimized ways" for that like always have the "local adapterobjects from same namespace cached available" and also subscribed tso we can update. Then we could optimize object access there with the need of some additional ram ... or we subscribe to all local objects but only store those that we have needed at least once before (so first setstate is getting the object into cache and so afterwards it is auto updated

**Comment by Apollon77** [comment]
> Then we would need to always get the object also on adapters that set strictObjectChecks=false otherwise, it would lead to inconsistencies

Here e could do the same definition: an adapter that uses strictObjectChecks=false is REQUIRED to do anything as it is defined also for min/max and need to pay a beer to all devs for each issue that states something different ;-)

**Comment by foxriver76** [comment]
Sh.. I don’t drink .. ;-)

Would be the easiest way

**Comment by Apollon77** [comment]
> Sh.. I don’t drink .. ;-)

Then a cake for each dev per isse? :-)
