### ISSUE TITLE
Add new host states to display number of started adapter processes

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#425]
Idea is to have two new  states to see the number of started processes by each host - and also for compact mode.

Proposal:
* system.host.xyz.instanceAsProcess = number of normal adapter instance processes
* system.host.xyz.compactGroupProcesses = number of started compact mode group controller processes
* system.host.xyz.instanceAsCompact = number of adapter instances started in compact mode

**Comment by AlCalzone** [comment]
Is the 2nd for the processes in each compact group or total?

**Comment by Apollon77** [comment]
Second is the number of group controller processes started. Also number of different Compact groups with active instances.

**Comment by Apollon77** [comment]
In fact the first two in sum are the number of child processes of this iobroker hosts

**Comment by Apollon77** [comment]
done
