### ISSUE TITLE
iobroker update 2.0 redis/redis migration user guidance 

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.js-controller#430]
![grafik](https://user-images.githubusercontent.com/6681528/63651105-ce5d2500-c751-11e9-9a48-02679be4cce4.png)

this message is from a slave device after upgrade to 2.0 and "iobroker setup custom"
i think we need here a other message or info 

a little info "mirgation in progress .. plz wait" is very helpfull
and maybe that new redis dump file is very big 

general more infos .. 

plz make also a separeate object/state backup befor migration start

**Comment by Apollon77** [comment]
We should also maybe check the redis persistence and error if none is enabled.

**Comment by Apollon77** [comment]
And we should tell the User on Master Slave System To not choose migration when migration in general was already done. Can we detect that somehow automatically?

**Comment by Apollon77** [comment]
I think we should also add a check that before allowing to choose redis/redis all hosts are Controller 2.0.0 already. If not Display a warning before the object DB to tell about risk that slaves will not longer work afterwards. 

Also maybe use ioredis to Test connection and also check if already states and/or objects are existing in this redis dB.

**Comment by Apollon77** [comment]
Partly implemented in 2.0.0 as infos without deeper checks, should be optimized post 2.0
