### ISSUE TITLE
after update 2.0 invalid alias warnings

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.js-controller#431]
![grafik](https://user-images.githubusercontent.com/6681528/63653471-6caab400-c76d-11e9-99cb-52024fe61283.png)

![grafik](https://user-images.githubusercontent.com/6681528/63653477-7b916680-c76d-11e9-8a01-2300cecb5037.png)

**Comment by Apollon77** [comment]
All objects do not had any alias configured. 

Must come from one of the commits >20.8.

**Comment by GermanBluefox** [comment]
Problem found and will be fixed
