### ISSUE TITLE
DB Migration unexpected effects

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#434]
* all instances are disabled after migration. It should stay as before or we need to communicate this effect to the users at the end of migration
* it seems that only files from instances on the host the migration is stated from are migrated. Other host files are missing. Expectation is that files for all instances are migrated.

Both should be effects from the backup/restore mechanism which is used inside migration. We should make sure that this is changed.

**Comment by arteck** [comment]
- adapter upload from slave machine after migration

**Comment by GermanBluefox** [comment]
>all instances are disabled after migration.

It is standard behavior. Normally the restore will be executed on different hardware. Many adapters, like web, admin, hm-xxx require that the bound IP-address must be defined. And on the new machine it is different.

The user have the possibility to execute: `iobroker enable all`

**Comment by Apollon77** [comment]
1.) i think we should add a „migration:true“ adoption für the restore logic/code and to prevent that the instances are disabled in this case?! I will check this. 

2.) but should gather not be uploaded also as files on master? I thought that files are also uploaded to master only ?! Hm ...

**Comment by Apollon77** [comment]
1.) yes this is one code Place so we should be able to change this. I think this makes sense. 

2.) yes it really seems that files are on the slaves. So we need to add an „execute ‚upload all‘ on all slaves“ as Info for the user after migration. And need to fix that function ;-)

How ‚upload all‘ on an 1.5.x system would react when master is using redis for objects?! ;-) should do nothing bad i hope. ;-)
