### ISSUE TITLE
Upload all with objects in redis destroys the system

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#435]
Todo: add reproduction info

**Comment by arteck** [comment]
test was :
 multihost -> upload from slave -> destroy host settings

**Comment by GermanBluefox** [comment]
We must reduce this error to "upload X/upload all" should upload files only if it is defined for the host, where the command is called.

**Comment by Apollon77** [comment]
If you give me a code point where I can start charging I can give it a try. Or you are faster ;-)
