### ISSUE TITLE
Alias also needs to be considered in "cli" state commands

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#440]
... they are using states.setState directly and there is no alias Handling included.

BTW: We need to document that all "system.* states" will not allow aliasses to be set because also here states.setState is used directly. Or we need to create kind of a tools method somewhere (for cli, controller and adapter.js) to have a "setStateWithAliasLogic" on a central place

**Comment by AlCalzone** [comment]
Sounds like we need the alias logic a level deeper than the public setState.

**Comment by Apollon77** [comment]
This is the problem. A level deeper is the states database. But this one is not knowing anything about objects. But alias needs to get data from objects. I think I do not want to introduce objects into states dB. And with this (separation of concerns and such) the current lebe is the relevant one - if we not create another states in between class just for this.

**Comment by GermanBluefox** [comment]
system.* will work. 
Because no matter how the states will be written.

**Comment by Apollon77** [comment]
ok, then also done here
