### ISSUE TITLE
after update to 2.0 vis has no projects

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.js-controller#442]
where are my other projects ??
i have many project and after update to 2.0 i cant see it

![grafik](https://user-images.githubusercontent.com/6681528/64445715-660a2e00-d0d7-11e9-84d8-eb8718c6ec12.png)

![grafik](https://user-images.githubusercontent.com/6681528/64445801-8cc86480-d0d7-11e9-9561-14d64bbd3bc4.png)

**Comment by Apollon77** [comment]
@GermanBluefox Where the Projct list comes from?

**Comment by Apollon77** [comment]
fixed
