### ISSUE TITLE
getEnum should return only translated name based on system language

### ISSUE THREAD

**Issue by rg-engineering** [ioBroker/ioBroker.js-controller#450]
At this point, `getEnumAsync ('functions')` returns a list of all translations for common.name.
If translations are not available (probably after importing from HM), the name will only be returned as a simple string.
It would be nice if getEnum / getEnumAsync always return the name as a string. If translations are available then the name string should be used for the given system language.

**Comment by AlCalzone** [comment]
We should consider the case that an adapter **wants** to retrieve a list of all translations. I propose an additional parameter to specify this.

**Comment by Apollon77** [comment]
Or new get methods to return the translated like getEnumTranslated(...)

**Comment by GermanBluefox** [comment]
I would decline it.
