### ISSUE TITLE
replace redis "KEYS" command by "SCAN" (in objects-lib and Redis-InMemDB

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#464]
... KEYS is not the best option and not best practice for production systems

**Comment by foxriver76** [comment]
Especially when considering this https://github.com/antirez/redis/issues/3190 may also make things like https://github.com/ioBroker/ioBroker.js-controller/issues/491 less worse..

**Comment by foxriver76** [comment]
Example of using SCAN and filtering out duplicates in Lua.
```lua
local cursor = "0";
local keys = {};
local has = {};
repeat
    local result=redis.call("SCAN", cursor, "MATCH", KEYS[1].."*", "COUNT", 100)
    cursor = result[1]
    for _, key in ipairs(result[2]) do
        if has[key] == nil then has[key] = 1; keys[#keys+1] = key; end
    end
until cursor == "0"
```

**Comment by Apollon77** [comment]
LUA script updated (https://github.com/ioBroker/ioBroker.js-controller/issues/491, objects lib 3.0), rest we wait if we get performance reports

**Comment by foxriver76** [comment]
test will pass with objects-redis 4 its just because test checks err.message but current objects-redis just throws string

**Comment by foxriver76** [comment]
Now using scan objects lib 4.0.1
