### ISSUE TITLE
[2.0.9] compact enable output is confusing if an adapter was not compact-enabled before

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.js-controller#470]
See this for example:
![grafik](https://user-images.githubusercontent.com/17641229/65535910-a56fb180-df02-11e9-92ff-4b01416c90e3.png)
Both adapters did not have compact mode enabled before. The line `compact group: 1 --> 2` suggests that I just moved it from group 1 to 2.

**Comment by Apollon77** [comment]
Group 1 is the default and the group cn also be et if the adapter is not enabled ... (but if undefined it will be set in this call too ... thats why the "1-->1" is shown. Can try to avoid that.

Do you have an idea to visualize it better?

**Comment by AlCalzone** [comment]
If compact was previously disabled, only log the target group not the old one.

**Comment by Apollon77** [comment]
That’s an idea. Thank you

**Comment by Apollon77** [comment]
Same for enabled then?

**Comment by AlCalzone** [comment]
Thats fine as is, because we actively changed that to enabled. 
If you only change the compact group, but not the enabled state, it should just show the arrow at the group
