### ISSUE TITLE
use deep-clone to clone objects instead of JSON-stringify/parse

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#478]
https://github.com/ahmadnassri/benchmark-node-clone ... 4 times faster then stringify

**Comment by Apollon77** [comment]
Make sure to also address:  https://github.com/ioBroker/ioBroker.javascript/issues/447 and change in extendObject !!

**Comment by AlCalzone** [comment]
We should also test how the performance of [this implementation](https://github.com/AlCalzone/shared-utils/blob/6025efec39eaa17870bed9d7014f39e26a95d7df/build/objects/index.js#L41) is. It can also be used to clone objects with `extend({}, obj)`.
That method does not handle all edge cases, but should be enough for our purposes.

**Comment by AlCalzone** [comment]
So, `deep-clone` is still the fastest by far and my lib cannot be used because it does not deep-copy arrays. I'll see what I can do :)
