### ISSUE TITLE
Check Differences in State Handling controller 1.5 vs 2.0 AND states in file vs redis

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#481]
Currently we have two areas where former js-controller and the new one is behaving differently when accessing States!:

* controller 1.5 when accessing a state that never had a value -> undefined
* controller 2.0  when accessing a state that never had a value -> null

A comparable scenario we have for states that use "expire" feature:

* controller 1.5 after exipre time -> objects with lc, ts and val = null
* controller 2.0 after exipre time -> null (not even an object)

Do we need to care about these differences or do we document it and fix adapters where needed?

**Comment by Apollon77** [comment]
The deeper I look into income to the point that these different behavior was already that way in controller <2.0 as soon as a user used states in redis. 

So from my point of view I would adjust that we decide for one behavior for the both topic and then implement it so that this is consistent.

**Comment by Apollon77** [comment]
My proposal:
1.) we Change that always null is returned and document that change. I think most developer use !state or such instead of checking for undefined, so it should not that a huge impact
2.) this is more tricky because „the redis way“ loose information like cloud/ts and such when Samstage is set to null. Is this acceptable? After deciding the way we also sync it in code - also here impact should not be that big because not many adapters uses expire for states.

**Comment by Apollon77** [comment]
Updated proposal after discussing with @AlCalzone:
1.) We return undefined when no state value exists
2.) We use Redis-Style expiry ... means we change "file "behavior and kill the stae completely on expiry.
@GermanBluefox ok?

**Comment by Apollon77** [comment]
As info: I also found how how to receive expire notifications do this can be done easiely.  So we also could set an „empty“ object again on expiry ... but only if at least one controller is running when the key expires. So problem: when keys expire while iobroker is offline the state object will be not existing anymore.

**Comment by Apollon77** [comment]
Lua scripts at the moment can not receive events ;-))

**Comment by Apollon77** [comment]
For state changes question: is there a semantic rule as for objects (when statechanged is called with empty  obj  it means that object got deleted) also for states?

**Comment by Apollon77** [comment]
And last but not least: On "delete" of an state "null" is published, so for the first thing "null" as "not existing" would be the cleanest option in my eyes

**Comment by GermanBluefox** [comment]
I would use redis style everywhere, because this behaviour is not under our control. Null => not exist or expired. 

Objects should use the same

**Comment by Apollon77** [comment]
So basically the first things are done in https://github.com/ioBroker/ioBroker.js-controller/tree/statechange
1.) All cases return "null" for non existing states (and objects ... was mainly so before, only one small fix will come in)
2.) On Redis we subscribe to keyspace events to get triggers when states expire (or are evicted) so that we can also trigger "onStateChanged" events. So Redis will here now behave "Like socket.io" for the fact that the triggers come

Open now is to change the socket.io logic so that on expire the state is removed completely (@GermanBluefox I understood you right here?). I would also propose this.
We then need to enhance history, influxdb and sql to also handle this correctly because they currently ignore "null" states

**Comment by AlCalzone** [comment]
> on expire the state is removed completely 

Does this mean the object is also deleted?

**Comment by Apollon77** [comment]
No only the state. 

It is in 2.0.16 on GitHub.
