### ISSUE TITLE
Implement function createOrExtendObject

### ISSUE THREAD

**Issue by DutchmanNL** [ioBroker/ioBroker.js-controller#492]
Currently we only have :

```
setObjectNotExists
```
or 
```
extendObject
```

there are several situation were names can be change in de root, meaning we have to code around and make a create function AND an extend object.
Would be very nice and handy if creation and update can be combined to 1 function.

**Comment by Apollon77** [comment]
I like that idea because it would be a good convenient method and less error prone fro devs.

BUT (especially for names) I had also enough cases where users set their own names and don't like when the names are overwritten ;-)
So the method should allow to not overwrite some defined fields

**Comment by DutchmanNL** [comment]
> So the method should allow to not overwrite some defined fields

Hmm aggree make sense, but let's keep that simple and combine something like in an array what kind of attributes can be excluded from overwriting.

**Comment by AlCalzone** [comment]
> users set their own names and don't like when the names are overwritten

You mean like this mess?
https://github.com/AlCalzone/ioBroker.ble/blob/master/src/lib/iobroker-objects.ts#L10
`default value < desired by adapter < existing`

**Comment by Apollon77** [comment]
Meine Version ist https://github.com/schmupu/iobroker-tools/blob/master/lib/objectHelper.js#L294

**Comment by Apollon77** [comment]
Hm ... I checked code again ... extendObject bsically is exactly that ...
It does:
* read objects
* if not existing initialize with {}
* extend the object with the delivered stuff
* save

So for the case that the object used in the extendObject call is always "complete" then it is alraeyd equivalent to this idea.

It will only break and create incomplete objects when you just call it with partial object data (like just to bring in a new name or such)

**Comment by DutchmanNL** [comment]
ok clear I will give it a try, the problem I have with this solution is the relation to : 

https://github.com/iobroker-community-adapters/ioBroker.coronavirus-statistics/issues/39

So what happens, every change on object level is causing the onObjectChange(){} function to fire which is overloading some other adapters.

I assume we have to filter that on adapter level in onObjectChange (most common example are the data loggers)

in basic for me it sounds that : 

- the "createState" is the most common one creating a state without attributes
- other functions can be used as well, but the "extendObject" would be the best practice

correct ?
