### ISSUE TITLE
Install OS packages if required by install of adapters (apt-get/yam)

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#495]

**Comment by AlCalzone** [comment]
I think we already have an issue for that

**Comment by AlCalzone** [comment]
... or not. I may have confused that.

**Comment by Apollon77** [comment]
We also searched yesterday night ... So seems we mainly talked about it several times :-)

**Comment by foxriver76** [comment]
Guess a problem is the variety of package mangers over different Linux distributions. However, with `apt` we get most of our users especially beginners.

**Comment by AlCalzone** [comment]
Since the installer script explicitly uses `apt`, I think it's safe to assume that `apt` is available.

**Comment by foxriver76** [comment]
According to https://github.com/ioBroker/ioBroker/blob/master/doc/SCHEMA.md#587 the attribute should be named 

> common.apt-get - list of debian packages, that required for this adapter (of course only debian)

**Comment by AlCalzone** [comment]
Property names with dashes are suboptimal, because you have to access the object with indexed accesses:
`common["apt-get"]`. I would prefer something that is more specific to what should be done instead of how, e.g. `linuxDependencies`. Or more general:
```
osDependencies: {
  linux: [...],
  windows: [...],
  macOS: [...]
}
```

**Comment by foxriver76** [comment]
I am with you on this. I also assume nobody has used this property before, so shouldn’t be a problem to change it.

**Comment by Apollon77** [comment]
I like the osDependency idea

**Comment by GermanBluefox** [comment]
Windows has no packages.

**Comment by Apollon77** [comment]
But windows could have download location and start parameters. ;-)

**Comment by Apollon77** [comment]
So on Linux the Array entry could be a package name OR an object like

{“apt”: “apt package name”, “...”: “...”}

To pot support different package names per package manager. ;-)

An on Windows have an object with download url and start parameters to silently start installers.

**Comment by GermanBluefox** [comment]
I implemented yet osDependencies: https://github.com/ioBroker/ioBroker.js-controller/commit/99219bfb62d050388c9582e36f68b182866b75b9

**Comment by Apollon77** [comment]
Created https://github.com/ioBroker/ioBroker.js-controller/issues/577 for enhancement ideas
