### ISSUE TITLE
Get rid of bluebird dependency (and mkdirp)

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.js-controller#497]
`bluebird` is only used in `lib/letsencryptStore.js`. 
* Many of the used methods are included in Node.js now (`Promise.all(), Promise.resolve(), Promise.reject()`) 
* `promisifyAll()` is used in a few places, but can be replaced with the Node.js utility function `util.promisify()` since we only promisify single specific methods.

This leaves these two calls:
```js
const mkdirpAsync = PromiseA.promisify(require('mkdirp'));
const fs = PromiseA.promisifyAll(require('fs'));
```
which can both be replaced if we use the `fs-extra` library (`mkdirp ==> ensurePath`, the default fs methods are promisified in `fs-extra` by default). 

I would advocate for using `fs-extra` anyways since we can benefit from it in a couple of places where we currently read files synchronously (while blocking the event loop).

**Comment by Apollon77** [comment]
bluebird is already removed.
mkdirp was removed but readded because used in several places
