### ISSUE TITLE
Update js-controller from @1.5.14 to @2.0.25

### ISSUE THREAD

**Issue by superpoli** [ioBroker/ioBroker.js-controller#500]
try to update from @1.5.14 to @2.0.25on my ubuntu server.

`NPM version: 6.4.1
npm install iobroker.js-controller@2.0.25 --unsafe-perm --production --save --pr                         efix "/opt/iobroker" (System call)
npm ERR! path /root/.npm/_logs
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall scandir
npm ERR! Error: EACCES: permission denied, scandir '/root/.npm/_logs'
npm ERR!  { Error: EACCES: permission denied, scandir '/root/.npm/_logs'
npm ERR!   stack: 'Error: EACCES: permission denied, scandir \'/root/.npm/_logs\                         '',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'scandir',
npm ERR!   path: '/root/.npm/_logs' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the                          current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check t                         he
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended                         ).
glob error { Error: EACCES: permission denied, scandir '/root/.npm/_logs'
  stack: 'Error: EACCES: permission denied, scandir \'/root/.npm/_logs\'',
  errno: -13,
  code: 'EACCES',
  syscall: 'scandir',
  path: '/root/.npm/_logs' }
npm ERR! path /root/.npm/_cacache/index-v5/1d/a8/f99642a9eccb731a5f4be46c26b08f8                         3c59d3cff19a70c94e745504ac47e
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall open
npm ERR! Error: EACCES: permission denied, open '/root/.npm/_cacache/index-v5/1d                         /a8/f99642a9eccb731a5f4be46c26b08f83c59d3cff19a70c94e745504ac47e'
npm ERR!  { Error: EACCES: permission denied, open '/root/.npm/_cacache/index-v5                         /1d/a8/f99642a9eccb731a5f4be46c26b08f83c59d3cff19a70c94e745504ac47e'
npm ERR!   cause:
npm ERR!    { Error: EACCES: permission denied, open '/root/.npm/_cacache/index-                         v5/1d/a8/f99642a9eccb731a5f4be46c26b08f83c59d3cff19a70c94e745504ac47e'
npm ERR!      errno: -13,
npm ERR!      code: 'EACCES',
npm ERR!      syscall: 'open',
npm ERR!      path: '/root/.npm/_cacache/index-v5/1d/a8/f99642a9eccb731a5f4be46c                         26b08f83c59d3cff19a70c94e745504ac47e' },
npm ERR!   isOperational: true,
npm ERR!   stack: 'Error: EACCES: permission denied, open \'/root/.npm/_cacache/                         index-v5/1d/a8/f99642a9eccb731a5f4be46c26b08f83c59d3cff19a70c94e745504ac47e\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'open',
npm ERR!   path: '/root/.npm/_cacache/index-v5/1d/a8/f99642a9eccb731a5f4be46c26b                         08f83c59d3cff19a70c94e745504ac47e' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the                          current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check t                         he
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended                         ).
host.iobroker-ubuntu Cannot install iobroker.js-controller@2.0.25: 243
root@iobroker-ubuntu:/opt/iobroker# from @1.5.14 to @2.0.25Update js-controller                          from @1.5.14 to @2.0.25
from: can't read /var/mail/@1.5.14
`

**Comment by Apollon77** [comment]
Please read info in forum! Use installation fixer to correct permissions and retry please.
