### ISSUE TITLE
Add error handling for json parse to lua scripts

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#504]

**Comment by Apollon77** [comment]
simple solution implemented (checks for "" and such). Prevent parsing error is needed too

**Comment by GermanBluefox** [comment]
https://stackoverflow.com/questions/16912606/how-to-capture-error-message-from-third-party-library-in-lua

**Comment by Apollon77** [comment]
I also found that article :-) so the "protected mode" seems to be the way to go

**Comment by foxriver76** [comment]
protected call is now implemented in lua scripts
