### ISSUE TITLE
Upgrade self: check exit code of npm

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.js-controller#505]
See https://forum.iobroker.net/topic/25759/pi4-l%C3%A4sst-js-kontrolle-nicht-updaten/21

npm update fails, but js-controller still thinks it succeeded: 
```
Host "iobrocker" (linux) updated
```

**Comment by Apollon77** [comment]
Do we know the exit code of npm in such cases? We mainly know that 0 and 1 are ok... this could be checked

**Comment by AlCalzone** [comment]
Sadly no...

**Comment by Apollon77** [comment]
maybe he can execute npm manually and get exitcode via shell?

**Comment by AlCalzone** [comment]
npm is working now, was some kind of cache issue

**Comment by GermanBluefox** [comment]
Close?

**Comment by Apollon77** [comment]
No, npm return code is still not checked.  So success message is maybe wrong.
