### ISSUE TITLE
Problems js-controller 2.x with justgage adapter 1.0.0

### ISSUE THREAD

**Issue by MK-66** [ioBroker/ioBroker.js-controller#513]
With js-controller 2.x justgage adapter 1.0.0 got problems with min, mid, max values. These values are always scaled from 0 to 100. With js-controller 1.15.14 justgage 1.0.0 worked fine, no problems at all.

I updated therefor justgage adapter to 1.0.1, the problems with min, mid, max values were fixed, But unfortunately in this version new problems occur: All entries in property layout/color will be ignored, e.g. Farbe 2, Farbe 3, Mitte Farbe 1+2, Mitte Farbe 2+3, Haken bei kein Farbverlauf, Ende Sektor 1, Ende Sektor 2 does not work anymore, have no effect. (ref. also issue from RK62)

Maybe the bug with the min, mid, max values can be fixed in js-controller 2.x, to use justgage adapter stable version 1.0.0 furthermore or the other bugs in justgage 1.0.1 can be fixed?

I use justgage widgets in many of my vis views and therefore it´s not possible for me to upgrade to latest js-controller 2.x or upgrade justgage to 1.0.1, I have to stay on 1.15.14 and 1.0.0. I already posted an issue on github – justgage adapter too.

(System: Debian Buster, nodejs 10.17.0, js-controller 2.0.35, vis 1.2.1, all adapters up to date)

Thanks for your great work at all !!!

**Comment by Apollon77** [comment]
Please open this issue in justgage!
