### ISSUE TITLE
Redis error:Error: Invalid Chunk: parse failed

### ISSUE THREAD

**Issue by sissiwup** [ioBroker/ioBroker.js-controller#514]
No Redis but Error
`host.zotac	2019-10-25 19:23:23.054	error	States 127.0.0.1:34146 (Init=false) Redis error:Error: Invalid Chunk: parse failed
host.zotac	2019-10-25 19:23:22.330	error	States 127.0.0.1:34122 (Init=false) Redis error:Error: Invalid Chunk: parse failed`

redis-cli works on the machine

**Comment by GermanBluefox** [comment]
Some old slave or "zombie" instance is running. Can you check it please?
If multihost, so check all your slaves. If no multihost, so restart your PC

**Comment by Apollon77** [comment]
You can also try to use the port info in the log (:xxxx) and 

sudo netstat -tulpn

Um zu schauen welcher Prozess es ist
