### ISSUE TITLE
Validity time of self-signed SSL certificates

### ISSUE THREAD

**Issue by jpawlowski** [ioBroker/ioBroker.js-controller#515]
The self-signed ioBroker certificate that it will generate during initial start is no longer compatible with iOS13 and macOS Catalina devices:

https://support.apple.com/en-us/HT210176

This means certificates in general cannot have a validity period longer than 825 days.
The self-signed certificate for ioBroker should take this into consideration to make the pre-generated certificate usable once again.

**Comment by Stabilostick** [comment]
@jpawlowski 
Thank you for this information. I'm trying to comment in italics right in the reqirement documentation from Apple (see link above):

"All TLS server certificates must comply with these new security requirements in iOS 13 and macOS 10.15:

- TLS server certificates and issuing CAs using RSA keys must use key sizes greater than or equal to 2048 bits. Certificates using RSA key sizes smaller than 2048 bits are no longer trusted for TLS.
_Beginning with js-controller 1.5.14 RSA (2048 Bits) is used as key size._ 

- TLS server certificates and issuing CAs must use a hash algorithm from the SHA-2 family in the signature algorithm. SHA-1 signed certificates are no longer trusted for TLS.
_The hash algorithm is sha-256 from the SHA-2 family._

- TLS server certificates must present the DNS name of the server in the Subject Alternative Name extension of the certificate. DNS names in the CommonName of a certificate are no longer trusted.
_The X509v3 Subject Alternative Name is generated as "DNS:<DNS name of ioBroker server>"_

Additionally, all TLS server certificates issued after July 1, 2019 (as indicated in the NotBefore field of the certificate) must follow these guidelines:

- TLS server certificates must contain an ExtendedKeyUsage (EKU) extension containing the id-kp-serverAuth OID.
_TLS Web Server Authentication with OID 1.3.6.1.5.5.7.3.1 is included in an X509v3 Extended Key Usage extension._

- TLS server certificates must have a validity period of 825 days or fewer (as expressed in the NotBefore and NotAfter fields of the certificate).
_For new generated certificates the validity period will be reduced from five to two years._

Connections to TLS servers violating these new requirements will fail and may cause network failures, apps to fail, and websites to not load in Safari in iOS 13 and macOS 10.15."

**Comment by jpawlowski** [comment]
Thanks, @Stabilostick! :-)
Personally would have set it to 825 right away  but 730 for sure is okay as well.
(I guess Apple thoroughly chose to go slightly above the year limits because they pretty well know how it usually goes in enterprises, missing those exact dates. So they added 3 month on top of it + a few more days because of 30/31 days variances and +1/+2 more days for highest escalation level. Typical for big companies inefficiencies... ;-))
