### ISSUE TITLE
js-controller will be updated at iobroker upgrade

### ISSUE THREAD

**Issue by simatec** [ioBroker/ioBroker.js-controller#518]
currently the js-controller is also updated via the command "iobroker upgrade".
This was previously only possible with "iobroker upgrade self"

**Comment by Apollon77** [comment]
seems wanted ... as designed ...

**Comment by AlCalzone** [comment]
> seems wanted ... as designed ...

Then how do we only update the adapters? A js-controller update should IMO be done on purpose, not as a side-effect.

**Comment by Apollon77** [comment]
good question. In fact I checked code back down to 1.4 and it was the same there ...

**Comment by Apollon77** [comment]
We could change it in 2.0 ... no problem ...

**Comment by GermanBluefox** [comment]
Ok. lets change it. `iobroker upgrdade all` => only adapters
