### ISSUE TITLE
alias.0 and getForeignStates() problem

### ISSUE THREAD

**Issue by algar42** [ioBroker/ioBroker.js-controller#520]
It looks like for new alias.0 object the getForeignStates function return target ID in result, but not the ID of state from alias.0. 

e.g. for object

`{
  "_id": "alias.0.house.cabinet.lights.light.ceil.Brightness",
  "type": "state",
  "common": {
    "name": "Яркость",
    "role": "level.brightness",
    "type": "number",
    "read": true,
    "write": true,
    "desc": "Manually created",
    "def": 0,
    "unit": "%",
    "alias": {
      "id": "ham.1.0x0000000008023ea7.0x0000000008023ea7.Brightness"
    }
  },
  "native": {},
 .........
  }
}`
when I call 
`getForeignStates('alias.0.house.cabinet.lights.light.ceil.Brightness', (err, states) => {})`
in resulted states, id is returned as ham.1.0x0000000008023ea7.0x0000000008023ea7.Brightness

Is it expected behaviour? I don't think so. 
Requesting states for an object I would like to get the state of exactly the object requested, but not the referenced one. Especially taking into account that in alias.0 states can be re-calculated and type and value can differ from targed state.
it could lead to many problems with atapters that subscribes to alias.0.  E.g. lovelace does not work correctly with devices autodetected from aliases...

**Comment by Apollon77** [comment]
Which Js-Controller version?

**Comment by algar42** [comment]
2.0.39...
I did look into js-controller code and it definitely has part of code that process aliases differently.. 
I don't believe it is correct. I think that all the fuctions opened for developers should behave the same way in relation to all objects.. 
Now, say if I have an array of IDs like [{key: alias.0.xxx, val:}, {key: alias.0.yyyy, val:}] and want to get val values by keys using getforeingstates, it returns me absolutely different IDs that are not in the array. Fail :)

**Comment by Apollon77** [comment]
you are correct. we need to fix this

**Comment by algar42** [comment]
Can you please make a release with this update?

**Comment by Apollon77** [comment]
you can test from github by installion "npm i ioBroker/ioBroker.js-controller" or you wait for 2.0.40 to come in some days
