### ISSUE TITLE
alias.0 and getForeignStates() problem (...continue)

### ISSUE THREAD

**Issue by algar42** [ioBroker/ioBroker.js-controller#526]
Following issue #520. 
GetForeignstates() still works incorrect. Yes, as per #520 it now returns correct IDs in states object, but now it changes input ids array with target object IDs - it is definitely wrong. I think that function should not change input parameters. 

**Example from Lovelace adapter code**
We have the following code:
![image](https://user-images.githubusercontent.com/40002726/68541157-213b9580-03ad-11ea-8d69-df9ca04e8f1b.png)

After execution, look at the console output:
![image](https://user-images.githubusercontent.com/40002726/68541171-47613580-03ad-11ea-9941-d7b01ed2c028.png)

**Comment by Apollon77** [comment]
Please test with install from GitHub. I would include this fix in 2.1.0 that comes into stable by end of the week latest.

**Comment by algar42** [comment]
Is current git version works ok? I just can only test on my working iob instance. I have no test iob intallation :)

**Comment by Apollon77** [comment]
GitHub is as 2.0.40 with this and one other fix in there. testing is green.

**Comment by algar42** [comment]
Seems to be Ok in 2.042. thanks!
