### ISSUE TITLE
setForeignObject causes crash

### ISSUE THREAD

**Issue by Zefau** [ioBroker/ioBroker.js-controller#532]
Using `setForeignObject` causes a crash and restarted the adapter.

### Log
Adapter | Time | Log-Level | Description |
-------- | ----- | ---------- | ------------ |
host.bananapim3 | 2019-11-17 21:58:48.188 | info | instance system.adapter.owntracks.1 terminated with code 156 (156)
owntracks.1 | 2019-11-17 21:58:47.604 | info | (9098) Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
owntracks.1 | 2019-11-17 21:58:47.598 | info | (9098) terminating
owntracks.1 | 2019-11-17 21:58:47.593 | info | (9098) Adapter stopped und unloaded.
owntracks.1 | 2019-11-17 21:58:47.584 | info | (9098) Got terminate signal TERMINATE_YOURSELF
host.bananapim3 | 2019-11-17 21:58:47.577 | info | stopInstance system.adapter.owntracks.1 send kill signal
host.bananapim3 | 2019-11-17 21:58:47.543 | info | stopInstance system.adapter.owntracks.1 (force=false, process=true)

### Code
Following code causes the adapter to restart:
```js
adapter.getForeignObject('system.adapter.owntracks.' + adapter.instance, (err, obj) => {
	if (err || obj === undefined) {
		return;
	}

	//
	obj.native.locations = obj.native.locations || [];
	obj.native.locations = obj.native.locations.map(location => {
		// ...
		// some stuff
		return location;
	});

	adapter.setForeignObject(obj._id, obj);
	resolve(obj.native.locations);
});
```

Removing `adapter.setForeignObject(obj._id, obj);` for test purposes works and the adapter does not crash / restart.

**Comment by Apollon77** [comment]
The described ehaviour do not match to the log. The log simply shows a stop of the adapter by admin.

Please open the issue with the adapter ... add more logging for "err" cases, checking "obj" only to "undefined" may also not be enough.

Try to run adapter file directly on console with --debug ... sometimes this brings more logs.

**Comment by AlCalzone** [comment]
@Zefau is changing the instance object of the current adapter instance. That ALWAYS restarts the instance (like when you update adapter settings in admin). I would say working as intended.

**Comment by Apollon77** [comment]
Aaahhh ... yes ... :-) SO you need to detect if the change is really needed and only update the object when needed.

**Comment by Zefau** [comment]
Ok, thanks for clarification. 

Is there an easy possibility to change the adapter configuration given in `adapter.config` persistently?

**Comment by Apollon77** [comment]
The way is correct, but in fact this object update will do a restart. So you need to detect if your config has changed and only then set the object ...
