### ISSUE TITLE
obj type 'adapter' not set if installing adapter via octocat

### ISSUE THREAD

**Issue by BuZZy1337** [ioBroker/ioBroker.js-controller#539]
If installing an adapter via octocat button the type 'adapter' is not set for the system.adapter.NAME object..
![image](https://user-images.githubusercontent.com/6979405/69870187-5aca3700-12af-11ea-8c4b-940ed08569eb.png)
...
https://github.com/ioBroker/ioBroker.js-controller/blob/10ee8398684e6b4fe57dfd03507c247964249617/lib/setup/setupInstall.js#L627

.....

Thats why the custom sendto blocks dont appear in the blockly editor..
(https://forum.iobroker.net/post/332448)
Because type !== 'adapter' and then the function for loading custom blocklys just continue;
(See:
https://github.com/ioBroker/ioBroker.javascript/blob/ab112daf52f6af049f5d5223695f47341438d256/src/src/Components/BlocklyEditor.js#L92 )

**Comment by Apollon77** [comment]
@GermanBluefox This is done too in 2.2, or ?!

**Comment by GermanBluefox** [comment]
Fixed
