### ISSUE TITLE
Upgrade all should not do major Upgrades 

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#540]
Major upgrades normally do have breaking changes in some way. 

Upgrade all should not do them to avoid unwanted changes. 

It could be allowed using a force parameter. 

At the end of upgrade all we should tell the user if upgrades were skipped because of this.

**Comment by AlCalzone** [comment]
YES, YES, YES!

**Comment by AlCalzone** [comment]
Also, should `iobroker upgrade <adaptername>` ask before doing a major upgrade?

**Comment by Apollon77** [comment]
together with #541 we would havw a "key press" anyway, so it could be canceled too, or?

**Comment by AlCalzone** [comment]
I'm thinking of something like in apt-get:
```
<short explanation of the problem>. Do you want to continue (y/N)?: _
```
1. User presses <kbd>ENTER</kbd>, no is selected, installation canceled
1. User enters `n` or `N`, presses <kbd>ENTER</kbd>, installation is canceled
1. User enters `y`, `Y`, `j` or `J`, presses <kbd>ENTER</kbd>, installation continues

**Comment by Apollon77** [comment]
Yes ... this is an active question ... maybe makes sense for major updates ?! But minor/micro?

**Comment by AlCalzone** [comment]
I would only do that for major updates. We could also go 1-2 steps further and build a selection for the user with [enquirer](https://github.com/enquirer/enquirer) (like we have in create-adapter):
```
There are multiple possible updates from your current version (v1.4.2). Which one would you like to perform?
> 1.5.17: only bugfixes and/or new features, no breaking changes
> 2.1.4: update to the newest version, with breaking changes
```

**Comment by Apollon77** [comment]
... also dafür gibts Admin :-)

**Comment by AlCalzone** [comment]
Ich denke nur an zwei Optionen, die klar kommuniziert werden. Non major und major update

**Comment by foxriver76** [comment]
Ich würde fast sagen, da wir mit #541 immer fragen mit changelog, wenn es vom tty ausgeführt wird und ohne force, dass wir es uns da sparen können? Sprich wenn kein tty, also admin und somit nicht gefragt wird, dann skippe und logge, das major des adapter geskippt wurde, wenn jedoch kein tty und force flag, dann upgrade trotzdem, somit halten wir usern die das wirklich wollen nach wie vor offen alles zu upgraden.

Also wenn kein tty und kein force und es ist major upgrade: skip
sonst upgrade durchführen bzw die frage stellen

**Comment by Apollon77** [comment]
Ack. bei tty vllt eine extra "Achtung: Dies ist ein major upgrade" Zeile?
