### ISSUE TITLE
Show „combined changelog“ when upgrading adapter

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#541]
We should show a combined Changelog like in admin also on upgrades on command line. 
For Single upgrades we also might wait for a key press before continuing (could be overwritten by a force parameter). 

We need to make sure not to break updating from admin because if this (so maybe without the keypress :-( )

**Comment by AlCalzone** [comment]
> We need to make sure not to break updating from admin because if this (so maybe without the keypress :-( )

Node.JS can test if stdout/stdin are TTYs. If so, we're on the console. If not, we're in the admin.

**Comment by foxriver76** [comment]
Or handle it with an extra parameter like `apt` where `apt upgrade -y` skips the need of a manual confirmation.
