### ISSUE TITLE
Add for delObject the recursive flag

### ISSUE THREAD

**Issue by GermanBluefox** [ioBroker/ioBroker.js-controller#547]
extend adapter.delObject/adapter.delForeignObject with recursive flag to delete all underlying objects: e.g.
```
adapter.delObject('channelName', true)
```
Will delete "channelName", "channelName.state1" and "channelName.state2".

**Comment by Apollon77** [comment]
@GermanBluefox this was done already, or ?! I can find code in adapter.js L2576+ ?!

If yes we should add a featureflag and documet it in 2.2 changelog!!

**Comment by GermanBluefox** [comment]
Done

**Comment by klein0r** [comment]
Because this was the first google match: The correct way to delete objects recursive is:

```adapter.delObject('channelName', {recursive: true})```
