### ISSUE TITLE
iobroker does not run after the restore of a redis/redis system

### ISSUE THREAD

**Issue by simatec** [ioBroker/ioBroker.js-controller#550]
Today I set up a new test system and performed a restore of a Redis/Redis system. The new system was before the restore file/file.
I found out that iobroker does not work anymore, because after that the new system is redis/redis directly and the Redis database is missing.
If I make a restore of the old database in advance and then the iobroker restore, the system runs without problems

**Comment by Apollon77** [comment]
Yes, verified ...
* the dbConnect takes place immediately after start of "restore" command
* then this DB is cleared out
* then config file gets written (which may contain a different db config! But no reconnect or such happens
* then restore happens

@GermanBluefox The fix of this would be some kind of behaviour change and may have big (negative/unawaited) effects if someone restores a slave (why ever he shoukd do it ... but ...)

**Comment by GermanBluefox** [comment]
Yes, we must to change the order and object.json behaviour

**Comment by Apollon77** [comment]
Changing the order is easy but what about the risk to restore to a master from a slave or such? Handle that via a "question " as soon as it is not master better ask the user if he reqlly want to restore there or such?)
