### ISSUE TITLE
Restart Controller via "restart" command/Admin does kill - 9 immediately

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#561]
... so no clean restart, but a "kill" of all adaptersd and controller. This has the efefct that e.g. "History" data are not stored

**Comment by AlCalzone** [comment]
Is this fixed by https://github.com/ioBroker/ioBroker.js-controller/commit/730e794a56e39aad1a00a335dc52d532525063be or is it a separate issue?

**Comment by Apollon77** [comment]
No different story.

**Comment by Apollon77** [comment]
We should introduce a "restartHost" command in main.js and trigger this then from Admin (I think admin now executes a cmdExec for the restart script directly. with this the controller is bypassed and all proesses get a kill .9 immediately

**Comment by AlCalzone** [comment]
Can we not just execute `iobroker restart` from admin?

**Comment by foxriver76** [comment]
https://github.com/ioBroker/ioBroker.admin/blob/6aeadeb83294db451b936c046bbcf84df92cad8e/src/js/adminHosts.js#L108 calls https://github.com/ioBroker/ioBroker.js-controller/blob/7f0897339b3794488bbeeb67c46ec9df6ea4f979/lib/setup.js#L2098 and ends up calling a `restart.js` which seems to be non-existing anymore. The normal `restart` cli command executes https://github.com/ioBroker/ioBroker.js-controller/blob/7f0897339b3794488bbeeb67c46ec9df6ea4f979/lib/cli/cliProcess.js#L179 and thus seems to be appropriate for a clean restart.

**Comment by Apollon77** [comment]
The clip command is one option. But controller also has restart logic used internally eg when databases are gone. So it would be easy to just do the Same. Basically calling stop method internally.

**Comment by Apollon77** [comment]
codse here because fix is in admin
