### ISSUE TITLE
Erweiterung Alias Funktionalität im Hinblick auf HM-Ip Geräte (Separate ID für Read und Write)

### ISSUE THREAD

**Issue by HMMike** [ioBroker/ioBroker.js-controller#565]
Gerade für HM-IP geräte würde sich eine Funktionale Erweiterung der Alias Funktionalität anbieten:
Diese Geräte haben einen separaten Datenpunkt für z.B. Dimmwert (beispielsweise in Kanal 3)
und einen separaten Datenpunkt zum setzen eines Dimmwertes (beispielsweise Kanal 4)

Gut wäre in diesem Zusammenhang die Möglichkeit, nicht nur eine read / write funktion zum konverteren angeben zu können sondern die optinale Möglichkeit, eine aliasID für einen ReadDP und einen aliasDP für einen WriteDP anzugeben.

Ich nutze diese Möglichkeit heute schon in meinem eigenen Wrapper-Script,  welches die Möglichkeit vorsieht, unterscheidliche Datenpunkte für read und write anzugeben.

Damit wäre es dann auch möglich, "normale" Widgets z.B. Für Lampen an diesen AliasDP anzubinden, wibei dieser AliasDP sich dann  den Istzustand aud dem readAlias holen würde und bei Änderung den Write Alias beschreiben würden.

Black

**Comment by AlCalzone** [comment]
Wäre auch für Z-Wave 2 gut, da dieses bei bestimmten Kommandoklassen z.B. `targetValue` und `currentValue` hat.
