### ISSUE TITLE
The options parameter in adapter.getObjectList is not optional.

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.js-controller#574]
https://github.com/ioBroker/ioBroker.js-controller/blob/5789680d49ded32291ccf86ee93776a2bee9fee9/lib/adapter.js#L2088

It used to be optional in `adapter.objects.getObjectList`. I think we should make it optional again.

@GermanBluefox @Apollon77 

Edit: To be more clear, this is the offending line:
https://github.com/ioBroker/ioBroker.js-controller/blob/5789680d49ded32291ccf86ee93776a2bee9fee9/lib/adapter.js#L2090

The code in objects correctly handles the optional parameters.

**Comment by Apollon77** [comment]
Häää?

```
        this.getObjectList = (params, options, callback) => {
            if (!this.objects) { // if objects is no longer existing, we do not need to unsubscribe
                callback && callback('Objects database not connected');
                return;
            }

            this.objects.getObjectList(params, options, callback);
        };

```
