### ISSUE TITLE
Remove local usage of Objects/State Server and replace by client classes

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#583]
Currently we have some duplicate code because of the fact that states/objectsInRedis is used by all adapters, but Server class offers the same functionality too and is used by CLI and js-controller (when file DB) locally.

Goal is to remove all unneeded logic and clearly separate "DB Server" and "clients". So also in CLI case a Server is started and then a "*InRedis"-client connects to it.
The overhead should be minimal ... but code much more clean

**Comment by foxriver76** [comment]
done? @Apollon77

**Comment by Apollon77** [comment]
yes
