### ISSUE TITLE
Feature Request: Check argument of `setState` if it is a valid state object

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.js-controller#584]
Related to https://github.com/AlCalzone/node-zwave-js/issues/527
The state object had type `number`, but the adapter (wrongly) passed an object to `setState`. I wouldn't have noticed without looking at the log files.

IMO, we should check if the passed object is a valid state object instead of assuming it is. This means:
- [ ] Are there any required properties missing?
- [ ] Are there properties in the state object that should not be there?

In that case we should probably return an error, but at least warn in the log (like the JS adapter does).

**Comment by foxriver76** [comment]
Should we also validate `min/max` attributes, which means an error will be logged if `max` is `100` and someone sets `105`? Currently `min/max` is mainly used for visualizations and iot, what about respecting it on controller level, is this desirable?

**Comment by AlCalzone** [comment]
> Currently `min/max` is mainly used for visualizations and iot

And admin - basically it prevents users from entering wrong data.

Regarding your question I would say no. The adapters are responsible for their own states and should know better than setting an invalid value. We cannot expect the same from users.

**Comment by Apollon77** [comment]
we could allow something like an "adapter strict mode" enabled in io-package and then the adapter class repects such like values < min are corrected to min, same for max, step repected, read/write respected and such ... to have it as convenient function for devs ... but optional

**Comment by foxriver76** [comment]
> > Currently `min/max` is mainly used for visualizations and iot
> 
> And admin - basically it prevents users from entering wrong data.

AFAIK Admin does not validate entered user data wrt min and max values.

Sou you mean we can expect devs to respect min max by theirselves but not the data type?

**Comment by AlCalzone** [comment]
This issue is about ensuring that nothing breaks when developers make a mistake in the object definition. A number that is too large  won't break iobroker.

Regarding admin: you're right! I was sure that min /Max was respected in admin. Did that change with admin 3 maybe?

**Comment by foxriver76** [comment]
I guess it would still be a helpful hint for some devs, making them notice that their set values are not matching their defined range for number values. Maybe, as @Apollon77  said as a special option, which you can pass on initialization of the adapter.

Admin: I don't know for sure, according to Changelog there is nothing that changed wrt to this. But when I started using ioBroker, admin3 was already out..

**Comment by AlCalzone** [comment]
Yes, I wouldn't want to annoy devs who make the "mistake" on purpose. But maybe I'm too paranoid and there is never a reason to set a value outside min/max...

**Comment by AlCalzone** [comment]
I just noticed we were talking about two different things. This issue is about the object argument to `setState`, e.g. `{val: "foo", ack: false}`, not the object definition in `setObject`.

**Comment by foxriver76** [comment]
Not 100 % sure, I thought you wanted to validate if the `val` passed to `setState` matches the type which is defined in its corresponding object (`common.type`). Thus, I came up with respecting other `common` properties of the corresponding object.

**Comment by AlCalzone** [comment]
Oh, that is a good point. But I was one step earlier in the logic. See #695 for details.

**Comment by foxriver76** [comment]
I really like the idea provided in your PR. And yes, then we were really talking about two different things.
