### ISSUE TITLE
Feature Request: add fileExists method to test if a file exists in the objects DB

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.js-controller#588]
Maybe also `directoryExists`, since we have the mkdir and readDir methods already?

**Comment by Apollon77** [comment]
In Fact Directories only "exist" as soon as there is minimum one file. so checking for that is tricky. And also Directories are created automatically as soon as a file is put there. So mkdir is not really needed before (but possible).
So maybe more an "isDirectoryEmpty" method or such?

**Comment by Apollon77** [comment]
And we also need to consider Rights here!
Does the File exists when you do not have needed rights to access it? Same for Directory (problem here is that dirs do not have rights at all - only the files in the dirs are considered ...)

**Comment by Apollon77** [comment]
For fileExists the method "checkFile" from objectsInRedis class could be used.
Singanture: 

```
checkFile(id, name, options, flag, callback)
```

Callback:
* on Error: callback(true, options)
* no error: callback(false, options, fileOptions)
Means "options" are passed through and can be ignored.

In fileOptions the file Metadata are returned (success) OR is {"notExists": true} (not exists). Error parameter true means "permissionError".

In fact using this would be using an internal methods ... normally not thought for external use ... but would be ok in this case I think ...

**Comment by Apollon77** [comment]
Thought again: I would make optimized methods in objectsInRedis lib first. ... but be should discuss the questions above for permission topics

**Comment by AlCalzone** [comment]
> And also Directories are created automatically as soon as a file is put there.

Ok I think my issue was more to determine whether the dir needs to be created. Although I'm not sure - it has been a while.
