### ISSUE TITLE
writeFile does not correctly sanitize Windows path separators, `iob rm` hangs indefinitely

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.js-controller#589]
I accidentally wrote a file using `adapter.writeFile` that had a Windows path separator `\` instead of `/`. This lands as-is in the files DB:
```
$ ./iob.bat list files zwave2.0

C:\iobroker>node node_modules/iobroker.js-controller/iobroker.js list files zwave2.0

-- zwave2.0 --
   Modified at  |Permission|     User     |     Group    | Size | Name
----------------+----------+--------------+--------------+------+---------
                 d?????????                                      zwave2.0/cache/
2020-01-04 13:48 -rw-r--r--          admin  administrator   1834 zwave2.0/cache\f6bda625.json
```

Furthermore, the `rm` command hangs indefinitely
```
$ ./iob.bat rm "zwave2.0/cache\\f6bda625.json"

C:\iobroker>node node_modules/iobroker.js-controller/iobroker.js rm zwave2.0/cache\f6bda625.json
[ nothing happens here]
```

**Comment by foxriver76** [comment]
Sanitize path only replaces backslashs if the file name contains `..` https://github.com/ioBroker/ioBroker.js-controller/blob/555cadfc7302b8ec48378739517e6443b419f9a6/lib/objects/objectsUtils.js#L483

What is the logic here, why not just replace it everytime @Apollon77?

**Comment by Apollon77** [comment]
I think this is basically because the intal storage paths are unix style by default, so mixing "was naver supposed to work". The sanitize mainly converts it to prevent "path attacks" when coming via web adapter or such.

But yes it makes sense to do it for the name in general. But if we change that we also need to make sure to add it to that correction logic here https://github.com/ioBroker/ioBroker.js-controller/blob/555cadfc7302b8ec48378739517e6443b419f9a6/lib/objects/objectsInMemFileDB.js#L152 to make sure data are consistent then

**Comment by Apollon77** [comment]
@AlCalzone Can you please retest if this still happens with latest 3.0 on GitHub?

**Comment by AlCalzone** [comment]
I'm not sure, I don't get that far :)
![grafik](https://user-images.githubusercontent.com/17641229/78369893-33210d80-75c6-11ea-85c2-7117119507f6.png)

**Comment by AlCalzone** [comment]
Update: The file is there, `iob list files zwave2.0` doesn't show it. And the path in _data.json still contains a backslash.
![grafik](https://user-images.githubusercontent.com/17641229/78370676-4385b800-75c7-11ea-9510-a50a8d63cd6a.png)

**Comment by Apollon77** [comment]
Can you please log the "err" in setupList.js line 167? An error seems to happen and it is not cated ... but question is what the error says

**Comment by foxriver76** [comment]
Its `cannot read property lenght of undefined`. However, when I use my local objects-redis version it works. So it seems like something is wrong in the published version?

**Comment by AlCalzone** [comment]
Line 166: `adapter === '0_userdata.0', path === ''`
Line 167: `err === 'not exists'`.

**Comment by Apollon77** [comment]
The code is mainly checking wrong:

            if (err && err.code === 'ENOTDIR') {

This is only happening when you do that while iobroker is not running (because ObjectsInMemFileDB.js is used) and the "else" case is not checking for Error.

As soon as ioBroker is running the objects lib is used and this NEVER created a err.code ENOTDIR :-(

But @AlCalzone what 0_uderdata.0 hat to do with your zwave2 query from above?

**Comment by Apollon77** [comment]
Please try GitHub controller again (objects lib 3.1.1)

**Comment by AlCalzone** [comment]
> what 0_uderdata.0 hat to do with your zwave2 query from above?

This comes when I just execute `iob list files` (the command that throws an error).
the zwave2 query runs but is just empty

**Comment by Apollon77** [comment]
And is it correct that it is empty?

**Comment by AlCalzone** [comment]
Not after I wrote a file in the name space zwave2.0

**Comment by foxriver76** [comment]
Is the zwave2.0 namespace of type `meta`? @AlCalzone

**Comment by Apollon77** [comment]
> Is the zwave2.0 namespace of type meta? @AlCalzone

I could ne see any in io-package being created ...

**Comment by AlCalzone** [comment]
No, I am not planning on using writeFile in production, I found the issue when I used it though.

**Comment by Apollon77** [comment]
So id Meta object created in your system or not??

**Comment by AlCalzone** [comment]
![grafik](https://user-images.githubusercontent.com/17641229/78529006-fed56900-77e0-11ea-950e-b7d113ea51aa.png)
Doesn't seem like it. Should it?

**Comment by Apollon77** [comment]
exactly and thats why it is "as designed" that list files is not showing it :-)

**Comment by AlCalzone** [comment]
Hm, where is this behavior documented? The comment on adapter.js -> writeFile does not mention anything about meta objects.

Nonetheless, its only the / vs \ issue now.
