### ISSUE TITLE
Add a force flag to "iobroker update" to bypass hash check

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#595]
...for cases where repo is invalid

**Comment by AlCalzone** [comment]
Should this be done regularly (like every 7 days) so [users with persistent problems ](https://github.com/ioBroker/ioBroker.zwave/issues/99#issuecomment-571934676) at least get an updated repo after a while?

**Comment by Apollon77** [comment]
The hash works in 99,999% of the cases. I  think a force param is enough

**Comment by AlCalzone** [comment]
Well, technically...
we have 2 users in the forum reporting the same issue, so that's about 2/32000 failure rate or 99.99375% success rate :smiling_imp:
And we don't know how many users don't know they have this problem or don't report it ;)

**Comment by gaudes** [comment]
Hi,
as written in forum, I had no hash-value.

Full info here:
https://forum.iobroker.net/topic/26440/probleme-nach-zwave-update-mit-zme_wallc-s/58

Regards, Ralf
