### ISSUE TITLE
`iobroker update` never updates if hash is missing

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.js-controller#596]
Given the following situation:
`system.repositories`
-> `native.repositories.<reponame>.json` is a valid object
-> AND `native.repositories.<reponame>.hash` is missing

the command `iobroker update` and the button in the admin download the updated hash from the server and store it, but **DO NOT** update the repo object, so the versions stay old.

This can be reproduced the following way:
1. Edit `system.repositories`
2. delete the `hash` property from a repo
3. in the same repo, edit the version of an adapter (in `json`)
4. `iobroker update`, notice that the version is unchanged
5. `iobroker update`, notice that ioBroker won't download the new repo file and the version is still unchanged.

**Comment by Apollon77** [comment]
@GermanBluefox checked the code and the effects and everything is as designed ... I also tried to reproduce with 2.2.7 but was not able to do that. I deleted "hash" from my repo object as described above. AN iobroker update added the hash and updated the object. Everything great.

It is important currently to do an "iobroker update" after switching the repo!!

**Comment by AlCalzone** [comment]
Then I need to do another check... Maybe I can debug it myself over the weekend.
As I wrote in the repro: I did `iobroker update` twice with different (but wrong) outcomes.
