### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by meldau** [ioBroker/ioBroker.js-controller#600]
Page https://www.iobroker.net/#de/documentation/config/cli.md mentioned in https://github.com/ioBroker/ioBroker.js-controller/blob/master/README.md#command-line-interface is hwoing a white page

**Comment by foxriver76** [comment]
the link is correct, but the documentation is broken in this markdown file

```
DOMException: "String contains an invalid character" react-dom.production.min.js:196:194
    React 5
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    unstable_runWithPriority scheduler.production.min.js:18
    React 6
    value Markdown.js:477
    value Markdown.js:498
```

**Comment by foxriver76** [comment]
Opened up the issue in docs repo, where it belongs.
