### ISSUE TITLE
Continuous logging in millisecond intervals

### ISSUE THREAD

**Issue by Mauflo** [ioBroker/ioBroker.js-controller#604]
I updatet the Hue Adapter from 2.5.0 to 3.0.1. (It runs in Compact Mode) The Problem was, that i had NodeJS 8.x installed on my Server. But the Hue Adapter 3.0.1 needs the Version of NodeJS 10.x. It should Log once that there is the wrong Version of NodeJS and stop the adapter. But it continuos in sending that info, stop and start the adapter. So the System is not longer usable, because of continious logging in millisecond intervals. So i got continuous logging in millisecond intervals with following lines:
`
  | 2020-01-10 17:05:36.765  - ^[[33mwarn^[[39m: host.ioBroker startInstance hue.0: instance disabled because of node.js version mismatch
-- | --
  | 2020-01-10 17:05:36.794  - ^[[33mwarn^[[39m: host.ioBroker.compactgroup1 startInstance hue.0: required node.js version >=10, actual version v8.15.0
  | 2020-01-10 17:05:36.822  - ^[[33mwarn^[[39m: host.ioBroker startInstance hue.0: required node.js version >=10, actual version v8.15.0
  | 2020-01-10 17:05:36.819  - ^[[33mwarn^[[39m: host.ioBroker.compactgroup1 startInstance hue.0: required node.js version >=10, actual version v8.15.0
  | 2020-01-10 17:05:36.841  - ^[[33mwarn^[[39m: host.ioBroker startInstance hue.0: instance disabled because of node.js version mismatch
  | 2020-01-10 17:05:36.892  - ^[[33mwarn^[[39m: host.ioBroker.compactgroup1 startInstance hue.0: required node.js version >=10, actual version v8.15.0
  | 2020-01-10 17:05:36.904  - ^[[33mwarn^[[39m: host.ioBroker startInstance hue.0: required node.js version >=10, actual version v8.15.0
  | 2020-01-10 17:05:36.919  - ^[[33mwarn^[[39m: host.ioBroker startInstance hue.0: instance disabled because of node.js version mismatch
  | 2020-01-10 17:05:36.952  - ^[[33mwarn^[[39m: host.ioBroker.compactgroup1 startInstance hue.0: required node.js version >=10, actual version v8.15.0
  | 2020-01-10 17:05:36.955  - ^[[33mwarn^[[39m: host.ioBroker startInstance hue.0: required node.js version >=10, actual version v8.15.0
  | 2020-01-10 17:05:36.971  - ^[[33mwarn^[[39m: host.ioBroker startInstance hue.0: instance disabled because of node.js version mismatch
  | 2020-01-10 17:05:37.006  - ^[[33mwarn^[[39m: host.ioBroker.compactgroup1 startInstance hue.0: required node.js version >=10, actual version v8.15.0
  | 2020-01-10 17:05:37.016  - ^[[33mwarn^[[39m: host.ioBroker startInstance hue.0: required node.js version >=10, actual version v8.15.0
  | 2020-01-10 17:05:37.067  - ^[[33mwarn^[[39m: host.ioBroker.compactgroup1 startInstance hue.0: required node.js version >=10, actual version v8.15.0
  | 2020-01-10 17:05:37.068  - ^[[33mwarn^[[39m: host.ioBroker startInstance hue.0: instance disabled because of node.js version mismatch
`
My System is a Raspberry 3B+, Modell ARMv7 Processor rev 4 (v7l), OS Linux, NPM 6.4.1, 16 instances active

**Comment by Apollon77** [comment]
Will be fixed in js-Controller 2.2. Pr exists already

**Comment by markuskobe** [comment]
Same issue fro me...do I have to update to node.js version >=10 manually, or is this the fix you mentioned
