### ISSUE TITLE
multihost del slave problem

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.js-controller#606]
i cant del a slave machine from multihost

![grafik](https://user-images.githubusercontent.com/6681528/72217424-ca2d7a80-352d-11ea-8116-7c7367f9c104.png)

**Comment by AlCalzone** [comment]
Does it work if you manually run `iobroker host remove salve2` from the CLI?

**Comment by Apollon77** [comment]
I can not reproduce it really ...
* used cli I get error that iobroker should not be running to do that; when stopped it worked
* in Admin I also get that error:

$ ./iobroker host remove tester
ERROR: Cannot execute changes on running system. Stop iobroker first.
ERROR: process exited with code 30

**Comment by Apollon77** [comment]
@arteck which host was selected in Admin on top? Maybe an host which is offline? because then it could feel like "Hanging". Plese verify this.

Else for me it is "can not reproduce" at the moment

**Comment by Apollon77** [comment]
Basically works ... still unknown why it hangs on one machine from @arteck  ... we lease issue here to monitor other cases

**Comment by Apollon77** [comment]
@arteck please retest with 3.0.4

**Comment by Garfonso** [comment]
> 
> 
> I can not reproduce it really ...
> 
>     * used cli I get error that iobroker should not be running to do that; when stopped it worked
> 
>     * in Admin I also get that error:
> 
> 
> $ ./iobroker host remove tester
> ERROR: Cannot execute changes on running system. Stop iobroker first.
> ERROR: process exited with code 30

I get the same message but the host that should be deleted is offline. So I just wanted to ask, which iobroker did you stop? Is it necessary to stop the master / all controllers? Or just the host that should be deleted (which then would not be working for me)?

If the master needs to be offline, how can a button in admin UI work at all? Shouldn't it be removed then and replaced by instructions on how to use the cli?

**Comment by twonky4** [comment]
I have the same issue. I have a master and a slave. The master is a docker container the slave was physically and is offline now. I'm in the master and want to delete the slave.

In admin and CLI it says:
`Cannot execute changes on running system. Stop iobroker first.`

I can not do `iobroker stop` in a docker container to stop the master.

**Comment by twonky4** [comment]
To workaround this I changed the file /opt/iobroker/node_modules/iobroker.js-controller/lib/cli/cliHost.js and commented the lines 86-89.

Changed from
```
 if (!isOffline) {
 	CLI.error.cannotChangeRunningSystem();
 	return void callback(30);
 }
```
to
```
// if (!isOffline) {
// 	CLI.error.cannotChangeRunningSystem();
// 	return void callback(30);
// }
```

https://github.com/ioBroker/ioBroker.js-controller/blob/4d4e103f1039c0a499b26ce896435fc22d67ff22/lib/cli/cliHost.js#L86-L89

Then I could remove the salve without stopping the master.

**Comment by Apollon77** [comment]
Why "I can not do iobroker stop in a docker container to stop the master." ??

**Comment by Apollon77** [comment]
In fact: There are reasons for that check,,so simply killing that check is completely "on your risk". You shpuld at least restar the system once now after the delete

**Comment by twonky4** [comment]
> Why "I can not do iobroker stop in a docker container to stop the master." ??

Because it says:
`iobroker controller daemon is not running`

**Comment by twonky4** [comment]
> In fact: There are reasons for that check,,so simply killing that check is completely "on your risk". You shpuld at least restar the system once now after the delete

I totally agree with you. 👍

**Comment by realwax** [comment]
![image](https://user-images.githubusercontent.com/14924590/136971323-458fce8b-76d3-48af-8809-b8a4ea8e8187.png)
Hi,
I am using buatnet/iobroker docker. After an  resetup of my master multihost on QNAP I did not specify the same hostname which led the buatnet docker container to iobroker host command. Now after getting everthing back up right I have an unwanted host in the list I get the same as above. I cannot delete it via admin as get the iobroker running message.
If I pkill in the container shell i still can't remove it.

Do have a fix/workaround?

Thank you!
