### ISSUE TITLE
Host update 2.2.8 Error log

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.js-controller#626]
Hmm .. updated hosts yesterday .. to 2.2.8 ..

host.ioBroker | 2020-01-26 08:21:43.278 | error | Caught by controller[0]:     at promise.then (/opt/iobroker/node_modules/standard-as-callback/built/index.js:19:49)
-- | -- | -- | --
host.ioBroker | 2020-01-26 08:21:43.278 | error | Caught by controller[0]:     at tryCatcher (/opt/iobroker/node_modules/standard-as-callback/built/utils.js:11:23)
host.ioBroker | 2020-01-26 08:21:43.278 | error | Caught  by controller[0]:     at client.keys  (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInRedis.js:684:17)
host.ioBroker | 2020-01-26 08:21:43.278 | error | Caught by controller[0]:     at states.getKeys (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:6811:25)
host.ioBroker | 2020-01-26 08:21:43.278 | error | Caught by controller[0]:     at initLogging (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:7114:22)
host.ioBroker | 2020-01-26 08:21:43.278 | error | Caught by controller[0]:     at Adapter.emit (events.js:198:13)
host.ioBroker | 2020-01-26 08:21:43.278 | error | Caught by controller[0]:     at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.amazon-dash/main.js:43:5)
host.ioBroker | 2020-01-26 08:21:43.278 | error | Caught by controller[0]:     at main (/opt/iobroker/node_modules/iobroker.amazon-dash/main.js:78:29)
host.ioBroker | 2020-01-26 08:21:43.278 | error | Caught by controller[0]:     at Object.exports.createSession (/opt/iobroker/node_modules/pcap/pcap.js:123:12)
host.ioBroker | 2020-01-26 08:21:43.278 | error | Caught by controller[0]:     at new PcapSession (/opt/iobroker/node_modules/pcap/pcap.js:49:39)
host.ioBroker | 2020-01-26 08:21:43.278 | error | Caught by controller[0]: Error: socket: Operation not permitted

**Comment by Apollon77** [comment]
Please use installation fixer. There are permissions broken for amazon dash.
