### ISSUE TITLE
Invalid message "Some packets could not be installed" on adapter installs

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#631]
The log from https://github.com/ioBroker/ioBroker.js-controller/blob/master/lib/setup/setupPacketManager.js#L260 is triggered for each adapter when automatically reinstalling adapers.

I checked the code but could not really see a reasbn :-(

**Comment by AlCalzone** [comment]
Please also change the message to "Some native dependencies could not be installed".

**Comment by foxriver76** [comment]
`TypeError: this.logger.info is not a function` fixed with https://github.com/ioBroker/ioBroker.js-controller/pull/656

**Comment by foxriver76** [comment]
However, there are more issues on this packet manager topic. This check https://github.com/ioBroker/ioBroker.js-controller/blob/cc287fe7f76c0ad39348bfc97dc4169abdbd834e/lib/setup/setupPacketManager.js#L61 won't work in all cases, e. g. apt-get returns a German output on my system and thus not include `options`, which leads to the check failing.

**Comment by foxriver76** [comment]
Fixed this. Another problem that occurs with `apt` is, that calls are happen parallel and thus multiple package requirements result in
`iobroker npm-install: Cannot install python3-dev: Error: Command failed: apt-get install python3-dev -yE: Sperrdatei /var/lib/dpkg/lock-frontend konnte nicht geöffnet werden. - open (13: Keine Berecht...`

It would be better to call `sudo apt-get install <pack1>, <pack2>, ..., <packN>`

**Comment by Apollon77** [comment]
Or really call sequencially ... these shoud be all promises or? Is there a way to call them after each other?

**Comment by AlCalzone** [comment]
apt-get can install multiple dependencies with one call. No need to handle it ourselves. Example from the Z-Wave adapter docs:
```
apt-get install pkg-config libudev-dev build-essential curl unzip
```

**Comment by foxriver76** [comment]
As mentioned above apt can handle it like `sudo apt-get install <pack1>, <pack2>, ..., <packN>` and `yum` can do the same.

**Comment by foxriver76** [comment]
`sudo` is missing in front of the command, because `this.sudo` is initialized with false and never changed in the whole code.
