### ISSUE TITLE
Decide about ending support for nodejs 8 with controller 2.3 (3.0?)

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#632]
Mainly (for now) because of 
* https://github.com/ioBroker/ioBroker.js-controller/pull/629
* https://github.com/ioBroker/ioBroker.js-controller/pull/628
* Nodejs 8 is eol since december 2019

**Comment by AlCalzone** [comment]
mkdirp can be replaced with fs-extra (https://github.com/ioBroker/ioBroker.js-controller/issues/497)

**Comment by AlCalzone** [comment]
Anyways..., fine with me. But we should announce it early enough.

**Comment by Apollon77** [comment]
ALso with the semver dep and the new idea to have strict mode enabled by default in installer I would say the next js-controller is nodejs 10+ only and we do it as js-controller 3.0.

Anyone against this? Please speak up till end of this week, else I merge in the PRs and we make it official

**Comment by foxriver76** [comment]
I am with you on this.

**Comment by Apollon77** [comment]
With the current semver topic it IS decided! I will change anything in master to continue as 3.0.0

**Comment by Apollon77** [comment]
done. Master is now 3.0.0
