### ISSUE TITLE
Option einbauen ob Logfiles gepackt werden

### ISSUE THREAD

**Issue by Baenker** [ioBroker/ioBroker.js-controller#633]
mit dem js-controller 2.2.8 wurde eine Funktion implementiert der Logfiles in ein Archiv packt. Die Funktion wurde eingeführt für User die iobroker auf einer sd-karte nutzen und nicht genug platz haben.

Für User die ioBroker auf Festplatte oder ssd nutzen gibt es kein Speicherproblem. Das Archiv ist umständlich für User die gerne die Logs im Fehlerfall prüfen. Deshalb wäre eine Option nett wo der User sagen kann ob die Logs gepackt werden sollen oder nicht.

Siehe Forum:

https://forum.iobroker.net/topic/28971/pl%C3%B6tzlich-logfiles-als-gz-files/25?page=2

**Comment by Apollon77** [comment]
Done by https://github.com/ioBroker/ioBroker.js-controller/commit/b3645ff7235ef131c8cd84ecf1b7512835e43859 ... Kommt in nächste Version
