### ISSUE TITLE
Introduce flexible Plugin system (with Sentry as first plugin)

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#637]
The idea is to allow the js-controller itself and especially adapters to be easiely extended by plugins. Each Plugin needs to be official approved by ioBroker core developers and will be published unter @iobroker/plugin-NAME on npm.
Some plugins will be installed automatically by js-controller package (e.g. sentry), more specific ones needs to be added to an adapter package.json when needed.

Plugins export a class that can be instanciated via "new" and gets a settings object as parameter like

```
{
    adapter: // adapter instance object,
    settings: {...} // plugin settings if specified by io-package
}
```

For easy usage plugins can be initialized automatically by declaring it with (optional) parameters in io-package like

```
{
    common: {
        plugins: {
            sentry: {
               ... // Settings here
            }
        }
    }
}
```
In this case after initiating the adapter and before calling "onReady" all so declared plugins are included (require by provided name with try catch) and an instance is created with the given parameters.
A new "getPlugin('NAME')" method in adapter will return this initiated instamce, so each plugin can define an own API on his object that can be used.

If a plugin uses timeouts or intervals the adapter is responsible to clear them, but I would prefer to disallow Timeouts/Intervals for plugins.

Open: We need to find a way that plugins can also extend the controller (e.g. planned ha-manager that also works on controller/DB level ...) ... this mainly affects the idea to have an adapter instance; would be objects and states DB objects then. Or we do this differnetly

**Comment by AlCalzone** [comment]
> If a plugin uses timeouts or intervals the adapter is responsible to clear them, but I would prefer to disallow Timeouts/Intervals for plugins.

I'm not sure this is too useful if we disallow timeouts completely or make all adapters handle the timeouts. I'd rather have the plugins handle the timeouts themselves (after all, plugins are reviewed by us). All resources can then be cleaned up by the plugin instances in a plugin unload handler.

We should think a bit more about the functionality we want to support, since this will influence how the API has to look like. Right now, I'm not sure what kind of plugins are even useful for adapters.

**Comment by Apollon77** [comment]
Ok, meaned that way: If an adapter uses a plugin that uses timeouts then the adapter need tomake sure to call e.g. "unload" on the plugin so that the plugin can clear all its timeouts ... it needs to be a trigger given. Or we define an "unload" method also for the plugins which is called from system level - maybe the better idea

**Comment by Apollon77** [comment]
Ok, rethinking some potential usecases
* Plugin constructor should get object with: his own settings and the system settings (e.g. dbs, logging ...) and can also maipulate these settings if needed and the logger object
* method "initDatabase" is called after DBs are connected and provides states and objects db objects for low level interacations -  the methods allow chargeback or return a promise to allow proper initialization with DB stuff
* method "setAdapterContext" is called when used in context of an adapter and passes the adapter object. Also here promise or callback and executioin waits for it to be finished before real adapter gets "on Ready"


Enhancement for js-controller usage of Plugins:
js-controller could also use plugins and have two ways to have them defined:
* in it's own io-package common.plugins
* in iobroker.json
Both places are checked and used on startup to initialize plugins mentioned there.


As written on Telegram I have two use cases for the Plugins:
1.) "Sentry" which plugs in to allow error reporting. It is basically the same logic in Adapter and in Controller. I has a generic part and a additional part where the DB connections are needed to get the User I of the installation. API wise it can offer an API to send "custom Messages" to the sentry instance

2.) "HA Manager" has a bit different requirements. Here the goal is to have a module which is installed and updated together with an adapter, but in the end runs in the js-controller context to add replication and sentinel (Master/SLave coordination) to the system. Idea would be to installthe module with an HA adapter and have something added to iobroker.json to activate this at start of the controller.

For now I do not have that many other ideas on use cases :-(

One idea: In the iobroker Docker project there was a discussion about "health checks". Maybe also this could be a plugin for js-controller to open a HTTP port with a status message that also checks for running status of a configurable list of adapters - but runs in context of the js-controller

**Comment by Apollon77** [comment]
One idea that came up: We could allow plugins to be disabled by the user (if this makes sense for the Plugin). or Sentry it could be a good "feature" for users :-)
Idea could be that we create control states eg at system.adapter.name.instance.plugins.pluginName as boolean. State is read on startup and plugin is not initialized if false. Same with "system.host.NAME.plugins.PluginName"

**Comment by AlCalzone** [comment]
👍🏻

**Comment by Apollon77** [comment]
BUT it is up to the plugin if it respects that flag or if it logs very loud that it is bad idea to disable it or such. But because we will only accept Plugins from @iobroker we have the code under our control
