### ISSUE TITLE
(Win10) Updated to JS 2.2.8 -> Problem with alexa and ioB log files

### ISSUE THREAD

**Issue by aleks-83** [ioBroker/ioBroker.js-controller#647]
OS: Win10 64
Node.js v10.17.0
NPM 6.11.3
admin 3.7.8
alexa 3.0.5

Since i am using windows i know that i am not supposed to update the JS controller via npm or something. I've never updated the JS controller by myself, it has always been done in the background without my assistance.

On the weekend i made the latest windows updates on my NUC (6CAYB).
Until that time my JS controller version was something like 2.1.X.
After the windows updates (and a few reboots) my JS controller version was 2.2.8.

1. Now my logfilles aren't available in admin WebIF anymore.
I can see the current few logfiles, but when i click on "download logfile" and on any date, the browser says "File D:/ioBroker/NUC/node_modules/log/iobroker.2020-02-04.log not found".
But in the explorer or via FTP i can see these logfiles, they are all there.

2. 3 adapters (email, pushover, telegram) are writing this warning message:
`adapter.getMessage is deprecated and will be removed in js-controller 2.3. Please report this warning to the developer of this adapter!`

3. From then on, my alexa adapter doesn't work anymore.
When i start the adapter, the following log lines appear:
(There are 3 or 4 slightly different messages. Appearing after (re)start of adapter)

host.NUC(NUC) | 2020-02-04 07:33:07.328 | error | instance system.adapter.alexa2.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | --
host.NUC(NUC) | 2020-02-04 07:33:07.328 | error | Caught by controller[34]: )
host.NUC(NUC) | 2020-02-04 07:33:07.327 | error | Caught by controller[33]: Module._compile (internal/modules/cjs/loader.js:778:30
host.NUC(NUC) | 2020-02-04 07:33:07.327 | error | Caught by controller[32]:
host.NUC(NUC) | 2020-02-04 07:33:07.327 | error | Caught by controller[31]: t
host.NUC(NUC) | 2020-02-04 07:33:07.327 | error | Caught by controller[30]: a
host.NUC(NUC) | 2020-02-04 07:33:07.327 | error | Caught by controller[29]:
host.NUC(NUC) | 2020-02-04 07:33:07.327 | error | Caught by controller[28]:
host.NUC(NUC) | 2020-02-04 07:33:07.326 | error | Caught by controller[28]: 3:13)
host.NUC(NUC) | 2020-02-04 07:33:07.326 | error | Caught by controller[27]: us>  (D:\ioBroker\NUC\node_modules\iobroker.alexa2\node_modules\virtual-device-sdk\lib\src\ConsolePrinter.js:
host.NUC(NUC) | 2020-02-04 07:33:07.326 | error | Caught by controller[26]: o
host.NUC(NUC) | 2020-02-04 07:33:07.326 | error | Caught by controller[25]: m
host.NUC(NUC) | 2020-02-04 07:33:07.326 | error | Caught by controller[24]: y
host.NUC(NUC) | 2020-02-04 07:33:07.326 | error | Caught by controller[23]: n
host.NUC(NUC) | 2020-02-04 07:33:07.326 | error | Caught by controller[22]: o
host.NUC(NUC) | 2020-02-04 07:33:07.326 | error | Caught by controller[21]: n
host.NUC(NUC) | 2020-02-04 07:33:07.325 | error | Caught by controller[20]: a
host.NUC(NUC) | 2020-02-04 07:33:07.325 | error | Caught by controller[19]: <
host.NUC(NUC) | 2020-02-04 07:33:07.325 | error | Caught by controller[18]: .
host.NUC(NUC) | 2020-02-04 07:33:07.325 | error | Caught by controller[17]: t
host.NUC(NUC) | 2020-02-04 07:33:07.325 | error | Caught by controller[16]: c
host.NUC(NUC) | 2020-02-04 07:33:07.325 | error | Caught by controller[15]: e
host.NUC(NUC) | 2020-02-04 07:33:07.325 | error | Caught by controller[14]: j
host.NUC(NUC) | 2020-02-04 07:33:07.325 | error | Caught by controller[13]: b
host.NUC(NUC) | 2020-02-04 07:33:07.325 | error | Caught by controller[12]: O
host.NUC(NUC) | 2020-02-04 07:33:07.324 | error | Caught by controller[11]:     at
host.NUC(NUC) | 2020-02-04 07:33:07.324 | error | Caught by controller[11]: 25:18)
host.NUC(NUC) | 2020-02-04 07:33:07.324 | error | Caught by controller[10]:    at require (internal/modules/cjs/helpers.js:
host.NUC(NUC) | 2020-02-04 07:33:07.324 | error | Caught by controller[9]:
host.NUC(NUC) | 2020-02-04 07:33:07.324 | error | Caught by controller[8]:
host.NUC(NUC) | 2020-02-04 07:33:07.324 | error | Caught by controller[7]: )
host.NUC(NUC) | 2020-02-04 07:33:07.324 | error | Caught by controller[6]: 7
host.NUC(NUC) | 2020-02-04 07:33:07.324 | error | Caught by controller[5]: 1
host.NUC(NUC) | 2020-02-04 07:33:07.323 | error | Caught by controller[4]: :
host.NUC(NUC) | 2020-02-04 07:33:07.323 | error | Caught by controller[3]: js/loader.js:692
host.NUC(NUC) | 2020-02-04 07:33:07.323 | error | Caught by controller[2]:     at Module.require (internal/modules/c
host.NUC(NUC) | 2020-02-04 07:33:07.323 | error | Caught by controller[2]: internal/modules/cjs/loader.js:585:3)
host.NUC(NUC) | 2020-02-04 07:33:07.323 | error | Caught by controller[1]: (
host.NUC(NUC) | 2020-02-04 07:33:07.323 | error | Caught by controller[0]:     at Function.Module._load
host.NUC(NUC) | 2020-02-04 07:33:07.323 | error | Caught by controller[0]:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
host.NUC(NUC) | 2020-02-04 07:33:07.322 | error | Caught by controller[0]:     at Module.load (internal/modules/cjs/loader.js:653:32)
host.NUC(NUC) | 2020-02-04 07:33:07.322 | error | Caught by controller[0]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
host.NUC(NUC) | 2020-02-04 07:33:07.322 | error | Caught by controller[0]:     at Module._compile (internal/modules/cjs/loader.js:778:30)
host.NUC(NUC) | 2020-02-04 07:33:07.322 | error | Caught by controller[0]:     at Object.<anonymous>  (D:\ioBroker\NUC\node_modules\iobroker.alexa2\node_modules\chalk\index.js:72:75)
host.NUC(NUC) | 2020-02-04 07:33:07.322 | error | Caught by controller[0]: TypeError: Cannot read property 'close' of undefined
host.NUC(NUC) | 2020-02-04 07:33:07.322 | error | Caught by controller[0]:
host.NUC(NUC) | 2020-02-04 07:33:07.322 | error | Caught by controller[0]:                                                                           ^
host.NUC(NUC) | 2020-02-04 07:33:07.321 | error | Caught by controller[0]: ansiStyles.color.closeRe = new RegExp(escapeStringRegexp(ansiStyles.color.close), 'g');
host.NUC(NUC) | 2020-02-04 07:33:07.320 | error | Caught by controller[0]: D:\ioBroker\NUC\node_modules\iobroker.alexa2\node_modules\chalk\index.js:72
host.NUC(NUC) | 2020-02-04 07:32:49.687 | info | "system.adapter.alexa2.0" disabled
host.NUC(NUC) | 2020-02-04 07:32:36.353 | info | Restart adapter system.adapter.alexa2.0 because enabled
host.NUC(NUC) | 2020-02-04 07:32:36.352 | error | instance system.adapter.alexa2.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.NUC(NUC) | 2020-02-04 07:32:36.352 | error | Caught by controller[14]:     at Module._compile (internal/modules/cjs/loader.js:778:30)
host.NUC(NUC) | 2020-02-04 07:32:36.352 | error | Caught by controller[14]: \src\ConsolePrinter.js:3:13)
host.NUC(NUC) | 2020-02-04 07:32:36.352 | error | Caught by controller[13]: lexa2\node_modules\virtual-device-sdk\lib
host.NUC(NUC) | 2020-02-04 07:32:36.352 | error | Caught by controller[12]: oBroker\NUC\node_modules\iobroker.a
host.NUC(NUC) | 2020-02-04 07:32:36.352 | error | Caught by controller[11]: bject.<anonymous> (D:\i
host.NUC(NUC) | 2020-02-04 07:32:36.352 | error | Caught by controller[10]:     at O
host.NUC(NUC) | 2020-02-04 07:32:36.352 | error | Caught by controller[10]:     at require (internal/modules/cjs/helpers.js:25:18)
host.NUC(NUC) | 2020-02-04 07:32:36.352 | error | Caught by controller[10]: der.js:692:17)
host.NUC(NUC) | 2020-02-04 07:32:36.351 | error | Caught by controller[9]:     at Module.require (internal/modules/cjs/loa
host.NUC(NUC) | 2020-02-04 07:32:36.351 | error | Caught by controller[9]: le._load (internal/modules/cjs/loader.js:585:3)
host.NUC(NUC) | 2020-02-04 07:32:36.351 | error | Caught by controller[8]:     at Function.Modu
host.NUC(NUC) | 2020-02-04 07:32:36.351 | error | Caught by controller[8]:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
host.NUC(NUC) | 2020-02-04 07:32:36.351 | error | Caught by controller[8]:  Module.load (internal/modules/cjs/loader.js:653:32)
host.NUC(NUC) | 2020-02-04 07:32:36.351 | error | Caught by controller[7]: at
host.NUC(NUC) | 2020-02-04 07:32:36.351 | error | Caught by controller[6]:
host.NUC(NUC) | 2020-02-04 07:32:36.351 | error | Caught by controller[6]: 789:10)
host.NUC(NUC) | 2020-02-04 07:32:36.351 | error | Caught by controller[5]: :
host.NUC(NUC) | 2020-02-04 07:32:36.350 | error | Caught by controller[4]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js
host.NUC(NUC) | 2020-02-04 07:32:36.350 | error | Caught by controller[4]: ternal/modules/cjs/loader.js:778:30)
host.NUC(NUC) | 2020-02-04 07:32:36.349 | error | Caught by controller[3]:     at Module._compile (in
host.NUC(NUC) | 2020-02-04 07:32:36.349 | error | Caught by controller[3]: onymous> (D:\ioBroker\NUC\node_modules\iobroker.alexa2\node_modules\chalk\index.js:72:75)
host.NUC(NUC) | 2020-02-04 07:32:36.349 | error | Caught by controller[2]:     at Object.<an
host.NUC(NUC) | 2020-02-04 07:32:36.349 | error | Caught by controller[2]: eError: Cannot read property 'close' of undefined
host.NUC(NUC) | 2020-02-04 07:32:36.349 | error | Caught by controller[1]: Typ
host.NUC(NUC) | 2020-02-04 07:32:36.349 | error | Caught by controller[1]:
host.NUC(NUC) | 2020-02-04 07:32:36.349 | error | Caught by controller[1]:                                                                           ^
host.NUC(NUC) | 2020-02-04 07:32:36.349 | error | Caught by controller[1]: ansiStyles.color.closeRe = new RegExp(escapeStringRegexp(ansiStyles.color.close), 'g');
host.NUC(NUC) | 2020-02-04 07:32:36.349 | error | Caught by controller[1]: r\NUC\node_modules\iobroker.alexa2\node_modules\chalk\index.js:72
host.NUC(NUC) | 2020-02-04 07:32:36.348 | error | Caught by controller[0]: D:\ioBroke
host.NUC(NUC) | 2020-02-04 07:32:35.083 | info | instance system.adapter.alexa2.0 started with pid 14372
host.NUC(NUC) | 2020-02-04 07:32:05.074 | info | Restart adapter system.adapter.alexa2.0 because enabled
host.NUC(NUC) | 2020-02-04 07:32:05.074 | error | instance system.adapter.alexa2.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.NUC(NUC) | 2020-02-04 07:32:05.074 | error | Caught by controller[12]: odule._compile (internal/modules/cjs/loader.js:778:30)
host.NUC(NUC) | 2020-02-04 07:32:05.074 | error | Caught by controller[11]:     at M
host.NUC(NUC) | 2020-02-04 07:32:05.073 | error | Caught by controller[11]: k\lib\src\ConsolePrinter.js:3:13)
host.NUC(NUC) | 2020-02-04 07:32:05.073 | error | Caught by controller[10]: \node_modules\iobroker.alexa2\node_modules\virtual-device-sd
host.NUC(NUC) | 2020-02-04 07:32:05.073 | error | Caught by controller[9]: s> (D:\ioBroker\NUC
host.NUC(NUC) | 2020-02-04 07:32:05.073 | error | Caught by controller[8]:     at Object.<anonymou
host.NUC(NUC) | 2020-02-04 07:32:05.072 | error | Caught by controller[8]:     at require (internal/modules/cjs/helpers.js:25:18)
host.NUC(NUC) | 2020-02-04 07:32:05.072 | error | Caught by controller[8]: modules/cjs/loader.js:692:17)
host.NUC(NUC) | 2020-02-04 07:32:05.072 | error | Caught by controller[7]:     at Module.require (internal/
host.NUC(NUC) | 2020-02-04 07:32:05.072 | error | Caught by controller[7]:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
host.NUC(NUC) | 2020-02-04 07:32:05.072 | error | Caught by controller[6]:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
host.NUC(NUC) | 2020-02-04 07:32:05.072 | error | Caught by controller[6]: load (internal/modules/cjs/loader.js:653:32)
host.NUC(NUC) | 2020-02-04 07:32:05.072 | error | Caught by controller[5]:     at Module.
host.NUC(NUC) | 2020-02-04 07:32:05.072 | error | Caught by controller[5]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
host.NUC(NUC) | 2020-02-04 07:32:05.071 | error | Caught by controller[5]: le._compile (internal/modules/cjs/loader.js:778:30)
host.NUC(NUC) | 2020-02-04 07:32:05.071 | error | Caught by controller[4]:     at Modu
host.NUC(NUC) | 2020-02-04 07:32:05.071 | error | Caught by controller[4]: odules\iobroker.alexa2\node_modules\chalk\index.js:72:75)
host.NUC(NUC) | 2020-02-04 07:32:05.071 | error | Caught by controller[3]:     at Object.<anonymous> (D:\ioBroker\NUC\node_m
host.NUC(NUC) | 2020-02-04 07:32:05.071 | error | Caught by controller[3]: TypeError: Cannot read property 'close' of undefined
host.NUC(NUC) | 2020-02-04 07:32:05.071 | error | Caught by controller[3]:
host.NUC(NUC) | 2020-02-04 07:32:05.071 | error | Caught by controller[3]:                            ^
host.NUC(NUC) | 2020-02-04 07:32:05.071 | error | Caught by controller[2]:
host.NUC(NUC) | 2020-02-04 07:32:05.071 | error | Caught by controller[1]:
host.NUC(NUC) | 2020-02-04 07:32:05.071 | error | Caught by controller[1]: ansiStyles.color.closeRe = new RegExp(escapeStringRegexp(ansiStyles.color.close), 'g');
host.NUC(NUC) | 2020-02-04 07:32:05.070 | error | Caught by controller[1]: odules\iobroker.alexa2\node_modules\chalk\index.js:72
host.NUC(NUC) | 2020-02-04 07:32:05.070 | error | Caught by controller[0]: D:\ioBroker\NUC\node_m
host.NUC(NUC) | 2020-02-04 07:32:03.668 | info | instance system.adapter.alexa2.0 started with pid 15000
host.NUC(NUC) | 2020-02-04 07:31:33.660 | info | Restart adapter system.adapter.alexa2.0 because enabled
host.NUC(NUC) | 2020-02-04 07:31:33.660 | error | instance system.adapter.alexa2.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.NUC(NUC) | 2020-02-04 07:31:33.659 | error | Caught by controller[11]: )
host.NUC(NUC) | 2020-02-04 07:31:33.659 | error | Caught by controller[10]:     at Module._compile (internal/modules/cjs/loader.js:778:30
host.NUC(NUC) | 2020-02-04 07:31:33.659 | error | Caught by controller[10]: er.js:3:13)
host.NUC(NUC) | 2020-02-04 07:31:33.659 | error | Caught by controller[9]: D:\ioBroker\NUC\node_modules\iobroker.alexa2\node_modules\virtual-device-sdk\lib\src\ConsolePrint
host.NUC(NUC) | 2020-02-04 07:31:33.659 | error | Caught by controller[8]: ject.<anonymous> (
host.NUC(NUC) | 2020-02-04 07:31:33.659 | error | Caught by controller[7]:     at Ob
host.NUC(NUC) | 2020-02-04 07:31:33.659 | error | Caught by controller[7]:     at require (internal/modules/cjs/helpers.js:25:18)
host.NUC(NUC) | 2020-02-04 07:31:33.658 | error | Caught by controller[7]: e.require (internal/modules/cjs/loader.js:692:17)
host.NUC(NUC) | 2020-02-04 07:31:33.658 | error | Caught by controller[6]:     at Modul
host.NUC(NUC) | 2020-02-04 07:31:33.658 | error | Caught by controller[6]:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
host.NUC(NUC) | 2020-02-04 07:31:33.658 | error | Caught by controller[6]: der.js:593:12)
host.NUC(NUC) | 2020-02-04 07:31:33.658 | error | Caught by controller[5]:     at tryModuleLoad (internal/modules/cjs/loa
host.NUC(NUC) | 2020-02-04 07:31:33.658 | error | Caught by controller[5]:     at Module.load (internal/modules/cjs/loader.js:653:32)
host.NUC(NUC) | 2020-02-04 07:31:33.657 | error | Caught by controller[5]: cjs/loader.js:789:10)
host.NUC(NUC) | 2020-02-04 07:31:33.657 | error | Caught by controller[4]:     at Object.Module._extensions..js (internal/modules/
host.NUC(NUC) | 2020-02-04 07:31:33.657 | error | Caught by controller[4]:     at Module._compile (internal/modules/cjs/loader.js:778:30)
host.NUC(NUC) | 2020-02-04 07:31:33.657 | error | Caught by controller[4]: chalk\index.js:72:75)
host.NUC(NUC) | 2020-02-04 07:31:33.657 | error | Caught by controller[3]:     at Object.<anonymous> (D:\ioBroker\NUC\node_modules\iobroker.alexa2\node_modules\
host.NUC(NUC) | 2020-02-04 07:31:33.657 | error | Caught by controller[3]: ot read property 'close' of undefined
host.NUC(NUC) | 2020-02-04 07:31:33.657 | error | Caught by controller[2]: TypeError: Cann
host.NUC(NUC) | 2020-02-04 07:31:33.656 | error | Caught by controller[2]:
host.NUC(NUC) | 2020-02-04 07:31:33.656 | error | Caught by controller[2]:                                                                           ^
host.NUC(NUC) | 2020-02-04 07:31:33.656 | error | Caught by controller[2]: , 'g');
host.NUC(NUC) | 2020-02-04 07:31:33.656 | error | Caught by controller[1]: ansiStyles.color.closeRe = new RegExp(escapeStringRegexp(ansiStyles.color.close)
host.NUC(NUC) | 2020-02-04 07:31:33.656 | error | Caught by controller[1]: roker.alexa2\node_modules\chalk\index.js:72
host.NUC(NUC) | 2020-02-04 07:31:33.655 | error | Caught by controller[0]: D:\ioBroker\NUC\node_modules\iob
host.NUC(NUC) | 2020-02-04 07:31:32.412 | info | instance system.adapter.alexa2.0 started with pid 7496
host.NUC(NUC) | 2020-02-04 07:31:06.496 | info | instance system.adapter.dwd.0 terminated with code 0 (NO_ERROR)
host.NUC(NUC) | 2020-02-04 07:31:02.403 | info | Restart adapter system.adapter.alexa2.0 because enabled
host.NUC(NUC) | 2020-02-04 07:31:02.403 | error | instance system.adapter.alexa2.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.NUC(NUC) | 2020-02-04 07:31:02.403 | error | Caught by controller[6]: oader.js:778:30)
host.NUC(NUC) | 2020-02-04 07:31:02.403 | error | Caught by controller[5]:     at Module._compile (internal/modules/cjs/l
host.NUC(NUC) | 2020-02-04 07:31:02.403 | error | Caught by controller[5]:     at Object.<anonymous>  (D:\ioBroker\NUC\node_modules\iobroker.alexa2\node_modules\virtual-device-sdk\lib\src\ConsolePrinter.js:3:13)
host.NUC(NUC) | 2020-02-04 07:31:02.403 | error | Caught by controller[5]:     at require (internal/modules/cjs/helpers.js:25:18)
host.NUC(NUC) | 2020-02-04 07:31:02.402 | error | Caught by controller[5]: Module.require (internal/modules/cjs/loader.js:692:17)
host.NUC(NUC) | 2020-02-04 07:31:02.402 | error | Caught by controller[4]:     at
host.NUC(NUC) | 2020-02-04 07:31:02.402 | error | Caught by controller[4]:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
host.NUC(NUC) | 2020-02-04 07:31:02.402 | error | Caught by controller[4]:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
host.NUC(NUC) | 2020-02-04 07:31:02.402 | error | Caught by controller[4]:   at Module.load (internal/modules/cjs/loader.js:653:32)
host.NUC(NUC) | 2020-02-04 07:31:02.402 | error | Caught by controller[3]:
host.NUC(NUC) | 2020-02-04 07:31:02.402 | error | Caught by controller[3]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
host.NUC(NUC) | 2020-02-04 07:31:02.402 | error | Caught by controller[3]:     at Module._compile (internal/modules/cjs/loader.js:778:30)
host.NUC(NUC) | 2020-02-04 07:31:02.401 | error | Caught by controller[3]: de_modules\chalk\index.js:72:75)
host.NUC(NUC) | 2020-02-04 07:31:02.401 | error | Caught by controller[2]:     at Object.<anonymous> (D:\ioBroker\NUC\node_modules\iobroker.alexa2\no
host.NUC(NUC) | 2020-02-04 07:31:02.401 | error | Caught by controller[2]: TypeError: Cannot read property 'close' of undefined
host.NUC(NUC) | 2020-02-04 07:31:02.401 | error | Caught by controller[2]:
host.NUC(NUC) | 2020-02-04 07:31:02.401 | error | Caught by controller[2]:                                     ^
host.NUC(NUC) | 2020-02-04 07:31:02.401 | error | Caught by controller[1]:
host.NUC(NUC) | 2020-02-04 07:31:02.401 | error | Caught by controller[1]: ansiStyles.color.closeRe = new RegExp(escapeStringRegexp(ansiStyles.color.close), 'g');
host.NUC(NUC) | 2020-02-04 07:31:02.401 | error | Caught by controller[1]: les\iobroker.alexa2\node_modules\chalk\index.js:72
host.NUC(NUC) | 2020-02-04 07:31:02.400 | error | Caught by controller[0]: D:\ioBroker\NUC\node_modu
host.NUC(NUC) | 2020-02-04 07:31:00.248 | info | instance system.adapter.alexa2.0 started with pid 40392
host.NUC(NUC) | 2020-02-04 07:31:00.015 | info | instance system.adapter.dwd.0 started with pid 824
host.NUC(NUC) | 2020-02-04 07:30:30.239 | info | Restart adapter system.adapter.alexa2.0 because enabled
host.NUC(NUC) | 2020-02-04 07:30:30.239 | error | instance system.adapter.alexa2.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.NUC(NUC) | 2020-02-04 07:30:30.239 | error | Caught by controller[12]: les/cjs/loader.js:778:30)
host.NUC(NUC) | 2020-02-04 07:30:30.239 | error | Caught by controller[11]:     at Module._compile (internal/modu
host.NUC(NUC) | 2020-02-04 07:30:30.239 | error | Caught by controller[11]: device-sdk\lib\src\ConsolePrinter.js:3:13)
host.NUC(NUC) | 2020-02-04 07:30:30.239 | error | Caught by controller[10]:     at Object.<anonymous> (D:\ioBroker\NUC\node_modules\iobroker.alexa2\node_modules\virtual-
host.NUC(NUC) | 2020-02-04 07:30:30.238 | error | Caught by controller[10]:     at require (internal/modules/cjs/helpers.js:25:18)
host.NUC(NUC) | 2020-02-04 07:30:30.238 | error | Caught by controller[10]: e.require (internal/modules/cjs/loader.js:692:17)
host.NUC(NUC) | 2020-02-04 07:30:30.238 | error | Caught by controller[9]:     at Modul
host.NUC(NUC) | 2020-02-04 07:30:30.238 | error | Caught by controller[9]:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
host.NUC(NUC) | 2020-02-04 07:30:30.238 | error | Caught by controller[9]:  (internal/modules/cjs/loader.js:593:12)
host.NUC(NUC) | 2020-02-04 07:30:30.238 | error | Caught by controller[8]:     at tryModuleLoad
host.NUC(NUC) | 2020-02-04 07:30:30.238 | error | Caught by controller[8]:     at Module.load (internal/modules/cjs/loader.js:653:32)
host.NUC(NUC) | 2020-02-04 07:30:30.238 | error | Caught by controller[8]: (internal/modules/cjs/loader.js:789:10)
host.NUC(NUC) | 2020-02-04 07:30:30.238 | error | Caught by controller[7]:     at Object.Module._extensions..js
host.NUC(NUC) | 2020-02-04 07:30:30.238 | error | Caught by controller[7]:     at Module._compile (internal/modules/cjs/loader.js:778:30)
host.NUC(NUC) | 2020-02-04 07:30:30.237 | error | Caught by controller[7]: \index.js:72:75)
host.NUC(NUC) | 2020-02-04 07:30:30.237 | error | Caught by controller[6]: Broker\NUC\node_modules\iobroker.alexa2\node_modules\chalk
host.NUC(NUC) | 2020-02-04 07:30:30.237 | error | Caught by controller[5]:     at Object.<anonymous> (D:\io
host.NUC(NUC) | 2020-02-04 07:30:30.237 | error | Caught by controller[5]: perty 'close' of undefined
host.NUC(NUC) | 2020-02-04 07:30:30.237 | error | Caught by controller[4]: TypeError: Cannot read pro
host.NUC(NUC) | 2020-02-04 07:30:30.237 | error | Caught by controller[4]:
host.NUC(NUC) | 2020-02-04 07:30:30.237 | error | Caught by controller[4]:                      ^
host.NUC(NUC) | 2020-02-04 07:30:30.237 | error | Caught by controller[3]:
host.NUC(NUC) | 2020-02-04 07:30:30.237 | error | Caught by controller[3]: g');
host.NUC(NUC) | 2020-02-04 07:30:30.237 | error | Caught by controller[2]: ansiStyles.color.closeRe = new RegExp(escapeStringRegexp(ansiStyles.color.close), '
host.NUC(NUC) | 2020-02-04 07:30:30.236 | error | Caught by controller[2]: _modules\chalk\index.js:72
host.NUC(NUC) | 2020-02-04 07:30:30.236 | error | Caught by controller[1]: :\ioBroker\NUC\node_modules\iobroker.alexa2\node
host.NUC(NUC) | 2020-02-04 07:30:30.236 | error | Caught by controller[0]: D
host.NUC(NUC) | 2020-02-04 07:30:28.497 | info | instance system.adapter.alexa2.0 started with pid 27644
host.NUC(NUC) | 2020-02-04 07:30:28.475 | info | "system.adapter.alexa2.0" enabled

**Comment by Apollon77** [comment]
1.) Please update Admin to at least 3.7.9 (did that?) If problem still exists please open Issue in Admin
2.) Please follow instructions and check the issues in the respective adapters and pot. create new issues or make sure to use newestversions. This is a warning only so no problem
3.) Strange. Plese try reinstalling alexa2 ... bt this error has nothing to do with controller

**Comment by aleks-83** [comment]
Due to other issues with my system i just reinstalled iobroker completely.
Now i am no admin 3.7.9 and JS Controller 2.1.0 and everything is working.
Will try the upgade to 2.2.8 in the next days and report if something is bad.
