### ISSUE TITLE
CLI command visdebug does change the cache.manifest file only once

### ISSUE THREAD

**Issue by armintan** [ioBroker/ioBroker.js-controller#648]
The visdebug icli command implementation reads the cache.manifest file from the iobroker.vis adapter directory (in node_modules), changes a number by incrementing it, and updates the cache.manifest file in the iobroker-data/files/vis directory. So the source is not changed and therefore the increment happens only the first time. 

Also, index.html.original an edit.html.original do not exist and hence are not copied. I do not know if this is an issue, but I saw it in some forums, that this step is required.

**Comment by Apollon77** [comment]
I transfered it :-)

**Comment by armintan** [comment]
Thank you :-)

**Comment by foxriver76** [comment]
'Problem' (at least partially) is, that we read `/opt/iobroker/node_modules/iobroker.vis/www/cache.manifest`, but write the file with incremented build number to `/opt/iobroker/iobroker-data/files/vis/cache.manifest `. When executing visdebug a second time, again the non-incremented version number is read ..
