### ISSUE TITLE
JS-Controller doesn't recognize correct admin adapter version

### ISSUE THREAD

**Issue by Diginix** [ioBroker/ioBroker.js-controller#653]
I have installed admin 4.0.1. GUI on top right and adapter list shows correct version 4.0.1. But javascript adapter dependency is supposedly not ok and it will not start.
`2020-02-09 12:14:17.681  - [31merror [39m: host.iobroker startInstance system.adapter.javascript.0: required adapter "admin" has wrong version. Installed "4.0.0", required ">=4.0.1"!`

**Comment by Apollon77** [comment]
Did you tried upload admin again and/or a restart?

**Comment by Diginix** [comment]
iobroker upload admin seems to solve it
