### ISSUE TITLE
iobroker restarts if adapter (with instance) is deleted

### ISSUE THREAD

**Issue by Garfonso** [ioBroker/ioBroker.js-controller#658]
Log: https://pastebin.com/ny5CL8zd
Admin 4.0.1

Seems to happen everytime on my system right now.
Steps to reproduce:
- install adapter
- create instance and make sure it is active
- delete adapter
- iobroker crashes with error message from log
- uninstal is not completed (admin reports that it starts to delete objects, but that is not necessarily finished)
- after iobroker restart uninstal can be started again and then completes.

if instance is not enabled, issue does not seem to happen.

**Comment by Apollon77** [comment]
Reason is that the adapter object is deleted internally already, but tries to store the kill timeout there. Needs to store kill timout differently again :-(
