### ISSUE TITLE
Replace encrypt/decrypt with a real encryption like AES-256

### ISSUE THREAD

**Issue by foxriver76** [ioBroker/ioBroker.js-controller#660]
See discussion starting at https://github.com/ioBroker/ioBroker.js-controller/issues/262#issuecomment-584343117

**Comment by foxriver76** [comment]
Currently testing this in iobroker.bring with built in crypto module in backend and built in WebCrypto. One issue I am currently facing is, that WebCrypto is undefined in Chrome on non-https sites and many users do not use https.

**Comment by foxriver76** [comment]
Probably due to the issues that we can not rely on WebCrypto, we should go for a third party lib like mentioned in https://github.com/ioBroker/ioBroker.js-controller/issues/262#issuecomment-585167719

**Comment by foxriver76** [comment]
And expose encrypt decrypt functions to adapter devs via adapter.js

**Comment by klein0r** [comment]
NodeRed has a similar approach. Maybe this will help: https://github.com/node-red/node-red/wiki/Design:-Encryption-of-credentials
