### ISSUE TITLE
Default value from io-package or state creation not used 

### ISSUE THREAD

**Issue by DutchmanNL** [ioBroker/ioBroker.js-controller#665]
Current behavior : 

Creating an object in io-package.json does not sent the default value into the object itself, meaning default value is useless now. Example : 

```
		{
			"_id": "test_auto_intervall",
			"type": "state",
			"common": {
				"role": "state",
				"name": "Intervall to run automatically tests with best-server",
				"type": "number",
				"read": true,
				"write": true,
				"def": 30,
				"unit": "minutes"
			},
			"native": {}
		}
```

Wanted behavior : def value should be used as real default, meaning the value must be present on the object until its changed by another event (currently NULL is not acceptable)

To Consider : should the default value also. be used at the expire set-state function as I can image its useful to set back to default instead of NULL

**Comment by foxriver76** [comment]
Note: https://github.com/ioBroker/ioBroker.js-controller/blob/c6b77f0cbdc75b9b46b140b734afe2b66d35d8eb/lib/setup/setupUpload.js#L688

**Comment by foxriver76** [comment]
IMO the expire topic should be a separate enhancement, also I would go for a solution where you can define the value which will be set after expire instead of the default value.

**Comment by DutchmanNL** [comment]
> IMO the expire topic should be a separate enhancement, also I would go for a solution where you can define the value which will be set after expire instead of the default value.

ageren https://github.com/ioBroker/ioBroker.js-controller/issues/667
