### ISSUE TITLE
Make sure object common properties are correct type

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#669]
We now had the first adapter that created common.name as number and this had some side effects because most code assumes correct type here. 

So we should:
A) make sure that datatypes are correct by converting them hidden to correct type OR
B) generating errors and do not accept the object creation/change when wrong

What’s better in the end?!

I would live to do B that devs see their faults ... backward compatibility wise it would by A ;-)

**Comment by Apollon77** [comment]
We need to do this at least for common.name. Which other fields might be relevant?!

**Comment by foxriver76** [comment]
Not exactly the same (there it's about states), but reminds me of https://github.com/ioBroker/ioBroker.js-controller/issues/584

In theory, but it might not be relevant to check all of them`type` has to be string, `common.role` string, `common.read/write` boolean, `def` should be type of `type`

**Comment by AlCalzone** [comment]
Let's do it in two steps. Deprecate now with a warning, throw error in the next version.
Magic conversion only leads to unexpected behavior.

**Comment by Apollon77** [comment]
Support that idea

**Comment by foxriver76** [comment]
checks will be necessary when creating instanceObjects in `adapter.js` and `setupInstall` and on basic `setForeignObject` calls via `adapter.js`
