### ISSUE TITLE
Increase Timeout time for hostinfo please

### ISSUE THREAD

**Issue by nob0dy80** [ioBroker/ioBroker.js-controller#671]
Hello,

i'm using iobroker in a multihost enviroment.
One of the host is a slow Raspberry Zero W which is handling only the Zigbee adapter (fast enough for that)
Since the Raspi Zero isnt the fastest device, the log shows multiple timeouts like this:

host.iobrokerslave | 2020-02-15 20:22:55.386 | error | cannot get getHostInfo: timeout
-- | -- | -- | --
host.iobrokerslave | 2020-02-15 20:05:53.112 | error | cannot get getHostInfo: timeout
host.iobrokerslave | 2020-02-15 19:51:46.465 | error | cannot get getHostInfo: timeout
host.iobrokerslave | 2020-02-15 19:51:46.260 | error | cannot get getHostInfo: timeout
host.iobrokerslave | 2020-02-15 18:05:41.304 | error | cannot get getHostInfo: timeout
host.iobrokerslave | 2020-02-15 17:44:03.807 | error | cannot get getHostInfo: timeout

**Comment by Apollon77** [comment]
I think the default is 5s ... what would be better?

**Comment by nob0dy80** [comment]
@Apollon77 
Not really sure about it.
i guess the npm version call makes it slow (a "npm -v" call takes about 5secs to screen the version) and i'm pretty sure that the raspi zero may be the only device that is affected in this way.

maybe we can give it a shot with 10s ? If you tell me where to make those changes i can do a test with it.

**Comment by Apollon77** [comment]
https://github.com/ioBroker/ioBroker.js-controller/blob/master/lib/tools.js#L1004

**Comment by nob0dy80** [comment]
@Apollon77 
ok 10 sec did the job.
maybe we can use this as default value in the next version.
dont see any negative consequences by increasing this???
