### ISSUE TITLE
No NPM Version in Hostinfo on armv6l

### ISSUE THREAD

**Issue by nob0dy80** [ioBroker/ioBroker.js-controller#672]
If you use a raspberry 1 or a raspberry zero, which expects a armv6l version of Nodejs and NPM, which has to be installed manually cause its not supported by the "curl -sL https://deb.nodesource.com/setup_x.x | sudo -E bash -"-command, the npm version on the hostinfo is not displayed:

https://user-images.githubusercontent.com/28686079/74594041-12aaed00-5032-11ea-9c67-0fc88cae3518.png
https://user-images.githubusercontent.com/28686079/74594198-ae892880-5033-11ea-9130-062a74e30a2a.png

**Comment by Apollon77** [comment]
And under which path it is installed ? How iobroker should see it if it is not available?

**Comment by nob0dy80** [comment]
like recommended by the developer the whole package goes to /usr/local

![image](https://user-images.githubusercontent.com/28686079/74600005-17e85600-508b-11ea-99e4-fcb5d4c73000.png)

**Comment by foxriver76** [comment]
Is this fixed by increasing the timeout?

**Comment by nob0dy80** [comment]
@foxriver76 
Good point! Forgot to take a look at this.

but yes, this issue gets fixed too after increasing the timeout time from 5 to 10 secs!
