### ISSUE TITLE
Make it impossible to delete the `system.adapter` tree / sanitize the argument to `iobroker del`

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.js-controller#675]
Found [here](https://forum.iobroker.net/topic/30281/system-adapter-gel%C3%B6scht-hilfe-erbeten/1):
![grafik](https://user-images.githubusercontent.com/17641229/74738895-13bd6380-5258-11ea-9828-2dd6d35e9958.png)

This seems to have happened because the user entered `iobroker del system.adapter.shuttercontrol` instead of just `iobroker del shuttercontrol`, and ioBroker assumed that `system` is the adapter name and `adapter` the instance number.

**Comment by Apollon77** [comment]
uuups
