### ISSUE TITLE
setState -> callback is not waiting for state change

### ISSUE THREAD

**Issue by cmartin61** [ioBroker/ioBroker.js-controller#677]
After installing 2.2.8 the callback to handle actions after setting the state is not waiting. Using the state in the callback references now the old value. Before changing the release, the new value was available in the callback.

**Comment by Apollon77** [comment]
Please show your code and describe more clearly what you mean? If you are in the scope of a script in JavaScript editor then this is the wrong place - this is be only relevant for Adapters.

**Comment by cmartin61** [comment]
what i did is something like this:

    setState(alarmstateID, 1/*active*/, function(){
        //do something when the new state is set
    })

Before update, this worked and it was very smart code to hancle async calls.

Ok - this is in the scope the JavaScript editor, so i am in the wrong place.

Sorry for my mistake and thank you for the fast response.

**Comment by Apollon77** [comment]
Also when off-topic here: Tht it worked before the update as you describe is not sure and if it worked it was "good timing".

The callback of the setState is called when the value is set in the database. But an issue for the javascript adater could help to solve the topic
