### ISSUE TITLE
check ids in getForeignState

### ISSUE THREAD

**Issue by TA2k** [ioBroker/ioBroker.js-controller#690]
I suggest to use the _fixId function also for getForeignState

**Comment by Apollon77** [comment]
Why? fixId normally makes sure to add proper namespace of local adapter if missing. getForeignState shoulkd only be used to access objects outside the adapters own namespace ...

**Comment by TA2k** [comment]
Sorry maybe fixId ist the wrong one. But when you handover undefined as an ID the Js controller will crash.

**Comment by Apollon77** [comment]
Ok so you mean error handling needs improved ;-)) got it.
