### ISSUE TITLE
Check type (and potentially min/max) of value in setState (and similar)?

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.js-controller#698]
If we were to check the type of the value in `setState` and similar methods, we could catch a bunch of errors in adapters. We could even go further and check if numeric values are within the configured min/max range.

However this could have severe performance implications because the object needs to be read every time (or cached in a reliable way).

@Apollon77 @GermanBluefox Thoughts?

**Comment by GermanBluefox** [comment]
Now, if the user is admin, object will not be read at all. Only for aliases.

**Comment by GermanBluefox** [comment]
We can do that configurable in iobroker.json and if the performance will be Ok can let it ON by default

**Comment by Apollon77** [comment]
In fact the object is read now already always (unless strictObjectChecks is false) ... so we shoul dhave the data.

I propose a warning in controller 3.3 with deprecation for 3.4

**Comment by foxriver76** [comment]
The object is currently not read, we just check if it's existing e. g. in Redis this is just an `EXISTS` call and no `GET` call. However, I will prepare a PR that implements #698 and #1234 +  after merge we can discuss how to add #424
