### ISSUE TITLE
Change socket io detected errormessage to be more understandable

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#714]

**Comment by foxriver76** [comment]
https://github.com/ioBroker/ioBroker.js-controller/blob/962d4e5fd7907d740ae08f8dc7c829f17e848efa/lib/states/statesInRedis.js#L163

**Comment by Apollon77** [comment]
Ok, short brainstorming ...

Proposal:
"Invalid protocol on Objects|States port XYZ for ioBroker database connection. Please make sure the IP and Port is correct and points to an js-controller >= 2.0"

**Comment by AlCalzone** [comment]
How about something like this?
```
Could not connect database at 123.45.67.8:9001 (invalid protocol). Please make sure the configured IP and port points to a host running JS-Controller >= 2.0.
```

**Comment by Apollon77** [comment]
ok for me
