### ISSUE TITLE
Alias: target value change delay

### ISSUE THREAD

**Issue by algar42** [ioBroker/ioBroker.js-controller#721]
This issue is to check whether the delay in state update between alias and its target value is expected or not. 
Say we have simple Boolean state javascript.0.test.aliasResponse:
```json
{
  "_id": "javascript.0.test.aliasResponse",
  "type": "state",
  "common": {
    "name": "aliasResponse",
    "role": "",
    "type": "boolean",
    "read": true,
    "write": true,
    "desc": "",
    "def": false
  },
  "native": {}
}
```
and its alias alias.0.aliasResponse defined as:
```json
{
  "_id": "alias.0.aliasResponse",
  "type": "state",
  "common": {
    "name": "aliasResponse",
    "role": "",
    "type": "boolean",
    "read": true,
    "write": true,
    "icon": "",
    "desc": "",
    "alias": {
      "id": "javascript.0.test.aliasResponse"
    }
  },
  "native": {}
}
```
If we subscribe to alias state and within code reads the state of target value immediately we get different values. 
e.g. this simple code:
```javascript
on({id: "alias.0.aliasResponse", change:"any"}, function(obj){
    console.log("Alias value: " + obj.state.val);
    console.log("Object value: " + getState("javascript.0.test.aliasResponse").val);
})
``` 
gives the following result:
```
Object value: true
Alias value: false
```

so, is this a bug or feature? :)

**Comment by Apollon77** [comment]
This needs to checked in JavaScript adapter. But I have no idea if this can be changed. 

Basically this is a timing issue - and especially in JavaScript adapter. State changes in general are not atomic actions. And especially when it comes to aliases. One state value change will update pot several other states. In a stateChange in js Adapter it is Never 100% secured that a getstate of the triggered change state is already reporting the new value. And when alias is triggered it is even more unlikely.

**Comment by Apollon77** [comment]
Please reopen in JavaScript adapter if you like more deep checks
