### ISSUE TITLE
New feature request/idea: make statesInMemFileDB.js disk writes interval configurable

### ISSUE THREAD

**Issue by tnowak** [ioBroker/ioBroker.js-controller#730]
Hi.
ioBroker writes all states to file states.json on disk every 30 seconds.
I'm not sure if such frequent write is necessary, but when ioBroker is runs on RPi with microSD card, that setting causes relatively high card wear.

Thanks to ioBroker forum I've found a way to extend that interval, see:
https://forum.iobroker.net/topic/31237/how-to-lower-disk-writes-for-extending-life-of-an-sd-card

I believe it would be great to have that setting configurable somewhere in the future versions.

**Comment by foxriver76** [comment]
Currently hard coded in https://github.com/ioBroker/ioBroker.js-controller/blob/master/lib/states/statesInMemFileDB.js

Maybe adding it to `iobroker.json`'s objects object as an attribute `fileWriteInterval`?

**Comment by Apollon77** [comment]
yes, then identically for the objects DB also because they work the exact same way under the hood. Question is if on "main level" or in "options" ... ?! https://github.com/ioBroker/ioBroker.js-controller/blob/master/conf/iobroker-dist.json#L51-L63

**Comment by foxriver76** [comment]
Idk.. what is the difference between options and main level. Options are changed more often?

**Comment by Apollon77** [comment]
hm ... thought again. NOT options  ... (these are redis options ...)
