### ISSUE TITLE
Call "setcap" on nodejs process when nodejs upgrade is detected

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#733]
The new installer (on linux) executes the relevant "setcap" commands on the node executable to setup everything as needed (low ports right and such).
As soon as nodejs gets updated (also minor/micro updates) these rights are removed.

Idea:
* We store the host nodejs version in a system.host.NAME state
* We read that version directly at start of controller and compare with current version
* If different we execute the relevant setcap command on node executable
* then continue and start compactgroups and instances

The challenge is how we detect the correct command because the installer checks things like "runs in docker" and such and possibly do things different then. So we need to collect all relevant checks and command and integrate in controller. Or we make a "iobroker fix cap" command  or we create an own shell script which is like installer loaded from remote that is doing just this part ...

**Comment by foxriver76** [comment]
Isn’t install fixer handling this stuff?

**Comment by Apollon77** [comment]
Yes ... but who thinks about to run it after an apt-get upgrade? Because also a minor or micro nodejs update causes this to break.

**Comment by foxriver76** [comment]
But then the `iobroker fix cap` would redundant, why not just run the fixer? So maybe detect the error and tell the users to execute the fixer?

**Comment by Apollon77** [comment]
The fixer itself is doing maaany other things too that might be unneeded ... ?!

**Comment by foxriver76** [comment]
Hm.. my opinion so far is, that it doesn't hurt to execute the fixer every now and then... however there may be unwanted side effects in some edge cases..

**Comment by AlCalzone** [comment]
We could also just check if the capabilities are there - takes a couple of ms during the controller start at maximum:
```
pi@Heizung:~ $ getcap $(eval readlink -f `which node`)
/usr/bin/node = cap_net_bind_service,cap_net_admin,cap_net_raw+eip
```
If the last line is missing, there are no capabilities set, so we need to set them.
