### ISSUE TITLE
Warn users with low free memory on adapter start in log

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#741]
Idea is that we check the free/available RAM before starting an adapter instance and warn if memory is low:
* <50MB log an error
* <100MB log an warning

Text proposal: "Your system only has %MB RAM left available and an additional adapter process ist started. Please check your system, settings and active instances to prevent swapping and Out-Of-Memory situaltions!"

**Comment by Apollon77** [comment]
Code wise we need to do like here
https://github.com/ioBroker/ioBroker.js-controller/blob/master/main.js#L649-L662

... especially the memAvailable is important to use for Linux systems! For windows I would go with freeMem

**Comment by Apollon77** [comment]
Maybe it is also an idea to "just" use the reported states - but these are pot 15s old and might not be current on "js-controller startup" conditions ... so maybe "duplicate" it :-(

**Comment by eric2905** [comment]
Text is ok, but I throw a few correction into the game:

Your system **has only** %MB RAM left available and an additional adapter process ist started. Please check your system, settings and **de**active instances to prevent swapping.....
