### ISSUE TITLE
Deprecation: remove adapter.objects and adater.states dummy objects

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#770]

**Comment by foxriver76** [comment]
@Apollon77 can you grep for adapters still using this?

**Comment by foxriver76** [comment]
Can you @Apollon77 ? ;-)

**Comment by Apollon77** [comment]
> ioBroker.opi/main.js:            adapter.objects.getObjectList({startkey: adapter.name + '.' + adapter.instance, endkey: adapter.name + '.' + adapter.instance + '\u9999'}, function (err, res) {
ioBroker.opi/main.js:        adapter.objects.getObjectList({include_docs: true}, function (err, res) {
ioBroker.radar2/fjadapter-core.js:				this.c2p(adapter.objects.getObjectList).bind(adapter.objects);
ioBroker.systeminfo/myAdapter.js:        this.getObjectList = this.c2p(adapter.objects.getObjectList).bind(adapter.objects);
iobroker.paw/main.js:  adapter.objects.getObjectList({

**Comment by foxriver76** [comment]
Cannot find c2p and it’s not in repository so.

OPI is community, I will fix.

Radar2 I will also have a look at.

**Comment by Apollon77** [comment]
c2p is "systeminfo" ... (sorry ... bad linebreak)

**Comment by foxriver76** [comment]
OPI fixed
