### ISSUE TITLE
[js-controller. 3.x] obj.type has to exist 

### ISSUE THREAD

**Issue by DutchmanNL** [ioBroker/ioBroker.js-controller#777]
objects are created with proper tuypes but messages occurs in log

code reference :

https://github.com/iobroker-community-adapters/ioBroker.sourceanalytix/blob/master/main.js#L592-L600

https://github.com/iobroker-community-adapters/ioBroker.sourceanalytix/blob/master/main.js#L607

https://github.com/iobroker-community-adapters/ioBroker.sourceanalytix/blob/master/main.js#L693-L709

```
			const commonData = {
				name: name,
				type: 'number',
				role: 'value',
				read: true,
				write: false,
				unit: this.activeStates[stateID].useUnit,
				def: 0,
			};

		await this.setObjectNotExistsAsync(stateName, {
			type: 'state',
			common: commonData,
			native: {},
		});


```

**Comment by foxriver76** [comment]
Please re-check with 3.0.4, its was most likely due to the extendObject which is used by your `localSetState` function.

**Comment by foxriver76** [comment]
@DutchmanNL is it fixed? ;-)

**Comment by Apollon77** [comment]
Please reopen if still there

**Comment by DutchmanNL** [comment]
confirmed but a new one introduced will open a separate issue for that
