### ISSUE TITLE
Detect "module not found" exceptions and also trigger a rebuild

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#781]
Module not found sometimes happen because unknown ... Could be tried to be fixed automatically with the rebuild logic now in

**Comment by AlCalzone** [comment]
Do you mean [this?](https://github.com/AlCalzone/ioBroker.ble/issues/390) That would be cool. But we should improve the rebuild logic so it works in the affected module's folder. Rebuilding directly in the adapter dir (without the --install flag) seems to do nothing.
