### ISSUE TITLE
The state is missing the required property val! 

### ISSUE THREAD

**Issue by Jey-Cee** [ioBroker/ioBroker.js-controller#782]
Check is false on setState with {val: value, ack: true}

**Comment by AlCalzone** [comment]
I'm investigating. Cannot reproduce atm.

**Comment by AlCalzone** [comment]
Can anyone reproduce this? @Apollon77 @Jey-Cee @foxriver76 @GermanBluefox ?

**Comment by Jey-Cee** [comment]
Here is the code which causes the log message:

` if (response[0]['success']) {
                adapter.setState(stateId, {ack: true});
            }`

This should not result in an error, because it is the conformation  from deConz that the set value was accepted.

**Comment by AlCalzone** [comment]
There is no Val property in the object!
