### ISSUE TITLE
js-controller 3.0.x - remove of Adapter not completed

### ISSUE THREAD

**Issue by Ilovegym66** [ioBroker/ioBroker.js-controller#808]
Hi, the remove of a Adapter finished with an error, the directorys in iobroker/iobroker-data/files/adatername and node_modules/iobroker.adaptername are still there.

only the icon of the adapter are gone, and replaced with a questionmark.
https://forum.iobroker.net/post/413157

**Comment by foxriver76** [comment]
Should be fixed
