### ISSUE TITLE
Default value from state creation not used

### ISSUE THREAD

**Issue by DutchmanNL** [ioBroker/ioBroker.js-controller#815]
Current behavior :

Creating an object does not set the default value into the object itself, meaning default value is useless now. Example :

await this.extendObjectAsync(${stateID}.Alexa_Wecker_Radio, {
          type: 'state',
          common: {
            name: 'Alexa_Wecker_Radio', 
            type: 'boolean', 
            def: false
          },
          native: {},
});

After creation of the state, the state value is set to 'null' instead fo false.

We had a similar issue in io-package creation of objects : https://github.com/ioBroker/ioBroker.js-controller/issues/665

Wanted behavior : def value should be used as real default, meaning the value must be present on the object until its changed by another event (currently NULL is not acceptable)

JS-Controller 3.0.14

**Comment by DutchmanNL** [comment]
> Hm ... we would need to check in extend if object is empty or not or better to checking state has a value. Or is not existent and so it then.

for now i can implement a WA by first doing an if getState = null OR undefined = set def value

but i assume the def value should fulfill this purpose or do I understand the meaning of that attribute wrong ?

**Comment by Apollon77** [comment]
I will add that for controller 3 later today. But controller 2 stays unchanged

**Comment by DutchmanNL** [comment]
fix confirmed, thank you !
