### ISSUE TITLE
 invalid type! Expected "string" or "object", received "number" at device creation

### ISSUE THREAD

**Issue by DutchmanNL** [ioBroker/ioBroker.js-controller#820]
js-controller 3.0.14 : 

Error in data refresh : Error: The id has an invalid type! Expected "string" or "object", received "number".

id is coming from API and used as state id and device name, convert it .toString solves the issue : 

https://github.com/iobroker-community-adapters/ioBroker.tado/commit/1c4eee6fb7cebae68715c20dfedfe667893d498f#diff-7a9076d6d94e62c13d641aa71f19ae8eR240

**Comment by foxriver76** [comment]
Yes, you should parse it to a string. Setting id with type number as id isn't a good style. We will deprecate now and decline in future versions.
