### ISSUE TITLE
Iobroker dont start after JS controller upgrade to 3.0.14 

### ISSUE THREAD

**Issue by m0rph2k** [ioBroker/ioBroker.js-controller#829]
Hi

After JS controller upgrade to 3.0.14 iobroker dont start

ioBroker.admin 4.0.9
JS: 2.2.9

From syslog
`Apr 23 17:26:15 Tux02-Home systemd[1]: Started ioBroker Server.
Apr 23 17:26:16 Tux02-Home bash[113358]: isDeepStrictEqual is not a function
Apr 23 17:26:16 Tux02-Home bash[113358]: TypeError: isDeepStrictEqual is not a function
Apr 23 17:26:16 Tux02-Home bash[113358]:     at StatesInMemoryServer.setState (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInMemFileDB.js:254:27)
Apr 23 17:26:16 Tux02-Home bash[113358]:     at startAliveInterval (/opt/iobroker/node_modules/iobroker.js-controller/main.js:660:16)
Apr 23 17:26:16 Tux02-Home bash[113358]:     at Object.connected (/opt/iobroker/node_modules/iobroker.js-controller/main.js:459:13)
Apr 23 17:26:16 Tux02-Home bash[113358]:     at Immediate.StatesInMemoryServer.setImmediate [as _onImmediate] (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInMemServerRedis.js:72:46)
Apr 23 17:26:16 Tux02-Home bash[113358]:     at runCallback (timers.js:810:20)
Apr 23 17:26:16 Tux02-Home bash[113358]:     at tryOnImmediate (timers.js:768:5)
Apr 23 17:26:16 Tux02-Home bash[113358]:     at processImmediate [as _immediateCallback] (timers.js:745:5)
Apr 23 17:26:16 Tux02-Home bash[113358]: /opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInMemFileDB.js:254
Apr 23 17:26:16 Tux02-Home bash[113358]:             hasChanged = !isDeepStrictEqual(oldObj.val, obj.val);
Apr 23 17:26:16 Tux02-Home bash[113358]:                           ^
Apr 23 17:26:16 Tux02-Home bash[113358]: TypeError: isDeepStrictEqual is not a function
Apr 23 17:26:16 Tux02-Home bash[113358]:     at StatesInMemoryServer.setState (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInMemFileDB.js:254:27)
Apr 23 17:26:16 Tux02-Home bash[113358]:     at wasForced (/opt/iobroker/node_modules/iobroker.js-controller/main.js:3970:16)
Apr 23 17:26:16 Tux02-Home bash[113358]:     at stopInstances (/opt/iobroker/node_modules/iobroker.js-controller/main.js:3922:43)
Apr 23 17:26:16 Tux02-Home bash[113358]:     at stop (/opt/iobroker/node_modules/iobroker.js-controller/main.js:3953:5)
Apr 23 17:26:16 Tux02-Home bash[113358]:     at process.exceptionHandler (/opt/iobroker/node_modules/iobroker.js-controller/main.js:4245:9)
Apr 23 17:26:16 Tux02-Home bash[113358]:     at emitOne (events.js:116:13)
Apr 23 17:26:16 Tux02-Home bash[113358]:     at process.emit (events.js:211:7)
Apr 23 17:26:16 Tux02-Home bash[113358]:     at process._fatalException (bootstrap_node.js:391:26)
Apr 23 17:26:16 Tux02-Home systemd[1]: iobroker.service: Main process exited, code=exited, status=7/NOTRUNNING
Apr 23 17:26:16 Tux02-Home systemd[1]: iobroker.service: Unit entered failed state.
Apr 23 17:26:16 Tux02-Home systemd[1]: iobroker.service: Failed with result 'exit-code'.
Apr 23 17:26:16 Tux02-Home systemd[1]: iobroker.service: Service hold-off time over, scheduling restart.
Apr 23 17:26:16 Tux02-Home systemd[1]: Stopped ioBroker Server.
`

**Comment by AlCalzone** [comment]
Js-Controller 3.0 does not support Node.js 8 anymore. Please update to Node.js 10 or 12.
