### ISSUE TITLE
Rewrite states/obejctsInRedis to use promise catch or async/await

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#840]
ioRedis library sometimes return a promise instead if a callback when an error occurs before the command is sent out (after send out callback is working great).

So we need to "catch" on all ioredis commands OR we rewrite the whole communication to use async/await with try/catch ...

**Comment by foxriver76** [comment]
PR for objects-redis exists, states-redis still needed
