### ISSUE TITLE
Upgrade error

### ISSUE THREAD

**Issue by Mr-REM-Esq** [ioBroker/ioBroker.js-controller#842]
During the upgrade the server, I received the following message.

Update js-controller from @3.0.18 to @3.0.19
NPM version: 6.14.4
npm install iobroker.js-controller@3.0.19 --loglevel error --unsafe-perm --prefix "/opt/iobroker" (System call)
(node:25044) UnhandledPromiseRejectionWarning: ReferenceError: allback is not defined
    at _0x411ccb._applyViewFunc (/opt/iobroker/node_modules/iobroker.objects-redis/index.js:1:115051)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:25044) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:25044) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Then the update freezes. I stopped him (Ctrl-C). Now the server does not start correctly.

**Comment by Apollon77** [comment]
Please use 3.0.20 SOrry

**Comment by Mr-REM-Esq** [comment]
I can't upgrade to this version.

sudo iobroker upgrade self
Host    "iobroker"  is up to date.

**Comment by Apollon77** [comment]
then do iobroker update ... 3.0.20 should appear soon

else install manually  via npm

npm install iobroker.js-controller@3.0.20

OR if this gets permission errors:

sudo -u iobroker -H npm install iobroker.js-controller@3.0.20

**Comment by Mr-REM-Esq** [comment]
Done.
Thank you so much.

**Comment by Apollon77** [comment]
you're welcome
