### ISSUE TITLE
SSL error with Node 12

### ISSUE THREAD

**Issue by Anzic23** [ioBroker/ioBroker.js-controller#844]
same error - https://stackoverflow.com/questions/59898050/axios-ssl-error-with-node-12-ssl-routinesssl-choose-client-versionunsupporte
this script stopped working. 
[samsung-air.txt](https://github.com/ioBroker/ioBroker.js-controller/files/4554858/samsung-air.txt)

Node.js v12.16.2
NPM 6.14.4
js-controller 3.0.20
```
2020-04-30 00:31:27.293 - error: javascript.0 (14338) uncaught exception: 140145197954880:error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol:../deps/openssl/openssl/ssl/statem/statem_lib.c:1942:
--
2020-04-30 00:31:27.293 - error: javascript.0 (14338) Error: 140145197954880:error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol:../deps/openssl/openssl/ssl/statem/statem_lib.c:1942:



```

**Comment by Apollon77** [comment]
Yes, we will add error handlers for all adapters that use it, but in fact ... what is wrong with the certifictaes?

**Comment by Apollon77** [comment]
Can you try to generate new certificates in iobroker? Use "iobroker cert" commands for that!

**Comment by Apollon77** [comment]
ANd: The full error/stack trace would be interesting. I would say you need to make sure to handle all errors in your script correctly. I do not nsee any topic for js-controller here ...

**Comment by Anzic23** [comment]
> ANd: The full error/stack trace would be interesting. I would say you need to make sure to handle all errors in your script correctly. I do not nsee any topic for js-controller here ...

perhaps. But on previous versions it worked without problems. error appeared after update nodejs and js-controller

**Comment by Anzic23** [comment]
> PS: or is this issues meaned to be a "feature request" to add "--tls-min-v1.0" as parameters when we execute certain adapter processes to allow insecure communication methods?

Yes, I think

**Comment by Anzic23** [comment]
any news?

**Comment by Apollon77** [comment]
> any news?

Not implemented till now ... PRs welcome

**Comment by foxriver76** [comment]
Not really sure what is the goal here? new io-pack flag to allow starting adapters with `--tls-min-v1.0`?

**Comment by Apollon77** [comment]
No idea would be to make it generic and allow to specify "nodejs params to add", so in ioPackage have a common.nodejsProcessParams = '--tls-min-v1.0 --whateverparameelse'

So the adapte rdev can specify params that are used when starting the adapter

**Comment by foxriver76** [comment]
Yes, thus compact groups where one adapter would use a flag would alle be started with this flag of course. Will this may be a problem?

**Comment by Apollon77** [comment]
or the definition is that an adapter with thsi flag can never run as compact  mode ... exactly because of this. I would not risk side effects here

**Comment by Apollon77** [comment]
meeehh ... you are right ... Elevating the parameterrs for the comapct group process i smaybe no good idea ... interesting ... yes needs to be considered

**Comment by Apollon77** [comment]
Another usecase https://github.com/ioBroker/ioBroker.parser/issues/68
