### ISSUE TITLE
Consistently use Error objects for error callbacks

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.js-controller#852]
#851 does this for most of the JS-Controller code. However, `ObjectsInMemoryFileDB` is still pretty mixed and `iobroker.objects-redis` is probably too. 
We should prioritize making this API more consistent for 3.1 (or 3.2?)

---

We could do this in a nice way and also address these ugly constructs `typeof callback === 'function' && setImmediate(...)`:

Add a utility function `maybeCallback` in `tools.js` which takes the callback and all of its parameters as arguments. This method checks if the callback is defined and calls it in `setImmediate` with all its parameters.
This issue would be addressed by adding a second utility method `maybeCallbackWithError`, which checks if the first param is an Error. If not, it converts the param to an error and calls `maybeCallback` internally.

**Comment by AlCalzone** [comment]
We could also go one step further and start promisifying all our methods. If no callback is given, these utility functions could return a Promise with the value that should be returned or given to the callback.
If we then do
```
return maybeCallback(callback, value);
```
whereever a callback is called, all the methods accepting a callback would return a Promise if none was given.

**Comment by Apollon77** [comment]
Also in ObjectInMemFileDB are still some in

**Comment by foxriver76** [comment]
The problem with the promisification using this method is, that it will not work when called inside a callback function. And this is currently done very often. However, I really like the error consistency idea using the proposed helper method.

**Comment by AlCalzone** [comment]
> The problem with the promisification using this method is, that it will not work when called inside a callback function

Can you provide an example? I'm not sure what you mean.

**Comment by foxriver76** [comment]
I try to:

```
const request = require('request');

function maybeCallback(cb, val) {
    if (typeof cb === 'function') {
        setImmediate(cb, val);
    } else {
        return Promise.resolve(val);
    }
}

async function reqUsingMaybeCb(execute, cb) {
    if (!execute) {
        // works
        return maybeCallback(cb, false);
    }

    request('https://forum.iobroker.net', (err, res) => {
        // wont work with Promise version
       return maybeCallback(cb, res);
    });
}

async function testIt() {
    // works because not async (not in cb)
    console.log(await reqUsingMaybeCb(false));
    // undefined - because promise returned inside cb
    console.log(await reqUsingMaybeCb(true));

    reqUsingMaybeCb(true, res => {
       // works
       console.log(res);
    });
}

testIt();
```

**Comment by foxriver76** [comment]
I try to:

```javascript
const request = require('request');

function maybeCallback(cb, val) {
    if (typeof cb === 'function') {
        setImmediate(cb, val);
    } else {
        return Promise.resolve(val);
    }
}

async function reqUsingMaybeCb(execute, cb) {
    if (!execute) {
        // works
        return maybeCallback(cb, false);
    }

    request('https://forum.iobroker.net', (err, res) => {
        // wont work with Promise version
       return maybeCallback(cb, res);
    });
}

async function testIt() {
    // works because not async (not in cb)
    console.log(await reqUsingMaybeCb(false));
    // undefined - because promise returned inside cb
    console.log(await reqUsingMaybeCb(true));

    reqUsingMaybeCb(true, res => {
       // works
       console.log(res);
    });
}

testIt();
```

**Comment by AlCalzone** [comment]
Ok that makes sense. However we can work our way outwards from simpler methods to these kinds of callback usage and slowly return Promises wherever possible.

**Comment by Apollon77** [comment]
we adjusted that in many places ... for sure there are some left ;-)

How we proceed? Adjust as soon as we touch code and close this issue here? or leave open and also bring into upcoming version project?
@AlCalzone @foxriver76 @GermanBluefox Opinions?

**Comment by foxriver76** [comment]
I would keep it open because there are of course occurrences let and I am not sure if every one of us is currently using the new method when implementing new code/changing old code.
