### ISSUE TITLE
getInstalledInfo -> hostRunningVersion is not optional

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.js-controller#854]
https://github.com/ioBroker/ioBroker.js-controller/blob/acb2ce7c022e77b10086dd472ae6f3abea9c2ab6/lib/tools.js#L619

or is it?
https://github.com/ioBroker/ioBroker.js-controller/blob/acb2ce7c022e77b10086dd472ae6f3abea9c2ab6/lib/setup/setupRepo.js#L139

What is it even for? I don't find any code using that property.

**Comment by Apollon77** [comment]
it is called with the js-controller version from main.js ... and the variaable is put into the resulting array for the controller info itself
https://github.com/ioBroker/ioBroker.js-controller/blob/acb2ce7c022e77b10086dd472ae6f3abea9c2ab6/lib/tools.js#L642

In the places where it is not set the relevant property is just not needed/used :-)

So we could declare it optional?!

**Comment by AlCalzone** [comment]
Yes but where is that property used?

**Comment by Apollon77** [comment]
https://github.com/ioBroker/ioBroker.admin/blob/master/src/js/adminHosts.js#L506 :-)

**Comment by AlCalzone** [comment]
Ok then I guess it should be optional.
Such interdependence between adapters is impossible to discover BTW. Not sure what we can do about it, though.
