### ISSUE TITLE
Some adapter methods don't make sense if no callback is provided

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.js-controller#856]
... because they just do unnecessary work. We should start deprecating calling them without a callback. Most of them also have the xyzAsync version that returns a Promise, so it doesn't make sense to change them to returning a Promise.

- [ ] getForeignObject
- [ ] getForeignObjects
- [ ] findForeignObject
- [ ] getObject
- [ ] getObjectView
- [ ] getObjectList
- [ ] getEnum
- [ ] getEnums
- [ ] calculatePermissions
- [ ] readDir
- [ ] readFile

The following methods check (may be imcomplete) but should warn or throw instead:
- [ ] getDevices
- [ ] getChannelsOf / getChannels
- [ ] getStatesOf

**Comment by foxriver76** [comment]
The methods which are meaningless w.o. cb are now planned to return a Promise in the future, due to the `maybeCallback` changes (just depends if they are using cb functions internally). Thus, I would not change the behaviour if no cb is provided.

**Comment by AlCalzone** [comment]
Closing in favor of returning Promises
