### ISSUE TITLE
The checks in adapter.subscribeForeignStates (and similar) don't make sense

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.js-controller#857]
`pattern` may only be a string or string array (officially), but is internally called with RegExps.
https://github.com/ioBroker/ioBroker.js-controller/blob/acb2ce7c022e77b10086dd472ae6f3abea9c2ab6/lib/adapter.js#L7014 assumes that `pattern` is a string and will crash when called with an array.

https://github.com/ioBroker/ioBroker.js-controller/blob/master/lib/adapter.js#L7034 checks if pattern is a RegExp, but does not check if it is an array of RegExps (the latter check would implicitly work for arrays btw).

https://github.com/ioBroker/ioBroker.js-controller/blob/master/lib/adapter.js#L7039-L7048 assume again that pattern is an array of strings, but
https://github.com/ioBroker/ioBroker.js-controller/blob/master/lib/adapter.js#L7052-L7054 seem to convert RegExp arrays, so the above code would crash if that is the case.

@Apollon77 @foxriver76

**Comment by foxriver76** [comment]
According to JSDoc we support only `string` and `string[]` that's also the way I've interpreted it when I fixed the restart issues of alias functionality which were present in controller v2. IMO we should just add a check, that if an array is provided, every entry is type `string`.

**Comment by AlCalzone** [comment]
But the alias code explicitly seems to accept regexp and/or arrays of regexp. I'm not sure if the latter makes sense - if it does, the checks must account for it.

**Comment by foxriver76** [comment]
Hm for me the `explicitly seems to accept` seems more like, it should be string, but just in case if its a regexp because of (really) unexplainable reasons, please don't crash. Because of https://github.com/ioBroker/ioBroker.js-controller/blob/master/lib/adapter.js#L7034 explicitly says RegExp not supported, I assume that BF didn't want to support it. But the RegExp logic is from BF.. better ask him @GermanBluefox

**Comment by Apollon77** [comment]
And especially for https://github.com/ioBroker/ioBroker.js-controller/blob/acb2ce7c022e77b10086dd472ae6f3abea9c2ab6/lib/adapter.js#L7014 the question is if we do not need to iterate over all strings if array :-)

**Comment by foxriver76** [comment]
Before doing anything here, we should discuss what we actually want to support in the future? Only string (or array and maybe regexp array, string array)?

**Comment by Apollon77** [comment]
for now (also because it was an Sentry error) I just committed a check that pattern is only allowed to be array or string (so failsafe for now)
