### ISSUE TITLE
Datenpunkt Settings ändern setzt Value auf "default" zurück

### ISSUE THREAD

**Issue by Omega236** [ioBroker/ioBroker.js-controller#863]
Seit einer der neueren Versionen (welche genau weiß ich nicht aber maximal seit 2 wochen) wird nach dem ändern der Settings (z.B. Settings ändern) oder auch nach dem bearbeiten (z.B. Max Wert ändern) der Value-Wert auf den def Wert gesetzt.

AdminVersion: 4.1.1
Js-Controller: 3.0.20
Node: v10.20.1
Object/State Type: File / passiert auch bei redis

**Comment by Diginix** [comment]
Bei mir dasselbe Verhalten. Wusste nur bis eben nicht, dass es ein Bug ist. ;-)
admin 4.1.1
nodejs 10.20.1
js-controller 3.0.20

**Comment by Omega236** [comment]
Der Admin-Adapter setzt jetzt zwar nicht mehr den default wert, aber andere Adapter verursachen den fehler immer noch. (scheinbar verursacht durch den extendForeignObject)
z.B. Sourceanalytix

```
for (const stateID in this.activeStates) {
			// Prepare custom object
			const obj = {};
			obj.common = {};
			obj.common.custom = {};
			obj.common.custom[this.namespace] = {};
			// get current meter value
			const reading = this.activeStates[stateID].calcValues.currentValuekWh;
			if (!reading) return;

			this.log.info(`Resetting startvalue for ${stateID} type ${type} with value ${reading}`);

			// Extend object with start value [type] & updat memory
			obj.common.custom[this.namespace][type] = reading;
			this.activeStates[stateID].calcValues[type] = reading;

			await this.extendForeignObject(stateID, obj);
			this.log.debug(`startvalue for ${stateID} resettet`);
		}
```

js-controller: 3.1.4
node: v10.20.1
Sourceanalytix: 0.3.1

**Comment by Apollon77** [comment]
Der js-controller 3.1.4 liesst an all diesen Stellen an sich das state aus und setzt es nur dann wenn es nicht gesetzt ist. Kannst Du es mit history oder bitte nochmal nachstellen

**Comment by Omega236** [comment]
Also der Log von heute nacht:


 val | ack  |  from |  ts |  
-- | -- | -- | -- | --
109729.1 | true | hm-rpc.1 | 2020-05-25 00:09:40.073 |  
109718.7 | true | hm-rpc.1 | 2020-05-25 00:06:47.716 |  
109708.3 | true | hm-rpc.1 | 2020-05-25 00:04:43.681 |  
109708.3 | true | hm-rpc.1 | 2020-05-25 00:02:25.738 |  
0 | true | sourceanalytix.0 | 2020-05-25 00:00:01.045 |  
0 | true | sourceanalytix.0 | 2020-05-25 00:00:00.908 |  
0 | true | sourceanalytix.0 | 2020-05-25 00:00:00.907 |  
109697.9 | true | hm-rpc.1 | 2020-05-24 23:59:53.641 |  
109687.5 | true | hm-rpc.1 | 2020-05-24 23:57:07.382 |  
109677 | true | hm-rpc.1 | 2020-05-24 23:55:09.707 |  
109666.6 | true | hm-rpc.1 | 2020-05-24 23:52:57.865 |  
109666.6 | true | hm-rpc.1 | 2020-05-24 23:50:31.881


im Testssystem Nachstellen versuch ich sobald ich zeit habe
