### ISSUE TITLE
backup-object folder isn't deleting files

### ISSUE THREAD

**Issue by liv-in-sky** [ioBroker/ioBroker.js-controller#866]
in the folder /opt/iobroker/iobroker-data/backup-objects are too much files - in my case over 7GB of files - the delete mechanism is not working - over 2000 files !

in the iobroker  forum: https://forum.iobroker.net/topic/32962/ordner-in-iobroker-explodiert-backup-objects

**Comment by foxriver76** [comment]
Fixed in https://github.com/ioBroker/ioBroker.js-controller/commit/289a6ddd63132a716526d2fff3a0ec0a95bfa93d

**Comment by liv-in-sky** [comment]
@foxriver76 erstmal danke - könntest du mir sagen, was ich jetzt machen muss (kann ich das installieren), damit ich das in 2 tagen überprüfen kann? oder muss ich einfach warten, bis es ein neues update gibt?

**Comment by Apollon77** [comment]
Am besten warte auf die nächste Version

**Comment by Apollon77** [comment]
js.controller 3.1 ist in GitHub Testing and will be latest this night
