### ISSUE TITLE
JavaScript install break js-controller. Windows.

### ISSUE THREAD

**Issue by Anzic23** [ioBroker/ioBroker.js-controller#867]
fresh Windows 10, fresh iobroker installation. When trying to install JavaScript, the js-controller broke down. helped installing js-controller `npm install iobroker.js-controller@3.0.20` and installation of the `npm install --global --production windows-build-tools` package.
some log:
[js_log.txt](https://github.com/ioBroker/ioBroker.js-controller/files/4582995/js_log.txt)

**Comment by Apollon77** [comment]
The reason is caused by the windows installer ... there is a newer one in beta or testing
