### ISSUE TITLE
Add Plugin CLI commands to enable/disable plugins

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#869]
We want to make sure that plugins can be configured via CLI and not only via states - and also before the adapter is started for the first time (at least Theoretically). The proposal would be the following:
* create CLI command "iobroker plugin "pluginname" host "name|this" enable|disable|on|off" to control a host plugin
    * When called the controller io-package and iobroker config file is checked if the given plugin is defined there and if yes the relevant state "system.host.HOSTNAME.plugins.PLUGINNAME.enabled" is set to true or false. Error when plugin is not listed in any of the two places
* create CLI command "iobroker plugin "pluginname" adapter "instancename.nr" enable|disable|on|off"
    * When called the adapter io-package file is checked if the given plugin is defined there and if yes the relevant state "system.adapter.ADAPTERNAME.NR.plugins.PLUGINNAME.enabled" is set to true or false. Error when plugin is not listed in io.package of adapter

**Comment by Apollon77** [comment]
We could also think about returning the plugin activation status when the last parameter is ommitted. Logic here is: 
* State exists and have a value, use this
* State not exists/no value:
    * if it is a reporting plugin check global diag flag in system.config. If seit to "none" then disabled
    * check plugin data in io-package/config for "enabled" and if === false then disabled
    * else enabled

**Comment by AlCalzone** [comment]
I can pick this up, but I'm not familiar with the plugin config stuff.
Is that a state ID

>     system.adapter.ADAPTERNAME.NR.plugins.PLUGINNAME.enabled

or is `system.adapter.ADAPTERNAME.NR` the object and the rest a part of the object?

**Comment by Apollon77** [comment]
1.) yes this is the state ID, example: system.adapter.meross.0.plugins.sentry.enabled
2.) yes need to be created when not existing
3.) currently only sentry. my next PR will contain a new setup/pluginInfos.js which contains a "isReportingPlugin" method and my idea was we define there for now. It is only "for future usage if sentry needs to be replaced later". So check for sentry for now and we adjust later that check to use the method.
4.) in general seehttps://github.com/ioBroker/plugin-base#configuration, also io-package see controller io-package itself or conf/iobroker-dist.json
5.) Yes this is supported, also disabling (but here a plugin could decline in theory then a info is logged in logfile, I would assume for CLI that it works)
