### ISSUE TITLE
rebuild doesn't work 

### ISSUE THREAD

**Issue by Ilovegym66** [ioBroker/ioBroker.js-controller#872]
with the command "iobroker rebuild" and "iobroker rebuild --install" (and adaptername) there is no function, no npm output, looks like npm don't start:
``ilovegym@iobroker /opt/iobroker $ iobroker rebuild mihome-vacuum --install
npm install --loglevel error --production (System call) in "/opt/iobroker/node_modules/iobroker.mihome-vacuum"

Rebuild mihome-vacuum done
ilovegym@iobroker /opt/iobroker $`

Issue taken from [mihome-vacuum](https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/issues/119#issuecomment-625058899)

**Comment by Apollon77** [comment]
very strange ... works for me :-(

**Comment by Apollon77** [comment]
@Ilovegym66 up for a test?
Please edit /opt/iobroker/node_modules/iobroker.js-controller/lib/setup.js and there in Line 2249 it should be:

```
        let cmd = 'npm ' + npmCommand +' --loglevel error';
```

Please change this to

```
```

**Comment by Apollon77** [comment]
duplicate #831 and such
