### ISSUE TITLE
no configuration for backup_objects possible

### ISSUE THREAD

**Issue by paul53** [ioBroker/ioBroker.js-controller#873]
Die Konfigurationen für das zyklische Backup der Objekte und Zustände werden weder aus der Datei /opt/iobroker/iobroker-data/iobroker.json noch aus der Datei /opt/iobroker/node_modules/iobroker.js-controller/conf/iobroker-dist.json bei ioBroker-Restart übernommen.

**Comment by Apollon77** [comment]
will be fixed in js.controller 3.0.21+
