### ISSUE TITLE
Re-think "readFile/writeFile checks"

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#883]
* there can be cases like via "web" adapter where simply non existant files are tried to be read
* sayit uses instance objects but in fact sayit.0 is not defined, but sayit.0.userfiles are defined as meta.user folder, but we only check "the id itself", so in fact the check on read or write needs to check the "path" objects too ...

**Comment by foxriver76** [comment]
>     * there can be cases like via "web" adapter where simply non existant files are tried to be read

I would consider, that the adapter needs to handle the 'non existing' file error.

>     * sayit uses instance objects but in fact sayit.0 is not defined, but sayit.0.userfiles are defined as meta.user folder, but we only check "the id itself", so in fact the check on read or write needs to check the "path" objects too ...

Either this, or the adapter should write via `writeFile('sayit.0.userfiles', 'filename', 'content')` but of course for File DB it could get messy because of the folder structure.

**Comment by Apollon77** [comment]
1.) Yes adapter alreayd handles it ... but then each "logging" that we can do on DB-Level on read at least would be a false positive

**Comment by foxriver76** [comment]
Hm when we start throwing we would remove the internal logging..
Only other option which comes to my mind yet, would be to first check file existence then do meta check..

**Comment by foxriver76** [comment]
I thought about it again.. I would keep the check as it is. For the sayit case I would claim, that write/read is not used as designed. It should read/write via id: `sayit.0.userfiles`.

For the read problem, I propose to remove the check completely from read and throw on write up from js-c 3.2.. so we stay backward compatible, and no adapter can create new 'wrongly structured' files, but already created ones can still be read by adapters.. 

Whats your opinion @Apollon77 @AlCalzone @GermanBluefox

**Comment by AlCalzone** [comment]
I link that approach
