### ISSUE TITLE
subscribes on pattern need to check the elements before blindly using them

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#894]
see https://github.com/ioBroker/ioBroker.js-controller/blob/3.1.x/lib/adapter.js#L7066 ... should affect more places I think we should ignore "empty" elements ... or error out?

**Comment by foxriver76** [comment]
I don't get what you mean here.. what is meant by "empty" elements?

**Comment by Apollon77** [comment]
see https://github.com/ioBroker/ioBroker.sql/issues/120

it seems that sql calls it with an array where array elements are null or undefined ... and here we assume all elements are valid without checking

**Comment by foxriver76** [comment]
Bf added a check in https://github.com/ioBroker/ioBroker.js-controller/commit/4b843cab3277ac8f4c412a6deff9678bb9e9ceb2 but I would rather go for a typeof check for string

**Comment by Apollon77** [comment]
I agree

**Comment by foxriver76** [comment]
I have added this small change to https://github.com/ioBroker/ioBroker.js-controller/pull/896
