### ISSUE TITLE
Update repo "latest" message

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.js-controller#895]
Update repository "latest" under "http://download.iobroker.net/sources-dist-latest.json"

I don't know how to do this. Could anyone help please.

**Comment by foxriver76** [comment]
Everything fine. The log means that iobroker is starting to read the repository and looking for new adapter versions.

**Comment by daniel-lo** [comment]
LOL .. "Updating ..." would not be so irritating .. at least not for me ;-)
Update sounded like an instruction or advice.
