### ISSUE TITLE
Zurück von redis to file erzeugt restarts ca. alle 15 Minuten

### ISSUE THREAD

**Issue by Marty56** [ioBroker/ioBroker.js-controller#898]
Ich bin von "redis" zurück zu "file" für Speicherung von Objekten gegangen.
Das hatte zur Folge, dass der js-Controller ca. alle 15 Minuten neu startet.

Error log zeigt nur Sigterm. 
Ich vermute, es hängt mit der persistenten Speicherung der Redis Datenbank alle 15 Minuten zusammen, die der js-controller trotz "file" immer noch machen will.

**Comment by Apollon77** [comment]
Nein. Iobroker macht gar nichts alle 15 mins. Volles log bitte zeigen.  ggf ein restart des Systems mal versucht? Steht irgendwas im /var/log/syslog?

**Comment by Marty56** [comment]
Die Logs haben keine Fehler gezeigt, sondern es wurde wie gesagt ca. alle 15 Minuten iobroker neu gestartet.  Die Logs sind leider gelöscht. 
/var/log/syslog zeigt nur noch den Betrieb von heute, also nicht die Restarts.

Wäre es möglich, dass Du mit Hilfe von Sentry auf die Log zugreifen kannst? Sollte bei js-controller 3.1.5 doch gehen.

Was ich gemacht habe
1. Als ich bemerkt habe, dass das Redis Backup riesig  (190 MB) war, habe ich wieder auf file umgestellt und iobroker gestartet. Ich hatte vorher nur die States in Redis gespeichert.

2. Danach habe ich Redis gestoppt und alle Dateien, die im Redis Speicherverzeichnis waren (ca. 5-6 Stück, irgendwelche Temp Dateien, temp-<nummer>.rdb) gelöscht.

3. Dann habe ich die permanenten Restarts von iobroker bemerkt und alle möglichen Fehlerursachen ausgeschlossen. Der Raspi ist nicht abgestürzt, es wurde nur iobroker immer wieder neu initialisiert (kein Absturz des iobroker Processes).
Die "Neustarts" wurde eindeutig von js-controller erzeugt. In meinen Tests habe ich alle Adapter inklusive des Javascriptadapter ausgeschaltet.

4. Behoben wurde das Problem, in dem ich wieder auf Redis umgestellt habe. Jetzt ist das Redis Backup ca. 90 kB groß und es befindet sich in /var/lib/redis nur noch ein file, dumb.rdb mit 340 kB.

Ich habe aus Interesse auf meinen zweiten iobroker Server das Redis Verzeichnis angeschaut und es befindet sich neben dem dumb.rdb nur ein weiteres temp File dort.

**Comment by Apollon77** [comment]
Ich hab da mal ne Frage. (Lange Antwort später wenn ich nicht am Handy bin)
Wieviel RAM hat der Radio denn so frei?

Objects und files Im redis zu haben können leicht die genannten 190mb werden. Das ist ok.  Soviel RAM muss frei sein. Für ein redis Backup braucht es quasi nochmal soviel freies RAM. Wären also mindestens 400mb RAM die from system nennenden iobroker Prozessen frei haben muss. Ist das gegeben?!

Für mich klingt es so das redis alle 15mins abgeraucht ist weil nicht genug RAM frei war und dann restarted der Controller. 

Unter https://forum.iobroker.net/topic/26327/redis-in-iobroker-überblick habe ich mal alles zusammengefasst vor einiger Zeit. 
Gelesen?

Achja: syslog.1 bzw syslog.2.gz und so haben die files der Tage davor.

**Comment by Marty56** [comment]
Die Maschine ist abgeraucht, wenn Redis **NICHT** aktiv war und läuft jetzt wieder nachdem ich Redis wieder eingeschaltet habe.

Was mich noch interessieren würde, wie Du die Zuordnung zu meiner Maschine machen kannst bzgl. der Sentry Logs?

**Comment by Apollon77** [comment]
> Was mich noch interessieren würde, wie Du die Zuordnung zu meiner Maschine machen kannst bzgl. der Sentry Logs?

Gar nicht. Was habe ich geschrieben was du darauf zurückführen würdest? Alles was ich geschrieben habe waren vermutungen. Aber es kamen auch bei Sentry die letzten tage keinerlei Meldungen rein die etwas mit Redis zu tun hatten oder den DBs.

**Comment by Apollon77** [comment]
> Die Maschine ist abgeraucht, wenn Redis NICHT aktiv war und läuft jetzt wieder nachdem ich Redis wieder eingeschaltet habe.

Das kapier ich nicht und kann an sich nicht sein

**Comment by Marty56** [comment]
War aber so. Meiner Beobachtung nach hat der js-controller den Wechsel Redis -> File nicht verkraftet.
Als ich dann wieder file-> Redis gemacht habe, waren die ca. 15 minütigen Neustarts weg.

**Comment by Apollon77** [comment]
Ok, sorry aber so kommen wir nicht weiter. Ich brauche Logs oder ich muss hier zu machen ... ich habe gestern nochmal teste in beide Richtungen bei mir getestet und es lief alles ...

**Comment by Marty56** [comment]
Kann ich verstehen! 
Die Log habe ich leider nicht mehr, aber sie beinhalteten keine Fehler oder Warnings. Es wurde nur dieses "Sigterm" angezeigt. 

Weiter Details würden sich nur über Sentry abrufen lassen. Sollen wir das versuchen?

**Comment by Apollon77** [comment]
Du verstehst Sentry falsch. Sentry bekommt crashes gemeldet, wenn es aber ein "sauberer restart" oder ein SIGTERM oder ähnliches war der einen sauberen restart auslöst, dann ist in Sentry nichts drin.

**Comment by Marty56** [comment]
Alles klar. Dann haben wir keine Chance und wir müssen das Issue schließen.
Danke für Deine Reaktionen.
