### ISSUE TITLE
Nicht Alias DP unter alias.0 erstellen

### ISSUE THREAD

**Issue by ldittmar81** [ioBroker/ioBroker.js-controller#906]
Wenn man ein State im alias.0.*** erstellt bekommt man eine Meldung. Wenn man also Skript-Datenpunkte braucht, muss man diese unter 0_userdata anlegen und ein Alias dazu machen. Also muss man 2 DPs anlegen. Es wäre viel einfacher, wenn es erlaubt wäre, gleich ein DP für Skripte unter alias anzulegen.

**Comment by Diginix** [comment]
Das widerspricht sich aber. Aliase sind eher für Objekte von physischen Geräten gedacht, die zB eine uid in der ObjektID enthalten, die sich bei Austausch des Gerätes ändert.

Dein Datenpunkt unter 0_userdata kann ja aber direkt im Skript verwendet werden ohne extra Alias und seine ObjektID sollte sich auch nicht ändern. Es muss nicht jedes sich nie verändernde Objekt ein Alias erhalten.
Solltest du selbst bei deinen eigenen Objekten eine Art Dynamik haben, dann brauchst du auch genau den separaten Alias Datenpunkt, der mal auf das eine 0_userdata Objekt und mal auf ein anderes zeigt. Ist dein 0_userdata Objekt aber beständig, dann nutze es auch direkt von da im Skript.

**Comment by foxriver76** [comment]
Sehe das wie @Diginix

**Comment by ldittmar81** [comment]
Ich nutze Alias um ein Gerät zu definieren und ich möchte dass alle Datenpunkte die dazu gehören, zusammen dort sind. Ich habe zum Beispiel ein Gerät "Briefkasten". Zum Briefkasten gohören 2 physikalische Sensoren (Bewegungsmelder und Tür/Fenster Sensor) und dazu noch ein Datenpunkt, der per Skript gesteuert wird und mir sagt, ob ein Brief drin ist oder nicht. Alle diese Datenpunkte sind zusammen im Gerät "Briefkasten" zu finden. Ich habe also nicht ein Gerät "Bewegung im Briefkasten" und ein "Briefkasten Tür Sensor", deswegen wäre die Erstellung eines "Briefkasten voll" Datenpunkten direkt darunter für meine Zwecke sinnvoll. Denn so lege ich irgendwo draußen ein Datenpunkt, der nur da ist, damit ich es im Gerät verlinken kann.

**Comment by Apollon77** [comment]
Die Frage ist ja die: Wenn es hier um komplett eigene Datenpunkte geht hast Du freie wahl über die Struktur und kannst dein gesamtes Gerät auch unter 0_userdata.0 anlegen ... warum willst Du es künstlich unter Alias haben?

**Comment by ldittmar81** [comment]
Ja nee... Ich kann ja nicht das gesamte Gerät unter 0_userdata.0 anlegen. Es geht nur um einzelnen Datenpunkte, die mehr Logik haben. Beim Beispiel Briefkasten habe ich ein boolean DP "FULL", der auf true gesetzt wird, wenn ein Brief rein kommt und auf false, wenn die Tür vom Briefkasten geöffnet wird. Alle andere Datenpunkte sind direkte Verknüpfungen zu den einzelnen Sensorendatenpunkte. Natürlich kann ich mein Datenpunkt für Briefkasten voll irgendwo unter 0_userdata.0 speichern und alle Skripte und Anzeigen auf den dortigen DP einstellen, aber ich finde, dass der DP "FULL" zum Gerät "Briefkasten" direkt gehört... ist ja ein Zustand des Briefkastens, deswegen habe ich ja ein Alias zum 0_userdata.0.briefkasten_voll erstellt. So sind alle DPs zum Briefkasten zusammen in einem Ordner.

Bei mir ist das einzige wichtige Ordner alias.0 ... Alle andere könnten ausgeblendet werden, denn alle für mich relevanten DPs sind dort zusammengefasst. Hmm... das wäre vielleicht eine coole Ansicht für den Admin: zeige NUR Alias bzw Linkeddevices

**Comment by algar42** [comment]
I agree, what @ldittmar81 describes here could be helpful in some cases when we need to combine several physical devices (or several physical states) into one virtual device and add some custom script controls (states) to it.  E.g. simple example - I have Mihome temperature sensor which I want to turn into virtual thermostat device. For this purpose I create alias.0.thermostat device where I redefine functions/roles and probably states type to fit into device-detector. But at the same time I also want to add custom On/Off state to this virtual thermostat and to do this I firstly need to create state in javascript.0 or User_data.0 namespace and then add an alias to this state to my virtual thermostat device. 
It would be nice if the state created in alias.0 namespace manually behaves like a usual state if no target ID is specified.

**Comment by GermanBluefox** [comment]
Technically not possible
