### ISSUE TITLE
Probleme mit "iobroker host [hostname]"

### ISSUE THREAD

**Issue by buanet** [ioBroker/ioBroker.js-controller#920]
Moin,
wie wir in #286 schon einmal zerpflückt haben, nutze ich in meinem ioBroker Docker Image den Befehl "iobroker host [hostname] um den beim der Installation von ioBroker während des Docker Build Prozess hinterlegten "temporären" Hostnamen zu ersetzen. 

Bis vor einigen Tagen hat dies auch wunderbar geklappt. Wie allerdings z.B. in https://github.com/buanet/docker-iobroker/issues/100 gemeldet gibt es seit kurzem vermehrt Fälle in denen der Aufruf von "iobroker host [hostname]" beim ersten Start des Containers die Fehlermeldung
`No instances found for host "[hostname]"`
nach sich zieht und der Hostname dementsprechend nicht korrigiert wird.
Ein Blick in die objects.json bestätigt das. 

Bei der Analyse zu diesem Fehlerbild ist mir durch Zufall ein etwas älteres Image in die Hände gefallen bei dem der Fehler (noch) nicht auftritt. Das Image ist im Großen und Ganzen gleich (dockerfile, schripts) allerdings wurde es mit einer älteren Node Version erstellt (v12.16.8). Bei Tests mit Images die Node Versionen v12.17.0 und v12.18.0 enthielten tritt der Fehler auf. 
Seltsam ist, dass der Fehler auch bei aktuellen Versionen von Node v10 auftritt. z. B. v10.20.1.
Allerdings ist des m. E. durchaus möglich dass trotzdem ein Zusammenhang mit der Node Version bestehen kann, z.B. wenn ein (Security)Fix sowohl in Node 12 als auch in node 10 implementiert worden ist.

Kann es sein dass die Node Version Auswirkungen auf den Befehl "iobroker host ..." hat? Und wie schaut es mit anderen Umgebungen aus, gibt es da vielleicht auch Probleme?

Und Zusatzfrage: 
Als temporären Workaround (und vielleicht zukünftige Lösung zur Vermeidung des "iobroker host ..." Befehls) baue ich gerade das Startscript des Containers etwas um, sodass statt "iobroker host ..." einfach der Hostname in states.json und objects.json ersetzt wird. Ist das aus ioBroker Sicht eine gute Idee?

Danke!

MfG,
André

**Comment by GermanBluefox** [comment]
> states.json und objects.json ersetzt wird.

Ist keine gute Idee. Da es mit REDIS z.B. nicht funktionieren wird. Wir finden schon den Fehler und danke fürs Melden :)

**Comment by AlCalzone** [comment]
Vermutlich related:
https://forum.iobroker.net/topic/34073/iobroker-startet-nach-hostwechsel-keine-instanzen-mehr/2

**Comment by Apollon77** [comment]
@buanet I have updated the 3.1.x branch with a fix that would be js-controller 3.1.5 ... could you test it?
Use
```
npm i ioBroker/ioBroker.js-controller#3.1.x
```

**Comment by buanet** [comment]
@Apollon77 Tested. Looks good. Thank you again! :)

**Comment by Apollon77** [comment]
3.1.5 on npm now
