### ISSUE TITLE
Problems with zoneminder adapter after upgrading iobroker to js.controller 3.1.4

### ISSUE THREAD

**Issue by maxgrosse1** [ioBroker/ioBroker.js-controller#921]
After upgrading to js.controller 3.1.4 the zoneminder adapter is not working any more and throws following log lines (cf. picture). Would you be so kind to advise. Thx.

![82332807-26297380-99e6-11ea-9024-708a34d19b41](https://user-images.githubusercontent.com/65607215/83727984-30827900-a646-11ea-8f15-8dd94824cf88.JPG)

**Comment by Apollon77** [comment]
Please open this issue with zoneminder adapter
