### ISSUE TITLE
Instanz lässt sich nicht entfernen wenn Slavehost gestorben ist

### ISSUE THREAD

**Issue by nob0dy80** [ioBroker/ioBroker.js-controller#945]
Hallo,
mir ist die SD Karte in meinem Slave gestorben. 
Die Instanz die darauf lief lässt sich weder im Admin (Endlosschleife) noch über die Kommandozeile entfernen.
Selbst wenn der Host entfernt wurde, bleibt die Instanz weiter vorhanden.
Weitere Details im Forum:
https://forum.iobroker.net/topic/34449/instanz-nicht-entfernbar-wenn-slave-gestorben-ist/

**Comment by foxriver76** [comment]
Wie wurde der Slave entfernt? Zeigt der Admin unter Objekte bei aktivem Expertenmodus den Kanal `system.adapter.ble.0`?

**Comment by nob0dy80** [comment]
@foxriver76 
Die Instanz wurde ganz normal über den Admin entfernt.  
Ich kann dir nicht sagen ob dieses Objekt noch da war, da ich mittlerweile alles platt gemacht habe.

**Comment by foxriver76** [comment]
K, should be the same as cli command:

https://github.com/ioBroker/ioBroker.admin/blob/2129603ca75d4d564ddab81a2816ac314adb2315/src/js/adminHosts.js#L111

**Comment by foxriver76** [comment]
`host remove <hostname>` transformiert alle Instanzen von dem zu löschenden Host auf den Host den `tools.getHostName` ausspuckt, könnte mir wenn dann vorstellen, dass dies wiederum der Salve Host selbst war und somit  die Instanzen als Leichen dort geblieben sind. Man könnte einen Check einbauen ob `hostname` gleich `newHostname` und entsprechend auffordern, das Kommando nicht vom zu entfernenden Host auszuführen.
