### ISSUE TITLE
Unable to login if username is uppercase

### ISSUE THREAD

**Issue by WolfspiritM** [ioBroker/ioBroker.js-controller#952]
Hi,

If Username contains uppercase then "checkPassword" is not able to find the correct userobject.

https://github.com/ioBroker/ioBroker.js-controller/blob/656e7282ab5bb15a9af10c3e53498fcd51c3d888/lib/adapter.js#L627

It still doesn't work if toLowerCase is removed as admin also does that check before.
https://github.com/ioBroker/ioBroker.admin/blob/6d5163c40e14d721c94def994d433d5b3e4a4e2e/lib/web.js#L370

And even then permissions aren't loaded correctly. (calculcatePermissions and checkGroup)

I think either: 
1. Uppercase Usernames should be supported then all these checks need to remove the "toLowerCase()"
or
2. Uppercase Usernames should be banned then Admin should prevent creating these

**Comment by Apollon77** [comment]
The problem is bigger because that lowercase handling is also in admin, web and socketio (at least) ...

**Comment by foxriver76** [comment]
I would opt to support uppercase usernames too or is there a good reason for not support them @GermanBluefox @Apollon77 

In both cases we would have to adapt controller and the 3 adapters.

**Comment by GermanBluefox** [comment]
I just wanted to avoid Admin and admin as users. 
User has ID and name, we can check in the  password checking function the name too.

**Comment by Apollon77** [comment]
Hm... yes it feels like checking the name could be better

**Comment by foxriver76** [comment]
Yes checking the name on auth and preventing id conflicts on user creation would probably be a good idea.

**Comment by WolfspiritM** [comment]
Are you proposing to check the Name aswell or to only check the Name?
Cause I think it might be very confusing for people if their id stopped working and some might use the full firstname and lastname while having the ID as the username.
At least that's what I was using it for.
