### ISSUE TITLE
On / off switch to exclude the search for a slave that is temporarily switched off

### ISSUE THREAD

**Issue by Berchemer** [ioBroker/ioBroker.js-controller#962]
I have several ioBroker installations running on different systems in different rooms of a multi-storey house.

Since the operation of a RasbPi with ioBroker is currently not required on the second floor

- no stay on the second floor until autumn -

my wish would be that a switch for slaves be introduced in ioBroker, which switches the constant demand to presence or not.

IoBroker currently complains at very regular intervals that "system.host.raspberrypi-2OG bedroom" is offline. So it is also queried regularly, which represents a useless query, since the affected system will not be switched on for weeks or possibly months. It hangs behind a "clever" plug and is only switched on again when the room is occupied via ioBroker.

It is clear to me that I can quickly deregister the slave using SSH and commandline and, if necessary, register again as a slave.

But I am concerned with a more user-friendly setting, which can also be entered or displayed by non-technical experts (wife, children) simply by clicking in a VIS-View.

Thanks for your work :-)

**Comment by foxriver76** [comment]
We would probably need a new `system.host.xy` state which can be used to deregister a host. I guess to message only comes from https://github.com/ioBroker/ioBroker.js-controller/blob/81324c1e7a43a0b9971bbdb7dbac3841cd1483e4/main.js#L1725

So we could say if this `system.host.xy.registered` is `false` do not complain.

**Comment by Apollon77** [comment]
Hm ... I'm unsure. An extra state just to prevent one log message? Especially because this message only is logged when Admin is used and the host screen is requested ... hm ....

**Comment by foxriver76** [comment]
I am also unsure, it’s a really specific use case
