### ISSUE TITLE
Enhance FORBIDDEN-CHARS to include other "Non ascii" stuff 

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#982]
Maybe really turn it around to a whitelist? or enhance blacklist

example: https://github.com/ioBroker/ioBroker.mqtt/issues/87 ... 

The object ID whitelist regex in objectsInRedis is 

[_A-Za-z0-9ÄÖÜäöüа-яА-Я] (for first character ... and plus "-" for following characters)

In fact we should decline anything which is not ascii?!

**Comment by Apollon77** [comment]
> That are all valid characters but don't make much sense as an ID.

Sure but they will also not break it ... else we need to decide between "valid" and "invalid" UTF8 chars... for all languages ... puuhhhh

**Comment by AlCalzone** [comment]
Thats why unicode has character classes: https://unicodebook.readthedocs.io/unicode.html

> On a total of 106,028 letters and symbols, 101,482 are in “other” subcategories (Lo and So): only 4.3% have well defined subcategories:
>
>        Letter, lowercase (Ll): 1,759
>        Letter, uppercase (Lu): 1,436
>        Symbol, math (Sm): 948
>        Letter, modifier (Lm): 210
>        Symbol, modifier (Sk): 115
>        Letter, titlecase (Lt): 31
>        Symbol, currency (Sc): 47

I propose we allow chars that are classified as lowercase and uppercase letters and decimal numbers (so basically like it is now but for more languages):
https://www.compart.com/en/unicode/category/Ll
https://www.compart.com/en/unicode/category/Lu
https://www.compart.com/en/unicode/category/Nd

and if we want we could limit those to the blocks that correspond to a few selected languages:
https://www.compart.com/en/unicode/block

BTW: I think its safe to say we don't need Braille in IDs ;)
https://www.compart.com/en/unicode/block/U+2800

**Comment by Apollon77** [comment]
We could also do this

**Comment by Apollon77** [comment]
@AlCalzone Any chance to implement this for 3.2??
