### ISSUE TITLE
SSL mit absoluten Pfad

### ISSUE THREAD

**Issue by mikekaldig** [ioBroker/ioBroker.js-controller#983]
wie in dem Menü beschrieben habe ich mein SSL Zertifikat unter dem Pfad /opt/certs/cert1.pem / privkey1.pem abgelegt. Sobald ich dann speichere kann ich Iobroker nicht mehr aufrufen. "Connection Refused".

Wenn ich aber den Inhalt des Zertifikats direkt in das Feld schreibe, dann funktioniert der Aufruf einwandfrei.

Kann es sein das es einen Fehler beim "absoluten Pfad" zu den SSL Certs gibt?

Anbei der Forenbeitrag: 

https://forum.iobroker.net/topic/35499/ssl-mit-absoluten-pfad

**Comment by foxriver76** [comment]
Hast du ein Rechteproblem ausgeschlossen?

https://github.com/ioBroker/ioBroker.js-controller/blob/master/lib/adapter.js#L1036

Wenn das Zertifikat nicht gelesen werden kann, returned er einfach den Pfad. Ist mMn etwas undurchsichtig und wir sollten hier mindestens einen Fehler loggen @Apollon77: https://github.com/ioBroker/ioBroker.js-controller/blob/master/lib/adapter.js#L1048

Stelle mal bitte sicher, dass dein iobroker Zugriffrechte auf die Zertifikatesdateien hat.

**Comment by Apollon77** [comment]
@mikekaldig Feedback zur Rechte-Thematik?
@foxriver76 jupp :-)
