### ISSUE TITLE
Multihost discovery server warnings

### ISSUE THREAD

**Issue by nob0dy80** [ioBroker/ioBroker.js-controller#993]
Hi,

hope this is the right place to go.

on regular base i'm getting warnings that look a little bit crypt ;-)

![image](https://user-images.githubusercontent.com/28686079/90008373-80139f80-dc9c-11ea-8e87-d2ff4dfb35c2.png)

Is there something i can do?

**Comment by foxriver76** [comment]
Schaut so aus als würde ein Gerät in deinem Netzwerk Nachrichten an den Multihost Server senden. 

https://github.com/ioBroker/ioBroker.js-controller/blob/ad8e718e2a7c52126ce7871043535782d7987623/lib/multihostServer.js#L241

**Comment by nob0dy80** [comment]
@foxriver76 
Der Verursacher lässt sich auch so rausfinden, steht ja im Log. 
In diesem Fall EdgeSwitch 8-Port, ES.bcmwh (noch ein Edgeswitch) und EdgeRouter-ER. Dieses ist auch absolut gewolltes Verhalten der Geräte da die selbst untereinander eine Art discovery bieten.

Es würde vermutlich schon ausreichen irgendwie einen Filter zu implementieren der Meldungen von *EdgeSwitch*, *EdgeRouter* und *ES.* ignoriert. Zumindest würde das reichen wenn noch keine anderen Beschwerden in dieser Form vorliegen.

**Comment by foxriver76** [comment]
Klar könnte man filtern, dann muss allerdings auch das entsprechende Frontend oder mindestens händische Konfiguration über iobroker.json her. Ich weiß nicht ob das wirklich Sinn macht, habe selbst kein Multihost im Einsatz, daher die Frage an @Apollon77

**Comment by Apollon77** [comment]
Ich würde loglevel auf Info runtersetzen. Ansonsten ist multihost discovery die Frage ob es Sinn Macht das immer an zu haben. Ist ja an sich nur dazu da um eine neuen Host aufzusetzen. 

Also : eher disablen und nur enabled wenn nötig.
